import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

async function seedGenericTopicQuestions(
  topicId: string, 
  topicName: string, 
  icon: string,
  sampleQuestions: Omit<Question, 'area' | 'subject' | 'topic'>[]
) {
  console.log(`${icon} Importing ${topicName} questions...`);
  
  const questions: Question[] = sampleQuestions.map(q => ({
    area: 'policial',
    subject: 'uso-progressivo-da-forca',
    topic: topicId,
    ...q
  }));

  for (const question of questions) {
    await saveQuestion(question);
  }

  console.log(`✅ ${topicName} questions imported successfully!`);
}

export async function seedQuestionsPrincipiosUsoForca() {
  return seedGenericTopicQuestions('principios-uso-forca', 'Princípios do Uso da Força', '⚖️', [
    { question: 'Segundo os Princípios Básicos sobre o Uso da Força e Armas de Fogo pelos Funcionários Responsáveis pela Aplicação da Lei (ONU, 1990), o uso da força deve ser:', options: ['Sempre letal para garantir efetividade', 'Legal, necessário, proporcional e progressivo', 'Utilizado apenas em crimes graves', 'Aplicado sem restrições contra criminosos', 'Exclusivamente defensivo'], correctAnswer: 1, explanation: 'PRINCÍPIOS FUNDAMENTAIS DO USO DA FORÇA (ONU 1990): 1) LEGALIDADE: conforme a lei; 2) NECESSIDADE: quando outros meios não funcionam; 3) PROPORCIONALIDADE: adequado à gravidade da ameaça; 4) MODERAÇÃO/PROGRESSIVIDADE: iniciar pelo nível mínimo necessário. Não é "sempre letal" nem "sem restrições". A força deve ser GRADUAL, começando pela presença policial, depois verbalização, e só escalar se necessário. O objetivo é CONTROLAR a situação com o MÍNIMO de força necessária.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'O princípio da proporcionalidade no uso da força estabelece que:', options: ['A força deve ser sempre igual à resistência', 'O nível de força deve ser adequado à ameaça, objetivo legítimo e circunstâncias', 'Qualquer resistência justifica força letal', 'A força máxima deve ser usada preventivamente', 'Não há limites se houver crime'], correctAnswer: 1, explanation: 'PROPORCIONALIDADE: a força empregada deve ser ADEQUADA à: 1) GRAVIDADE da ameaça; 2) OBJETIVO LEGÍTIMO perseguido; 3) CIRCUNSTÂNCIAS do caso. Não significa "força igual" (espelhar), mas BALANCEAMENTO. Exemplo: suspeito desarmado fugindo de furto → força letal é DESPROPORCIONAL. Suspeito armado atirando → força letal pode ser proporcional. Análise caso a caso. STF: desproporcionalidade = excesso = abuso. Teste de proporcionalidade: adequação (meio apto) + necessidade (meio menos gravoso) + proporcionalidade em sentido estrito (benefício supera sacrifício).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'O princípio da necessidade exige que o uso da força:', options: ['Seja utilizado em qualquer situação policial', 'Seja o último recurso, quando meios menos lesivos não são suficientes', 'Não seja precedido de aviso ou negociação', 'Seja aplicado preventivamente', 'Dispense avaliação da situação'], correctAnswer: 1, explanation: 'NECESSIDADE: força só pode ser usada quando outros meios NÃO são suficientes. É o teste do "ÚLTIMO RECURSO razoável". Antes da força: 1) PRESENÇA policial (pode dissuadir); 2) COMUNICAÇÃO/verbalização; 3) NEGOCIAÇÃO (quando possível). Se estes não funcionam ou são inviáveis (perigo iminente): força pode ser necessária. Não é "preventiva" nem "em qualquer situação". Exemplo: suspeito colaborativo → força NÃO é necessária. Suspeito resistindo violentamente → força pode ser necessária. Policial deve sempre buscar solução MENOS lesiva viável.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'A legalidade do uso da força significa que:', options: ['Policial tem liberdade total para decidir', 'O uso da força deve ter base legal e respeitar direitos fundamentais', 'Apenas crimes hediondos justificam força', 'A lei não se aplica em situações de risco', 'Força letal é sempre legal'], correctAnswer: 1, explanation: 'LEGALIDADE: uso da força deve ter BASE LEGAL (lei que autoriza) e respeitar DIREITOS FUNDAMENTAIS (dignidade, vida, integridade). Fontes: CF art. 5º (direitos fundamentais), CPP (prisão, busca), leis específicas (força policial). Limites: 1) Dignidade humana (vedação tortura, tratamento desumano); 2) Proporcionalidade; 3) Devido processo legal. Força ILEGAL: sem base legal, arbitrária, desproporcional. Consequências: responsabilidade penal (abuso, lesão, homicídio), civil (indenização), administrativa (demissão). Policial não age "livremente" - age dentro dos limites LEGAIS.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'O uso progressivo (ou diferenciado) da força determina que:', options: ['Policial deve começar sempre pela força letal', 'A força deve ser escalada gradualmente conforme resistência/ameaça', 'Todos os níveis devem ser usados simultaneamente', 'Não há necessidade de avaliar a situação', 'Presença policial é dispensável'], correctAnswer: 1, explanation: 'USO PROGRESSIVO/DIFERENCIADO DA FORÇA: escala GRADUAL de níveis, conforme resistência/ameaça. MODELO (do menor ao maior): 1) PRESENÇA POLICIAL (uniformizado, visível); 2) VERBALIZAÇÃO (ordens, diálogo); 3) CONTROLE DE CONTATO (mãos vazias, técnicas leves); 4) TÁTICAS DEFENSIVAS (técnicas dolorosas, imobilização); 5) FORÇA MENOS LETAL (armas menos letais); 6) FORÇA LETAL (último recurso). NÃO é rígido: situações extremas podem pular níveis (ex: tiroteio → força letal imediata). Mas sempre buscar MENOR nível viável. Após controle: DESESCALAR (reduzir força).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsNiveisForca() {
  return seedGenericTopicQuestions('niveis-forca', 'Níveis de Força', '📊', [
    { question: 'O modelo de uso progressivo da força estabelece quantos níveis principais?', options: ['Apenas 2 níveis: não letal e letal', 'Tradicionalmente 5 a 6 níveis: presença, verbalização, controle, táticas defensivas, força menos letal, força letal', '3 níveis apenas', 'Não há níveis definidos', '10 níveis fixos'], correctAnswer: 1, explanation: 'MODELO TRADICIONAL (Polícia Militar - varia conforme corporação): 5-6 NÍVEIS: 1) NÍVEL 1 - Presença policial; 2) NÍVEL 2 - Verbalização; 3) NÍVEL 3 - Controle de contato (mãos vazias); 4) NÍVEL 4 - Táticas defensivas (técnicas dolorosas); 5) NÍVEL 5 - Força menos letal (spray, taser, munição de impacto); 6) NÍVEL 6 - Força letal (arma de fogo). Alguns modelos agrupam diferente. ESSÊNCIA: gradação do MENOR ao MAIOR potencial lesivo. Policial escolhe nível adequado à SITUAÇÃO (não precisa percorrer todos se há perigo iminente).', difficulty: 'easy', examBoard: 'VUNESP', year: 2024 },
    { question: 'Quanto à progressão entre níveis de força:', options: ['Deve sempre ser sequencial, sem pular níveis', 'Pode ser não-linear, conforme a ameaça e risco, podendo iniciar em nível mais alto se necessário', 'Apenas de baixo para cima', 'Não pode regredir após escalar', 'Sempre termina em força letal'], correctAnswer: 1, explanation: 'PROGRESSÃO NÃO-LINEAR: policial NÃO precisa percorrer todos os níveis sequencialmente. Pode INICIAR em nível mais alto se: perigo iminente, ameaça grave, circunstâncias urgentes. Exemplo: suspeito sacando arma → policial pode usar força letal IMEDIATAMENTE (não precisa verbalizar primeiro). DESESCALADA: após controlar, deve REDUZIR força ao mínimo necessário para manter controle. Exemplo: suspeito resistia com violência (nível 4), mas foi dominado → volta a nível 3 ou 2. Flexibilidade: essência do modelo. Proibido: usar força ALÉM do necessário, ou MANTER força alta após cessar ameaça.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'A avaliação do nível de força adequado deve considerar:', options: ['Apenas a gravidade do crime', 'A conduta do suspeito, nível de resistência/ameaça, capacidade de resposta do policial, circunstâncias', 'Somente a vontade do policial', 'Exclusivamente o tipo penal', 'Apenas se há testemunhas'], correctAnswer: 1, explanation: 'FATORES PARA ESCOLHA DO NÍVEL: 1) CONDUTA do suspeito (colaborativo, resistente, agressivo); 2) NÍVEL DE RESISTÊNCIA/AMEAÇA (passiva, ativa, agressão); 3) CAPACIDADE do policial (treinamento, condição física, equipamentos); 4) CIRCUNSTÂNCIAS (local, presença de terceiros, tempo disponível); 5) GRAVIDADE da situação. NÃO é apenas "gravidade do crime" (furto com suspeito atirando → força letal; roubo com suspeito rendido → sem força). Avaliação DINÂMICA: situação muda, nível muda. Treinamento: fundamental para decisão rápida e adequada.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { question: 'A força menos letal (nível 5) caracteriza-se por:', options: ['Nunca causar lesões', 'Ter baixa probabilidade de causar morte ou lesões graves, mas não garantia absoluta', 'Ser totalmente inofensiva', 'Dispensar cuidados médicos', 'Não ter limites de uso'], correctAnswer: 1, explanation: 'FORÇA MENOS LETAL (less-lethal): equipamentos/técnicas com BAIXA probabilidade de morte/lesão grave, mas NÃO são "não-letais" (non-lethal - termo incorreto). Exemplos: spray de pimenta, taser, munição de impacto controlado (borracha), gás lacrimogêneo. RISCOS: podem causar morte em situações específicas (taser em cardiopata, borracha em curta distância/olhos, spray em asmático grave). CUIDADOS: 1) Uso conforme protocolo; 2) Prestar socorro após; 3) Não usar como punição; 4) Avaliar vulnerabilidades. Mesmos princípios: necessidade, proporcionalidade.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Sobre a transição entre níveis de força:', options: ['É proibido regredir após escalar', 'Deve haver desescalada sempre que a situação permitir', 'Apenas aumenta, nunca diminui', 'Não é necessário reavaliar', 'Permanece fixo após escolhido'], correctAnswer: 1, explanation: 'DESESCALADA (de-escalation): tão importante quanto escalada. Após CONTROLAR situação, policial deve REDUZIR força ao mínimo necessário para manter controle. Exemplo: suspeito violento foi dominado → reduzir de imobilização intensa para contenção moderada. Suspeito rendeu → parar força. REAVALIAÇÃO CONTÍNUA: situação é dinâmica. Cessou ameaça? Reduz força. Voltou ameaça? Aumenta. Manter força DESNECESSÁRIA: excesso, abuso. Técnicas: comunicação ("calma, não vou te machucar"), afastamento tático, posicionamento. Objetivo final: RESOLUÇÃO sem violência sempre que possível.', difficulty: 'easy', examBoard: 'VUNESP', year: 2024 }
  ]);
}

export async function seedQuestionsPresencaPolicial() {
  return seedGenericTopicQuestions('presenca-policial', 'Presença Policial', '👮', [
    { question: 'A presença policial, como primeiro nível de força, caracteriza-se por:', options: ['Uso imediato de equipamentos', 'Simples presença uniformizada e identificada, que pode dissuadir condutas ilegais', 'Sempre exige abordagem física', 'Dispensa identificação visual', 'Apenas em patrulhamento motorizado'], correctAnswer: 1, explanation: 'PRESENÇA POLICIAL (Nível 1): SIMPLES presença do policial, uniformizado, identificado, visível. Efeito DISSUASÓRIO: presença pode prevenir crimes, interromper condutas ilegais, tranquilizar vítimas. NÃO envolve contato físico nem verbalização necessariamente. Exemplos: patrulhamento ostensivo, policial em pé de esquina, viatura circulando. Efetividade: muitos conflitos cessam apenas com chegada policial. Postura: profissional, alerta, confiante (não agressiva). Importante: identificação (uniforme, viatura) - policial à paisana não tem mesmo efeito dissuasório.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'Os elementos importantes da presença policial incluem:', options: ['Apenas estar no local', 'Uniforme, equipamentos visíveis, postura profissional, atenção situacional', 'Esconder equipamentos', 'Postura agressiva', 'Não precisa de uniforme'], correctAnswer: 1, explanation: 'ELEMENTOS DA PRESENÇA EFETIVA: 1) UNIFORME completo (identificação institucional); 2) EQUIPAMENTOS visíveis (colete, rádio - não necessariamente arma ostensiva); 3) POSTURA profissional (ereta, confiante, não agressiva nem relaxada); 4) ATENÇÃO SITUACIONAL (awareness - observar ambiente, pessoas, ameaças potenciais); 5) Linguagem corporal (aberta, não ameaçadora, mas firme). Objetivo: TRANSMITIR autoridade legítima, segurança, sem provocar escalada. Presença despreparada (desleixada, distraída): inefetiva. Presença agressiva: pode escalar desnecessariamente.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'A presença policial pode ser suficiente para:', options: ['Apenas observação, sem efeitos práticos', 'Prevenir crimes, interromper condutas, tranquilizar cidadãos, possibilitar avaliação da situação', 'Somente registro de ocorrências', 'Não tem função no uso da força', 'Apenas em crimes consumados'], correctAnswer: 1, explanation: 'FUNÇÕES DA PRESENÇA: 1) PREVENÇÃO: criminosos desistem ao ver polícia; 2) INTERRUPÇÃO: crime em andamento cessa com chegada policial; 3) TRANQUILIZAÇÃO: vítimas/cidadãos se sentem seguros; 4) AVALIAÇÃO: policial observa, analisa situação antes de agir; 5) CONTENÇÃO: presença mantém ordem sem força física. Estatística: maioria das intervenções policiais resolve-se APENAS com presença (sem força física/verbalização). Economia de força: resolver sem violência é objetivo. Presença bem executada: DESESCALA situações tensas.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'A atenção situacional (situational awareness) na presença policial significa:', options: ['Ignorar o ambiente', 'Observar e avaliar continuamente pessoas, ambiente, ameaças potenciais', 'Apenas olhar o suspeito', 'Não se preocupar com arredores', 'Focar apenas em documentos'], correctAnswer: 1, explanation: 'ATENÇÃO SITUACIONAL (situational awareness): capacidade de OBSERVAR, AVALIAR, ANTECIPAR continuamente. Policial deve: 1) Varrer ambiente (360º, não fixar olhar); 2) Identificar PESSOAS (quantas, comportamento, mãos visíveis); 3) Identificar AMEAÇAS potenciais (armas, rotas de fuga, coberturas); 4) Avaliar DINÂMICA (situação escalando ou desescalando); 5) Posicionar-se taticamente (distância, cobertura, rota de fuga própria). Cooper Color Code: branco (desatento) → amarelo (relaxado mas alerta) → laranja (alerta específico) → vermelho (confronto). Policial deve estar em AMARELO/LARANJA.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'O posicionamento tático na presença policial envolve:', options: ['Ficar parado em qualquer lugar', 'Manter distância segura, usar cobertura, garantir rota de retirada, ângulo de visão', 'Aproximar-se sempre ao máximo', 'Dar as costas é aceitável', 'Não importa a posição'], correctAnswer: 1, explanation: 'POSICIONAMENTO TÁTICO: 1) DISTÂNCIA REATIVA (reactionary gap): mínimo 2-3 metros de suspeito (tempo de reagir a ataque); 2) COBERTURA: usar obstáculos (veículos, muros) que protegem de disparos; 3) CONCEALMENT: ocultação visual (arbustos) - não protege de balas; 4) ÂNGULO DE VISÃO: ver suspeito e arredores; 5) ROTA DE RETIRADA: sempre ter saída; 6) Não dar COSTAS a ameaça; 7) Posição de VANTAGEM (terreno alto, iluminação favorável). Fatal funnel: evitar entradas/corredores (funil de morte). Triângulo da vida: distância + cobertura + atenção = sobrevivência.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsVerbalizacao() {
  return seedGenericTopicQuestions('verbalizacao', 'Verbalização', '🗣️', [
    { question: 'A verbalização, como segundo nível de força, consiste em:', options: ['Gritar e ameaçar', 'Comunicação verbal clara, ordens diretas, comandos de voz, persuasão', 'Apenas perguntas', 'Diálogo informal sem direção', 'Xingamentos'], correctAnswer: 1, explanation: 'VERBALIZAÇÃO (Nível 2): uso da COMUNICAÇÃO VERBAL para controlar situação. Tipos: 1) COMANDOS DE VOZ (ordens claras: "POLÍCIA! PARE! MÃOS NA CABEÇA!"); 2) PERSUASÃO (convencer: "Vamos conversar, não precisa ser assim"); 3) ORIENTAÇÕES ("Mantenha calma, não será ferido"); 4) ADVERTÊNCIAS ("Se não parar, usarei força"). Características: voz FIRME (não agressiva), CLARA, DIRETA. Tom: autoridade sem desrespeito. Objetivo: COMPLIANCE (obediência) sem força física. Não é: gritar desnecessariamente, xingar, humilhar.', difficulty: 'easy', examBoard: 'VUNESP', year: 2024 },
    { question: 'Os elementos de uma verbalização efetiva incluem:', options: ['Voz baixa e incerta', 'Voz firme, comandos claros e diretos, tom respeitoso mas autoritativo, linguagem simples', 'Xingamentos e ameaças', 'Gírias e linguagem informal', 'Falar baixo e rápido'], correctAnswer: 1, explanation: 'VERBALIZAÇÃO EFETIVA: 1) VOZ FIRME (confiante, não gritada desnecessariamente); 2) COMANDOS CLAROS ("Pare!" melhor que "Seria bom parar"); 3) DIRETOS (sem rodeios); 4) Tom RESPEITOSO mas AUTORITATIVO (não subserviente nem arrogante); 5) LINGUAGEM SIMPLES (todos entendem); 6) REPETIÇÃO se necessário; 7) Contato visual; 8) Linguagem corporal coerente (gestos reforçam palavras). Evitar: gírias, palavrões (podem escalar), ameaças vazias, múltiplos comandos simultâneos (confunde). "PARE! MÃOS NA CABEÇA! DEVAGAR!" - cada comando, uma ação.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'A escuta ativa durante a verbalização significa:', options: ['Apenas falar, não ouvir', 'Ouvir atentamente o interlocutor, demonstrar compreensão, responder adequadamente', 'Interromper constantemente', 'Ignorar o que dizem', 'Apenas dar ordens'], correctAnswer: 1, explanation: 'ESCUTA ATIVA (active listening): técnica de comunicação que melhora verbalização. Elementos: 1) ATENÇÃO (ouvir genuinamente, não apenas esperar sua vez de falar); 2) DEMONSTRAR compreensão ("Entendo que está nervoso"); 3) PARAFRASEAR ("Você está dizendo que..."); 4) NÃO interromper desnecessariamente; 5) Validar sentimentos sem concordar com crime ("Sei que está difícil, mas não pode fazer isso"); 6) Fazer perguntas abertas. Benefícios: reduz tensão, constrói rapport, obtém informações, facilita rendição. Não significa: ser passivo, aceitar tudo. Equilíbrio: firmeza + empatia.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { question: 'A comunicação não-verbal durante verbalização:', options: ['Não é importante', 'Deve ser congruente com verbal: postura, gestos, expressão facial reforçam mensagem', 'Pode contradizer a fala', 'Apenas palavras importam', 'Gestos agressivos são recomendados'], correctAnswer: 1, explanation: 'COMUNICAÇÃO NÃO-VERBAL: 55% da mensagem é linguagem corporal, 38% tom de voz, apenas 7% palavras. Deve ser CONGRUENTE: 1) POSTURA ereta, confiante (não agressiva); 2) GESTOS deliberados (apontar direção, palma aberta "PARE"); 3) EXPRESSÃO FACIAL firme (não raivosa); 4) CONTATO VISUAL (autoridade, sinceridade); 5) Distância adequada (nem invadindo espaço pessoal nem distante demais). INCONGRUÊNCIA: dizer "calma" com punhos cerrados → confunde, desacredita. Braços cruzados: defensivo. Apontar dedo: agressivo. Palmas abertas: tranquilizador.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Quando a verbalização falha ou é inviável:', options: ['Insistir indefinidamente', 'Policial deve avaliar progressão para próximo nível de força se necessário', 'Desistir da ação', 'Sempre esperar mais tempo', 'Nunca usar força'], correctAnswer: 1, explanation: 'LIMITES DA VERBALIZAÇÃO: não funciona sempre. Falha quando: 1) Suspeito RECUSA obedecer; 2) Está sob efeito de DROGAS/ÁLCOOL (não compreende); 3) DOENÇA MENTAL grave; 4) BARREIRA de idioma; 5) PERIGO IMINENTE (não há tempo). Nesses casos: policial deve PROGREDIR para nível superior (controle de contato, táticas defensivas). Não é: insistir indefinidamente (policial/terceiros em risco) nem desistir (crime continua). Regra: tentar verbalização quando SEGURO e VIÁVEL. Se não funciona/não é possível: escalar. Sempre documentar tentativas de verbalização no relatório.', difficulty: 'easy', examBoard: 'VUNESP', year: 2024 }
  ]);
}

export async function seedQuestionsControleContato() {
  return seedGenericTopicQuestions('controle-de-contato', 'Controle de Contato', '🤲', [
    { question: 'O controle de contato (mãos vazias) caracteriza-se por:', options: ['Uso de armas', 'Técnicas de controle físico com mãos vazias, baixo potencial lesivo', 'Apenas técnicas dolorosas', 'Força letal', 'Não envolve contato físico'], correctAnswer: 1, explanation: 'CONTROLE DE CONTATO (Nível 3): técnicas físicas com MÃOS VAZIAS (sem armas), BAIXO potencial lesivo. Objetivos: 1) CONDUZIR suspeito (pegar braço, guiar); 2) IMOBILIZAR (segurar, conter movimento); 3) CONTROLAR (impedir ações); 4) ALGEMAR. Técnicas: pegadas de pulso, braço, escolta, controle de articulações (sem torção excessiva). Resistência passiva: suspeito não obedece mas não agride (ex: sentado no chão recusando levantar) → controle de contato adequado. NÃO é: socar, chutar, técnicas dolorosas (nível 4).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'As técnicas de controle de contato devem priorizar:', options: ['Máxima dor', 'Controle de articulações, pontos de pressão, alavancas, com mínimo de lesão', 'Estrangulamento', 'Golpes traumáticos', 'Força máxima sempre'], correctAnswer: 1, explanation: 'TÉCNICAS PREFERIDAS: 1) CONTROLE DE ARTICULAÇÕES (pulso, cotovelo, ombro) - limitação de movimento sem lesão; 2) PONTOS DE PRESSÃO (nervos) - dor compliance sem trauma; 3) ALAVANCAS (mecânica corporal favorece policial); 4) ESCOLTA/CONDUÇÃO (guiar respeitosamente). Princípio: CONTROLE > DOR > LESÃO. Evitar: técnicas de alto risco (estrangulamento - pode ser letal, golpes articulares com quebra, pressão excessiva). Treinamento: essencial (técnica errada → lesão ou ineficácia). Vulneráveis (idosos, crianças, grávidas): cuidado EXTRA.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'O controle de contato é apropriado para situações de:', options: ['Resistência ativa agressiva com arma', 'Resistência passiva ou ativa não agressiva', 'Tiroteio', 'Apenas crimes hediondos', 'Nunca deve ser usado'], correctAnswer: 1, explanation: 'QUANDO USAR CONTROLE DE CONTATO: 1) RESISTÊNCIA PASSIVA: suspeito recusa obedecer mas não agride (ex: ativista deitado bloqueando via); 2) RESISTÊNCIA ATIVA NÃO AGRESSIVA: tenta fugir, empurrar, mas não ataca (ex: tentando correr); 3) Necessidade de CONDUZIR colaborativo (não é resistência, é condução). NÃO usar se: resistência AGRESSIVA (socos, chutes - escalar para nível 4), ARMA (escalar para arma menos letal ou letal), perigo iminente. Regra: força equivalente + 1 nível (para prevalecer). Resistência passiva → controle contato. Agressão → táticas defensivas.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'Durante o controle de contato, o policial deve:', options: ['Aplicar força máxima sempre', 'Comunicar-se, orientar movimentos, usar força mínima necessária', 'Não falar com suspeito', 'Usar técnicas dolorosas automaticamente', 'Não explicar o que está fazendo'], correctAnswer: 1, explanation: 'BOM CONTROLE DE CONTATO: 1) COMUNICAÇÃO contínua ("Vou algemar, não resista", "Coloque mão nas costas"); 2) ORIENTAR movimentos ("Vire-se devagar", "Ajoelhe"); 3) Força MÍNIMA necessária (não esmagar, não torcer excessivamente); 4) MONITORAR sinais de dor/desconforto extremo; 5) RESPEITO à dignidade (não humilhar); 6) Após controle: AFROUXAR (não manter força desnecessária). Benefícios comunicação: reduz resistência (pessoa entende o que esperar), previne mal-entendidos, demonstra profissionalismo. Suspeito que colabora: tratamento mais suave.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Sobre o controle de pessoas em situação de vulnerabilidade (idosos, grávidas, crianças):', options: ['Usar força igual a adultos jovens', 'Redobrar cuidados, avaliar técnicas menos lesivas, considerar fragilidades', 'Não abordar nunca', 'Aplicar técnicas dolorosas', 'Não há diferença no tratamento'], correctAnswer: 1, explanation: 'GRUPOS VULNERÁVEIS: 1) IDOSOS: ossos frágeis (osteoporose), quedas perigosas, condições cardíacas; 2) GRÁVIDAS: risco ao feto, quedas graves; 3) CRIANÇAS: estrutura menor, trauma psicológico; 4) DEFICIENTES: limitações físicas/mentais. CUIDADOS: 1) AVALIAR técnicas (evitar quedas, torções); 2) Preferir ESCOLTA suave; 3) COMUNICAÇÃO adaptada; 4) Acionar SUPERVISÃO/serviços sociais quando possível; 5) Documentar cuidados. NÃO significa: não abordar (se crime/risco, abordar SIM), ser negligente (controlar adequadamente), mas ADAPTAR técnicas. Dignidade humana: especial atenção a vulneráveis.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsTecnicasImobilizacao() {
  return seedGenericTopicQuestions('tecnicas-imobilizacao', 'Técnicas de Imobilização', '🔒', [
    { question: 'As técnicas de imobilização (táticas defensivas - nível 4) caracterizam-se por:', options: ['Controle suave sem dor', 'Técnicas que causam dor ou desequilíbrio para vencer resistência ativa agressiva', 'Apenas conversa', 'Força letal', 'Não envolvem contato físico'], correctAnswer: 1, explanation: 'TÁTICAS DEFENSIVAS/IMOBILIZAÇÃO (Nível 4): técnicas que causam DOR, DESEQUILÍBRIO, ou DESORIENTAÇÃO temporária para vencer RESISTÊNCIA ATIVA AGRESSIVA (suspeito ataca com socos, chutes, mordidas). Inclui: bloqueios, golpes de impacto não letal (soco, joelhada em áreas permitidas), chaves articulares dolorosas, quedas controladas, spray de pimenta manual. Objetivo: CESSAR agressão, IMOBILIZAR para algemar. Não é força letal (não visa morte), mas pode causar LESÕES (fraturas, hematomas). Usar apenas se necessário: controle de contato falhou ou é insuficiente.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'Durante a aplicação de técnicas de imobilização, o policial deve evitar:', options: ['Qualquer técnica', 'Golpes na cabeça, coluna, pescoço, genitais; pressão prolongada no tórax', 'Comunicar-se', 'Observar o suspeito', 'Usar técnicas de contenção'], correctAnswer: 1, explanation: 'ÁREAS PROIBIDAS/ALTO RISCO: 1) CABEÇA (trauma craniano, morte); 2) COLUNA (paralisia); 3) PESCOÇO/GARGANTA (estrangulamento, morte); 4) GENITAIS (lesão grave, desproporcional); 5) PRESSÃO PROLONGADA no TÓRAX (asfixia posicional - "I can\'t breathe" - morte por compressão). ÁREAS PERMITIDAS (impacto controlado): membros (braços, pernas - músculos grandes), tronco lateral (evitar órgãos vitais). Após dominar: CESSAR golpes, assumir posição segura. Monitorar respiração (se dificuldade: reposicionar URGENTE). Morte em custódia: responsabilidade criminal.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'A posição de segurança após imobilização deve:', options: ['Manter suspeito de bruços indefinidamente', 'Evitar asfixia posicional, permitir respiração, colocar em decúbito lateral ou sentado quando possível', 'Pressionar tórax continuamente', 'Ignorar sinais de dificuldade respiratória', 'Algemar com joelho nas costas prolongado'], correctAnswer: 1, explanation: 'ASFIXIA POSICIONAL: morte por compressão torácica impedindo respiração. CAUSAS: 1) Decúbito ventral (bruços) + peso policial nas costas; 2) Hogtie (amarrar pés e mãos juntos - proibido); 3) Obesidade/drogas estimulantes (aumentam risco). PREVENÇÃO: 1) Após algemar: VIRAR para DECÚBITO LATERAL (recovery position) ou SENTAR; 2) NÃO manter peso no tórax/costas; 3) MONITORAR respiração ("Consegue respirar?" - se não responde: emergência); 4) Chamar socorro se necessário. Casos famosos: George Floyd, Eric Garner. Treinar: posicionamento seguro salva vidas.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'Sobre técnicas de estrangulamento (choke holds):', options: ['São recomendadas em qualquer situação', 'Devem ser evitadas ou proibidas na maioria das polícias por risco de morte', 'Não causam risco', 'Podem ser aplicadas sem treinamento', 'São técnicas de controle suave'], correctAnswer: 1, explanation: 'ESTRANGULAMENTO (choke/neck restraint): técnica que comprime pescoço, interrompendo: 1) FLUXO SANGUÍNEO (blood choke - carotídeo): inconsciência em 5-15 segundos, morte em minutos se mantido; 2) FLUXO DE AR (air choke - traqueia): sufocamento, morte. RISCOS ALTOS: morte, lesão cerebral, fratura de laringe. TENDÊNCIA ATUAL: maioria das polícias PROÍBE ou RESTRINGE severamente (apenas situações extremas de risco de vida, último recurso antes de arma letal). Exemplos: NYPD proibiu após Eric Garner. Uso indevido: homicídio. Se permitido: exige treinamento rigoroso, aplicação correta (segundos, não minutos), liberar imediatamente após rendição.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Após aplicar técnicas de imobilização, o policial deve:', options: ['Ignorar lesões do suspeito', 'Prestar primeiros socorros, acionar serviço médico se necessário, documentar uso de força', 'Deixar algemado sem assistência', 'Não informar supervisor', 'Continuar aplicando força'], correctAnswer: 1, explanation: 'PÓS-IMOBILIZAÇÃO (dever de cuidado): 1) CESSAR força (ameaça controlada); 2) AVALIAR lesões (sangramento, fraturas, dificuldade respiratória); 3) PRIMEIROS SOCORROS (estancar sangue, posição segura); 4) ACIONAR SAMU/serviço médico (lesões moderadas/graves); 5) MONITORAR continuamente (piora súbita); 6) DOCUMENTAR uso de força (relatório detalhado); 7) INFORMAR supervisor; 8) Preservar cena se perícia necessária. RESPONSABILIDADE: policial responde por omissão de socorro (CP art. 135). Suspeito sob custódia: Estado garante integridade. Negligência pós-força: agravante.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsForcaMenosLetal() {
  return seedGenericTopicQuestions('forca-menos-letal', 'Força Menos Letal', '⚡', [
    { question: 'Armas ou equipamentos de força menos letal (less-lethal) são definidos como:', options: ['Totalmente inofensivos', 'Equipamentos com baixa probabilidade de causar morte ou lesão grave, mas não garantia absoluta', 'Sempre não letais', 'Sem necessidade de protocolo', 'Podem ser usados sem restrições'], correctAnswer: 1, explanation: 'FORÇA MENOS LETAL (less-lethal, não "non-lethal"): equipamentos projetados para BAIXA probabilidade de morte/lesão grave, mas NÃO garantia absoluta. Exemplos: 1) Spray de pimenta (OC); 2) Taser/CEW (arma de choque elétrico); 3) Munição de impacto controlado (projéteis de borracha, bean bags); 4) Bastão (tonfa); 5) Gás lacrimogêneo. PODE MATAR em circunstâncias: distância inadequada, alvo vulnerável (cardíaco, asmático), uso repetido, áreas vitais. Portanto: mesmos princípios (necessidade, proporcionalidade), protocolos de uso, cuidados médicos após.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'O spray de pimenta (OC - Oleoresin Capsicum) deve ser usado:', options: ['Sem limitações', 'A distância segura, evitando exposição prolongada, considerando ambiente fechado e vulnerabilidades', 'Sempre em ambientes fechados', 'Direto nos olhos de perto', 'Sem considerar condições de saúde'], correctAnswer: 1, explanation: 'SPRAY DE PIMENTA: irritante derivado de pimenta que causa ardência intensa, lacrimejamento, tosse, dificuldade respiratória temporária. USO CORRETO: 1) DISTÂNCIA: 1-2 metros (muito perto: pode lesar olhos; longe: ineficaz); 2) Rajadas CURTAS (1-2 segundos, não esvaziar lata); 3) Mirar ROSTO (olhos/nariz); 4) AMBIENTE aberto preferível (fechado: contamina todos, inclusive policiais); 5) VENTO: atenção à direção (evitar auto-contaminação). RISCOS: asmáticos graves, DPOC (pode causar parada respiratória), alérgicos severos. PÓS-USO: lavar com água fria, ar fresco, monitorar respiração.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'O taser (CEW - Conducted Electrical Weapon) funciona por:', options: ['Impacto físico apenas', 'Descarga elétrica que causa incapacitação neuromuscular temporária', 'Queimaduras graves', 'Som alto', 'Luz cegante'], correctAnswer: 1, explanation: 'TASER/CEW: dispara 2 dardos conectados a fios que aplicam descarga elétrica (50.000 volts, baixa amperagem) causando INCAPACITAÇÃO NEUROMUSCULAR (músculos contraem, pessoa cai, não consegue se mover). Duração: 5 segundos por ciclo (pode repetir). EFETIVO contra: resistência ativa violenta, suspeito com faca (a distância), situações onde controle físico é arriscado. RISCOS: 1) CARDÍACOS: pode desencadear arritmia fatal (raro, mas documentado); 2) QUEDAS: traumatismo craniano; 3) MÚLTIPLOS CICLOS: aumenta risco. PROIBIÇÕES: não usar em grávidas, crianças, idosos frágeis, pessoas em altura (queda fatal). Distância: 2-7 metros ideal.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'Munições de impacto controlado (projéteis de borracha, bean bags) devem:', options: ['Ser disparadas na cabeça', 'Ser disparadas em grandes grupos musculares, evitando cabeça, pescoço, genitais, à distância mínima segura', 'Ser usadas a queima-roupa', 'Não seguir protocolo', 'Sempre atingir múltiplas vezes'], correctAnswer: 1, explanation: 'MUNIÇÃO DE IMPACTO CONTROLADO: projéteis de borracha, espuma, bean bags (saquinhos de chumbo), lançados por espingarda/lançador. OBJETIVO: dor/impacto que incapacita sem perfuração. USO CORRETO: 1) DISTÂNCIA MÍNIMA: 5-10 metros (perto demais: pode perfurar, quebrar ossos); 2) ALVO: grandes MÚSCULOS (coxas, nádegas, tronco inferior - evitar órgãos vitais); 3) EVITAR: cabeça (cegueira, morte), pescoço, coluna, genitais; 4) Disparo ÚNICO (avaliar efeito antes de repetir). MORTES documentadas: tiro na cabeça, peito (coração). Distúrbios civis: uso em massa exige cuidado redobrado.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Após o uso de força menos letal, o policial deve:', options: ['Deixar suspeito sem assistência', 'Prestar socorro imediato, avaliar lesões, acionar serviço médico, documentar', 'Não informar nada', 'Aplicar mais força se não obedeceu', 'Ignorar queixas de dor'], correctAnswer: 1, explanation: 'PÓS-USO FORÇA MENOS LETAL: 1) SOCORRO IMEDIATO: descontaminar spray (água), remover dardos taser (protocolo médico), avaliar impactos (munição); 2) SINAIS VITAIS: respiração, consciência, pulso (taser: risco cardíaco; spray: respiratório); 3) ACIONAR MÉDICO: sempre em idosos, cardíacos, múltiplos disparos, queixas graves; 4) DOCUMENTAR: equipamento usado, quantos disparos, justificativa, lesões observadas; 5) FOTOGRAFAR lesões (prova). DEVER DE CUIDADO: força menos letal não isenta responsabilidade. Mortes ocorrem: policial responde se omitir socorro ou usar inadequadamente.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsForcaLetal() {
  return seedGenericTopicQuestions('forca-letal', 'Força Letal', '🔫', [
    { question: 'A força letal (arma de fogo) só pode ser empregada quando:', options: ['Em qualquer crime', 'Houver ameaça iminente de morte ou lesão grave ao policial ou terceiros, e não há outro meio menos lesivo viável', 'Suspeito está fugindo de furto', 'Para intimidar', 'Como primeira opção'], correctAnswer: 1, explanation: 'FORÇA LETAL (último recurso): uso da arma de fogo visando PARAR ameaça de MORTE ou LESÃO GRAVE iminente. REQUISITOS CUMULATIVOS (ONU): 1) AMEAÇA GRAVE E IMINENTE à vida (policial ou terceiro); 2) NECESSIDADE ABSOLUTA (outros meios não funcionam/não há tempo); 3) PROPORCIONALIDADE (ameaça justifica força letal). EXEMPLOS VÁLIDOS: suspeito atirando, esfaqueando vítima, apontando arma. EXEMPLOS INVÁLIDOS: fuga de crime patrimonial sem violência, resistência passiva, ameaça verbal sem arma. Erro: homicídio doloso ou culposo.', difficulty: 'easy', examBoard: 'VUNESP', year: 2024 },
    { question: 'A regra dos 21 pés (6,4 metros) estabelece que:', options: ['Distância mínima para conversar', 'Distância na qual suspeito com faca pode atingir policial antes que este saque e dispare', 'Distância de tiro de advertência', 'Tamanho do perímetro de segurança', 'Distância para usar spray'], correctAnswer: 1, explanation: '21-FOOT RULE (Dennis Tueller, 1983): pesquisa demonstrou que suspeito com FACA a 21 pés (6,4m) pode ATACAR policial em 1,5 segundos - tempo menor que sacar arma de coldre e disparar com precisão. IMPLICAÇÃO: suspeito com arma branca a distância curta = ameaça LETAL iminente (uso de arma de fogo pode ser justificado). MAS: não é regra automática. Fatores: suspeito está avançando? Há barreiras? Policial está com arma em punho? Há cobertura? Pode recuar? Análise CONTEXTUAL. Crítica: aplicação rígida levou a mortes evitáveis. Melhor: treinamento em desescalada, distância tática, uso de menos letais quando viável.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'Ao empregar força letal, o policial deve:', options: ['Atirar para matar sempre', 'Atirar para parar a ameaça, mirando centro de massa (tronco), cessando disparos quando ameaça cessar', 'Dar múltiplos tiros sem avaliar', 'Mirar cabeça sempre', 'Continuar atirando após rendição'], correctAnswer: 1, explanation: 'DISPARO POLICIAL: 1) OBJETIVO: PARAR ameaça (incapacitar, não necessariamente matar - embora morte seja consequência provável); 2) ALVO: CENTRO DE MASSA (tronco/peito - área maior, maior chance de acerto, órgãos vitais param ameaça); NÃO cabeça (difícil, risco balas perdidas); NÃO membros (ineficaz, difícil); 3) SEQUÊNCIA: disparos até ameaça CESSAR (pode ser 1 tiro ou vários - depende de reação); 4) REAVALIAR: ameaça parou? (desarmou, caiu, rendeu) → PARAR disparos; 5) NUNCA: "tiro de misericórdia" (executar rendido/ferido = homicídio). Pós: socorro, preservar cena, não alterar provas.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { question: 'O tiro de advertência (warning shot):', options: ['É sempre recomendado', 'É geralmente proibido ou desaconselhado por risco de balas perdidas e ineficácia', 'Deve ser o primeiro tiro', 'Pode ser dado em qualquer direção', 'Substitui verbalização'], correctAnswer: 1, explanation: 'TIRO DE ADVERTÊNCIA: disparo PARA O AR ou SOLO para intimidar/avisar. PROBLEMAS: 1) BALAS PERDIDAS: tiro para cima cai e pode matar inocente (gravidade); solo: ricochete imprevisível; 2) INEFICÁCIA: se há tempo para advertir, talvez não haja ameaça letal iminente (contradição); 3) DESPERDÍCIO de munição (em tiroteio real, cada bala conta); 4) Pode ESCALAR situação (assustar pessoas). POLÍTICAS: maioria das corporações PROÍBE ou desaconselha fortemente. EXCEÇÃO rara: certas leis antigas (Brasil: Lei 4898/65 em desuso; preferir verbalização). REGRA: se usa arma, é para PARAR ameaça letal, não intimidar.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'Após uso de força letal com resultado morte, o policial deve:', options: ['Fugir do local', 'Prestar socorro, acionar SAMU, preservar cena, não alterar provas, comunicar imediatamente, colaborar com investigação', 'Recolher cápsulas', 'Limpar sangue', 'Não informar supervisor'], correctAnswer: 1, explanation: 'PROCEDIMENTOS PÓS-DISPARO FATAL: 1) SEGURANÇA: garantir que não há mais ameaças; 2) ARMAS: desarmar suspeito (se não feito); 3) SOCORRO: mesmo ferimento mortal, prestar primeiros socorros, acionar SAMU (dever legal - art. 135 CP); 4) PRESERVAR CENA: isolar, NÃO tocar em provas (cápsulas, armas, sangue), marcar posições; 5) COMUNICAR: supervisor, corregedoria, investigação (homicídio é sempre investigado - legítima defesa é excludente, mas precisa ser provada); 6) NÃO ALTERAR: trocar arma, recarregar antes de perícia, combinar versão; 7) DIREITO: advogado, silêncio (não obrigado a auto-incriminar, mas cooperar). Investigação: perícia, testemunhas, vídeos.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedQuestionsRelatorioUsoForca() {
  return seedGenericTopicQuestions('relatorio-uso-forca', 'Relatório de Uso da Força', '📋', [
    { question: 'O relatório de uso da força deve ser elaborado:', options: ['Apenas se houver morte', 'Sempre que houver emprego de força além da presença e verbalização', 'Só se vítima reclamar', 'Nunca é necessário', 'Apenas em força letal'], correctAnswer: 1, explanation: 'OBRIGATORIEDADE DO RELATÓRIO: uso de força ACIMA de presença/verbalização EXIGE documentação formal. Incluir: 1) Controle de contato; 2) Táticas defensivas; 3) Força menos letal; 4) Força letal. PRAZO: imediato (ao fim do turno/24h - conforme protocolo). OBJETIVO: 1) TRANSPARÊNCIA (accountability); 2) Revisão supervisória; 3) Identificar padrões (treinamento, disciplina); 4) PROVA (processo criminal/civil); 5) Estatísticas. NÃO relatar: omissão, obstrução de justiça. Relatório DETALHADO, HONESTO (mentir: agrava responsabilidade).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { question: 'O relatório de uso da força deve conter:', options: ['Apenas data e hora', 'Circunstâncias, tipo de resistência, nível de força usado, tentativas prévias, lesões, testemunhas, justificativa', 'Só o nome do suspeito', 'Não precisa de detalhes', 'Apenas a conclusão'], correctAnswer: 1, explanation: 'CONTEÚDO MÍNIMO DO RELATÓRIO: 1) CONTEXTO: data, hora, local, motivo da intervenção (crime, chamado); 2) PARTES: policial(is), suspeito(s), testemunhas, vítima(s); 3) CONDUTA do suspeito: tipo de resistência (passiva, ativa, agressiva), armas, ameaças; 4) TENTATIVAS PRÉVIAS: verbalização (o que disse), tempo dado, por que falhou; 5) FORÇA USADA: nível, técnicas específicas, quantas vezes, por quê; 6) LESÕES: suspeito, policial, terceiros (descrever, fotografar); 7) SOCORRO: médico acionado, hospital; 8) TESTEMUNHAS: nome, contato; 9) PROVAS: vídeos, áudios; 10) JUSTIFICATIVA: por que força era necessária, proporcional, legal.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { question: 'A importância de documentar tentativas de desescalada e verbalização no relatório está em:', options: ['Não é importante', 'Demonstrar que força foi último recurso, atendendo princípio da necessidade', 'Apenas preencher espaço', 'Confundir investigação', 'Não precisa documentar isso'], correctAnswer: 1, explanation: 'DOCUMENTAR DESESCALADA: crucial para demonstrar NECESSIDADE (princípio fundamental). Tribunal/corregedoria perguntará: "Por que não tentou X antes de usar força?". REGISTRAR: 1) O QUE DISSE: comandos verbais exatos ("PARE! POLÍCIA! MÃOS NA CABEÇA!"); 2) QUANTAS VEZES: repetiu? 3) RESPOSTA do suspeito: ignorou, desafiou, atacou; 4) POR QUE PAROU de verbalizar: perigo iminente, ineficaz, não havia tempo; 5) OUTRAS tentativas: recuo tático, pedir reforço, negociação. PROVA: testemunhas, câmeras (bodycam, viatura). Falta de tentativas documentadas: presunção de uso precipitado/desnecessário.', difficulty: 'hard', examBoard: 'VUNESP', year: 2024 },
    { question: 'Sobre evidências audiovisuais (bodycam, dash cam, celulares) no contexto de uso da força:', options: ['Não são relevantes', 'São cruciais, devem ser preservadas, não editadas, incluídas no relatório, podem proteger policial ou incriminá-lo', 'Podem ser apagadas', 'Só importam se favoráveis', 'Não precisam ser mencionadas'], correctAnswer: 1, explanation: 'EVIDÊNCIAS AUDIOVISUAIS: cada vez mais ESSENCIAIS (bodycams obrigatórias em muitas polícias). VANTAGENS: 1) OBJETIVIDADE (não depende de memória/versão); 2) Protege policial CORRETO (prova legítima defesa); 3) Identifica policial ABUSIVO (responsabilização); 4) Reduz queixas infundadas; 5) Melhora comportamento (efeito câmera). OBRIGAÇÕES: 1) LIGAR bodycam ANTES de intervenção (desligar: presunção de má-fé); 2) NÃO editar, deletar (adulteração de prova - crime); 3) PRESERVAR arquivos (evidência); 4) Mencionar no relatório ("conforme vídeo anexo"); 5) Fornecer à investigação/defesa. Vídeo contradiz relatório: policial perde credibilidade, pode ser processado.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    { question: 'A revisão do relatório de uso da força por supervisores visa:', options: ['Apenas arquivar', 'Identificar uso inadequado, necessidade de treinamento, padrões, responsabilização, melhorias', 'Proteger policial sempre', 'Encobrir erros', 'Não é necessária'], correctAnswer: 1, explanation: 'REVISÃO SUPERVISÓRIA: não é mera formalidade, é CONTROLE INTERNO essencial. OBJETIVOS: 1) IDENTIFICAR uso inadequado: desnecessário, desproporcional, ilegal → medidas disciplinares/criminais; 2) TREINAMENTO: policial usou técnica errada? Precisa reciclagem?; 3) PADRÕES: determinado policial usa força com frequência excessiva? (alerta); 4) POLÍTICAS: táticas/equipamentos são eficazes? Precisam mudanças?; 5) RESPONSABILIZAÇÃO: supervisor que não revisa/age: conivente (responsabilidade solidária). MELHORES PRÁTICAS: revisão por oficial não envolvido, prazos (48-72h), sistema de flags (casos graves sobem para corregedoria), transparência. Relatórios acumulam: banco de dados (early warning systems).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 }
  ]);
}

export async function seedAllUsoProgressivoForcaQuestions() {
  console.log('🚀 Starting Uso Progressivo da Força questions import...');
  try {
    await seedQuestionsPrincipiosUsoForca();
    await seedQuestionsNiveisForca();
    await seedQuestionsPresencaPolicial();
    await seedQuestionsVerbalizacao();
    await seedQuestionsControleContato();
    await seedQuestionsTecnicasImobilizacao();
    await seedQuestionsForcaMenosLetal();
    await seedQuestionsForcaLetal();
    await seedQuestionsRelatorioUsoForca();
    console.log('✅ ALL USO PROGRESSIVO DA FORÇA QUESTIONS IMPORTED! 🎯⚡');
    console.log('📊 Total: 45 questions across 9 topics');
  } catch (error) {
    console.error('❌ Error importing Uso Progressivo da Força questions:', error);
    throw error;
  }
}
