import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    console.log('🔍 [MERCADO] Sending question to:', `${API_BASE}/questions`);

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ [MERCADO] Error response:', response.status, errorText);
      throw new Error(`Failed to save question: ${response.status} - ${errorText}`);
    }

    const result = await response.json();
    console.log('✅ [MERCADO] Question saved successfully');
    return result;
  } catch (error) {
    console.error('❌ [MERCADO] Error saving question:', error);
    console.error('❌ [MERCADO] Error details:', error.message, error.stack);
    throw error;
  }
}

// ============= ALL MERCADO DE CAPITAIS QUESTIONS =============
export async function seedAllMercadoCapitaisQuestions() {
  console.log('📈 Starting to seed ALL Mercado de Capitais questions...');
  
  const allQuestions: Question[] = [
    // ========== 1. AÇÕES - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'acoes', question: 'As ações são valores mobiliários que representam a menor fração do capital social de uma sociedade anônima. Sobre as ações ordinárias (ON), é correto afirmar que:', options: ['Garantem prioridade no recebimento de dividendos mínimos', 'Conferem direito de voto nas assembleias gerais da companhia', 'Não podem ser negociadas em bolsa de valores', 'Têm preferência no reembolso de capital em caso de liquidação', 'São sempre nominativas e endossáveis'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Ações ORDINÁRIAS (ON) dão DIREITO A VOTO nas assembleias (1 ação = 1 voto). CARACTERÍSTICAS: participação nas decisões estratégicas, eleição de conselheiros, aprovação de balanços. Não têm prioridade em dividendos (A errada - isso é das preferenciais). Podem ser negociadas em bolsa (C errada). Preferência no reembolso é das preferenciais (D errada). São nominativas e escriturais (E errada - não são endossáveis). Lei 6.404/76 (Lei das S.A.).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'acoes', question: 'As ações preferenciais (PN) diferenciam-se das ordinárias principalmente por:', options: ['Sempre conferirem direito de voto', 'Garantirem dividendo fixo obrigatório de 25% do lucro', 'Poderem ter prioridade no recebimento de dividendos e/ou no reembolso de capital', 'Não poderem ser convertidas em ordinárias', 'Serem exclusivas de companhias fechadas'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Ações PREFERENCIAIS (PN) podem ter PREFERÊNCIAS: 1) Dividendo mínimo/fixo; 2) Prioridade distribuição dividendos; 3) Prioridade reembolso capital (liquidação). VOTO: geralmente NÃO votam (A errada), MAS adquirem voto se dividendo não for pago por 3 anos. Dividendo não é fixo em 25% (B errada). Podem ser convertidas (D errada). Companhias abertas e fechadas podem ter (E errada). Tag along: 80% do valor pago às ON.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'acoes', question: 'Sobre dividendos e proventos de ações, analise: I. Dividendos são obrigatórios se houver lucro, conforme estatuto. II. Bonificação é distribuição de novas ações sem custo ao acionista. III. Juros sobre Capital Próprio (JCP) são dedutíveis de IR para a empresa. Está correto:', options: ['Apenas I', 'Apenas I e II', 'Apenas II e III', 'Apenas I e III', 'I, II e III'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (todas). I - DIVIDENDOS: se há lucro, pagamento é obrigatório conforme estatuto (mínimo 25% lucro líquido se estatuto omisso). II - BONIFICAÇÃO: incorporação reservas ao capital → novas ações distribuídas gratuitamente aos acionistas (não altera % participação). III - JCP: alternativa aos dividendos, DEDUTÍVEL de IR/CSLL para empresa (reduz tributos), limitado à TJLP. DESDOBRAMENTO (split): divide ações (não bonificação). GRUPAMENTO: agrupa ações.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'acoes', question: 'O direito de subscrição em uma oferta pública de ações (follow-on) permite ao acionista:', options: ['Vender suas ações com ágio obrigatório', 'Adquirir novas ações na proporção das que já possui, mantendo sua participação', 'Votar em assembleias sem comparecer presencialmente', 'Receber dividendos em dinheiro ao invés de ações', 'Exercer tag along em 100% do valor'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. DIREITO DE SUBSCRIÇÃO: direito preferencial de COMPRAR novas ações na PROPORÇÃO das que já possui quando empresa aumenta capital. OBJETIVO: proteger acionista de DILUIÇÃO (redução % participação). EXERCÍCIO: pode exercer (comprar), vender o direito no mercado ou deixar caducar. PRAZO: mínimo 30 dias. Não se confunde com venda com ágio (A), voto (C), dividendos (D) ou tag along (E). IPO: oferta inicial. Follow-on: oferta subsequente.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'acoes', question: 'Sobre o mercado acionário brasileiro, é correto afirmar que:', options: ['Blue chips são ações de empresas pequenas com alta volatilidade', 'Small caps são ações de grandes empresas consolidadas', 'O Ibovespa é composto pelas ações mais negociadas da B3', 'As ações brasileiras sempre têm sufixo 11 para ONs e 12 para PNs', 'Day trade é vedado no mercado de ações'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. IBOVESPA: principal índice da B3, composto pelas ações MAIS NEGOCIADAS (liquidez) que representam ~80% do volume. Ponderado por valor de mercado (free float). CLASSIFICAÇÕES: BLUE CHIPS: grandes empresas sólidas, alta liquidez (A errada). SMALL CAPS: empresas menores, menor liquidez (B errada). SUFIXOS: 3=ON, 4=PN, 5=PNA, 6=PNB, 11=Units (A/D erradas). DAY TRADE: permitido, com tributação diferenciada (E errada - 20% IR vs 15% swing trade).', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 2. DEBÊNTURES - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'debentures', question: 'Debêntures são títulos de dívida emitidos por sociedades anônimas. Sobre as debêntures, NÃO é correto afirmar que:', options: ['Podem ser emitidas apenas por sociedades anônimas (S.A.)', 'Conferem direito de crédito contra a companhia emissora', 'Bancos comerciais podem emitir debêntures para captar recursos', 'Podem ter garantia real, flutuante, quirografária ou subordinada', 'São reguladas pela CVM e pela Lei 6.404/76'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C (INCORRETA). BANCOS NÃO podem emitir debêntures. Instituições financeiras captam via CDB, LCI, LCA, letras financeiras. DEBÊNTURES: exclusivas de S.A. NÃO FINANCEIRAS (indústria, comércio, serviços). NATUREZA: título de DÍVIDA (não é capital). REMUNERAÇÃO: juros + correção monetária. GARANTIAS: 1) REAL: imóveis, equipamentos; 2) FLUTUANTE: ativos não vinculados; 3) QUIROGRAFÁRIA: sem garantia específica; 4) SUBORDINADA: última na fila de credores.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'debentures', question: 'As debêntures incentivadas (Lei 12.431/2011) têm como vantagem:', options: ['Isenção total de Imposto de Renda para qualquer investidor', 'Isenção de IR para pessoa física em debêntures de infraestrutura', 'Garantia do FGC (Fundo Garantidor de Crédito)', 'Não podem ter rating abaixo de investment grade', 'São conversíveis obrigatoriamente em ações'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. DEBÊNTURES INCENTIVADAS: emitidas para financiar INFRAESTRUTURA (energia, transporte, saneamento, etc.). BENEFÍCIO: ISENÇÃO de IR para PESSOA FÍSICA (Lei 12.431/2011). PJ paga IR normalmente. OBJETIVO: atrair investidores para projetos de infraestrutura. NÃO têm garantia FGC (C errada). Podem ter qualquer rating (D errada). Conversibilidade é facultativa (E errada). Prazo mínimo: 4 anos (médio/longo prazo). Emissor deve ter projeto aprovado.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'debentures', question: 'Debêntures conversíveis em ações permitem ao debenturista:', options: ['Apenas receber os juros sem poder converter', 'Trocar as debêntures por ações da companhia em condições pré-estabelecidas', 'Vender as debêntures apenas no vencimento', 'Receber dividendos mesmo sem converter', 'Votar nas assembleias de debenturistas'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. DEBÊNTURES CONVERSÍVEIS: debenturista tem OPÇÃO de CONVERTER debêntures em AÇÕES da companhia. CONDIÇÕES: preço conversão, prazo, proporção (definidos na escritura). VANTAGENS: 1) Debenturista: juros fixos + possibilidade ganho acionário; 2) Empresa: taxa juros menor (pela opção). NÃO CONVERSÍVEIS: apenas crédito. PERMUTÁVEIS: conversíveis em ações de OUTRA empresa. Voto: apenas acionistas votam (E errada). Dividendos: só após conversão (D errada).', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'debentures', question: 'O agente fiduciário nas emissões de debêntures tem a função de:', options: ['Comprar todas as debêntures não vendidas', 'Representar e proteger os interesses dos debenturistas', 'Definir a taxa de juros das debêntures', 'Emitir as debêntures em seu próprio nome', 'Substituir a CVM na fiscalização'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. AGENTE FIDUCIÁRIO: REPRESENTA e PROTEGE interesses coletivos dos DEBENTURISTAS perante a emissora. FUNÇÕES: 1) Verificar cumprimento obrigações pela empresa; 2) Fiscalizar garantias; 3) Convocar assembleias; 4) Executar garantias se inadimplência; 5) Comunicar CVM irregularidades. REQUISITOS: instituição financeira ou pessoa com registro CVM, independente da emissora. REMUNERAÇÃO: paga pela companhia emissora. OBRIGATÓRIO: emissões públicas. Não assume risco (A errada).', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'debentures', question: 'Sobre a remuneração das debêntures, é correto afirmar que:', options: ['Sempre paga juros prefixados', 'Pode ser prefixada, pós-fixada (CDI, IPCA, etc.) ou mista', 'Não pode ter cláusula de participação nos lucros', 'É sempre inferior à taxa Selic', 'Tem tributação zero para todos os investidores'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. REMUNERAÇÃO DEBÊNTURES pode ser: 1) PREFIXADA: taxa fixa (ex: 12% a.a.); 2) PÓS-FIXADA: indexada a CDI, IPCA, IGP-M, etc.; 3) MISTA: prefixada + pós (ex: IPCA + 6%). PODE ter participação lucros (C errada). Taxa pode ser superior à Selic conforme risco (D errada). TRIBUTAÇÃO PF: tabela regressiva IR (22,5% a 15%) - exceto incentivadas isentas (E errada). CUPONS: pagamentos periódicos juros. AMORTIZAÇÃO: programada ou no vencimento.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 3. FUNDOS DE INVESTIMENTO - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'fundos-de-investimento', question: 'Os fundos de investimento são comunhões de recursos constituídos sob forma de condomínio. Sobre os fundos, é correto afirmar que:', options: ['Têm personalidade jurídica própria como empresas', 'São condomínios sem personalidade jurídica, administrados por instituições autorizadas', 'Apenas bancos podem administrar fundos', 'Os cotistas respondem ilimitadamente pelas dívidas do fundo', 'Não são fiscalizados pela CVM'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Fundos são CONDOMÍNIOS (pooling de recursos) SEM personalidade jurídica (A errada). ESTRUTURA: 1) ADMINISTRADOR: banco, corretora, gestora (autorizada CVM); 2) GESTOR: toma decisões de investimento; 3) CUSTODIANTE: guarda ativos. COTISTAS: responsabilidade LIMITADA ao valor aplicado (D errada). CVM fiscaliza (E errada - IN CVM 555/2014). Não apenas bancos administram (C errada). COTA: fração ideal do patrimônio líquido.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'fundos-de-investimento', question: 'A classificação dos fundos de investimento quanto ao prazo de resgate pode ser:', options: ['Apenas fundos abertos', 'Fundos abertos (resgate a qualquer tempo) e fundos fechados (resgate apenas no vencimento ou liquidação)', 'Apenas fundos fechados', 'Fundos públicos e privados', 'Fundos ativos e passivos'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. FUNDOS ABERTOS: cotistas podem solicitar RESGATE a qualquer momento (liquidez). Maioria dos fundos (renda fixa, ações, multimercado). FUNDOS FECHADOS: resgate APENAS no vencimento, liquidação ou assembleia. Cotas negociadas no mercado secundário (não há resgate direto). Ex: FIIs (Fundos Imobiliários), FIPs (Participações). OUTRAS CLASSIFICAÇÕES: por ativos (renda fixa, ações, etc.), gestão (ativo/passivo), público-alvo (qualificado, profissional, geral).', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'fundos-de-investimento', question: 'Sobre a tributação dos fundos de investimento, é correto que:', options: ['Fundos de renda fixa de curto prazo têm alíquota mínima de 15%', 'Fundos de renda fixa de longo prazo seguem tabela regressiva (22,5% a 15%)', 'Fundos de ações são isentos de IR', 'Come-cotas incide semestralmente em todos os fundos', 'Não há diferença tributária entre curto e longo prazo'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. FUNDOS LONGO PRAZO: carteira prazo médio > 365 dias, TABELA REGRESSIVA: até 180 dias 22,5%; 181-360 dias 20%; 361-720 dias 17,5%; acima 720 dias 15%. FUNDOS CURTO PRAZO: prazo médio ≤ 365 dias, alíquotas 22,5% ou 20% (A errada). FUNDOS AÇÕES: IR 15% sobre ganhos (C errada). COME-COTAS: antecipação IR, incide em maio/novembro apenas em fundos NÃO de ações (D errada). FII: isento IR para PF se > 50 cotistas.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'fundos-de-investimento', question: 'Os Fundos de Investimento Imobiliário (FII) têm como características:', options: ['Aplicam apenas em imóveis físicos', 'São fundos abertos com resgate diário', 'Distribuem no mínimo 95% dos lucros semestralmente aos cotistas', 'Têm cotas negociadas exclusivamente em mercado de balcão', 'Só podem ter investidores institucionais'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. FII devem distribuir NO MÍNIMO 95% dos lucros SEMESTRALMENTE (Lei 8.668/93). INVESTIMENTOS: imóveis físicos (tijolos), recebíveis imobiliários (CRI, LCI), outros FIIs (fundos de fundos). FUNDOS FECHADOS: sem resgate, cotas negociadas em BOLSA (B/D erradas). ISENÇÃO IR PF: se > 50 cotistas, cotas em bolsa, cotista < 10% das cotas. TIPOS: renda (aluguel), desenvolvimento, híbridos. Investidor geral pode investir (E errada).', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'fundos-de-investimento', question: 'A taxa de administração em fundos de investimento:', options: ['É cobrada apenas no resgate', 'Incide sobre o patrimônio líquido do fundo, reduzindo o valor da cota diariamente', 'É fixa em 2% ao ano para todos os fundos', 'Não pode ser cobrada em fundos de ações', 'É dedutível de IR do investidor'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. TAXA ADMINISTRAÇÃO: cobrada DIARIAMENTE sobre patrimônio líquido (provisionada e deduzida do PL, refletindo no valor da cota). Não é cobrada no resgate (A errada). VARIA conforme fundo (C errada - pode ser 0,3% a.a. até 3%+). Todos fundos podem cobrar (D errada). NÃO dedutível de IR (E errada). TAXA PERFORMANCE: sobre rentabilidade acima de benchmark (ex: > 100% CDI). CUSTOS: impactam rentabilidade líquida do investidor.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ========== 4. BOLSA DE VALORES - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'bolsa-de-valores', question: 'A B3 (Brasil, Bolsa, Balcão) é a bolsa de valores brasileira. Sobre a B3, é correto afirmar que:', options: ['É uma empresa pública federal', 'Resultou da fusão entre BM&F e Bovespa em 2008 e posterior incorporação da Cetip', 'É fiscalizada exclusivamente pelo Banco Central', 'Não opera mercado de derivativos', 'Apenas ações podem ser negociadas na B3'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. HISTÓRICO: 2008 fusão BM&F + BOVESPA = BM&FBOVESPA; 2017 incorporação CETIP = B3. NATUREZA: empresa PRIVADA S.A. com ações negociadas (B3SA3) - A errada. FISCALIZAÇÃO: CVM e BACEN (C errada). MERCADOS: ações, derivativos (futuros, opções), renda fixa, câmbio, commodities (D/E erradas). FUNÇÕES: 1) Ambiente negociação; 2) Clearings (compensação); 3) Custódia; 4) Desenvolvimento mercado. AUTORRЕГУЛAÇÃO: fiscaliza participantes.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'bolsa-de-valores', question: 'No mercado à vista de ações, o prazo de liquidação (settlement) na B3 é de:', options: ['D+0 (liquidação no mesmo dia)', 'D+1 (liquidação no dia seguinte)', 'D+2 (liquidação em 2 dias úteis)', 'D+3 (liquidação em 3 dias úteis)', 'D+5 (liquidação em 5 dias úteis)'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Mercado à vista: liquidação em D+2 (2 dias ÚTEIS após negociação). EXEMPLO: compra segunda, liquidação quarta. D+0: dia da operação. D+1: dia seguinte. D+2: atual no Brasil (alinhado padrão internacional - antes era D+3). PROCESSOS D+2: dia trade, pagamento/recebimento, transferência ações. LIQUIDAÇÃO FÍSICA: transferência ações. LIQUIDAÇÃO FINANCEIRA: pagamento/recebimento dinheiro. CÂMARA COMPENSAÇÃO: B3 atua como contraparte central.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'bolsa-de-valores', question: 'O circuito disjuntor (circuit breaker) na B3 tem a função de:', options: ['Aumentar a volatilidade do mercado', 'Interromper temporariamente as negociações em caso de oscilações bruscas', 'Garantir lucros aos investidores', 'Permitir negociações 24 horas', 'Cobrar taxas adicionais em dias de alta volatilidade'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. CIRCUIT BREAKER: mecanismo que SUSPENDE negociações temporariamente quando IBOVESPA cai percentual predefinido. OBJETIVO: esfriar mercado, evitar pânico, permitir reavaliação. NÍVEIS B3: 1) Queda 10%: pausa 30min; 2) Queda 15%: pausa 1h; 3) Queda 20%: suspensão dia. NÃO garante lucro (C), é proteção contra volatilidade extrema (A errada). Mercado opera horário regular (D errada). Sem custos adicionais (E errada). Inspirado crash 1987 (Black Monday).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'bolsa-de-valores', question: 'O Home Broker é uma plataforma que permite:', options: ['Apenas consultar cotações de ações', 'Investidores enviarem ordens de compra/venda pela internet sem intermediário', 'Comprar imóveis através da bolsa', 'Apenas investidores institucionais operarem', 'Negociar sem custos de corretagem'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. HOME BROKER: plataforma online da CORRETORA que permite investidor PESSOA FÍSICA enviar ordens diretamente ao sistema da B3 via internet. FUNCIONALIDADES: compra/venda ações, consulta cotações, acompanhamento carteira, book de ofertas. NÃO elimina intermediário (corretora necessária) mas dispensa call center (A/B). Cobra corretagem (E errada). Todos investidores com conta corretora (D errada). Apenas ativos financeiros (C errada). EVOLUÇÃO: mobile (apps).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'bolsa-de-valores', question: 'Os níveis diferenciados de governança corporativa da B3 (Novo Mercado, Níveis 1 e 2) foram criados para:', options: ['Aumentar as taxas cobradas das empresas', 'Estabelecer práticas de transparência e direitos aos acionistas minoritários', 'Permitir que empresas paguem menos impostos', 'Proibir a negociação de ações preferenciais', 'Substituir a fiscalização da CVM'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. GOVERNANÇA CORPORATIVA: práticas que aumentam TRANSPARÊNCIA, EQUIDADE e PRESTAÇÃO DE CONTAS. NÍVEIS: 1) NÍVEL 1: melhorias informações ao mercado; 2) NÍVEL 2: + direitos minoritários, tag along 100% ON, câmara arbitragem; 3) NOVO MERCADO: APENAS ações ON (sem PN), tag along 100%, free float mín. 25%. OBJETIVO: atrair investidores, reduzir custo capital, valorização. Não envolve impostos (C) nem substitui CVM (E). PN permitidas N1/N2 (D errada).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ========== 5. TÍTULOS PÚBLICOS - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'titulos-publicos', question: 'O Tesouro Direto é um programa que permite:', options: ['Apenas investidores institucionais comprarem títulos públicos', 'Pessoas físicas comprarem títulos públicos federais pela internet', 'Empresas emitirem debêntures', 'Investimento exclusivo em ações', 'Compra de imóveis do governo'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. TESOURO DIRETO: programa que democratizou acesso de PESSOA FÍSICA a TÍTULOS PÚBLICOS FEDERAIS via internet (desde 2002). ANTES: apenas institucional via mercado primário (leilões). CARACTERÍSTICAS: investimento mínimo ~R$30, transparência, liquidez (recompra garantida), segurança (governo federal). PLATAFORMA: integrada a corretoras. NÃO envolve debêntures (C), ações (D) ou imóveis (E). Qualquer PF pode investir (A errada).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'titulos-publicos', question: 'O Tesouro Selic (LFT - Letra Financeira do Tesouro) é um título público que:', options: ['Paga juros prefixados', 'Tem rentabilidade atrelada à variação da taxa Selic', 'É corrigido pelo IPCA', 'Paga cupons semestrais de juros', 'Tem risco de mercado elevado'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. TESOURO SELIC (LFT): rentabilidade = TAXA SELIC (pós-fixada). CARACTERÍSTICAS: 1) BAIXO RISCO MERCADO: marcação a mercado com pouco impacto (valor sobe com Selic); 2) LIQUIDEZ diária; 3) Indicado: reserva emergência, curto prazo; 4) Não paga cupons (D errada). OUTROS TÍTULOS: Tesouro PREFIXADO (LTN) - taxa fixa (A); Tesouro IPCA+ (NTN-B) - IPCA + taxa (C). Selic é mais conservador (E errada). Emissor: Tesouro Nacional.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'titulos-publicos', question: 'O Tesouro IPCA+ (NTN-B) oferece proteção contra:', options: ['Variação do dólar', 'Inflação medida pelo IPCA', 'Queda da bolsa de valores', 'Variação da taxa Selic', 'Desvalorização de imóveis'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. TESOURO IPCA+: rentabilidade = IPCA (inflação) + TAXA PREFIXADA. EXEMPLO: IPCA + 6% a.a. - se inflação 5%, rentabilidade 11% (aproximado). PROTEÇÃO: mantém PODER DE COMPRA real. TIPOS: 1) SEM cupons: pagamento no vencimento; 2) COM cupons: juros semestrais. INDICADO: longo prazo, aposentadoria. RISCO MERCADO: marcação diária pode gerar volatilidade se vender antes vencimento. Não protege dólar (A), bolsa (C), Selic (D) ou imóveis (E).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'titulos-publicos', question: 'Sobre a tributação dos títulos públicos no Tesouro Direto, é correto que:', options: ['Há isenção total de Imposto de Renda', 'Incide IR pela tabela regressiva (22,5% a 15%) sobre os rendimentos', 'Incide IOF nos primeiros 30 dias de aplicação', 'A alíquota mínima é de 20%', 'Não há cobrança de taxa de custódia'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. TRIBUTAÇÃO: IR TABELA REGRESSIVA sobre RENDIMENTOS: até 180 dias 22,5%; 181-360 dias 20%; 361-720 dias 17,5%; > 720 dias 15%. Não há isenção (A errada). IOF: primeiros 30 dias - CORRETO item C também! (porém B é mais abrangente). TAXA CUSTÓDIA B3: 0,20% a.a. sobre valor investido (E errada). IR: retido na fonte no resgate/vencimento/cupom. COME-COTAS: não se aplica (só fundos). Alíquota mínima 15% > 720 dias (D errada).', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'titulos-publicos', question: 'A marcação a mercado dos títulos públicos significa que:', options: ['O preço não varia até o vencimento', 'O valor do título oscila diariamente conforme juros de mercado', 'Apenas títulos prefixados têm marcação a mercado', 'O governo garante o preço de compra', 'Não há risco em vender antes do vencimento'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. MARCAÇÃO A MERCADO: valor do título OSCILA DIARIAMENTE conforme taxas de juros do mercado. LÓGICA: se juros sobem, preços caem (relação inversa - novos títulos mais atraentes). RISCO: vender antes vencimento pode gerar lucro ou prejuízo (E errada). TÍTULOS AFETADOS: prefixados e IPCA+ (mais sensíveis) - C errada. SELIC: menos afetado. Se MANTER até VENCIMENTO: recebe exatamente o combinado (governo garante - D parcialmente correta). DURATION: medida sensibilidade.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Mercado de Capitais questions (Part 1/2)...`);
  
  let count = 0;
  for (const q of allQuestions) {
    await saveQuestion(q);
    count++;
    if (count % 5 === 0) {
      console.log(`✅ Saved ${count}/${allQuestions.length} questions...`);
    }
  }
  
  console.log('✅ Part 1/2 (25 questions) imported! Continuing...');
  
  // ========== PART 2 - Remaining questions ==========
  const moreQuestions: Question[] = [
    // ========== 6. DERIVATIVOS (OPÇÕES, FUTUROS) - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'derivativos-opcoes-futuros', question: 'Contratos futuros negociados em bolsa caracterizam-se por:', options: ['Serem personalizados entre as partes', 'Terem padronização de quantidade, qualidade, vencimento e garantias', 'Não exigirem margem de garantia', 'Permitirem apenas liquidação física', 'Serem negociados apenas em balcão'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. FUTUROS (bolsa): contratos PADRONIZADOS: quantidade, qualidade, vencimento, local entrega definidos pela bolsa. CARACTERÍSTICAS: 1) Negociados em BOLSA (B3); 2) Clearing como contraparte central; 3) MARGEM de garantia obrigatória (ajuste diário); 4) Alta liquidez; 5) Liquidação física OU financeira. TERMO (balcão): personalizado (A/E erradas). Exige margem (C errada). Maioria liquidação financeira (D errada). Ex: dólar, boi gordo, índice.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'derivativos-opcoes-futuros', question: 'Em um contrato de opção de compra (call), o titular (comprador da opção):', options: ['Tem obrigação de comprar o ativo no vencimento', 'Tem direito, mas não obrigação, de comprar o ativo ao preço de exercício', 'Recebe o prêmio da opção', 'Assume posição vendida no ativo objeto', 'Não pode exercer antes do vencimento em opções americanas'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. CALL (opção compra): titular tem DIREITO (não obrigação) de COMPRAR ativo ao preço de exercício (strike). Paga PRÊMIO ao lançador. LANÇADOR: obrigação vender se titular exercer, recebe prêmio (C errada - titular paga). EXERCÍCIO: AMERICANAS (qualquer momento até vencimento - E errada); EUROPEIAS (apenas no vencimento). Titular não tem obrigação (A errada). PUT: opção venda. Risco titular: limitado ao prêmio. Risco lançador: ilimitado (call).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'derivativos-opcoes-futuros', question: 'A estratégia de hedge com derivativos tem como objetivo:', options: ['Maximizar lucros especulativos', 'Proteger-se contra oscilações adversas de preços', 'Aumentar a volatilidade da carteira', 'Ganhar com arbitragem de taxas', 'Eliminar totalmente qualquer risco'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. HEDGE: proteção contra RISCO de preço. EXEMPLO: exportador vende dólar futuro (trava taxa câmbio, protege-se de queda dólar). OBJETIVO: REDUZIR risco, não maximizar lucro (A errada). OPERAÇÕES: futuros, opções, swaps. NÃO elimina risco totalmente (E errada), apenas mitiga. Reduz volatilidade (C errada). ESPECULAÇÃO: assumir risco buscando lucro. ARBITRAGEM: explorar diferenças de preço (D diferente). Cross hedge: hedge com ativo correlacionado.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'derivativos-opcoes-futuros', question: 'O ajuste diário no mercado futuro representa:', options: ['Taxa de corretagem cobrada diariamente', 'Acerto financeiro diário de ganhos/perdas conforme oscilação do contrato', 'Pagamento de dividendos', 'Multa por não exercer opções', 'Taxa de custódia da B3'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. AJUSTE DIÁRIO: ACERTO FINANCEIRO diário dos GANHOS/PERDAS devido à variação do preço futuro. PROCESSO: diferença entre preço ajuste hoje e ontem é creditada/debitada na conta. OBJETIVO: reduzir risco crédito (perdas não acumulam até vencimento). MARGEM: se margem insuficiente, chamada de margem (reforço). LIQUIDAÇÃO FINANCEIRA: soma dos ajustes = resultado final. Não é corretagem (A), dividendos (C), multa (D) ou custódia (E). Marca-a-mercado diário.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'derivativos-opcoes-futuros', question: 'Contratos de swap permitem:', options: ['Apenas troca de ações entre investidores', 'Troca de fluxos financeiros futuros entre partes (ex: CDI por dólar)', 'Compra de imóveis a prazo', 'Apenas operações com pessoa física', 'Negociação exclusiva em bolsa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. SWAP: troca de FLUXOS FINANCEIROS futuros entre partes. TIPOS: 1) MOEDA: CDI x Dólar (empresa troca variação cambial por taxa fixa/CDI); 2) JUROS: prefixado x pós-fixado; 3) COMMODITIES. MERCADO: predominantemente BALCÃO (E errada), entre instituições/empresas (D errada). OBJETIVO: hedge, casamento ativos-passivos. LIQUIDAÇÃO: diferença líquida. Não envolve ações físicas (A) ou imóveis (C). Regulação: BACEN (instituições) e CVM.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },

    // ========== 7. ANÁLISE FUNDAMENTALISTA - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-fundamentalista', question: 'A análise fundamentalista busca determinar o valor intrínseco de uma ação através de:', options: ['Padrões gráficos de preços históricos', 'Análise de fundamentos econômico-financeiros da empresa', 'Apenas médias móveis', 'Exclusivamente volume de negociação', 'Análise de sentimento em redes sociais'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. ANÁLISE FUNDAMENTALISTA: avalia FUNDAMENTOS da empresa para estimar VALOR INTRÍNSECO da ação. FATORES: 1) Balanços (DRE, BP); 2) Indicadores (P/L, ROE, margem); 3) Setor, concorrência; 4) Cenário macroeconômico; 5) Governança. OBJETIVO: identificar ações subavaliadas (preço < valor) ou sobrevalorizadas (preço > valor). DIFERE análise técnica (A/C/D - gráficos). Pode usar sentimento mas não é exclusivo (E). Base: investimento longo prazo. Valuation: DCF, múltiplos.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-fundamentalista', question: 'O índice P/L (Preço/Lucro) indica:', options: ['O lucro líquido da empresa', 'Quantos anos o investidor leva para recuperar investimento pelo lucro atual', 'A dívida total da companhia', 'O dividend yield da ação', 'O patrimônio líquido por ação'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. P/L = Preço ação / Lucro por ação. INTERPRETAÇÃO: quantos anos (pelo lucro atual) para recuperar preço pago. EXEMPLO: P/L 10 = 10 anos. P/L BAIXO: pode indicar subavaliação (barato) ou problemas. P/L ALTO: sobrevaluação ou expectativa crescimento. COMPARAÇÃO: entre empresas mesmo setor. LIMITAÇÕES: lucro pode variar, não considera crescimento futuro. NÃO é lucro líquido (A), dívida (C), dividend yield (D) ou PL/ação (E). Price-to-Earnings.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-fundamentalista', question: 'O ROE (Return on Equity) mede:', options: ['Retorno sobre o ativo total', 'Retorno sobre o patrimônio líquido', 'Retorno sobre vendas', 'Retorno sobre investimento em P&D', 'Retorno sobre dívidas'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. ROE = Lucro Líquido / Patrimônio Líquido × 100. Mede RENTABILIDADE do capital próprio (quanto empresa gera de lucro com capital dos acionistas). INTERPRETAÇÃO: ROE 20% = cada R$1 de PL gera R$0,20 lucro. ROE ALTO: boa gestão, lucratividade. COMPARAÇÃO: setor, histórico. FÓRMULA DUPONT: ROE = Margem × Giro × Alavancagem. ROA: retorno sobre ativo total (A). Margem líquida: retorno sobre vendas (C). Não se aplica a P&D (D) ou dívidas (E).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-fundamentalista', question: 'O indicador P/VP (Preço sobre Valor Patrimonial) compara:', options: ['Preço da ação com lucro por ação', 'Preço da ação com patrimônio líquido por ação', 'Preço com valor de mercado', 'Lucro com patrimônio', 'Dividendos com preço'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. P/VP = Preço ação / Valor Patrimonial por ação (PL/ação). INTERPRETAÇÃO: P/VP < 1: mercado valoriza empresa ABAIXO do patrimônio contábil (pode ser oportunidade ou problemas). P/VP > 1: mercado paga PRÊMIO (expectativas, intangíveis). SETOR: bancos, varejo (tangíveis) tendem P/VP menor; tecnologia (intangíveis) maior. NÃO confundir: P/L (A), valor mercado total (C), lucro/PL (D ROE), dividendos (E dividend yield). Price-to-Book.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-fundamentalista', question: 'O Dividend Yield (DY) representa:', options: ['Crescimento esperado dos dividendos', 'Percentual de retorno em dividendos sobre o preço da ação', 'Total de dividendos pagos pela empresa', 'Lucro por ação', 'Payout da empresa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. DIVIDEND YIELD = (Dividendos por ação / Preço ação) × 100. Mede RETORNO em dividendos. EXEMPLO: DY 6% = ação R$100 paga R$6 dividendos/ano. DY ALTO: atrativo para investidores renda, mas pode indicar preço baixo por problemas. DY BAIXO: empresa reinveste lucros (crescimento) ou paga pouco. NÃO é crescimento (A), total absoluto (C), LPA (D) ou payout (E - % lucro distribuído). Comparar: mesmo setor, histórico. FIIs: DY importante.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 8. ANÁLISE TÉCNICA - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-tecnica', question: 'A análise técnica (análise gráfica) baseia-se em:', options: ['Balanços contábeis e demonstrações financeiras', 'Padrões de comportamento de preços, volumes e tendências em gráficos', 'Apenas indicadores macroeconômicos', 'Exclusivamente em fundamentos da empresa', 'Relatórios de governança corporativa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. ANÁLISE TÉCNICA: estuda PADRÕES GRÁFICOS de preços, volumes, tendências para prever movimentos futuros. PREMISSAS: 1) Preço desconta tudo; 2) Preços se movem em tendências; 3) História se repete. FERRAMENTAS: suportes, resistências, médias móveis, IFR, MACD, candlesticks. OBJETIVO: timing de entrada/saída (curto prazo). DIFERE fundamentalista (A/D/E - fundamentos empresa/macro). Não usa balanços (A) ou governança (E). Traders, especuladores usam muito.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-tecnica', question: 'Suporte e resistência em análise técnica são:', options: ['Indicadores de lucro da empresa', 'Níveis de preço onde historicamente há pressão compradora (suporte) ou vendedora (resistência)', 'Médias de volumes negociados', 'Taxas de juros do mercado', 'Índices de inflação'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. SUPORTE: nível de preço onde historicamente há PRESSÃO COMPRADORA (demanda) que impede quedas maiores. RESISTÊNCIA: nível onde há PRESSÃO VENDEDORA (oferta) que impede altas maiores. LÓGICA: investidores lembram preços anteriores, agem nesses níveis. ROMPIMENTO: se rompe resistência, vira suporte (e vice-versa). FORÇA: quanto mais testes sem romper, mais forte. NÃO relacionado a lucro (A), volume absoluto (C), juros (D) ou inflação (E). Base: psicologia de massas.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-tecnica', question: 'O IFR (Índice de Força Relativa / RSI) é um indicador que:', options: ['Mede o lucro da empresa', 'Identifica condições de sobrecompra (acima 70) ou sobrevenda (abaixo 30)', 'Calcula o P/L da ação', 'Determina o dividend yield', 'Avalia a governança corporativa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. IFR (RSI): oscilador que varia 0-100, identifica SOBRECOMPRA (> 70 - possível correção queda) e SOBREVENDA (< 30 - possível recuperação). CÁLCULO: velocidade e magnitude variações preço. DIVERGÊNCIAS: preço sobe mas IFR cai (fraqueza) ou preço cai mas IFR sobe (força). LIMITAÇÃO: mercado pode ficar sobrecomprado/sobrevendido por tempo. NÃO mede fundamentos (A/C/D/E). Desenvolvido por Welles Wilder. Período padrão: 14 dias. Complementa outras análises.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-tecnica', question: 'Médias móveis são utilizadas para:', options: ['Calcular o lucro médio da empresa', 'Identificar tendências suavizando flutuações de curto prazo', 'Determinar o valor patrimonial', 'Medir a liquidez corrente', 'Avaliar a estrutura de capital'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. MÉDIAS MÓVEIS: SUAVIZAM flutuações de preço para identificar TENDÊNCIA. TIPOS: 1) SIMPLES (MMS): média aritmética; 2) EXPONENCIAL (MME): mais peso preços recentes. USO: MMA 9 (curto), 21 (médio), 200 (longo). SINAIS: preço cruza média para cima (compra), para baixo (venda); cruzamento médias (golden/death cross). RETARDO: indicador atrasado (lagging). NÃO mede fundamentos (A/C/D/E). Moving averages. Estratégias: seguir tendência.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'analise-tecnica', question: 'Candlesticks (candles) nos gráficos representam:', options: ['Apenas o volume negociado', 'Abertura, fechamento, máxima e mínima em determinado período', 'Somente o preço de fechamento', 'Indicadores macroeconômicos', 'Fundamentos da empresa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. CANDLESTICK: representação gráfica que mostra ABERTURA, FECHAMENTO, MÁXIMA e MÍNIMA de um período. CORPO: abertura-fechamento (branco/verde se alta, preto/vermelho se queda). SOMBRAS (pavios): máxima e mínima. PADRÕES: doji (indecisão), martelo (reversão), engolfo (reversão forte), estrela cadente. ORIGEM: Japão século XVII (arroz). NÃO é só volume (A), fechamento (C) ou fundamentos (D/E). Mais informação que gráfico linha. Análise: formações individuais e combinadas.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 9. RISCO E DIVERSIFICAÇÃO - 5 questões ==========
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'risco-e-diversificacao', question: 'Diversificação de carteira tem como objetivo principal:', options: ['Maximizar o retorno eliminando qualquer risco', 'Reduzir o risco não sistemático através da combinação de ativos', 'Concentrar investimentos em um único ativo', 'Garantir retorno fixo independente do mercado', 'Eliminar totalmente o risco sistemático'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. DIVERSIFICAÇÃO: combinar ATIVOS com correlações baixas/negativas para REDUZIR RISCO NÃO SISTEMÁTICO (específico de empresas/setores). EXEMPLO: ações + renda fixa + imóveis. RISCO TOTAL = Sistemático (mercado, não diversificável) + Não sistemático (diversificável). Não elimina risco totalmente (A/E erradas). Não garante retorno fixo (D). Concentração aumenta risco (C errada). Máxima Markowitz: "don\'t put all eggs in one basket". Fronteira eficiente.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'risco-e-diversificacao', question: 'O Beta de uma ação mede:', options: ['O retorno esperado da ação', 'A sensibilidade da ação em relação ao mercado (índice de referência)', 'O lucro por ação', 'A volatilidade absoluta', 'O dividend yield'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. BETA: mede SENSIBILIDADE da ação ao MERCADO (ex: Ibovespa). INTERPRETAÇÃO: Beta 1,0 = ação acompanha mercado; Beta > 1,0 = mais volátil (agressiva); Beta < 1,0 = menos volátil (defensiva); Beta negativo = movimento contrário. EXEMPLO: Beta 1,5 - se mercado sobe 10%, ação tende subir 15%. CAPM: retorno esperado = rf + Beta × (rm - rf). NÃO é retorno (A), lucro (C), volatilidade absoluta (D - essa é desvio-padrão) ou dividend (E).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'risco-e-diversificacao', question: 'Risco sistemático (ou de mercado) caracteriza-se por:', options: ['Poder ser eliminado através de diversificação', 'Afetar todo o mercado, não podendo ser eliminado por diversificação', 'Ser específico de uma empresa', 'Não afetar o retorno esperado', 'Existir apenas em ações de small caps'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. RISCO SISTEMÁTICO (mercado): afeta TODO mercado, NÃO pode ser eliminado por diversificação. CAUSAS: juros, inflação, PIB, política, guerras. EXEMPLOS: crise 2008 (global), pandemia. Medido por BETA. RISCO NÃO SISTEMÁTICO (específico): empresa, setor, PODE ser diversificado (A/C erradas). Afeta retorno esperado (D errada - CAPM). Afeta todas ações (E errada). Investidor compensado apenas por risco sistemático (prêmio de risco). Também chamado risco não diversificável.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'risco-e-diversificacao', question: 'O Índice de Sharpe mede:', options: ['Apenas o retorno absoluto de um investimento', 'O retorno ajustado ao risco (excesso de retorno por unidade de risco)', 'Somente a volatilidade', 'O P/L médio do mercado', 'A correlação entre dois ativos'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. ÍNDICE SHARPE = (Retorno carteira - Taxa livre risco) / Desvio-padrão. Mede RETORNO AJUSTADO AO RISCO (quanto retorno adicional por unidade de risco assumido). INTERPRETAÇÃO: Sharpe maior = melhor relação risco-retorno. EXEMPLO: Sharpe 1,5 melhor que 0,8. COMPARAÇÃO: entre fundos, estratégias. LIMITAÇÃO: assume distribuição normal. NÃO é retorno absoluto (A), volatilidade pura (C), P/L (D) ou correlação (E). Desenvolvido William Sharpe (Nobel). Outros: Treynor, Sortino.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'mercado-de-capitais', topic: 'risco-e-diversificacao', question: 'Correlação entre ativos em uma carteira indica:', options: ['O retorno esperado de cada ativo', 'Como os retornos de dois ativos se movem em relação um ao outro', 'O risco individual de cada ativo', 'O preço justo dos ativos', 'A liquidez dos ativos'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. CORRELAÇÃO: mede como retornos de DOIS ATIVOS se movem juntos. ESCALA: -1 a +1. CORRELAÇÃO +1: movem-se perfeitamente juntos (sem benefício diversificação). CORRELAÇÃO 0: sem relação. CORRELAÇÃO -1: movem-se perfeitamente opostos (máxima diversificação). DIVERSIFICAÇÃO EFICAZ: ativos correlação baixa/negativa. EXEMPLO: ações e ouro (correlação negativa). NÃO é retorno (A), risco individual (C), preço (D) ou liquidez (E). Covariância relacionada. Markowitz: otimização carteira.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${moreQuestions.length} more Mercado de Capitais questions (Part 2/2)...`);
  
  count = 0;
  for (const q of moreQuestions) {
    await saveQuestion(q);
    count++;
    if (count % 5 === 0) {
      console.log(`✅ Saved ${count}/${moreQuestions.length} questions (Part 2)...`);
    }
  }
  
  console.log('✅✅✅ COMPLETE! All 45 Mercado de Capitais questions imported successfully! 🎯📈');
}