import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL ADMINISTRAÇÃO FINANCEIRA QUESTIONS =============
export async function seedAllAdministracaoFinanceiraQuestions() {
  console.log('🚀 Starting to seed ALL Administração Financeira questions...');
  
  const allQuestions: Question[] = [
    // ============= ANÁLISE DE INVESTIMENTOS (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'analise-de-investimentos', question: 'A análise de investimentos tem como objetivo principal:', options: ['Maximizar os custos da empresa', 'Avaliar a viabilidade econômico-financeira de projetos para decisões de alocação de recursos', 'Apenas calcular impostos', 'Reduzir o capital de giro', 'Eliminar todos os riscos'], correctAnswer: 1, explanation: 'ANÁLISE INVESTIMENTOS: processo avaliar VIABILIDADE econômico-FINANCEIRA projetos/alternativas investimento. OBJETIVO PRINCIPAL: subsidiar DECISÃO alocação RECURSOS escassos entre projetos competitivos, maximizando VALOR empresa. DIMENSÕES ANÁLISE: 1) FINANCEIRA: fluxos caixa, retorno, payback, VPL, TIR. 2) ECONÔMICA: impactos sociedade (análise social). 3) TÉCNICA: exequibilidade projeto. 4) AMBIENTAL: sustentabilidade. 5) MERCADOLÓGICA: demanda, competitividade. ETAPAS: identificação oportunidades, estimativa fluxos caixa, aplicação critérios decisão (VPL, TIR, Payback), análise sensibilidade/risco, decisão investir/rejeitar. IMPORTÂNCIA: recursos limitados exigem escolhas. Investimento errado = prejuízo, oportunidades perdidas. FERRAMENTAS: orçamento capital, matemática financeira, estatística. vs GESTÃO OPERACIONAL: investimento = longo prazo, decisão estratégica. Operacional = curto prazo. IMPORTANTE: análise NÃO elimina risco (reduz incerteza, fundamenta decisão).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'analise-de-investimentos', question: 'São características do fluxo de caixa de um projeto de investimento:', options: ['Apenas entradas de caixa', 'Investimento inicial, fluxos operacionais futuros e valor residual', 'Somente custos fixos', 'Apenas receitas contábeis', 'Não considera depreciação'], correctAnswer: 1, explanation: 'FLUXO CAIXA PROJETO INVESTIMENTO: projeção ENTRADAS - SAÍDAS caixa ao longo VIDA ÚTIL projeto. COMPONENTES: 1) INVESTIMENTO INICIAL (t0): desembolsos imediatos. Capital fixo (máquinas, construções, instalações), capital giro adicional, despesas pré-operacionais. SINAL negativo (saída). 2) FLUXOS OPERACIONAIS (t1...tn): resultado operação projeto cada período. Receitas operacionais, (-) Custos/Despesas operacionais (exceto depreciação - não-caixa), (-) Impostos s/lucro, (+) Depreciação (soma volta - escudo fiscal). Variação capital giro. 3) VALOR RESIDUAL (tn): recuperação ativos fim projeto. Venda equipamentos, liberação capital giro. REGIME CAIXA: considera momento EFETIVO entrada/saída recursos (não competência contábil). INCREMENTAL: considera apenas fluxos ADICIONAIS projeto (vs sem projeto). IMPORTANTE: depreciação NÃO é caixa MAS afeta (reduz IR = escudo fiscal). Inflação: fluxos nominais × taxa nominal, ou reais × real. Custo oportunidade: fluxo considera alternativa abandonada.', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'analise-de-investimentos', question: 'Sobre projetos mutuamente excludentes:', options: ['Podem ser executados simultaneamente', 'A aceitação de um implica rejeição dos demais (escolha exclusiva)', 'Sempre têm mesmo investimento inicial', 'Não necessitam análise comparativa', 'São sempre rejeitados'], correctAnswer: 1, explanation: 'PROJETOS MUTUAMENTE EXCLUDENTES: alternativas competitivas onde ACEITAÇÃO uma implica REJEIÇÃO automática demais. ESCOLHA EXCLUSIVA. EXEMPLOS: 1) Localização fábrica: construir cidade A OU B (não ambas). 2) Tecnologia: processo manual OU automatizado. 3) Expansão: produto X OU Y (recursos limitados). ANÁLISE: COMPARAR projetos (não só viabilidade individual). Escolher melhor (maior VPL, geralmente). vs PROJETOS INDEPENDENTES: aceitação um não afeta outros. Critério: cada um viável individualmente (VPL > 0). CONFLITO RANKING VPL × TIR: projetos excludentes, escalas/prazos diferentes podem gerar rankings divergentes. SOLUÇÃO conflito: SEMPRE VPL (maximiza valor). TIR pode enganar (taxa, não valor absoluto). TAXA DESCONTO: essencial comparar mesma taxa (custo capital). IMPORTANTE: decisão excludente = OPORTUNIDADE. Escolher projeto significa renunciar outros (custo oportunidade). Análise incremental: comparar diferença fluxos (projeto A - projeto B), calcular VPL incremental. Positivo = escolhe A.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'analise-de-investimentos', question: 'A análise de sensibilidade em projetos de investimento visa:', options: ['Eliminar todos os riscos', 'Avaliar como mudanças em variáveis-chave afetam a viabilidade do projeto', 'Apenas calcular VPL', 'Fixar preços de venda', 'Não considera incertezas'], correctAnswer: 1, explanation: 'ANÁLISE SENSIBILIDADE: técnica avaliar como MUDANÇAS variáveis-CHAVE (premissas) afetam VIABILIDADE projeto (VPL, TIR). OBJETIVO: identificar VARIÁVEIS CRÍTICAS (maior impacto), entender RISCOS, subsidiar DECISÃO. MÉTODO: 1) IDENTIFICAR variáveis incertas (preço venda, volume vendas, custos, taxa desconto). 2) VARIAR cada uma (mantendo outras constantes - análise univariada). Ex: preço +10%, -10%. 3) RECALCULAR indicadores (VPL, TIR). 4) ANALISAR impacto (qual variável causa maior variação VPL). APRESENTAÇÃO: tabelas, gráficos (tornado chart - mostra variáveis + sensíveis). EXEMPLO: projeto VPL = 100 (cenário base). Preço -10% → VPL = -50 (muito sensível). Custo -10% → VPL = 120 (menos sensível). AÇÃO: monitorar/controlar preço (crítico). vs ANÁLISE CENÁRIOS: varia MÚLTIPLAS variáveis simultaneamente (pessimista, base, otimista). vs SIMULAÇÃO MONTE CARLO: varia todas probabilisticamente. IMPORTANTE: sensibilidade NÃO diz PROBABILIDADE mudança (só impacto SE mudar). Complementar com análise risco.', difficulty: 'medium', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'analise-de-investimentos', question: 'O custo de oportunidade na análise de investimentos representa:', options: ['Apenas custos contábeis', 'Retorno da melhor alternativa renunciada ao escolher determinado investimento', 'Somente despesas operacionais', 'Valor residual do projeto', 'Não é relevante na análise'], correctAnswer: 1, explanation: 'CUSTO OPORTUNIDADE: retorno MELHOR alternativa RENUNCIADA ao escolher determinado investimento. "Custo de não fazer outra coisa". CONCEITO ECONÔMICO (não contábil): investir projeto A = renunciar projeto B (retorno B = custo oportunidade A). APLICAÇÕES ANÁLISE INVESTIMENTO: 1) TAXA DESCONTO: reflete custo oportunidade capital. Se empresa pode investir mercado financeiro 10% a.a. (risco similar), projeto deve superar 10% (senão melhor aplicar). 2) RECURSOS PRÓPRIOS: usar terreno próprio = custo oportunidade aluguel que deixou receber. 3) TEMPO GESTORES: dedicar tempo projeto X = não dedicar Y. EXEMPLO: empresa tem R$ 1 milhão. Projeto A: VPL 200 mil. Projeto B: VPL 150 mil (mutuamente excludentes). Escolhe A. Custo oportunidade A = 150 mil (B renunciado). Benefício líquido = 200 - 150 = 50 mil. FLUXO CAIXA INCREMENTAL: considera apenas diferença vs cenário sem projeto (incorpora oportunidade). IMPORTANTE: custo oportunidade NÃO aparece contabilidade (não é desembolso), mas ESSENCIAL decisão econômica. Ignorar = decisões subótimas.', difficulty: 'hard', examBoard: 'CVM', year: 2024 },

    // ============= VALOR PRESENTE LÍQUIDO (VPL) (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'valor-presente-liquido-vpl', question: 'O Valor Presente Líquido (VPL) representa:', options: ['Apenas o investimento inicial', 'Diferença entre valor presente das entradas e saídas de caixa, trazidas à data zero pela taxa de desconto', 'Somente as receitas futuras', 'Taxa de retorno do projeto', 'Valor contábil do ativo'], correctAnswer: 1, explanation: 'VPL - VALOR PRESENTE LÍQUIDO (NPV - Net Present Value): diferença entre VALOR PRESENTE entradas caixa FUTURAS e SAÍDAS (investimento), descontadas taxa apropriada. FÓRMULA: VPL = Σ [FCt / (1+k)^t] - I0. Onde: FCt = fluxo caixa período t, k = taxa desconto (custo capital), I0 = investimento inicial. INTERPRETAÇÃO: VPL > 0 → projeto VIÁVEL (cria valor, retorno > custo capital). VPL = 0 → indiferente (retorno = custo). VPL < 0 → INVIÁVEL (destrói valor). VPL = VALOR ABSOLUTO criado/destruído. VANTAGENS: considera valor tempo dinheiro, todos fluxos, adiciona valor (VPLs somam-se), consistente objetivo maximizar riqueza. DECISÃO: ACEITAR se VPL > 0. Projetos excludentes: escolher MAIOR VPL. TAXA DESCONTO: crítica. Geralmente WACC (custo médio ponderado capital). Reflete risco projeto. IMPORTANTE: VPL é PADRÃO-OURO análise investimento (melhor critério). Medida ABSOLUTA valor (R$). vs TIR (taxa). Múltiplos projetos: SOMAR VPLs (aditividade).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'valor-presente-liquido-vpl', question: 'Um projeto com investimento inicial de R$ 100.000, fluxos anuais de R$ 30.000 por 5 anos e taxa de desconto de 10% a.a. Considerando que o fator de valor presente de anuidade (5 anos, 10%) = 3,7908, o VPL é:', options: ['R$ 13.724', 'R$ 113.724', '-R$ 13.724', 'R$ 50.000', 'R$ 100.000'], correctAnswer: 0, explanation: 'CÁLCULO VPL: VPL = VP(entradas) - Investimento inicial. DADOS: I0 = 100.000, FC anual = 30.000 (5 anos), k = 10% a.a., Fator VP anuidade (5 anos, 10%) = 3,7908. CÁLCULO: VP entradas = FC × Fator = 30.000 × 3,7908 = 113.724. VPL = 113.724 - 100.000 = 13.724. INTERPRETAÇÃO: VPL = R$ 13.724 POSITIVO → projeto VIÁVEL. Cria valor R$ 13.724 (acima custo capital). Retorno > 10% a.a. DECISÃO: ACEITAR projeto. SENSIBILIDADE: VPL positivo mas relativamente pequeno vs investimento (13,7%). Analisar sensibilidade (se premissas mudarem ligeiramente, pode ficar negativo). FATOR ANUIDADE: simplifica cálculo quando fluxos são uniformes (anuidade). Fórmula: FVP = [(1+i)^n - 1] / [i(1+i)^n] = [(1,10)^5 - 1] / [0,10(1,10)^5] = 3,7908. IMPORTANTE: HP12C: 30.000 PMT, 5 n, 10 i, PV (resultado 113.724), menos 100.000 = VPL 13.724. Excel: =VPL(10%; B2:B6) - I0. Sem fator: somar cada FC/(1,10)^t.', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'valor-presente-liquido-vpl', question: 'Quando a taxa de desconto aumenta, o VPL de um projeto:', options: ['Sempre aumenta', 'Geralmente diminui', 'Permanece constante', 'Não há relação', 'Depende apenas do investimento inicial'], correctAnswer: 1, explanation: 'RELAÇÃO VPL × TAXA DESCONTO: INVERSA. ↑taxa → ↓VPL (geralmente). EXPLICAÇÃO: VPL = Σ [FCt / (1+k)^t] - I0. Quando ↑k (denominador): divisor maior → VP cada fluxo menor → soma VPs menor → VPL diminui. GRÁFICO: VPL (eixo Y) × taxa desconto (eixo X) = curva DECRESCENTE. Intercepta eixo X no ponto TIR (VPL = 0). EXCEÇÕES: fluxos não-convencionais (múltiplas mudanças sinal) podem ter múltiplas TIRs, comportamento atípico. Projeto com saídas futuras (desativação) pode ter relação diferente. IMPLICAÇÕES: 1) Ambiente juros ALTOS: projetos menos viáveis (VPLs menores). Critérios aceitação mais rigorosos. 2) Ambiente juros BAIXOS: mais projetos viáveis. 3) Projetos longo prazo: MAIS sensíveis taxa (fluxos distantes, exponencial maior). Curto prazo: menos sensível. ANÁLISE SENSIBILIDADE taxa: crucial. Testar VPL com taxas +/- 2%, 5%. IMPORTANTE: taxa desconto reflete RISCO + custo oportunidade. Maior risco → maior taxa exigida → menor VPL (compensa risco). Escolha taxa = decisão crítica.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'valor-presente-liquido-vpl', question: 'A regra de decisão do VPL para projetos independentes é:', options: ['Rejeitar se VPL > 0', 'Aceitar todos os projetos com VPL > 0 (sujeito a restrições de capital)', 'Aceitar apenas VPL = 0', 'Rejeitar sempre', 'VPL não é critério de decisão'], correctAnswer: 1, explanation: 'REGRA DECISÃO VPL - PROJETOS INDEPENDENTES: ACEITAR TODOS projetos VPL > 0 (desde que capital disponível). RACIONALIDADE: VPL > 0 significa projeto CRIA VALOR (retorno > custo capital). Aceitar = aumentar riqueza acionistas. VPL = 0: indiferente (retorno = custo). Geralmente rejeita (risco não compensado). VPL < 0: REJEITAR (destrói valor). PROJETOS INDEPENDENTES: aceitação um NÃO afeta outros. Não competem. Critério: viabilidade individual. Exemplo: empresa 5 projetos independentes, 3 com VPL > 0 → aceita 3, rejeita 2. RESTRIÇÃO CAPITAL (racionamento): se capital LIMITADO, NÃO pode aceitar todos VPL > 0. Solução: ÍNDICE LUCRATIVIDADE (IL = VPL/Investimento), ordena por rentabilidade relativa. Aceita até esgotar capital. ADITIVIDADE: VPLs somam-se. Portfólio projetos: VPL total = Σ VPLs individuais. vs PROJETOS MUTUAMENTE EXCLUDENTES: escolher MAIOR VPL (um só). IMPORTANTE: VPL > 0 = condição NECESSÁRIA (não sempre suficiente se racionamento). Regra alinhada objetivo: maximizar valor firma.', difficulty: 'medium', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'valor-presente-liquido-vpl', question: 'O Índice de Lucratividade (IL) relaciona-se com VPL da seguinte forma:', options: ['IL = VPL × Investimento', 'IL = (VPL + Investimento) / Investimento = VP Entradas / Investimento', 'IL = VPL - Investimento', 'Não há relação', 'IL = 1 / VPL'], correctAnswer: 1, explanation: 'ÍNDICE LUCRATIVIDADE (IL ou Profitability Index - PI): relação entre VALOR PRESENTE entradas e INVESTIMENTO. FÓRMULAS: IL = VP(entradas futuras) / Investimento inicial. Ou: IL = (VPL + I0) / I0 = 1 + (VPL/I0). INTERPRETAÇÃO: IL > 1 → VPL > 0 (viável). IL = 1 → VPL = 0 (indiferente). IL < 1 → VPL < 0 (inviável). IL = retorno por R$ 1 investido. Ex: IL = 1,20 → cada R$ 1 investido retorna R$ 1,20 (VP), lucro R$ 0,20. VANTAGEM vs VPL: medida RELATIVA (rentabilidade). Útil RACIONAMENTO CAPITAL: ordena projetos por rentabilidade relativa. Maximiza VPL total com capital limitado. EXEMPLO: Projeto A: I0=100, VPL=20, IL=1,20. Projeto B: I0=200, VPL=30, IL=1,15. Se capital ilimitado: aceita ambos (VPL>0). Se capital=200: aceita A (IL maior, sobra 100 para outros). DECISÃO: IL > 1 → aceitar. Excludentes: pode conflitar VPL (escolher maior VPL, não IL). IMPORTANTE: IL consistente VPL (mesma decisão projetos independentes). Útil complemento análise. Excel: =VPL(taxa;fluxos)/I0.', difficulty: 'hard', examBoard: 'CVM', year: 2024 },

    // ============= TAXA INTERNA DE RETORNO (TIR) (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'taxa-interna-de-retorno-tir', question: 'A Taxa Interna de Retorno (TIR) de um projeto é:', options: ['Sempre igual à taxa de desconto', 'Taxa de desconto que torna o VPL igual a zero', 'Valor presente dos fluxos futuros', 'Investimento inicial do projeto', 'Taxa de inflação do período'], correctAnswer: 1, explanation: 'TIR - TAXA INTERNA RETORNO (IRR - Internal Rate of Return): taxa DESCONTO que torna VPL = 0. Taxa que IGUALA VP entradas = VP saídas. FÓRMULA: 0 = Σ [FCt / (1+TIR)^t] - I0. Resolver para TIR (iteração, HP12C, Excel). INTERPRETAÇÃO: TIR = taxa retorno IMPLÍCITA projeto. Rentabilidade anualizada. DECISÃO: TIR > custo capital (k) → ACEITAR. TIR = k → indiferente. TIR < k → REJEITAR. VANTAGENS: fácil comunicar (%), intuitivo (taxa retorno). DESVANTAGENS: 1) Pode haver MÚLTIPLAS TIRs (fluxos não-convencionais, + 1 mudança sinal). 2) Pressupõe REINVESTIMENTO fluxos à própria TIR (irreal). 3) CONFLITA VPL projetos excludentes (escalas/prazos diferentes). REGRA: TIR útil screening inicial. Decisão final: VPL (superior). CÁLCULO: HP12C: fluxos CFj, IRR. Excel: =TIR(valores). IMPORTANTE: TIR mede taxa (%), VPL valor (R$). TIR alta ≠ melhor projeto (pode ter VPL menor). Exemplo: TIR 50% em R$ 10 mil vs TIR 20% em R$ 1 milhão (segunda melhor - cria + valor).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'taxa-interna-de-retorno-tir', question: 'Um projeto com investimento inicial de R$ 10.000 e retorno único de R$ 12.100 após 1 ano possui TIR de:', options: ['10%', '21%', '12,1%', '2,1%', '100%'], correctAnswer: 1, explanation: 'CÁLCULO TIR SIMPLES: VPL = 0. DADOS: I0 = -10.000, FC1 = 12.100. FÓRMULA: 0 = -10.000 + 12.100/(1+TIR)^1. Resolver: 10.000 = 12.100/(1+TIR). 1+TIR = 12.100/10.000 = 1,21. TIR = 0,21 = 21% a.a. VERIFICAÇÃO: VPL com 21%: -10.000 + 12.100/1,21 = -10.000 + 10.000 = 0 ✓. INTERPRETAÇÃO: projeto rende 21% a.a. Se custo capital < 21% (ex: 15%) → aceitar (TIR > k). Se custo capital > 21% (ex: 25%) → rejeitar. GANHO: 12.100 - 10.000 = 2.100 (1 ano). Rentabilidade: 2.100/10.000 = 21%. HP12C: 10000 CHS g CFj, 12100 g CFj, f IRR → 21. EXEMPLO PRÁTICO: aplicação rende 21% a.a., banco oferece 15% a.a. → projeto viável (supera alternativa). IMPORTANTE: caso SIMPLES (1 período, 1 fluxo). Múltiplos períodos: iteração necessária (não-linear). Fórmula geral não-explícita (precisa calculadora financeira/Excel). Regra: TIR compara com TMA (Taxa Mínima Atratividade = custo capital).', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'taxa-interna-de-retorno-tir', question: 'O conflito entre VPL e TIR pode ocorrer quando:', options: ['Projetos são independentes e têm mesma escala', 'Projetos são mutuamente excludentes com diferentes escalas de investimento ou prazos', 'VPL é sempre positivo', 'TIR não existe', 'Não há taxa de desconto'], correctAnswer: 1, explanation: 'CONFLITO VPL × TIR: rankings DIVERGENTES projetos mutuamente excludentes. CAUSAS: 1) ESCALAS DIFERENTES: Projeto A (I0=10, VPL=5, TIR=50%). Projeto B (I0=100, VPL=30, TIR=30%). VPL: B > A. TIR: A > B. Conflito! 2) PRAZOS DIFERENTES: A (curto prazo, TIR alta). B (longo prazo, TIR menor, VPL maior). 3) PADRÃO FLUXOS: A (fluxos concentrados início). B (fluxos tardios). CAUSA CONFLITO: TIR pressupõe REINVESTIMENTO à própria TIR. VPL: à taxa desconto (realista). Quando taxas diferem, rankings divergem. TAXA FISHER: taxa que iguala VPLs (interseção curvas). Abaixo Fisher: um ranking. Acima: outro. SOLUÇÃO: SEMPRE VPL. Objetivo: maximizar VALOR (R$), não taxa (%). VPL consistente aditividade, reinvestimento realista. ANÁLISE INCREMENTAL: calcular TIR diferença fluxos (B - A). Se TIR incremental > k → escolhe B. Equivale VPL. IMPORTANTE: TIR não é ERRADA (útil comunicação). Mas decisão final: VPL. Exemplo clássico: pequeno projeto alta TIR vs grande projeto TIR menor VPL maior → segundo cria + riqueza.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'taxa-interna-de-retorno-tir', question: 'Fluxos de caixa não-convencionais podem resultar em:', options: ['Sempre uma única TIR', 'Múltiplas TIRs ou nenhuma TIR', 'VPL sempre positivo', 'TIR negativa sempre', 'Não afeta cálculo TIR'], correctAnswer: 1, explanation: 'FLUXOS NÃO-CONVENCIONAIS: mais de UMA mudança SINAL (+ para -, - para +). CONVENCIONAL: saída inicial, entradas depois (-,+,+,+). NÃO-CONVENCIONAL: ex: -,+,+,-,+ (investimento inicial, operação positiva, desativação custosa final). PROBLEMA: equação VPL=0 pode ter MÚLTIPLAS raízes (TIRs) ou NENHUMA. Regra Descartes: nº máximo raízes positivas = nº mudanças sinal. EXEMPLO: FC = -1000, +6000, -11000, +6000. 3 mudanças sinal → até 3 TIRs. Possível: TIR1=0%, TIR2=100%, TIR3=200% (todas tornam VPL=0!). Qual usar? AMBIGUIDADE. SOLUÇÃO: 1) TIR MODIFICADA (MTIR): assume reinvestimento à taxa desconto (elimina problema). 2) VPL: não sofre problema. DECISÃO confiável. SITUAÇÕES não-convencionais: projetos mineração (desativação custosa), substituição equipamentos, concessões (devolução ativo). IMPORTANTE: TIR NÃO CONFIÁVEL fluxos não-convencionais. Excel/HP podem mostrar uma TIR (menor positiva), mas outras existem. SEMPRE verificar padrão fluxo antes confiar TIR. VPL robusto qualquer padrão. Teste: plotar VPL × taxa (curva pode cruzar eixo X múltiplas vezes = múltiplas TIRs).', difficulty: 'hard', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'taxa-interna-de-retorno-tir', question: 'A TIR Modificada (MTIR ou TIRM) foi desenvolvida para:', options: ['Aumentar o VPL', 'Eliminar problemas de múltiplas TIRs e usar premissa de reinvestimento mais realista', 'Reduzir investimento inicial', 'Apenas para fluxos convencionais', 'Calcular payback'], correctAnswer: 1, explanation: 'TIR MODIFICADA (MTIR/TIRM - Modified IRR): variante TIR que resolve LIMITAÇÕES. OBJETIVO: 1) Eliminar MÚLTIPLAS TIRs. 2) Premissa REINVESTIMENTO realista (à taxa desconto k, não à TIR). MÉTODO: 1) Calcular VALOR FUTURO fluxos POSITIVOS (entradas), capitalizados à taxa desconto k até fim projeto. VF = Σ FC+ × (1+k)^(n-t). 2) Manter investimentos INICIAIS VP (ou trazer saídas intermediárias a VP). 3) MTIR: taxa que iguala PV saídas = VF entradas. PV(saídas) × (1+MTIR)^n = VF(entradas). VANTAGENS: 1) Sempre ÚNICA solução. 2) Reinvestimento à k (+ realista que TIR à própria taxa). 3) Ranking consistente VPL (geralmente). CÁLCULO Excel: =MTIR(valores; taxa_financiamento; taxa_reinvestimento). HP12C não tem função direta (manual). DESVANTAGEM: menos conhecido que TIR. DECISÃO: MTIR > k → aceitar. IMPORTANTE: MTIR soluciona problemas TIR, mas VPL ainda superior (medida valor absoluto). Empresas usam MTIR quando preferem comunicar taxa (%) vs valor (R$ VPL). Útil apresentações executivos (taxa + intuitiva).', difficulty: 'medium', examBoard: 'CVM', year: 2024 },

    // ============= PAYBACK (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'payback', question: 'O Payback Simples (período de recuperação) mede:', options: ['Taxa de retorno do projeto', 'Tempo necessário para recuperar o investimento inicial através dos fluxos de caixa', 'Valor presente líquido', 'Custo de capital', 'Lucro contábil'], correctAnswer: 1, explanation: 'PAYBACK SIMPLES (Período Recuperação): TEMPO necessário recuperar INVESTIMENTO INICIAL através fluxos caixa projeto. Quanto tempo para "empatar". CÁLCULO: acumula fluxos caixa até soma = investimento. Momento que FC acumulado = I0. EXEMPLO: I0 = 15.000, FC1=5.000, FC2=6.000, FC3=6.000. Acumulado: ano 1=5.000, ano 2=11.000, ano 3=17.000. Payback entre ano 2-3. Ano 2: falta 4.000 (15-11). Ano 3 traz 6.000. Fração: 4/6 = 0,67 ano. Payback = 2,67 anos (2 anos 8 meses). DECISÃO: aceitar se payback ≤ prazo máximo definido empresa (ex: 3 anos). VANTAGENS: simples calcular/comunicar, foco LIQUIDEZ (rápida recuperação), útil ambientes alto risco (preferência retorno rápido). DESVANTAGENS: 1) IGNORA valor tempo dinheiro (trata R$ ano 1 = ano 3). 2) IGNORA fluxos APÓS payback (projeto pode ser muito lucrativo depois). 3) Critério ARBITRÁRIO (prazo máximo subjetivo). NÃO mede rentabilidade. IMPORTANTE: payback COMPLEMENTAR (não substitui VPL/TIR). Útil análise risco liquidez. Empresas: frequentemente usam como filtro inicial.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'payback', question: 'Um projeto com investimento de R$ 50.000 e fluxos anuais de R$ 12.000 (uniforme) tem payback simples de:', options: ['5,00 anos', '4,17 anos', '3,00 anos', '6,00 anos', '4,50 anos'], correctAnswer: 1, explanation: 'CÁLCULO PAYBACK FLUXOS UNIFORMES: Payback = Investimento / Fluxo Anual. DADOS: I0 = 50.000, FC anual = 12.000. CÁLCULO: Payback = 50.000 / 12.000 = 4,1667 anos = 4,17 anos (4 anos 2 meses). VERIFICAÇÃO: 4 anos × 12.000 = 48.000 (falta 2.000). Ano 5: entra 12.000. Fração ano 5: 2.000/12.000 = 0,1667. Total: 4,17 anos ✓. INTERPRETAÇÃO: projeto recupera investimento em 4 anos 2 meses. Se empresa aceita payback ≤ 5 anos → viável (critério payback). Se exige ≤ 4 anos → não atende. DECISÃO: payback isolado NÃO SUFICIENTE. Precisa VPL/TIR. Exemplo: pode ter payback 4,17 anos MAS VPL negativo (se custo capital alto, fluxos futuros descontados valem pouco). Ou payback 4,17 anos, VPL positivo grande (muitos anos vida útil após payback). IMPORTANTE: fórmula simplificada SÓ fluxos UNIFORMES (anuidade). Fluxos irregulares: acumular manualmente ano a ano. Excel: criar coluna acumulado, identificar quando vira positivo.', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'payback', question: 'O Payback Descontado difere do Payback Simples por:', options: ['Não considera fluxos de caixa', 'Trazer os fluxos a valor presente pela taxa de desconto antes de calcular recuperação', 'Sempre ser maior que payback simples', 'Não ter aplicação prática', 'Ser igual ao VPL'], correctAnswer: 1, explanation: 'PAYBACK DESCONTADO (Discounted Payback): tempo recuperar investimento considerando VALOR PRESENTE fluxos (descontados). Corrige principal falha payback simples. MÉTODO: 1) Descontar cada FC pela taxa k: VP(FCt) = FCt/(1+k)^t. 2) Acumular VPs. 3) Identificar quando VP acumulado = I0. EXEMPLO: I0=10.000, FC1=4.000, FC2=4.000, FC3=4.000, k=10%. VP1=4.000/1,10=3.636, VP2=4.000/1,21=3.306, VP3=4.000/1,331=3.005. Acum: ano 1=3.636, ano 2=6.942, ano 3=9.947 (ainda não recuperou!). Ano 4: VP4=4.000/1,464=2.732 → acum=12.679 (recuperou). Payback descontado ≈ 3,1 anos. vs Payback simples: 10.000/4.000=2,5 anos. DIFERENÇA: descontado SEMPRE ≥ simples (VP < valor nominal). DECISÃO: payback descontado ≤ prazo máximo E VPL > 0. VANTAGEM vs simples: considera valor tempo dinheiro. DESVANTAGEM vs VPL: ainda ignora fluxos após payback, critério arbitrário. IMPORTANTE: melhoria sobre simples, mas VPL/TIR superiores. Útil quando liquidez é crítica (startups, alto risco).', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'payback', question: 'Uma limitação importante do Payback Simples é:', options: ['Considera valor do dinheiro no tempo', 'Ignora fluxos de caixa após o período de recuperação', 'Sempre leva à mesma decisão que o VPL', 'É muito complexo de calcular', 'Não considera investimento inicial'], correctAnswer: 1, explanation: 'LIMITAÇÕES PAYBACK SIMPLES: 1) IGNORA valor TEMPO dinheiro: R$ ano 1 tratado igual R$ ano 5 (erro conceitual). Solução: payback descontado. 2) IGNORA fluxos APÓS payback: projeto pode gerar lucros enormes após recuperação (ignorados). Exemplo: payback 3 anos, projeto vive 20 anos com lucros anuais altos → payback rejeita, VPL aceita. 3) Critério decisão ARBITRÁRIO: "prazo máximo aceitável" subjetivo (2 anos? 5 anos?). Sem base econômica. 4) NÃO MEDE RENTABILIDADE: apenas liquidez/risco. Projeto payback curto pode ter TIR baixa. Payback longo pode ter TIR altíssima. 5) VIÉS contra projetos LONGO PRAZO: desfavorece investimentos infraestrutura, P&D (retorno + tardio mas alto VPL). CONSEQUÊNCIA: usar payback ISOLADO = decisões SUBÓTIMAS. Rejeitar projetos VPL positivo (lucrativos). Aceitar projetos VPL negativo (recuperam rápido mas destroem valor depois). APLICAÇÃO CORRETA: filtro INICIAL (liquidez/risco), COMPLEMENTAR a VPL/TIR. Nunca critério único. IMPORTANTE: empresas startups, alto risco, capital escasso: payback relevante (sobrevivência). Mas sempre calcular VPL também.', difficulty: 'medium', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'payback', question: 'Dois projetos têm mesmo investimento inicial e mesmo payback. Necessariamente:', options: ['Têm mesmo VPL', 'Têm mesma TIR', 'Não necessariamente têm mesmo VPL ou TIR (fluxos após payback diferem)', 'São igualmente rentáveis', 'Devem ser rejeitados'], correctAnswer: 2, explanation: 'PAYBACK IGUAL ≠ PROJETOS EQUIVALENTES: payback mede APENAS tempo recuperação, NÃO rentabilidade total. EXEMPLO: ambos I0=10.000, payback=2 anos. PROJETO A: FC1=5.000, FC2=5.000, FC3-10=0 (acaba ano 2). VPL (10%)=-10.000+4.545+4.132=−1.323 (NEGATIVO). PROJETO B: FC1=5.000, FC2=5.000, FC3-10=3.000/ano. VPL (10%)=−10.000+4.545+4.132+15.026=+13.703 (POSITIVO). Mesmo payback (2 anos), VPLs TOTALMENTE diferentes. TIRs diferentes. CAUSA: payback IGNORA o que acontece APÓS recuperação. Projeto A morre (VPL negativo). Projeto B continua gerando (VPL positivo alto). DECISÃO: payback sozinho INSUFICIENTE. Projeto A: payback 2 anos (bom?), mas VPL negativo (ruim!). Rejeitar. Projeto B: payback 2 anos E VPL positivo (ótimo!). Aceitar. IMPORTANTE: payback útil COMPARAR projetos mesma vida útil, similar risco. Mas SEMPRE calcular VPL/TIR decisão final. Empresas erro comum: aceitar projeto payback curto sem olhar VPL (pode destruir valor). Ou rejeitar payback longo sem ver VPL alto. Análise completa essencial.', difficulty: 'hard', examBoard: 'CVM', year: 2024 },

    // ============= ESTRUTURA DE CAPITAL (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'estrutura-de-capital', question: 'Estrutura de Capital refere-se a:', options: ['Apenas ativos da empresa', 'Combinação de recursos próprios (capital próprio/patrimônio líquido) e de terceiros (dívidas) que financiam os ativos', 'Somente capital social', 'Apenas dívidas de curto prazo', 'Valor de mercado das ações'], correctAnswer: 1, explanation: 'ESTRUTURA CAPITAL: mix FINANCIAMENTO empresa. Combinação CAPITAL PRÓPRIO (patrimônio líquido - PL) e CAPITAL TERCEIROS (dívidas). COMPONENTES: 1) CAPITAL PRÓPRIO: ações ordinárias/preferenciais, lucros retidos. Custo: dividendos, valorização ações (custo oportunidade acionistas). SEM obrigação pagamento. 2) CAPITAL TERCEIROS: empréstimos, debêntures, financiamentos. Custo: juros. Obrigação contratual. MÉTRICAS: a) Endividamento = Dívida/PL ou Dívida/Ativo. b) Alavancagem financeira = Dívida/Equity. DECISÃO ESTRUTURA: trade-off benefícios dívida (juros dedutíveis IR - escudo fiscal, menor custo que equity) vs custos (risco falência, custos agência). TEORIA: Modigliani-Miller (MM): mundo perfeito, estrutura irrelevante (valor independe financiamento). Mundo real: impostos, falência, agência → estrutura IMPORTA. Existe estrutura ÓTIMA (minimiza WACC, maximiza valor). OBJETIVO: minimizar custo capital ponderado, maximizar valor empresa. IMPORTANTE: escolha estrutura = decisão ESTRATÉGICA. Impacta risco, retorno, flexibilidade.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'estrutura-de-capital', question: 'O benefício fiscal da dívida (tax shield) ocorre porque:', options: ['Dívida não tem custo', 'Juros da dívida são dedutíveis do lucro tributável, reduzindo impostos', 'Acionistas não pagam dividendos', 'Dívida elimina risco', 'Não há benefício fiscal'], correctAnswer: 1, explanation: 'BENEFÍCIO FISCAL DÍVIDA (Tax Shield/Escudo Fiscal): JUROS dívida são DEDUTÍVEIS IR, reduzindo base tributável → ECONOMIA imposto. MECÂNICA: Empresa sem dívida: LAIR 100, IR 34% → imposto 34, lucro líquido 66. Empresa com dívida (juros 30): LAIR 100, (-) Juros 30, Lucro antes IR 70, IR 34% × 70 = 23,8, lucro líquido 46,2. DIFERENÇA imposto: 34 - 23,8 = 10,2 (economia = 34% × 30 juros). VALOR ESCUDO: economia anual IR = Taxa IR × Juros. Perpetuidade: VPL escudo = Taxa IR × Dívida. Ex: dívida 1.000, IR 34% → escudo 340. IMPLICAÇÃO: dívida MAIS BARATA que capital próprio (após IR). Custo efetivo dívida = juros × (1 - IR). Juros 10%, IR 34% → custo líquido 6,6%. TEORIA MM com impostos: valor firma alavancada = valor sem dívida + VP escudo fiscal. Incentiva endividamento. LIMITE: custos falência (excessivo endividamento) compensam benefício fiscal. Trade-off. IMPORTANTE: benefício NÃO EXISTE se empresa prejuízo (não paga IR). Escudo só vale se lucro tributável. Estrutura ótima balanceia escudo fiscal vs risco falência.', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'estrutura-de-capital', question: 'Segundo a Teoria do Trade-Off, a estrutura ótima de capital resulta de:', options: ['Máxima dívida possível', 'Equilíbrio entre benefícios fiscais da dívida e custos de dificuldades financeiras', 'Apenas capital próprio', 'Não existe estrutura ótima', 'Mínima dívida possível'], correctAnswer: 1, explanation: 'TEORIA TRADE-OFF: estrutura ótima capital resulta EQUILÍBRIO entre BENEFÍCIOS e CUSTOS dívida. BENEFÍCIOS DÍVIDA: 1) ESCUDO FISCAL: juros dedutíveis IR (economia imposto). 2) Disciplina gestores (obrigação pagar juros reduz fluxo livre - menos desperdício). CUSTOS DÍVIDA: 1) CUSTOS FALÊNCIA: diretos (advogados, liquidação) e indiretos (perda clientes, fornecedores). Probabilidade falência ↑ com alavancagem. 2) CUSTOS AGÊNCIA: conflito acionistas-credores (acionistas incentivo projetos arriscados com dinheiro credores). Covenants, monitoramento (custosos). 3) Perda FLEXIBILIDADE financeira. ESTRUTURA ÓTIMA: ponto onde benefício MARGINAL dívida adicional = custo MARGINAL. Maximiza valor firma. GRÁFICO: valor firma = V sem dívida + VP escudo fiscal - VP custos falência. Máximo = estrutura ótima. APLICAÇÃO: varia por SETOR. Empresas ativos tangíveis, fluxo estável (utilities): + dívida (menor risco falência). Empresas tecnologia, ativos intangíveis: - dívida (alto risco, flexibilidade). IMPORTANTE: não existe fórmula única. Depende: impostos, risco negócio, garantias, flexibilidade necessária. Gestores avaliam trade-off especificamente empresa.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'estrutura-de-capital', question: 'A Teoria de Pecking Order (Hierarquia das Fontes) sugere que empresas preferem financiar-se:', options: ['Sempre com dívida externa', 'Primeiro com recursos internos, depois dívida, por último emissão de ações', 'Apenas com emissão de ações', 'Sempre com capital próprio', 'Não há ordem de preferência'], correctAnswer: 1, explanation: 'TEORIA PECKING ORDER (Myers-Majluf): empresas seguem HIERARQUIA financiamento. ORDEM PREFERÊNCIA: 1º) RECURSOS INTERNOS (lucros retidos): custo zero emissão, sem assimetria informação, flexível. 2º) DÍVIDA: quando internos insuficientes. Menos assimetria que ações, escudo fiscal. 3º) EMISSÃO AÇÕES: última opção. RACIONALIDADE: ASSIMETRIA INFORMAÇÃO. Gestores sabem + que mercado. Emitir ações quando supervalorizadas (sinal negativo). Mercado interpreta emissão = "ações caras" → preço cai. Empresa evita. Lucros retidos: sem sinal. Dívida: menos assimetria (valor fixo, não afeta controle). CONSEQUÊNCIA: NÃO existe estrutura ótima (trade-off). Estrutura resulta de necessidades financiamento históricas. Empresas lucrativas: pouca dívida (autofinanciamento). Empresas déficit: + dívida. EVIDÊNCIA EMPÍRICA: empresas realmente seguem ordem (observações confirmam). Explicação diferente trade-off. IMPORTANTE: pecking order vs trade-off: visões distintas. Realidade: ambos fatores atuam. Empresas balanceiam assimetria informação (pecking) com trade-off fiscal-falência. Estrutura = resultado múltiplos fatores.', difficulty: 'hard', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'estrutura-de-capital', question: 'O índice de endividamento (Dívida Total / Ativo Total) de 60% significa que:', options: ['Empresa não tem dívidas', '60% dos ativos são financiados por capital de terceiros', 'Empresa está falida', '60% das receitas são dívidas', 'Patrimônio líquido é 60% do ativo'], correctAnswer: 1, explanation: 'ÍNDICE ENDIVIDAMENTO (Debt Ratio): Dívida Total / Ativo Total. Mede proporção ativos FINANCIADOS por CAPITAL TERCEIROS. INTERPRETAÇÃO 60%: 60% ativos financiados DÍVIDA (passivo oneroso + não-oneroso). 40% financiados CAPITAL PRÓPRIO (PL). EXEMPLO: ativo 100, dívida 60, PL 40 (Balanço: A=P+PL, 100=60+40). Endividamento: 60/100=60%. ANÁLISE: 60% considerado ALTO (regra geral). Risco financeiro elevado. Menor flexibilidade. Maior exposição juros, vencimentos. VARIA SETOR: utilities, infraestrutura: 60-70% normal (fluxo previsível). Tecnologia: 10-30% (incerteza, intangíveis). OUTROS ÍNDICES: a) Dívida/PL (alavancagem financeira): 60/40=1,5. Cada R$ 1 PL, R$ 1,50 dívida. b) PL/Ativo: 40%. c) Composição Endividamento: CP vs LP (preferível LP). CONSEQUÊNCIAS alto endividamento: + risco falência, - flexibilidade, + custo capital (prêmio risco), pressão fluxo caixa (juros/principal). Mas: escudo fiscal. DECISÃO: analisar tendência (aumentando?), comparar setor, avaliar capacidade pagamento (cobertura juros). IMPORTANTE: índice isolado insuficiente. Combinar com rentabilidade, liquidez, cobertura. Contexto setorial fundamental.', difficulty: 'medium', examBoard: 'CVM', year: 2024 },

    // ============= CUSTO DE CAPITAL (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'custo-de-capital', question: 'O custo de capital representa:', options: ['Apenas juros de empréstimos', 'Taxa de retorno exigida pelos fornecedores de capital (credores e acionistas) para investir na empresa', 'Somente dividendos', 'Valor contábil da dívida', 'Custo de produção'], correctAnswer: 1, explanation: 'CUSTO CAPITAL: taxa RETORNO EXIGIDA fornecedores capital (credores + acionistas) para investir empresa. Custo OPORTUNIDADE capital. COMPONENTES: 1) Custo DÍVIDA (Kd): juros exigidos credores. Após IR: Kd(1-T). 2) Custo CAPITAL PRÓPRIO (Ke): retorno exigido acionistas (dividendos + ganho capital). CAPM: Ke = Rf + β(Rm-Rf). IMPORTÂNCIA: 1) Taxa DESCONTO análise investimentos (VPL, TIR vs custo). 2) Benchmark DESEMPENHO (retorno > custo = cria valor). 3) Avaliação empresa (fluxo descontado). 4) Decisão ESTRUTURA capital (minimizar custo). FONTES CAPITAL: externas (dívida, ações novas) e internas (lucros retidos). Cada uma: custo próprio. CUSTO vs RETORNO: investidores exigem retorno compensando RISCO. Maior risco empresa → maior custo capital (prêmio). EMPRESA VISTA: custo (paga retorno investidores). INVESTIDOR VISTA: retorno exigido. IMPORTANTE: custo capital NÃO é taxa bancária simplesmente. É taxa que EQUILIBRA oferta-demanda capital dada risco empresa. Empresa não "escolhe" custo (mercado determina, dado risco). Pode influenciar via estrutura capital, reduzir risco operacional.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'custo-de-capital', question: 'Uma empresa emite debêntures pagando 12% a.a. de juros. Com alíquota de IR de 34%, o custo da dívida após impostos é:', options: ['12,0%', '7,92%', '34,0%', '4,08%', '46,0%'], correctAnswer: 1, explanation: 'CUSTO DÍVIDA APÓS IMPOSTOS: Kd × (1 - T). Onde Kd = taxa juros, T = alíquota IR. RACIONALIDADE: juros DEDUTÍVEIS IR → economia fiscal reduz custo efetivo. DADOS: Kd = 12% a.a., T = 34%. CÁLCULO: Custo líquido = 12% × (1 - 0,34) = 12% × 0,66 = 7,92% a.a. INTERPRETAÇÃO: empresa paga 12% credores, MAS economia IR 34% reduz custo real para 7,92%. Cada R$ 100 juros: paga 100, economiza 34 IR, custo líquido 66 (7,92% se base 1.000). EXEMPLO NUMÉRICO: dívida 1.000, juros 120/ano. Sem dívida: lucro antes IR 500, IR 170, líquido 330. Com dívida: lucro antes IR 500, (-) juros 120, base IR 380, IR 129,2, líquido 250,8. Diferença IR: 170-129,2 = 40,8 (economia = 34% × 120). Custo líquido juros: 120 - 40,8 = 79,2 (7,92% de 1.000). IMPORTANTE: custo dívida SEMPRE após impostos para decisões. Uso: WACC. Empresas prejuízo: não se beneficiam escudo (usar Kd bruto). Dívida + BARATA fonte capital (vs ações) devido escudo + menor risco (prioridade falência).', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'custo-de-capital', question: 'O modelo CAPM (Capital Asset Pricing Model) para calcular custo do capital próprio utiliza:', options: ['Apenas taxa livre de risco', 'Ke = Rf + β × (Rm - Rf), onde Rf é taxa livre risco, β é beta da ação, Rm é retorno mercado', 'Somente dividendos', 'Valor contábil do PL', 'Não considera risco'], correctAnswer: 1, explanation: 'CAPM - CAPITAL ASSET PRICING MODEL: modelo calcular RETORNO EXIGIDO (custo) capital próprio baseado RISCO. FÓRMULA: Ke = Rf + β(Rm - Rf). COMPONENTES: 1) Rf (Risk-free rate): taxa LIVRE RISCO. Títulos governo (Tesouro Selic, Treasury bonds US). Retorno sem risco. 2) β (Beta): medida RISCO SISTEMÁTICO ação. β=1: volatilidade = mercado. β>1: + volátil (+ risco). β<1: - volátil. β empresa tech: 1,5. β utility: 0,6. 3) (Rm - Rf): PRÊMIO RISCO mercado. Retorno adicional mercado ações vs livre risco. Histórico Brasil: ~6-8%. EUA: ~7%. 4) β(Rm-Rf): PRÊMIO RISCO ação específica. EXEMPLO: Rf=6%, Rm=14%, β=1,2. Ke = 6% + 1,2(14%-6%) = 6% + 1,2×8% = 6% + 9,6% = 15,6%. Acionistas exigem 15,6% a.a. LÓGICA: investidor exige compensação RISCO. Quanto + arriscado (β alto) → + retorno exigido. IMPORTANTE: CAPM modelo + usado (simplicidade). Críticas: β passado não prevê futuro, pressupostos irreais. Alternativas: modelo 3-fatores Fama-French, APT. Uso: custo capital próprio no WACC, taxa desconto projetos, avaliação.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'custo-de-capital', question: 'O WACC (Weighted Average Cost of Capital) é:', options: ['Apenas custo da dívida', 'Custo médio ponderado de capital, combinando custo dívida e capital próprio pelas proporções na estrutura', 'Somente custo do patrimônio líquido', 'Taxa livre de risco', 'Valor de mercado da empresa'], correctAnswer: 1, explanation: 'WACC - WEIGHTED AVERAGE COST OF CAPITAL (Custo Médio Ponderado Capital): taxa desconto reflete custo TODAS fontes financiamento, ponderadas proporções. FÓRMULA: WACC = (E/V)×Ke + (D/V)×Kd×(1-T). Onde: E=valor mercado equity (PL), D=valor mercado dívida, V=E+D (valor total), Ke=custo equity, Kd=custo dívida, T=alíquota IR. EXEMPLO: E=600, D=400, V=1.000. Ke=15%, Kd=10%, T=34%. WACC = (600/1.000)×15% + (400/1.000)×10%×0,66 = 0,6×15% + 0,4×6,6% = 9% + 2,64% = 11,64%. INTERPRETAÇÃO: empresa precisa gerar 11,64% retorno médio satisfazer credores+acionistas. APLICAÇÕES: 1) Taxa DESCONTO projetos investimento (VPL). 2) Avaliação empresa (fluxo caixa descontado WACC). 3) Benchmark desempenho (EVA: retorno - WACC). MINIMIZAR WACC: objetivo estrutura capital ótima. Estrutura minimiza WACC → maximiza valor. IMPORTANTE: usar valores MERCADO (não contábil). Equity: capitalização bolsa. Dívida: valor presente pagamentos. WACC muda com estrutura capital (proporções E/D). Projetos risco diferente empresa: ajustar WACC (+ risco → + taxa).', difficulty: 'hard', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'custo-de-capital', question: 'Por que o custo do capital próprio geralmente é maior que o custo da dívida?', options: ['Capital próprio não tem custo', 'Acionistas assumem maior risco (residuais, sem garantia) e exigem maior retorno; dívida tem prioridade e benefício fiscal', 'Dívida é mais arriscada', 'Acionistas pagam menos', 'Não há diferença'], correctAnswer: 1, explanation: 'CUSTO EQUITY > DÍVIDA: RISCO diferente. DÍVIDA (menor custo): 1) PRIORIDADE: credores têm direito PRIORITÁRIO ativos (falência: pagos antes acionistas). Garantias, covenants. 2) FLUXO FIXO: juros contratuais (previsíveis). 3) BENEFÍCIO FISCAL: juros dedutíveis IR (reduz custo efetivo). 4) Menor RISCO credores → menor retorno exigido. EQUITY (maior custo): 1) RESIDUAL: acionistas recebem APÓS todos (credores, impostos). Último na fila. 2) INCERTEZA: dividendos não garantidos (depende lucro, decisão gestores). Retorno via dividendos + valorização (volátil). 3) SEM benefício fiscal: dividendos NÃO dedutíveis. 4) RISCO total empresa: acionistas absorvem volatilidade negócio. 5) Maior RISCO → maior retorno exigido (compensação). EXEMPLO: empresa mesma, credores exigem 8%, acionistas 14%. Diferença: prêmio risco equity. HIERARQUIA RISCO/RETORNO: dívida senior < dívida subordinada < ações preferenciais < ações ordinárias. IMPORTANTE: custo equity 1,5-2× custo dívida (típico). Excesso endividamento: custo dívida sobe (risco inadimplência), pode superar equity temporariamente (distress). Estrutura ótima balanceia: dívida barata mas arriscada × equity caro mas flexível.', difficulty: 'medium', examBoard: 'CVM', year: 2024 },

    // ============= ADMINISTRAÇÃO DO CAPITAL DE GIRO (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'administracao-capital-de-giro', question: 'Capital de Giro Líquido (CGL) é definido como:', options: ['Ativo Total menos Passivo Total', 'Ativo Circulante menos Passivo Circulante', 'Apenas estoques', 'Somente caixa e bancos', 'Patrimônio Líquido'], correctAnswer: 1, explanation: 'CAPITAL GIRO LÍQUIDO (CGL ou Working Capital): diferença entre ATIVO CIRCULANTE (AC) e PASSIVO CIRCULANTE (PC). CGL = AC - PC. ATIVO CIRCULANTE: caixa, bancos, aplicações CP, contas receber, estoques. Recursos disponíveis < 1 ano. PASSIVO CIRCULANTE: fornecedores, empréstimos CP, salários pagar, impostos. Obrigações vencer < 1 ano. INTERPRETAÇÃO: CGL > 0 (positivo): AC > PC. Folga financeira. Ativos líquidos excedem obrigações CP. Saúde financeira. CGL = 0: AC = PC. Justo. Risco liquidez. CGL < 0 (negativo): PC > AC. Insuficiência recursos CP. Risco inadimplência. IMPORTÂNCIA: CGL mede LIQUIDEZ (capacidade honrar obrigações CP). Margem segurança operacional. GESTÃO: otimizar CGL (não muito alto = ocioso, ineficiente; não negativo = risco). FONTES CGL: lucros retidos, emissão ações/dívida LP, redução Ativo Não-Circulante. USOS: crescimento vendas (+ recebíveis, estoques), prejuízos, dividendos, investimentos. IMPORTANTE: CGL varia CICLO OPERACIONAL. Empresas sazonais: oscila. Varejo: CGL grande (estoques). Serviços: menor. Análise: CGL isolado insuficiente. Ver índices liquidez (corrente, seca).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'administracao-capital-de-giro', question: 'O Ciclo Operacional é composto por:', options: ['Apenas prazo médio de estocagem', 'Prazo Médio de Estocagem (PME) + Prazo Médio de Recebimento (PMR)', 'Somente prazo de pagamento', 'Apenas caixa', 'Não há ciclo definido'], correctAnswer: 1, explanation: 'CICLO OPERACIONAL (CO): tempo entre COMPRA matéria-prima/mercadoria até RECEBIMENTO venda. Período recursos aplicados operação. FÓRMULA: CO = PME + PMR. COMPONENTES: 1) PME (Prazo Médio Estocagem): tempo médio mercadoria/MP fica estoque até venda. PME = (Estoque Médio / CMV) × 360 dias. Ex: estoque 100, CMV anual 1.200 → PME = (100/1.200)×360 = 30 dias. 2) PMR (Prazo Médio Recebimento): tempo médio entre venda e recebimento (crédito clientes). PMR = (Duplicatas Receber Médio / Vendas) × 360. Ex: recebíveis 80, vendas 1.440 → PMR = (80/1.440)×360 = 20 dias. CICLO OPERACIONAL: 30 + 20 = 50 dias. INTERPRETAÇÃO: empresa leva 50 dias desde compra até receber. Recursos IMOBILIZADOS 50 dias. GESTÃO: REDUZIR CO = + eficiência, - necessidade capital giro. Ações: - estoque (JIT), - prazo clientes (desconto à vista), + giro. VARIAÇÃO SETORIAL: indústria pesada: CO longo (meses). Varejo alimentar: curto (dias). IMPORTANTE: CO isolado não diz se empresa precisa financiamento. Para isso: CICLO FINANCEIRO (CO - Prazo Pagamento Fornecedores). CO mostra OPERAÇÃO. Ciclo Financeiro: CAIXA.', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'administracao-capital-de-giro', question: 'O Ciclo Financeiro (ou Ciclo de Caixa) representa:', options: ['Apenas entradas de caixa', 'Prazo entre desembolso (pagamento fornecedores) e recebimento vendas. CF = CO - PMP', 'Somente saídas de caixa', 'Não existe ciclo financeiro', 'Igual ao ciclo operacional'], correctAnswer: 1, explanation: 'CICLO FINANCEIRO (CF ou Ciclo Caixa): tempo entre PAGAMENTO fornecedores (desembolso) e RECEBIMENTO vendas. Período empresa FINANCIA operação (precisa caixa). FÓRMULA: CF = CO - PMP = PME + PMR - PMP. Onde PMP = Prazo Médio Pagamento fornecedores. EXEMPLO: PME=30 dias, PMR=20 dias, PMP=40 dias. CO = 30+20 = 50 dias. CF = 50-40 = 10 dias. INTERPRETAÇÃO CF=10: empresa paga fornecedores (dia 40 desde compra), recebe clientes (dia 50). Intervalo 10 dias precisa FINANCIAR (capital giro). CF > 0: necessita financiamento (comum). Quanto maior CF → maior necessidade CG. CF = 0: pagamento = recebimento (equilíbrio). CF < 0: recebe ANTES pagar (fornecedores financiam). Raro, ótimo (supermercados, varejo). GESTÃO REDUZIR CF: 1) ↓PME (- estoque, + giro). 2) ↓PMR (- prazo clientes, cobrar rápido). 3) ↑PMP (negociar + prazo fornecedores). IMPORTANTE: CF determina NECESSIDADE Capital Giro (NCG). NCG = (Vendas/360) × CF. Empresa vendas 3.600, CF=10 → NCG = 10×10 = 100 (precisa R$ 100 capital giro permanente). CF negativo = autofinanciamento (libera caixa).', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'administracao-capital-de-giro', question: 'São estratégias para reduzir a necessidade de capital de giro:', options: ['Aumentar estoques e prazos de recebimento', 'Reduzir prazos de estocagem e recebimento, aumentar prazo de pagamento a fornecedores', 'Apenas reduzir vendas', 'Aumentar todos os prazos', 'Não há estratégias'], correctAnswer: 1, explanation: 'ESTRATÉGIAS REDUZIR NECESSIDADE CAPITAL GIRO (NCG): atuar nos componentes CICLO FINANCEIRO. AÇÕES: 1) REDUZIR PME (estocagem): a) Just-in-Time (JIT): produção puxada, - estoque. b) Gestão estoques: ABC, lote econômico, previsão demanda. c) Parcerias fornecedores (entregas frequentes). Resultado: - recursos imobilizados estoque. 2) REDUZIR PMR (recebimento): a) Desconto pagamento antecipado (2/10, n/30). b) Análise crédito (evitar inadimplência). c) Cobrança eficiente. d) Cartão crédito/débito (recebimento rápido). e) Antecipação recebíveis (factoring, desconto duplicatas). Resultado: - prazo recebimento, + caixa. 3) AUMENTAR PMP (pagamento): a) Negociar prazos fornecedores. b) Aproveitar descontos só se vantajoso. c) Programação pagamentos. Resultado: fornecedores financiam + tempo. EFEITO COMBINADO: ↓PME + ↓PMR + ↑PMP → ↓Ciclo Financeiro → ↓NCG → - necessidade financiamento, + liquidez. CUIDADO: exagero prejudica. PMR muito baixo: perde vendas. PMP muito alto: perde descontos, prejudica relação. IMPORTANTE: reduzir NCG = eficiência operacional. Libera caixa para investimentos, reduz custos financeiros. Gestão contínua (não pontual).', difficulty: 'medium', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'administracao-capital-de-giro', question: 'A política de capital de giro agressiva caracteriza-se por:', options: ['Alto nível de ativos circulantes, alta liquidez, baixo risco', 'Baixo nível de ativos circulantes, baixa liquidez, alto risco, maior rentabilidade potencial', 'Apenas investir em estoques', 'Não ter passivo circulante', 'Manter todo caixa possível'], correctAnswer: 1, explanation: 'POLÍTICA CAPITAL GIRO: escolha nível AC vs risco/retorno. POLÍTICA AGRESSIVA (Tight/Restritiva): BAIXO AC relativo vendas. CARACTERÍSTICAS: 1) ESTOQUES mínimos (JIT, risco ruptura). 2) CRÉDITO restritivo (- prazo clientes, análise rígida, - vendas potenciais). 3) CAIXA mínimo (aplicado, pouca folga). 4) ALTO risco liquidez (- margem segurança). 5) MAIOR rentabilidade (- recursos ociosos, - custos financeiros AC). TRADE-OFF: - custo oportunidade × + risco operacional/financeiro. POLÍTICA CONSERVADORA (Relaxed): ALTO AC. Características: estoques fartos, crédito liberal, caixa alto. - risco, - rentabilidade (recursos ociosos). POLÍTICA MODERADA: equilíbrio risco/retorno. EXEMPLO NUMÉRICO: Empresa vendas 1.000. Agressiva: AC 300 (30% vendas). Conservadora: AC 500 (50%). Se retorno AC = 5%, custos financeiros 10%: Agressiva: custo oportunidade 30 (300×10%), mas - rupturas. Conservadora: custo 50, + segurança. ESCOLHA: depende setor, risco aceitável, acesso crédito. Startups, restrição capital: agressiva. Empresas consolidadas: moderada/conservadora. IMPORTANTE: não há política única. Balancear liquidez × rentabilidade. Monitorar índices liquidez, NCG, ciclos. Ajustar conforme contexto.', difficulty: 'hard', examBoard: 'CVM', year: 2024 },

    // ============= RISCO E RETORNO (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'risco-e-retorno', question: 'Em finanças, risco refere-se a:', options: ['Apenas prejuízos', 'Variabilidade ou incerteza dos retornos esperados', 'Somente ganhos', 'Valor do ativo', 'Não existe risco'], correctAnswer: 1, explanation: 'RISCO (Finanças): VARIABILIDADE ou INCERTEZA retornos futuros. Dispersão resultados possíveis. NÃO apenas prejuízo (também volatilidade ganhos). MEDIDAS RISCO: 1) VARIÂNCIA (σ²): média desvios quadrados vs retorno esperado. 2) DESVIO-PADRÃO (σ): raiz variância. Medida + usada. Alto σ = alto risco (retornos dispersos). 3) COEFICIENTE VARIAÇÃO: σ/retorno médio (risco relativo). 4) BETA (β): risco sistemático (correlação com mercado). TIPOS RISCO: 1) SISTEMÁTICO (não-diversificável, mercado): afeta todos ativos (recessão, inflação, guerra). Medido β. NÃO elimina diversificação. Compensado prêmio risco. 2) NÃO-SISTEMÁTICO (diversificável, específico): afeta ativo/empresa particular (greve, produto defeituoso). ELIMINADO diversificação portfólio. RELAÇÃO RISCO-RETORNO: investidores avessos risco EXIGEM maior retorno para assumir + risco. Compensação. EXEMPLO: Tesouro Selic (baixo risco): 6% a.a. Ações (alto risco): 14% a.a. Diferença 8% = prêmio risco. IMPORTANTE: risco ≠ perda certa. É INCERTEZA. Mesmo investimento "seguro" tem risco (inflação, crédito). Gestão: identificar, medir, mitigar/aceitar conforme perfil. Diversificação reduz risco não-sistemático.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'risco-e-retorno', question: 'Dois ativos com retornos esperados iguais de 12% a.a. Ativo A tem desvio-padrão 5%, Ativo B tem 15%. Para investidor avesso ao risco:', options: ['Ambos são iguais', 'Ativo A é preferível (menor risco para mesmo retorno)', 'Ativo B é preferível', 'Risco não importa', 'Não é possível decidir'], correctAnswer: 1, explanation: 'ESCOLHA SOB RISCO: investidor avesso risco prefere MENOR risco dado MESMO retorno. DADOS: Ativo A: E(R)=12%, σ=5%. Ativo B: E(R)=12%, σ=15%. ANÁLISE: MESMO retorno esperado (12%), MAS B tem TRIPLO volatilidade (15% vs 5%). A menos arriscado. DECISÃO: investidor AVESSO RISCO escolhe A (domina B - mesmo retorno, - risco). PERFIS INVESTIDOR: 1) AVESSO risco: prefere - risco dado retorno. Maioria. 2) NEUTRO risco: indiferente risco (só retorno importa). Raro. 3) PROPENSO risco: prefere + risco (jogadores). Raríssimo. DOMINÂNCIA: Ativo DOMINA outro se: (maior retorno, mesmo risco) OU (mesmo retorno, menor risco). FRONTEIRA EFICIENTE: conjunto ativos/portfólios que maximizam retorno dado risco (ou minimizam risco dado retorno). A está na fronteira, B não (ineficiente). PRÁTICA: investidor exige COMPENSAÇÃO (+ retorno) para aceitar + risco. Se B oferecesse 18% (vs 12% A), decisão difícil (6% a mais compensa 10% a mais σ?). Depende aversão risco. IMPORTANTE: retorno esperado IGUAL, escolha óbvia (- risco). Retornos diferentes: trade-off (análise Sharpe: (retorno-Rf)/σ).', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'risco-e-retorno', question: 'A diversificação de portfólio reduz principalmente:', options: ['Risco sistemático', 'Risco não-sistemático (específico da empresa)', 'Todo o risco', 'Retorno esperado', 'Não reduz risco'], correctAnswer: 1, explanation: 'DIVERSIFICAÇÃO: estratégia combinar MÚLTIPLOS ativos reduzir risco. "Não colocar ovos uma cesta". EFEITO: reduz principalmente RISCO NÃO-SISTEMÁTICO (específico, diversificável). MECÂNICA: ativos não perfeitamente correlacionados (ρ<1): quando um cai, outro pode subir/estável. Oscilações compensam-se. Portfólio: volatilidade MENOR que média ponderada volatilidades individuais. EXEMPLO: Ativo A (varejo): σ=20%. Ativo B (tecnologia): σ=25%. Correlação ρ=0,3 (baixa). Portfólio 50%A+50%B: σ portfólio ≈ 15% (< 22,5% que seria média). LIMITE DIVERSIFICAÇÃO: risco NÃO-sistemático → 0 (muitos ativos não-correlacionados). Risco SISTEMÁTICO permanece (afeta todos - mercado, economia). Não elimina diversificação. REGRA: ~20-30 ações bem diversificadas eliminam maior parte risco diversificável. Além disso: ganho marginal pequeno. RISCO PORTFÓLIO: σ²p = w²Aσ²A + w²Bσ²B + 2wAwBρσAσB. Quanto menor ρ (correlação) → menor σp. IMPORTANTE: diversificação é "almoço grátis" (reduz risco SEM sacrificar retorno esperado). Portfólio eficiente > ativo individual. Investidor deve diversificar. Risco sistemático: compensado via prêmio risco (CAPM).', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'risco-e-retorno', question: 'O Índice de Sharpe mede:', options: ['Apenas retorno absoluto', 'Retorno excedente (acima taxa livre risco) por unidade de risco total. Sharpe = (Rp - Rf) / σp', 'Somente risco', 'Valor do ativo', 'Não tem aplicação'], correctAnswer: 1, explanation: 'ÍNDICE SHARPE: medida desempenho ajustado risco. RETORNO EXCEDENTE por unidade RISCO TOTAL. FÓRMULA: Sharpe = (Rp - Rf) / σp. Onde: Rp = retorno portfólio/ativo, Rf = taxa livre risco, σp = desvio-padrão portfólio. INTERPRETAÇÃO: quanto investidor ganhou (acima livre risco) para cada unidade risco assumido. Sharpe MAIOR = melhor desempenho risco-ajustado. EXEMPLO: Fundo A: retorno 15%, σ=20%, Rf=5%. Sharpe = (15-5)/20 = 0,50. Cada 1% risco, ganhou 0,50% excesso retorno. Fundo B: retorno 12%, σ=10%, Rf=5%. Sharpe = (12-5)/10 = 0,70 (MELHOR, embora retorno absoluto menor). APLICAÇÃO: COMPARAR fundos/portfólios. Maior Sharpe = melhor (+ retorno por risco, ou mesmo retorno com - risco). LIMITAÇÕES: 1) Assume retornos normais (pode não ser). 2) Usa σ total (não distingue sistemático/não-sistemático). 3) Passado não garante futuro. OUTROS ÍNDICES: Treynor (usa β, não σ), Sortino (só desvio negativo), Alfa Jensen. IMPORTANTE: Sharpe muito usado benchmarking fundos. Sharpe > 1: excelente. 0,5-1: bom. <0,5: fraco. Negativo: perdeu para livre risco (ruim). Investidor racional escolhe maior Sharpe (eficiência).', difficulty: 'hard', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'risco-e-retorno', question: 'A relação fundamental entre risco e retorno em finanças estabelece que:', options: ['Não há relação', 'Maior risco exige maior retorno esperado (prêmio por risco)', 'Maior risco sempre resulta em maior retorno realizado', 'Investidores preferem sempre menor retorno', 'Risco não afeta decisões'], correctAnswer: 1, explanation: 'RELAÇÃO RISCO-RETORNO: princípio FUNDAMENTAL finanças. Maior RISCO → maior RETORNO ESPERADO (exigido). RACIONALIDADE: investidores AVESSOS risco (maioria). Aceitam + risco SÓ SE compensados com + retorno. PRÊMIO RISCO: retorno adicional acima taxa livre risco para compensar risco. Prêmio = E(R) - Rf. CAPM formaliza: E(R) = Rf + β[E(Rm)-Rf]. HIERARQUIA RISCO-RETORNO (típico Brasil): 1) Tesouro Selic (baixíssimo risco): 6% a.a. 2) CDB banco grande (baixo risco): 8%. 3) Debêntures empresa boa (médio): 10%. 4) Ações blue chips (alto): 14%. 5) Ações small caps (altíssimo): 20%. IMPORTANTE: relação com RETORNO ESPERADO (exigido), NÃO realizado. Ex-post, alto risco pode resultar prejuízo (incerteza materializou-se negativamente). Ex-ante, exige-se compensação. IMPLICAÇÕES: 1) Ativos seguros: retorno baixo (aceitável, sem risco). 2) Ativos arriscados: precisam prometer alto retorno (atrair investidor). 3) Precificação ativos: mercado ajusta preços até retorno esperado compatível risco. EXCEÇÃO: ativos mal precificados (bolhas, pânico). Correção eventual. REGRA OURO: "não existe almoço grátis" (high return without risk). Se alguém promete alto retorno sem risco → fraude/erro.', difficulty: 'medium', examBoard: 'CVM', year: 2024 },

    // ============= ALAVANCAGEM FINANCEIRA (5) =============
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'alavancagem-financeira', question: 'Alavancagem Financeira refere-se a:', options: ['Apenas vendas da empresa', 'Uso de capital de terceiros (dívida) para amplificar retorno sobre capital próprio', 'Somente custos fixos', 'Não existe alavancagem', 'Apenas lucro operacional'], correctAnswer: 1, explanation: 'ALAVANCAGEM FINANCEIRA: uso DÍVIDA (capital terceiros) amplificar RETORNO capital próprio (ROE). "Alavanca" resultados acionistas. MECÂNICA: empresa capta dívida custo fixo (juros), investe retorno > custo → diferença vai acionistas. EFEITO POSITIVO: ROA (retorno ativo) > custo dívida → alavancagem AUMENTA ROE. Lucro adicional (acima juros) pertence acionistas (base PL menor). EFEITO NEGATIVO: ROA < custo dívida → alavancagem REDUZ ROE. Prejuízo ampliado. EXEMPLO: Empresa A (sem dívida): ativo 100, PL 100, lucro op. 10, ROA=10%, ROE=10%. Empresa B (alavancada): ativo 100, dívida 50 (juros 8%), PL 50. Lucro op. 10, (-) juros 4, lucro líquido 6. ROA=10%, ROE=12% (6/50). Alavancagem positiva (ROA 10% > custo 8%). Se lucro op. cai para 2: A: ROE=2%. B: lucro líquido -2 (2-4 juros), ROE=-4%. Risco! GRAU ALAVANCAGEM FINANCEIRA (GAF): GAF = LAJIR / (LAJIR - Juros). Mede amplificação. IMPORTANTE: alavancagem = espada dois gumes. Bons tempos: + lucro acionistas. Maus: + prejuízo. Aumenta RISCO financeiro (volatilidade ROE). Estrutura capital determina alavancagem.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'alavancagem-financeira', question: 'O Grau de Alavancagem Financeira (GAF) é calculado por:', options: ['Vendas / Custos Variáveis', 'LAJIR / (LAJIR - Juros) ou % Variação LPA / % Variação LAJIR', 'Apenas Patrimônio Líquido', 'Ativo Total', 'Não existe fórmula'], correctAnswer: 1, explanation: 'GRAU ALAVANCAGEM FINANCEIRA (GAF ou DFL - Degree Financial Leverage): mede SENSIBILIDADE lucro acionistas (LPA) a variações lucro operacional (LAJIR). FÓRMULAS: 1) GAF = LAJIR / (LAJIR - Juros - Dividendos Pref/[(1-T)]). Simplificado (sem dividendos pref): GAF = LAJIR / (LAJIR - Juros). 2) GAF = % Variação LPA / % Variação LAJIR. INTERPRETAÇÃO: GAF=2 → aumento 10% LAJIR gera aumento 20% LPA (amplificação 2×). GAF=1: sem alavancagem (sem dívida). GAF>1: alavancado (quanto > 1, + alavancagem). EXEMPLO: LAJIR 100, Juros 30. GAF = 100/(100-30) = 100/70 = 1,43. Se LAJIR ↑10% (para 110): Juros continuam 30 (fixos), lucro líquido antes 70, depois 80 (↑14,3%). Confirmação: GAF=1,43 × 10% = 14,3% ✓. RISCO: GAF alto = alta volatilidade LPA. Pequenas oscilações LAJIR causam grandes oscilações lucro acionistas. IMPORTANTE: GAF complementa GAO (alavancagem operacional). Alavancagem TOTAL (GAT) = GAO × GAF. Empresas alto GAO evitam alto GAF (risco excessivo). GAF controlado via estrutura capital (- dívida → - GAF).', difficulty: 'medium', examBoard: 'BB', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'alavancagem-financeira', question: 'O ponto de indiferença entre financiamento por dívida ou capital próprio ocorre quando:', options: ['Dívida sempre é melhor', 'Retorno sobre Ativos (ROA) iguala o custo da dívida', 'Capital próprio sempre é melhor', 'Não existe ponto de indiferença', 'ROE é sempre negativo'], correctAnswer: 1, explanation: 'PONTO INDIFERENÇA: nível LAJIR onde ROE é IGUAL sob estruturas capital diferentes (dívida vs equity). CONDIÇÃO: ROA = custo dívida (taxa juros). ACIMA ponto: dívida SUPERIOR (alavancagem positiva, ROE maior). ABAIXO ponto: equity SUPERIOR (alavancagem negativa, dívida prejudica). CÁLCULO: igualar LPA (lucro por ação) sob ambas estruturas. EXEMPLO: Estrutura A (sem dívida): PL 1.000, nº ações 100, LPA = (LAJIR × 0,66) / 100. Estrutura B (dívida 500, juros 10%): PL 500, nº ações 50, juros 50. LPA = [(LAJIR-50)×0,66] / 50. Igualar: (LAJIR×0,66)/100 = [(LAJIR-50)×0,66]/50. Resolver: LAJIR×0,66×50 = (LAJIR-50)×0,66×100. 33 LAJIR = 66 LAJIR - 3.300. 33 LAJIR = 3.300. LAJIR = 100 (ponto indiferença). LAJIR > 100: estrutura B melhor. LAJIR < 100: estrutura A melhor. IMPLICAÇÕES: empresas LAJIR estável alto: podem alavancar (acima ponto). Volátil/incerto: evitar dívida (risco cair abaixo ponto). IMPORTANTE: análise simplifica (ignora risco falência, flexibilidade, custos transação). Decisão real: múltiplos fatores. Mas ponto indiferença útil análise inicial.', difficulty: 'hard', examBoard: 'Petrobras', year: 2024 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'alavancagem-financeira', question: 'O efeito da alavancagem financeira sobre o ROE depende:', options: ['Apenas do tamanho da empresa', 'Da relação entre ROA (retorno sobre ativo) e custo da dívida', 'Somente do valor das vendas', 'Do número de funcionários', 'Não há efeito mensurável'], correctAnswer: 1, explanation: 'EFEITO ALAVANCAGEM FINANCEIRA sobre ROE: depende SPREAD (ROA - custo dívida). SITUAÇÃO 1 - ALAVANCAGEM POSITIVA: ROA > custo dívida. Empresa ganha + nos ativos que paga juros → diferença acionistas → ↑ROE. Quanto maior spread, maior efeito positivo. Exemplo: ROA 15%, custo dívida 8%, spread +7% → alavancagem aumenta ROE. SITUAÇÃO 2 - ALAVANCAGEM NEUTRA: ROA = custo dívida. Empresa ganha exato que paga → sem efeito ROE (igual sem dívida). SITUAÇÃO 3 - ALAVANCAGEM NEGATIVA: ROA < custo dívida. Empresa ganha menos que paga juros → acionistas absorvem diferença → ↓ROE (pior que sem dívida). Destrói valor. Exemplo: ROA 5%, custo 10%, spread -5% → prejuízo acionistas. FÓRMULA DEMONSTRAÇÃO: ROE = ROA + (ROA - Custo dívida) × (Dívida/PL). Termo (ROA - Custo) = spread. Se positivo: ↑ROE. Negativo: ↓ROE. VARIÁVEIS: 1) SPREAD: crucial. 2) Nível ENDIVIDAMENTO (D/PL): amplifica spread (+ dívida = + amplificação positiva OU negativa). IMPORTANTE: alavancagem funciona BEM quando ROA consistentemente > custo dívida. Arriscado quando ROA volátil (pode cair < custo). Empresas estáveis (utilities): podem alavancar. Cíclicas: cuidado (recessão → ROA cai).', difficulty: 'hard', examBoard: 'BNDES', year: 2023 },
    
    { area: 'fiscal', subject: 'administracao-financeira', topic: 'alavancagem-financeira', question: 'Uma empresa totalmente financiada por capital próprio decide emitir dívida e recomprar ações. O principal risco é:', options: ['Não há riscos', 'Aumento do risco financeiro e da volatilidade do ROE', 'Redução do lucro operacional', 'Aumento da receita', 'Eliminação de todos os custos'], correctAnswer: 1, explanation: 'SUBSTITUIÇÃO EQUITY por DÍVIDA (leveraged recapitalization): empresa emite dívida, usa recursos recomprar ações (↑alavancagem). BENEFÍCIOS: 1) Escudo fiscal (juros dedutíveis). 2) Sinalização confiança gestores. 3) ↑ROE (se ROA > custo dívida). 4) Disciplina (obrigação pagar juros). PRINCIPAL RISCO: ↑RISCO FINANCEIRO. MANIFESTAÇÕES: 1) ↑VOLATILIDADE ROE: GAF aumenta (resultado acionistas mais sensível oscilações operacionais). Bons anos: lucro explosivo. Maus: prejuízo grave. 2) RISCO INADIMPLÊNCIA: obrigação fixa juros/principal. Fluxo caixa insuficiente → default, falência. 3) ↓FLEXIBILIDADE: covenants dívida restringem ações (dividendos, novos investimentos). 4) Custo FALÊNCIA: probabilidade aumenta com alavancagem. Custos diretos (legais) + indiretos (perda valor empresa). 5) ↑CUSTO capital próprio: acionistas exigem + retorno (compensar + risco financeiro). EXEMPLO: empresa estável ROA 12%, emite dívida 8%, recompra ações. ROE sobe. MAS recessão → ROA cai 6% → alavancagem negativa, ROE desaba, risco inadimplência. IMPORTANTE: decisão depende: estabilidade fluxo caixa, nível endividamento atual, acesso mercados capital (refinanciar), apetite risco acionistas. Trade-off retorno × risco. Excessivo endividamento = distress financeiro (custoso).', difficulty: 'medium', examBoard: 'CVM', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Administração Financeira questions...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Administração Financeira questions seeded successfully!');
}
