import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    console.log('🔍 [SFN] Sending question to:', `${API_BASE}/questions`);

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ [SFN] Error response:', response.status, errorText);
      throw new Error(`Failed to save question: ${response.status} - ${errorText}`);
    }

    const result = await response.json();
    console.log('✅ [SFN] Question saved successfully');
    return result;
  } catch (error) {
    console.error('❌ [SFN] Error saving question:', error);
    console.error('❌ [SFN] Error details:', error.message, error.stack);
    throw error;
  }
}

// ============= ALL SFN QUESTIONS =============
export async function seedAllSFNQuestions() {
  console.log('🏛️ Starting to seed ALL Sistema Financeiro Nacional questions...');
  
  const allQuestions: Question[] = [
    // ========== 1. CONSELHO MONETÁRIO NACIONAL (CMN) - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'conselho-monetario-nacional', question: 'O Conselho Monetário Nacional (CMN) é o órgão máximo do Sistema Financeiro Nacional, responsável por formular a política da moeda e do crédito. Sobre as competências do CMN, assinale a alternativa correta.', options: ['Executar a política monetária e cambial definida pelo Banco Central', 'Autorizar as emissões de papel-moeda e regular a constituição de instituições financeiras', 'Fiscalizar diretamente as instituições financeiras', 'Determinar as taxas de juros praticadas pelos bancos comerciais', 'Administrar as reservas internacionais do país'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. O CMN é o órgão normativo máximo do SFN e tem como competências: regular a constituição, funcionamento e fiscalização das instituições financeiras; autorizar emissões de papel-moeda; e estabelecer diretrizes gerais para a política monetária e cambial. A execução dessas políticas cabe ao BACEN (alternativa A). A fiscalização direta é função do BACEN (alternativa C). O CMN não determina taxas específicas, apenas diretrizes (D). A administração das reservas é do BACEN (E).', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'conselho-monetario-nacional', question: 'A composição do Conselho Monetário Nacional foi alterada pela Lei 9.069/95. Atualmente, o CMN é composto por quantos membros e quais são eles?', options: ['Cinco membros: Ministro da Fazenda, Presidente do Banco Central, Presidente da CVM, Presidente do Banco do Brasil e Presidente da CEF', 'Três membros: Ministro da Fazenda (presidente), Ministro do Planejamento e Presidente do Banco Central', 'Sete membros, incluindo representantes do setor bancário privado', 'Quatro membros: Ministro da Fazenda, Presidente do Banco Central, Presidente do BNDES e Presidente da CVM', 'Nove membros, incluindo representantes de entidades de classe'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Desde 1995, com a Lei 9.069/95, o CMN passou a ter composição mais enxuta, sendo integrado por apenas 3 membros: Ministro da Fazenda (que o preside), Ministro do Planejamento, Orçamento e Gestão, e Presidente do Banco Central do Brasil. Esta mudança visou maior agilidade e eficiência nas decisões.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'conselho-monetario-nacional', question: 'Dentre as atribuições do Conselho Monetário Nacional, NÃO se inclui:', options: ['Fixar as diretrizes e normas da política cambial', 'Disciplinar o crédito em todas as suas modalidades', 'Executar os serviços do meio circulante', 'Regular a constituição, funcionamento e fiscalização de instituições financeiras', 'Determinar recolhimentos compulsórios'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Executar os serviços do meio circulante (emissão de moeda) é atribuição do BANCO CENTRAL, não do CMN. O CMN é órgão NORMATIVO, ou seja, estabelece normas e diretrizes, mas não executa. As alternativas A, B, D e E são competências do CMN previstas na Lei 4.595/64.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'conselho-monetario-nacional', question: 'O CMN estabelece normas para o Sistema Financeiro Nacional. Sobre as deliberações do CMN, é correto afirmar que:', options: ['São executadas diretamente pelo próprio CMN através de suas superintendências regionais', 'Dependem de aprovação do Congresso Nacional para entrarem em vigor', 'São implementadas principalmente pelo Banco Central do Brasil e pela CVM, conforme a área de atuação', 'Têm validade imediata apenas para instituições financeiras públicas', 'Necessitam de referendo do Presidente da República em todos os casos'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. As deliberações do CMN são IMPLEMENTADAS pelos órgãos executivos do SFN: principalmente o Banco Central (para bancos, política monetária, cambial) e a CVM (para mercado de valores mobiliários). O CMN não tem estrutura executiva própria. Esta é a essência da estrutura normativa-executiva do SFN.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'conselho-monetario-nacional', question: 'Em relação às funções do Conselho Monetário Nacional no contexto do Sistema Financeiro Nacional, analise as afirmativas: I. Zelar pela liquidez e solvência das instituições financeiras. II. Fixar diretrizes de aplicações dos recursos das instituições financeiras. III. Autorizar emissões de papel-moeda. Está correto o que se afirma em:', options: ['Apenas I', 'Apenas II e III', 'Apenas I e III', 'Apenas III', 'I, II e III'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (todas). O CMN tem todas essas atribuições previstas na Lei 4.595/64: I - zelar pela liquidez e solvência das instituições financeiras; II - fixar diretrizes de aplicações dos recursos; III - autorizar emissões de papel-moeda. Todas são competências fundamentais do CMN como órgão normativo máximo do SFN.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },

    // ========== 2. BANCO CENTRAL DO BRASIL (BACEN) - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'banco-central-do-brasil', question: 'O Banco Central do Brasil é o principal executor das orientações do Conselho Monetário Nacional e responsável por garantir o poder de compra da moeda nacional. Sobre as atribuições do BACEN, assinale a alternativa INCORRETA.', options: ['Emitir papel-moeda e moeda metálica', 'Executar os serviços do meio circulante', 'Receber os recolhimentos compulsórios dos bancos', 'Conceder empréstimos diretos a empresas privadas não financeiras', 'Realizar operações de compra e venda de títulos públicos federais'], correctAnswer: 3, explanation: 'CORRETO: Alternativa D (INCORRETA). O BACEN NÃO pode conceder empréstimos diretos a empresas privadas não financeiras. Esta proibição foi estabelecida pela Constituição Federal de 1988 (art. 164, §1º) para evitar favorecimentos e preservar a independência do BC. O BACEN pode: emitir moeda, executar serviços do meio circulante, receber compulsórios e operar com títulos públicos.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'banco-central-do-brasil', question: 'No Brasil, o Banco Central é responsável pela autorização, regulamentação e supervisão das instituições financeiras. Qual instrumento NÃO é utilizado pelo BACEN no controle da política monetária?', options: ['Operações de mercado aberto (open market)', 'Depósitos compulsórios', 'Redesconto bancário', 'Emissão de debêntures', 'Taxa SELIC'], correctAnswer: 3, explanation: 'CORRETO: Alternativa D. Emissão de debêntures é instrumento de CAPTAÇÃO DE RECURSOS por empresas privadas (S.A.), regulado pela CVM, NÃO é instrumento de política monetária do BACEN. Os instrumentos clássicos do BACEN são: Open Market, Depósitos Compulsórios, Redesconto e Taxa SELIC.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'banco-central-do-brasil', question: 'O Banco Central do Brasil atua como "banco dos bancos" e "banqueiro do governo". Nessa função, o BACEN:', options: ['Recebe depósitos à vista do público em geral', 'Concede empréstimos ao Tesouro Nacional para cobrir déficits orçamentários', 'Mantém reservas bancárias e concede assistência financeira de liquidez aos bancos', 'Administra diretamente os fundos de pensão dos servidores públicos', 'Opera exclusivamente no mercado de câmbio comercial'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Como "banco dos bancos", o BACEN mantém as RESERVAS BANCÁRIAS dos bancos comerciais (depósitos compulsórios e voluntários) e concede ASSISTÊNCIA FINANCEIRA DE LIQUIDEZ através do redesconto. Não recebe depósitos do público (A), não empresta ao Tesouro (B - proibido pela CF/88), não administra fundos de pensão (D) e atua em todos os segmentos (E).', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'banco-central-do-brasil', question: 'A autonomia do Banco Central do Brasil foi estabelecida pela Lei Complementar 179/2021. Sobre essa autonomia, é correto afirmar que:', options: ['O presidente do BACEN passa a ter mandato fixo de 4 anos, coincidente com o do Presidente da República', 'O BACEN pode emprestar recursos ao Tesouro Nacional em situações emergenciais', 'Os diretores do BACEN têm mandatos fixos não coincidentes com o mandato presidencial, vedada a exoneração ad nutum', 'O BACEN pode definir autonomamente a meta de inflação sem consultar o CMN', 'O presidente do BACEN deixa de integrar o Conselho Monetário Nacional'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. A LC 179/2021 estabeleceu autonomia operacional do BACEN com MANDATOS FIXOS para presidente e diretores (4 anos, não coincidentes com mandato presidencial), vedando exoneração ad nutum (só por justa causa). A autonomia visa despolitizar a política monetária.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'banco-central-do-brasil', question: 'O BACEN fiscaliza e supervisiona as instituições financeiras. Sobre as sanções que pode aplicar, analise: I. Advertência. II. Multa pecuniária. III. Suspensão do exercício de cargos. IV. Cassação da autorização para funcionamento. Pode o BACEN aplicar:', options: ['Apenas I e II', 'Apenas I, II e III', 'Apenas II, III e IV', 'Apenas I, II e IV', 'I, II, III e IV'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (todas). O BACEN tem amplo poder sancionador previsto na Lei 4.595/64: advertência, multa pecuniária, suspensão do exercício de cargos e cassação de autorização para funcionamento (liquidação extrajudicial). Estas sanções são graduadas conforme a gravidade da infração.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },

    // ========== 3. COMISSÃO DE VALORES MOBILIÁRIOS (CVM) - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'comissao-de-valores-mobiliarios', question: 'A Comissão de Valores Mobiliários (CVM) foi criada pela Lei 6.385/76 para regular e fiscalizar o mercado de valores mobiliários. NÃO é atribuição da CVM:', options: ['Fiscalizar e disciplinar o funcionamento das bolsas de valores', 'Autorizar a emissão e distribuição de valores mobiliários no mercado', 'Fixar a taxa básica de juros da economia (SELIC)', 'Proteger os investidores contra emissões irregulares de valores mobiliários', 'Regulamentar e fiscalizar os fundos de investimento'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Fixar a taxa SELIC é competência do COPOM do BANCO CENTRAL, não da CVM. A CVM atua especificamente no MERCADO DE VALORES MOBILIÁRIOS: fiscaliza bolsas, autoriza emissões de ações/debêntures, protege investidores e regula fundos. A divisão é clara: BACEN cuida de bancos e política monetária; CVM cuida do mercado de capitais.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'comissao-de-valores-mobiliarios', question: 'São considerados valores mobiliários sob fiscalização da CVM, EXCETO:', options: ['Ações de companhias abertas', 'Debêntures e commercial papers', 'Certificados de Depósito Bancário (CDB)', 'Cotas de fundos de investimento', 'Contratos derivativos negociados em bolsa'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. CDB é título de RENDA FIXA emitido por BANCOS, portanto fiscalizado pelo BACEN, não pela CVM. Os demais são valores mobiliários sob jurisdição da CVM conforme Lei 6.385/76: ações, debêntures, commercial papers, cotas de fundos e derivativos. A diferença-chave: títulos bancários = BACEN; títulos do mercado de capitais = CVM.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'comissao-de-valores-mobiliarios', question: 'A CVM tem como objetivo assegurar o funcionamento eficiente e regular do mercado de valores mobiliários. Para isso, a autarquia pode:', options: ['Apenas emitir normas e regulamentos, sem poder de fiscalização direta', 'Fiscalizar, mas não aplicar penalidades às companhias abertas', 'Disciplinar, fiscalizar e punir práticas irregulares no mercado de capitais', 'Atuar apenas mediante provocação de investidores prejudicados', 'Regular exclusivamente as bolsas de valores, sem jurisdição sobre fundos'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. A CVM tem poderes AMPLOS: DISCIPLINAR (criar normas), FISCALIZAR (investigar e supervisionar) e PUNIR (aplicar sanções como multas, suspensões, cassação de registros). A CVM fiscaliza diretamente, pode punir, age de ofício e regula TODO o mercado de valores mobiliários.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'comissao-de-valores-mobiliarios', question: 'Sobre a estrutura e funcionamento da CVM, assinale a alternativa correta:', options: ['É um órgão do Ministério da Fazenda, sem autonomia administrativa', 'É uma autarquia federal vinculada ao Ministério da Economia, com autonomia administrativa e financeira', 'É uma empresa pública federal que visa lucro com a fiscalização do mercado', 'É gerida por um único presidente nomeado pelo Ministro da Fazenda', 'Seus diretores têm mandatos coincidentes para garantir uniformidade de gestão'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. A CVM é uma AUTARQUIA FEDERAL vinculada ao Ministério da Economia, dotada de AUTONOMIA administrativa e financeira (Lei 6.385/76). É gerida por colegiado (presidente + 4 diretores) com mandatos ESCALONADOS (não coincidentes) para garantir continuidade.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'comissao-de-valores-mobiliarios', question: 'A Lei 6.385/76 estabelece as competências da CVM. Analise: I. Assegurar o acesso do público a informações sobre valores mobiliários. II. Assegurar a observância de práticas comerciais equitativas. III. Estimular a formação de poupança e sua aplicação em valores mobiliários. Está correto:', options: ['Apenas I', 'Apenas I e II', 'Apenas II e III', 'Apenas I e III', 'I, II e III'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (todas). O art. 4º da Lei 6.385/76 estabelece TRÊS objetivos: assegurar acesso a informações (transparência), assegurar práticas equitativas (prevenir fraudes) e estimular a poupança em valores mobiliários (desenvolver o mercado). Estes três pilares formam a base da atuação da CVM.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 4. BANCOS COMERCIAIS - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-comerciais', question: 'Os bancos comerciais são instituições financeiras constituídas sob a forma de sociedade anônima. Sobre suas características e operações, é correto afirmar que:', options: ['Captam recursos apenas através de depósitos à vista', 'São especializados em operações de longo prazo, como financiamentos imobiliários', 'Captam depósitos à vista e a prazo, sendo a principal função a criação de moeda escritural', 'Não podem realizar operações de câmbio', 'São proibidos de conceder crédito a pessoas físicas'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Os bancos comerciais captam via DEPÓSITOS À VISTA (conta corrente) e A PRAZO (CDB, RDB), e sua principal característica é a CRIAÇÃO DE MOEDA ESCRITURAL através do multiplicador bancário. Captam também a prazo (A errada), não são especializados em longo prazo (B errada), podem operar câmbio se autorizados (D errada) e concedem crédito a PF e PJ (E errada).', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-comerciais', question: 'A conta de depósitos à vista (conta corrente) é o principal produto dos bancos comerciais. Sobre essa operação, assinale a afirmativa INCORRETA:', options: ['Os depósitos à vista são considerados moeda escritural e integram o M1', 'Não há prazo de resgate, podendo o cliente sacar a qualquer momento', 'Os bancos podem livremente emprestar 100% dos depósitos à vista recebidos', 'Estão sujeitos a recolhimento compulsório ao Banco Central', 'São utilizados para movimentação financeira do dia a dia'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C (INCORRETA). Os bancos NÃO podem emprestar 100% dos depósitos à vista porque precisam manter RESERVA COMPULSÓRIA no BACEN (cerca de 25%) e reserva livre para saques. Se emprestassem tudo, não teriam como honrar saques. O compulsório controla o multiplicador bancário.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-comerciais', question: 'Os bancos comerciais são obrigados por lei a constituir-se sob qual forma societária?', options: ['Sociedade Limitada (LTDA)', 'Sociedade Anônima (S.A.)', 'Empresa Individual de Responsabilidade Limitada (EIRELI)', 'Sociedade em Comandita Simples', 'Qualquer forma societária, desde que autorizada pelo BACEN'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. A Lei 4.595/64 estabelece que bancos comerciais DEVEM ser SOCIEDADE ANÔNIMA (S.A.). Esta exigência visa maior transparência, facilitar fiscalização, permitir captação via mercado de capitais e proteger depositantes. A forma S.A. é OBRIGATÓRIA para todas as instituições financeiras.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-comerciais', question: 'Sobre o multiplicador bancário, analise: Um banco recebe depósito à vista de R$ 100.000. Considerando taxa de compulsório de 20%, o sistema bancário pode criar moeda no valor máximo de:', options: ['R$ 80.000', 'R$ 100.000', 'R$ 400.000', 'R$ 500.000', 'R$ 600.000'], correctAnswer: 3, explanation: 'CORRETO: Alternativa D. O multiplicador bancário = 1/c. Com c = 20% (0,2), temos M = 1/0,2 = 5. Portanto, R$ 100.000 x 5 = R$ 500.000 em moeda escritural. Banco A empresta 80.000; quem recebe deposita em Banco B; Banco B empresta 64.000; e assim sucessivamente. A soma geométrica resulta em 500.000.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-comerciais', question: 'Os bancos comerciais podem realizar diversas operações. NÃO é operação típica de banco comercial:', options: ['Desconto de duplicatas e notas promissórias', 'Concessão de crédito rotativo (cheque especial)', 'Captação via Caderneta de Poupança', 'Underwriting (subscrição de ações)', 'Cobrança de títulos'], correctAnswer: 3, explanation: 'CORRETO: Alternativa D. UNDERWRITING é operação de BANCO DE INVESTIMENTO, não de banco comercial. Bancos comerciais fazem: desconto de títulos, cheque especial, poupança (quando múltiplos) e cobrança. A Resolução CMN 2.624/99 proíbe bancos comerciais de fazer underwriting.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ========== 5. BANCOS DE INVESTIMENTO - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-de-investimento', question: 'Os bancos de investimento são especializados em operações de médio e longo prazo. Sobre essas instituições, é INCORRETO afirmar que:', options: ['Não podem captar depósitos à vista', 'Realizam operações de underwriting', 'Captam recursos através de depósitos a prazo (CDB e RDB)', 'Podem administrar fundos de investimento', 'São os principais responsáveis pela criação de moeda escritural na economia'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (INCORRETA). A criação de moeda escritural é função dos BANCOS COMERCIAIS. Bancos de investimento não captam depósitos à vista (A correta), realizam underwriting (B correta), captam via CDB/RDB (C correta) e administram fundos (D correta). Como não trabalham com conta corrente, não participam do multiplicador bancário.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-de-investimento', question: 'No underwriting firme (straight), o banco de investimento:', options: ['Apenas distribui as ações, sem assumir riscos', 'Subscreve integralmente a emissão, assumindo o risco de não colocação no mercado', 'Se compromete a vender o máximo possível, devolvendo o que não for vendido', 'Só recebe comissão sobre as ações efetivamente vendidas', 'Atua apenas como consultor, sem participar da venda'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. No UNDERWRITING FIRME, o banco COMPRA todas as ações/debêntures da empresa e depois as revende ao mercado, assumindo TODO O RISCO. É a modalidade de maior risco para o banco e maior segurança para a empresa. Best Efforts é alternativa C/D. Stand-by é garantia firme do restante.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-de-investimento', question: 'Sobre as fontes de recursos dos bancos de investimento, assinale a alternativa correta:', options: ['Depósitos à vista e caderneta de poupança', 'Apenas recursos próprios (patrimônio líquido)', 'Depósitos a prazo, repasses de instituições oficiais e recursos externos', 'Exclusivamente emissão de ações no mercado', 'Apenas repasses do BNDES'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Bancos de investimento captam: DEPÓSITOS A PRAZO (CDB, RDB), REPASSES de BNDES e outras instituições oficiais, RECURSOS EXTERNOS e recursos próprios. NÃO captam depósitos à vista nem poupança (A errada). Não são únicas fontes (B, D, E erradas). A diversificação permite financiar operações de médio/longo prazo.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-de-investimento', question: 'Os bancos de investimento devem ser constituídos sob a forma de:', options: ['Sociedade Limitada (LTDA)', 'Sociedade Anônima (S.A.)', 'Qualquer forma societária', 'Empresa pública', 'Cooperativa'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Bancos de investimento devem ser SOCIEDADE ANÔNIMA (S.A.), conforme Resolução CMN 4.122/2013. Esta exigência garante transparência, facilita fiscalização pelo BACEN e CVM, permite acesso ao mercado de capitais e assegura proteção aos investidores através de governança corporativa.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'bancos-de-investimento', question: 'Sobre operações de bancos de investimento, analise: I. Financiamento de capital fixo e de giro. II. Administração de recursos de terceiros. III. Operações de câmbio. Pode o banco de investimento realizar:', options: ['Apenas I', 'Apenas I e II', 'Apenas I e III', 'Apenas II e III', 'I, II e III'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E (todas). Bancos de investimento podem: I - financiar capital fixo e de giro de médio/longo prazo (função principal); II - administrar recursos de terceiros via fundos; III - realizar operações de câmbio se autorizados. Todas permitidas pela Resolução CMN 4.122/2013.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} SFN questions (Part 1/2)...`);
  
  let count = 0;
  for (const q of allQuestions) {
    await saveQuestion(q);
    count++;
    if (count % 5 === 0) {
      console.log(`✅ Saved ${count}/${allQuestions.length} questions...`);
    }
  }
  
  console.log('✅ Part 1/2 (25 questions) imported! Continuing...');
  
  // ========== PART 2 - Remaining questions ==========
  const moreQuestions: Question[] = [
    // ========== 6. COOPERATIVAS DE CRÉDITO - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'cooperativas-de-credito', question: 'As cooperativas de crédito são formadas pela associação de pessoas com vínculo comum. Sobre suas características, é correto afirmar que:', options: ['Têm finalidade lucrativa e distribuem dividendos aos acionistas', 'São sociedades de pessoas, sem fins lucrativos, que prestam serviços financeiros aos cooperados', 'Podem captar recursos apenas de cooperados, sendo vedado emprestar a eles', 'São controladas pelo BACEN mas não integram o Sistema Financeiro Nacional', 'Não estão sujeitas à fiscalização do Banco Central'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Cooperativas são SOCIEDADES DE PESSOAS, SEM FINS LUCRATIVOS, que prestam serviços financeiros EXCLUSIVAMENTE AOS COOPERADOS. Não têm fim lucrativo (A errada), captam E emprestam aos cooperados (C errada), integram o SFN (D errada) e são fiscalizadas pelo BACEN (E errada). Princípios: adesão voluntária, gestão democrática.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'cooperativas-de-credito', question: 'A Lei Complementar 130/2009 dispõe sobre o Sistema Nacional de Crédito Cooperativo. Segundo essa lei, as cooperativas:', options: ['Podem captar recursos de não cooperados livremente', 'Estão dispensadas do recolhimento compulsório', 'Têm acesso aos instrumentos do mercado financeiro, inclusive depósitos interfinanceiros', 'Não podem operar com pessoas jurídicas, apenas pessoas físicas', 'São isentas de fiscalização do BACEN'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. A LC 130/2009 assegurou às cooperativas ACESSO AOS INSTRUMENTOS DO MERCADO FINANCEIRO: depósitos interfinanceiros (DI), redesconto, operações no mercado aberto, equiparando-as aos bancos. Só captam de cooperados (A errada), recolhem compulsório (B errada), podem operar com PF e PJ cooperadas (D errada), são fiscalizadas (E errada).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'cooperativas-de-credito', question: 'Sobre a estrutura das cooperativas de crédito no Brasil, é correto afirmar que:', options: ['Existem apenas cooperativas singulares, sem estrutura em níveis', 'Podem ser singulares (1º grau), centrais (2º grau) e confederações (3º grau)', 'São sempre de livre admissão de associados', 'O voto é proporcional ao capital integralizado por cada cooperado', 'Não podem formar redes ou sistemas cooperativos'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Sistema cooperativista tem TRÊS NÍVEIS: SINGULARES (1º grau - cooperados são PF/PJ), CENTRAIS (2º grau - cooperados são singulares) e CONFEDERAÇÕES (3º grau - cooperados são centrais). Admissão é restrita ao vínculo comum (C errada), voto é por cabeça (D errada), podem formar sistemas como Sicoob/Sicredi (E errada).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'cooperativas-de-credito', question: 'NÃO é permitido às cooperativas de crédito:', options: ['Captar depósitos à vista e a prazo de cooperados', 'Conceder crédito e financiamento aos cooperados', 'Captar recursos de não cooperados sem vínculo com a cooperativa', 'Aplicar recursos no mercado financeiro', 'Oferecer cartão de crédito aos cooperados'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Cooperativas NÃO podem captar de NÃO COOPERADOS. Captação e crédito devem ser EXCLUSIVAMENTE entre cooperados. Este é princípio fundamental do cooperativismo. As demais operações são permitidas: captação e crédito entre cooperados (A, B), aplicação no mercado para gestão de liquidez (D) e serviços aos cooperados (E).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'cooperativas-de-credito', question: 'Sobre a gestão democrática nas cooperativas de crédito:', options: ['Cada cooperado tem voto proporcional ao valor de suas quotas-parte', 'As decisões são tomadas por conselho nomeado pelo BACEN', 'Vigora o princípio "um cooperado, um voto", independentemente do capital', 'Apenas os maiores investidores podem votar', 'O voto é proporcional ao tempo de associação'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. Nas cooperativas: UM COOPERADO = UM VOTO, independentemente do capital, tempo ou volume de operações. Isso diferencia cooperativas de S.A. (onde voto é proporcional a ações). Não é proporcional ao capital (A errada), decisões são da assembleia (B errada), todos votam igual (D errada), não depende do tempo (E errada). Este é dos 7 princípios universais do cooperativismo.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ========== 7. CORRETORAS E DISTRIBUIDORAS - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'corretoras-e-distribuidoras', question: 'Sobre corretoras (CTVM) e distribuidoras (DTVM), é correto afirmar que:', options: ['Corretoras podem operar em bolsa; distribuidoras não podem', 'Ambas podem intermediar operações de câmbio', 'Apenas distribuidoras podem administrar fundos de investimento', 'Corretoras são fiscalizadas apenas pela CVM; distribuidoras apenas pelo BACEN', 'Não há mais diferenças significativas entre CTVMs e DTVMs desde 2009'], correctAnswer: 4, explanation: 'CORRETO: Alternativa E. A Instrução CVM 461/2007 e Resolução CMN 3.828/2009 EQUIPARARAM CTVMs e DTVMs - NÃO HÁ MAIS diferenças significativas. Ambas podem: operar em bolsa, fazer câmbio se autorizadas, administrar fundos. São fiscalizadas por BACEN E CVM. Historicamente corretoras tinham exclusividade na bolsa, mas acabou. Hoje a diferença é só o nome.', difficulty: 'hard', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'corretoras-e-distribuidoras', question: 'NÃO é atividade de corretoras e distribuidoras:', options: ['Intermediação de operações em bolsas de valores, mercadorias e futuros', 'Administração de carteiras e custódia de valores mobiliários', 'Captação de depósitos à vista (conta corrente)', 'Operações no mercado aberto (open market)', 'Subscrição de emissões (underwriting)'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. CTVMs e DTVMs NÃO podem captar depósitos à vista (conta corrente) - atividade EXCLUSIVA de bancos comerciais. As demais são TÍPICAS: intermediação em bolsas (A), administração de carteiras (B), operar no open market como dealers (D) e underwriting (E). A proibição de captar depósitos à vista as diferencia dos bancos.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'corretoras-e-distribuidoras', question: 'Corretoras e distribuidoras devem ser constituídas como:', options: ['Sociedade Anônima (S.A.) ou Sociedade Limitada (LTDA)', 'Exclusivamente Sociedade Anônima (S.A.)', 'Qualquer forma societária', 'Cooperativa de profissionais', 'Empresa Individual'], correctAnswer: 0, explanation: 'CORRETO: Alternativa A. CTVMs e DTVMs podem ser S.A. OU LTDA, conforme Resolução CMN 1.655/89. Esta flexibilidade difere dos bancos que DEVEM ser S.A. A opção pela LTDA é comum em corretoras menores; grandes geralmente optam por S.A. para acesso ao mercado de capitais. Autorização do BACEN é necessária em qualquer caso.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'corretoras-e-distribuidoras', question: 'Sobre a fiscalização de corretoras e distribuidoras:', options: ['São fiscalizadas exclusivamente pelo Banco Central', 'São fiscalizadas exclusivamente pela CVM', 'São fiscalizadas pelo Banco Central e pela CVM, conforme a operação', 'Não estão sujeitas a fiscalização por serem intermediárias', 'São fiscalizadas apenas pelas bolsas de valores'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. CTVMs e DTVMs têm DUPLA FISCALIZAÇÃO: BANCO CENTRAL (aspectos prudenciais, autorização, câmbio, regras gerais) e CVM (valores mobiliários, fundos, conduta no mercado). Esta supervisão compartilhada garante controle completo: BACEN cuida da solidez financeira; CVM cuida da conduta e proteção aos investidores.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'corretoras-e-distribuidoras', question: 'Quando corretoras e distribuidoras atuam como dealers, isso significa que:', options: ['Apenas intermediam operações entre terceiros, sem assumir posições', 'Operam por conta própria, assumindo posições compradas ou vendidas', 'Só podem operar com autorização prévia para cada operação', 'Atuam exclusivamente como consultoras de investimento', 'Não podem ter carteira própria de títulos'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Como DEALERS, operam POR CONTA PRÓPRIA, assumindo POSIÇÕES COMPRADAS ou VENDIDAS em títulos, diferente de BROKERS (apenas intermediando). Como dealers: compram para carteira própria, fazem market making (dão liquidez), assumem risco de mercado. A atuação como dealer é permitida mas regulada, exigindo capital mínimo e controles de risco.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },

    // ========== 8. SISTEMA DE PAGAMENTOS BRASILEIRO (SPB) - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'sistema-de-pagamentos-brasileiro', question: 'O Sistema de Pagamentos Brasileiro (SPB) foi reestruturado em 2002. Sobre o SPB, é correto afirmar que:', options: ['É gerido exclusivamente pela B3', 'Tem como órgão responsável o Banco Central do Brasil', 'Processa apenas transações de valores mobiliários', 'Não inclui transferências interbancárias', 'É fiscalizado pela CVM'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. O SPB é de responsabilidade do BANCO CENTRAL (Lei 10.214/2001), que regulamenta, supervisiona e opera sistemas-chave como o STR. B3 opera câmaras mas não gere todo o SPB (A errada). Processa diversos tipos de transações (C errada). Transferências interbancárias são a essência do SPB (D errada). Fiscalização é do BACEN (E errada).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'sistema-de-pagamentos-brasileiro', question: 'O principal objetivo da reestruturação do SPB em 2002 foi:', options: ['Aumentar as tarifas bancárias', 'Eliminar o risco sistêmico e aumentar a segurança', 'Privatizar o Banco Central', 'Reduzir o número de bancos', 'Criar a moeda digital'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. A reforma visou ELIMINAR/REDUZIR O RISCO SISTÊMICO (risco de efeito dominó) e AUMENTAR SEGURANÇA. Antes operava em D+1 (confirmava dia seguinte), gerando risco. Após reforma: liquidação em tempo real (LBTR no STR), mecanismos de garantia, monitoramento contínuo. Alternativas A, C, D, E não têm relação com a reforma.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'sistema-de-pagamentos-brasileiro', question: 'O STR (Sistema de Transferência de Reservas) é o componente central do SPB. Sobre o STR:', options: ['Opera em D+1 (liquidação no dia seguinte)', 'Processa transferências de qualquer valor entre pessoas físicas', 'Opera em LBTR (Liquidação Bruta em Tempo Real) para grandes valores interbancários', 'É operado pela Caixa Econômica Federal', 'Só funciona das 10h às 16h'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. O STR opera em LBTR (Liquidação Bruta em Tempo Real), processando transferências de GRANDE VALOR entre bancos instantaneamente, operação por operação. Não é em D+1 (A errada), é interbancário não para PF diretamente (B errada), operado pelo BACEN (D errada), horário mais amplo 6h30-18h30 (E errada). Eliminou risco ao processar em tempo real.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'sistema-de-pagamentos-brasileiro', question: 'O PIX, lançado em 2020, é parte do SPB. Sobre o PIX, é INCORRETO:', options: ['Permite transferências instantâneas 24/7', 'É gerenciado pelo Banco Central', 'Utiliza chaves como CPF, e-mail e telefone', 'Cobra tarifa obrigatória para pessoas físicas em todas as transações', 'Reduz uso de papel-moeda'], correctAnswer: 3, explanation: 'CORRETO: Alternativa D (INCORRETA). O PIX é GRATUITO para pessoas físicas em operações pessoais e entre contas de mesma titularidade. Pode haver cobrança em uso comercial, mas não é obrigatória em todas as transações. As demais corretas: funciona 24/7/365 (A), gerido pelo BACEN (B), usa chaves (C), reduz dinheiro físico (E). PIX revolucionou pagamentos no Brasil.', difficulty: 'easy', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'sistema-de-pagamentos-brasileiro', question: 'As câmaras de compensação (clearings) no SPB têm como principal função:', options: ['Emitir moeda para o mercado', 'Registrar, compensar e liquidar operações, atuando como contraparte central', 'Fiscalizar a conduta dos participantes', 'Definir a taxa básica de juros', 'Autorizar funcionamento de instituições financeiras'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. As câmaras (B3, CIP) REGISTRAM operações, COMPENSAM (calculam posições líquidas multilaterais) e LIQUIDAM (efetuam transferências), atuando como CONTRAPARTE CENTRAL (assumem risco de crédito entre partes). Emissão é do BACEN (A), fiscalização é BACEN/CVM (C), SELIC é do COPOM (D), autorização é do BACEN (E). Câmaras reduzem riscos no SPB.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },

    // ========== 9. POLÍTICA MONETÁRIA - 5 questões ==========
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'politica-monetaria', question: 'A política monetária controla oferta de moeda e juros. No Brasil, o órgão responsável pela execução da política monetária é:', options: ['Conselho Monetário Nacional (CMN)', 'Banco Central do Brasil (BACEN)', 'Comissão de Valores Mobiliários (CVM)', 'Ministério da Fazenda', 'Banco do Brasil'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. O BANCO CENTRAL (BACEN) EXECUTA a política monetária através do COPOM que define a SELIC. O CMN (A) FORMULA diretrizes gerais, mas quem EXECUTA é o BACEN. CVM (C) cuida do mercado de capitais. Ministério da Fazenda (D) define política fiscal. BB (E) é banco comercial. Esta divisão - CMN formula, BACEN executa - é fundamental no SFN.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'politica-monetaria', question: 'O COPOM se reúne para definir a taxa básica de juros. Com que frequência ocorrem as reuniões ordinárias?', options: ['Mensalmente', 'Bimestralmente', 'A cada 45 dias (8 vezes ao ano)', 'Trimestralmente', 'Semestralmente'], correctAnswer: 2, explanation: 'CORRETO: Alternativa C. O COPOM se reúne A CADA 45 DIAS, totalizando 8 REUNIÕES ORDINÁRIAS/ano (calendário divulgado no início do ano). Duram 2 dias: dia 1 apresentações técnicas; dia 2 definição da SELIC. Ata divulgada em 8 dias. Desde 2006 foram reduzidas de 12 para 8 reuniões para dar tempo aos efeitos da política se manifestarem. Extraordinárias são raras.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'politica-monetaria', question: 'Instrumentos de política monetária: I. Open Market. II. Compulsórios. III. Redesconto. IV. Debêntures. Estão corretos:', options: ['Apenas I e II', 'Apenas I, II e III', 'Apenas II, III e IV', 'Apenas I, III e IV', 'I, II, III e IV'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B (I, II, III). Os três instrumentos CLÁSSICOS do BACEN são: I - OPEN MARKET (compra/venda de títulos públicos, principal); II - COMPULSÓRIOS (recolhimento obrigatório); III - REDESCONTO (empréstimos aos bancos). IV ERRADA: DEBÊNTURES são títulos de EMPRESAS privadas (S.A.), regulados pela CVM, NÃO são instrumento de política monetária. Estes 3 controlam liquidez e juros.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'politica-monetaria', question: 'A taxa SELIC é a taxa básica de juros. Sobre a SELIC, é correto:', options: ['É a taxa cobrada por bancos em empréstimos ao consumidor', 'É a taxa de operações compromissadas de um dia (overnight) com títulos públicos', 'É definida livremente pelo mercado, sem interferência', 'Não tem relação com inflação', 'É igual à TJLP'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. A SELIC é a taxa média das operações de EMPRÉSTIMO DE UM DIA (overnight) entre instituições, com lastro em TÍTULOS PÚBLICOS registrados no sistema SELIC. O COPOM define a META e o BACEN atua via open market para mantê-la próxima. Taxa do consumidor é muito maior (A errada), é controlada pelo COPOM (C errada), é principal instrumento contra inflação (D errada), TJLP foi substituída pela TLP (E errada).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'sistema-financeiro-nacional', topic: 'politica-monetaria', question: 'Para política monetária CONTRACIONISTA (reduzir liquidez/controlar inflação), o BACEN pode:', options: ['Reduzir SELIC e diminuir compulsório', 'Vender títulos públicos e aumentar compulsório', 'Comprar títulos e reduzir redesconto', 'Aumentar emissão de moeda e reduzir juros', 'Proibir empréstimos bancários'], correctAnswer: 1, explanation: 'CORRETO: Alternativa B. Política CONTRACIONISTA (restritiva) visa REDUZIR liquidez/CONTROLAR inflação. Instrumentos: VENDER títulos no open market (retira dinheiro), AUMENTAR compulsório (imobiliza recursos), AUMENTAR SELIC (encarece crédito). Alternativa A é EXPANSIONISTA. C: comprar títulos é expansionista. D: aumentar moeda é expansionista. E: não pode proibir, apenas encarecer. Contracionista = apertar; Expansionista = afrouxar.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${moreQuestions.length} more SFN questions (Part 2/2)...`);
  
  count = 0;
  for (const q of moreQuestions) {
    await saveQuestion(q);
    count++;
    if (count % 5 === 0) {
      console.log(`✅ Saved ${count}/${moreQuestions.length} questions (Part 2)...`);
    }
  }
  
  console.log('✅✅✅ COMPLETE! All 45 Sistema Financeiro Nacional questions imported successfully! 🎯🏛️');
}