import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL CONTABILIDADE GERAL QUESTIONS =============
export async function seedAllContabilidadeGeralQuestions() {
  console.log('🚀 Starting to seed ALL Contabilidade Geral questions...');
  
  const allQuestions: Question[] = [
    // ============= PATRIMÔNIO (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'patrimonio', question: 'O patrimônio de uma entidade é composto por:', options: ['Apenas bens e direitos', 'Bens, direitos e obrigações', 'Apenas ativos circulantes', 'Receitas e despesas', 'Apenas capital social e reservas'], correctAnswer: 1, explanation: 'PATRIMÔNIO: conjunto de BENS, DIREITOS e OBRIGAÇÕES de uma entidade. EQUAÇÃO FUNDAMENTAL: ATIVO (bens + direitos) = PASSIVO (obrigações) + PATRIMÔNIO LÍQUIDO. BENS: imóveis, veículos, estoques, dinheiro. DIREITOS: contas a receber, aplicações financeiras. OBRIGAÇÕES: fornecedores, empréstimos, salários a pagar. PATRIMÔNIO LÍQUIDO: capital próprio = Ativo - Passivo Exigível. IMPORTANTE: receitas e despesas afetam PL mas não são componentes diretos do patrimônio.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'patrimonio', question: 'Uma empresa possui: Caixa R$ 50.000, Estoques R$ 80.000, Fornecedores R$ 30.000, Capital Social R$ 100.000. O valor do Patrimônio Líquido é:', options: ['R$ 100.000', 'R$ 130.000', 'R$ 150.000', 'R$ 80.000', 'R$ 200.000'], correctAnswer: 0, explanation: 'CÁLCULO DO PL: Ativo Total = Caixa (50) + Estoques (80) = R$ 130.000. Passivo Exigível = Fornecedores = R$ 30.000. PL = Ativo - Passivo Exigível = 130.000 - 30.000 = R$ 100.000. VERIFICAÇÃO: PL informado = Capital Social R$ 100.000 ✓. EQUAÇÃO: A = P + PL → 130.000 = 30.000 + 100.000 ✓. IMPORTANTE: Capital Social é CONTA do PL, não do Passivo. PL representa recursos PRÓPRIOS da empresa.', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'patrimonio', question: 'Sobre a Situação Líquida Patrimonial, é CORRETO afirmar que:', options: ['Situação Líquida Positiva ocorre quando Ativo > Passivo Exigível', 'Situação Líquida Nula significa Ativo = Patrimônio Líquido', 'Situação Líquida Negativa (Passivo a Descoberto) ocorre quando Passivo Exigível > Ativo', 'Apenas alternativa A está correta', 'Alternativas A e C estão corretas'], correctAnswer: 4, explanation: 'SITUAÇÕES LÍQUIDAS: 1) POSITIVA (superavitária): A > PE → PL > 0. Empresa tem bens/direitos que superam obrigações. 2) NULA: A = PE → PL = 0. Situação crítica, todo ativo compromete com dívidas. 3) NEGATIVA (Passivo a Descoberto): PE > A → PL < 0. Dívidas superam ativos, falência técnica. ALTERNATIVA B ERRADA: situação nula é A = PE (não A = PL). IMPORTANTE: PL negativo aparece entre parênteses no Balanço. Sociedades anônimas não podem operar com PL negativo (Lei 6.404/76).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'patrimonio', question: 'Os bens, direitos e obrigações classificam-se, respectivamente, em:', options: ['Passivo, Ativo e Patrimônio Líquido', 'Ativo, Ativo e Passivo', 'Receita, Despesa e Resultado', 'Ativo, Passivo e Patrimônio Líquido', 'Circulante, Não Circulante e Exigível'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO PATRIMONIAL: BENS: compõem o ATIVO (tangíveis: veículos, imóveis; intangíveis: marcas, patentes). DIREITOS: também compõem o ATIVO (contas a receber, aplicações). OBRIGAÇÕES: compõem o PASSIVO EXIGÍVEL (fornecedores, empréstimos, tributos a pagar). ESQUEMA: ATIVO = Bens + Direitos. PASSIVO = Obrigações + PL. ATENÇÃO: PL NÃO é obrigação (é capital próprio). Obrigações = Passivo EXIGÍVEL (dívidas com terceiros). IMPORTANTE: distinção entre obrigações (passivo exigível) e PL (capital próprio).', difficulty: 'easy', examBoard: 'CESGRANRIO', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'patrimonio', question: 'Uma empresa apresenta Ativo de R$ 500.000 e Passivo Exigível de R$ 600.000. Sobre essa situação, é correto afirmar:', options: ['A empresa está em situação líquida positiva', 'O Patrimônio Líquido é de R$ 100.000', 'A empresa apresenta Passivo a Descoberto de R$ 100.000', 'A situação patrimonial é nula', 'O Capital Social é negativo'], correctAnswer: 2, explanation: 'PASSIVO A DESCOBERTO: PE > A → empresa tem mais dívidas que bens/direitos. CÁLCULO: PL = A - PE = 500.000 - 600.000 = -R$ 100.000. INTERPRETAÇÃO: faltam R$ 100.000 de ativos para cobrir todas obrigações. BALANÇO: PL aparece NEGATIVO (entre parênteses). CONSEQUÊNCIAS: 1) Falência técnica; 2) S.A. deve convocar AGE (art. 173, Lei 6.404); 3) Redução capital ou dissolução. ATENÇÃO: Capital Social NÃO fica negativo (é conta do PL). PL total que fica negativo. GRAVE SITUAÇÃO FINANCEIRA.', difficulty: 'medium', examBoard: 'ESAF', year: 2023 },

    // ============= CONTAS CONTÁBEIS (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'contas-contabeis', question: 'As contas do ATIVO têm natureza:', options: ['Credora', 'Devedora', 'Depende da situação', 'Neutra', 'Variável'], correctAnswer: 1, explanation: 'NATUREZA DAS CONTAS: ATIVO: natureza DEVEDORA (aumenta a DÉBITO, diminui a CRÉDITO). PASSIVO e PL: natureza CREDORA (aumentam a CRÉDITO, diminuem a DÉBITO). RECEITAS: credoras. DESPESAS: devedoras. REGRA DÉBITO/CRÉDITO: débito no ATIVO aumenta; crédito no ATIVO diminui. LÓGICA: débito = aplicação recursos; crédito = origem recursos. MACETE: A.D.R.C. (Ativo e Despesa = Débito; Receita e Crédito). SALDO: Ativo tem saldo devedor; Passivo/PL saldo credor.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'contas-contabeis', question: 'São contas PATRIMONIAIS:', options: ['Receitas de Vendas, Custo das Mercadorias Vendidas', 'Caixa, Fornecedores, Capital Social', 'Despesas de Salários, Receitas Financeiras', 'Todas as anteriores', 'Apenas receitas e despesas'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO CONTAS: PATRIMONIAIS: representam BENS, DIREITOS, OBRIGAÇÕES e PL. Aparecem no BALANÇO PATRIMONIAL. Exemplos: Caixa, Estoques, Fornecedores, Capital Social. RESULTADO: representam RECEITAS e DESPESAS. Aparecem na DRE. Exemplos: Receitas de Vendas, CMV, Despesas Salários. CARACTERÍSTICAS: Patrimoniais: permanentes (saldos passam exercício). Resultado: temporárias (zeradas no encerramento). IMPORTANTE: CMV é conta de RESULTADO (despesa), não patrimonial. Contas patrimoniais formam situação estática; resultado mostra dinâmica.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'contas-contabeis', question: 'O Plano de Contas é:', options: ['Obrigatório por lei para todas as empresas', 'Conjunto de contas utilizadas pela entidade, com critérios próprios', 'Igual para todas as empresas do mesmo setor', 'Definido exclusivamente pelo CFC', 'Apenas para grandes empresas'], correctAnswer: 1, explanation: 'PLANO DE CONTAS: conjunto ordenado de TODAS contas utilizadas pela entidade. ESTRUTURA: 1) Elenco de contas (código e nome); 2) Função/natureza; 3) Funcionamento (débito/crédito). CARACTERÍSTICAS: NÃO obrigatório por lei (exceto instituições financeiras, seguradoras). Adaptado à realidade de cada empresa. Respeita princípios contábeis. HIERARQUIA: contas sintéticas (agregadoras) e analíticas (movimentação). EXEMPLO: 1 Ativo, 1.1 Circulante, 1.1.1 Caixa. MANUAL: complemento com orientações. IMPORTANTE: flexível mas deve seguir estrutura legal do Balanço.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'contas-contabeis', question: 'São contas RETIFICADORAS do Ativo:', options: ['Receitas Antecipadas, Provisões', 'Depreciação Acumulada, Perdas Estimadas com Créditos de Liquidação Duvidosa (PECLD)', 'Capital Social, Reservas de Lucros', 'Despesas Antecipadas, Fornecedores', 'Receitas Financeiras, Despesas Operacionais'], correctAnswer: 1, explanation: 'CONTAS RETIFICADORAS (redutoras): DIMINUEM grupo que pertencem. Natureza OPOSTA ao grupo. ATIVO: contas retificadoras têm natureza CREDORA. Exemplos: 1) Depreciação Acumulada (reduz Imobilizado); 2) PECLD (reduz Clientes/CR); 3) Ajuste Valor Presente. APRESENTAÇÃO: (-) antes do valor no Balanço. PASSIVO: contas retificadoras (raras) têm natureza devedora. Ex: Despesas Antecipadas (retifica Receitas Antecipadas). PL: Ações em Tesouraria, Prejuízos Acumulados (reduzem PL). IMPORTANTE: não confundir com contas compensativas (controle).', difficulty: 'hard', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'contas-contabeis', question: 'O método das partidas dobradas estabelece que:', options: ['Todo débito corresponde a um crédito de igual valor', 'Débitos devem ser maiores que créditos', 'Cada conta tem dois saldos', 'Apenas contas de resultado seguem essa regra', 'Créditos devem exceder débitos'], correctAnswer: 0, explanation: 'PARTIDAS DOBRADAS (Luca Pacioli, 1494): REGRA FUNDAMENTAL: NÃO há débito sem crédito correspondente. SOMA débitos = SOMA créditos (em cada lançamento). CONSEQUÊNCIAS: 1) Ativo sempre = Passivo + PL; 2) Rastreabilidade (origem e aplicação); 3) Verificação erros. EXEMPLO: compra à vista: D-Estoques C-Caixa (ambos R$ 1.000). IMPORTANTE: em um lançamento, pode haver múltiplos débitos/créditos, mas totais devem se equivaler. BASE: contabilidade moderna. Não confundir: partidas dobradas ≠ dois lançamentos. É débito E crédito no MESMO lançamento.', difficulty: 'easy', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= BALANÇO PATRIMONIAL (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'balanco-patrimonial', question: 'No Balanço Patrimonial, o Ativo é classificado em:', options: ['Circulante e Permanente', 'Circulante e Não Circulante', 'Circulante, Realizável a Longo Prazo e Permanente', 'Operacional e Financeiro', 'Corrente e Não Corrente'], correctAnswer: 1, explanation: 'ESTRUTURA ATIVO (Lei 6.404/76 - nova redação): 1) ATIVO CIRCULANTE: realizável até fim exercício seguinte (caixa, clientes, estoques). 2) ATIVO NÃO CIRCULANTE: subdivisões: a) Realizável a Longo Prazo: > 12 meses; b) Investimentos: participações permanentes; c) Imobilizado: bens operação; d) Intangível: sem substância física (marcas, software). MUDANÇA 11.638/07: extinto PERMANENTE, criado NÃO CIRCULANTE. ATENÇÃO: "corrente" é termo internacional (IFRS), no Brasil usa CIRCULANTE. ORDEM: decrescente liquidez.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'balanco-patrimonial', question: 'Devem ser classificados no ATIVO CIRCULANTE:', options: ['Apenas disponibilidades e estoques', 'Bens e direitos realizáveis até o término do exercício seguinte', 'Todos os bens da empresa', 'Apenas contas de resultado', 'Investimentos permanentes'], correctAnswer: 1, explanation: 'ATIVO CIRCULANTE: bens/direitos REALIZÁVEIS no CICLO OPERACIONAL ou até fim do EXERCÍCIO SEGUINTE (o MAIOR). CRITÉRIO: curto prazo (normalmente 12 meses). EXEMPLOS: 1) Disponibilidades (caixa, bancos); 2) Clientes; 3) Estoques; 4) Despesas Antecipadas; 5) Aplicações Financeiras CP. EXCEÇÃO: se ciclo operacional > 12 meses (construção civil, estaleiros) → circulante segue ciclo. NÃO incluir: realizável LP, imobilizado. ORDEM BP: liquidez decrescente (disponibilidade → estoques). IMPORTANTE: "até término exercício seguinte" = até 31/12 do próximo ano.', difficulty: 'easy', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'balanco-patrimonial', question: 'O Patrimônio Líquido é composto por:', options: ['Capital Social, Reservas, Lucros/Prejuízos Acumulados', 'Apenas Capital Social e Reservas', 'Receitas e Despesas', 'Fornecedores e Empréstimos', 'Ativo Circulante menos Passivo Circulante'], correctAnswer: 0, explanation: 'PATRIMÔNIO LÍQUIDO (Lei 6.404/76): 1) CAPITAL SOCIAL: investimento sócios/acionistas. 2) RESERVAS: a) Capital: ágio, doações; b) Lucros: legal, estatutárias, contingências; c) Incentivos fiscais. 3) AJUSTES AVALIAÇÃO PATRIMONIAL: MTM, hedge, coligadas. 4) (-) AÇÕES EM TESOURARIA: recompra próprias ações. 5) LUCROS/PREJUÍZOS ACUMULADOS: S.A. não pode ter lucros acumulados (distribuir ou destinar). Ltda. pode manter. FÓRMULA: PL = A - PE. NATUREZA: credora. REPRESENTA: capital próprio, riqueza líquida sócios.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'balanco-patrimonial', question: 'Uma obrigação deve ser classificada no Passivo Circulante quando:', options: ['Vencer em qualquer prazo', 'Vencer até o término do exercício seguinte', 'For uma dívida trabalhista', 'For superior a R$ 100.000', 'Relacionar-se ao imobilizado'], correctAnswer: 1, explanation: 'PASSIVO CIRCULANTE: obrigações exigíveis no CICLO OPERACIONAL ou até fim EXERCÍCIO SEGUINTE (o MAIOR). CRITÉRIO: curto prazo (normalmente 12 meses). EXEMPLOS: 1) Fornecedores; 2) Salários a Pagar; 3) Tributos a Recolher; 4) Empréstimos CP; 5) Dividendos a Pagar. CONTRAPARTIDA: > 12 meses → Não Circulante. ATENÇÃO: vencimento define, NÃO natureza ou valor. Empréstimo R$ 1 milhão vence 6 meses → Circulante. R$ 10 mil vence 18 meses → Não Circulante. IMPORTANTE: reclassificação quando prazo diminui (LP → CP).', difficulty: 'easy', examBoard: 'CESGRANRIO', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'balanco-patrimonial', question: 'Sobre a estrutura do Balanço Patrimonial, é INCORRETO afirmar:', options: ['O Ativo evidencia as aplicações de recursos', 'O Passivo Exigível mostra as origens de recursos de terceiros', 'O Patrimônio Líquido representa origens de recursos próprios', 'As contas são ordenadas por ordem alfabética', 'O BP é uma demonstração estática'], correctAnswer: 3, explanation: 'ESTRUTURA BP: ATIVO: ordem decrescente de LIQUIDEZ (facilidade conversão em $). Disponível → Realizável → Imobilizado. PASSIVO + PL: ordem decrescente de EXIGIBILIDADE (prioridade pagamento). Circulante → Não Circulante → PL. INCORRETO: NÃO é ordem alfabética! É liquidez/exigibilidade. CONCEITOS: APLICAÇÕES (Ativo) × ORIGENS (Passivo + PL). Terceiros (PE) × Próprios (PL). ESTÁTICA: foto momento (31/12). vs DRE (dinâmica, período). EQUILÍBRIO: A = P + PL sempre. QUALITATIVA: apenas valores, não quantidades físicas.', difficulty: 'medium', examBoard: 'ESAF', year: 2023 },

    // ============= DRE - DEMONSTRAÇÃO DO RESULTADO (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'dre-demonstracao-resultado', question: 'A Demonstração do Resultado do Exercício (DRE) apresenta:', options: ['A situação patrimonial em determinada data', 'As variações do patrimônio líquido no período', 'As receitas, custos e despesas de um período, apurando o resultado', 'Apenas receitas e despesas operacionais', 'Somente o lucro líquido'], correctAnswer: 2, explanation: 'DRE (Lei 6.404/76): demonstração DINÂMICA, confronta RECEITAS × CUSTOS/DESPESAS de um PERÍODO (exercício/trimestre). OBJETIVO: apurar resultado (lucro/prejuízo). ESTRUTURA: Receita Bruta (-) Deduções = Receita Líquida (-) CMV/CPV = Lucro Bruto (-) Despesas Operacionais (+/-) Resultado Financeiro = EBITDA (-) Depreciação/Amortização = EBIT (-) Juros = LAIR (-) IR/CSLL = Lucro Líquido. CARACTERÍSTICAS: regime COMPETÊNCIA, confrontação receitas×despesas. NÃO confundir: BP = estática (data); DRE = dinâmica (período). Resultado → PL (via lucros/prejuízos).', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'dre-demonstracao-resultado', question: 'São deduções da Receita Bruta:', options: ['Despesas administrativas e comerciais', 'Impostos sobre vendas, devoluções e abatimentos', 'Custo das Mercadorias Vendidas', 'Despesas financeiras', 'Provisão para IR'], correctAnswer: 1, explanation: 'DEDUÇÕES RECEITA BRUTA: 1) IMPOSTOS s/ VENDAS: ICMS, ISS, PIS, COFINS (não cumulativos). IPI NÃO deduz (por fora). 2) DEVOLUÇÕES: vendas canceladas. 3) ABATIMENTOS: descontos incondicionais concedidos. 4) DESCONTOS COMERCIAIS. FÓRMULA: Receita Líquida = Receita Bruta - Deduções. APÓS: subtrai CMV → Lucro Bruto. NÃO SÃO DEDUÇÕES: despesas operacionais (vêm depois), CMV (deduzido da receita líquida). IMPORTANTE: impostos recuperáveis (não cumulativos) deduzem; não recuperáveis vão custo. IPI por fora: não integra receita bruta.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'dre-demonstracao-resultado', question: 'O Lucro Bruto é obtido por:', options: ['Receita Bruta menos todas as despesas', 'Receita Líquida menos Custo das Mercadorias/Produtos Vendidos', 'Receita Bruta menos CMV', 'EBITDA menos IR', 'Lucro Operacional menos despesas financeiras'], correctAnswer: 1, explanation: 'LUCRO BRUTO: Receita Líquida (-) CMV/CPV. INDICA: margem operação antes despesas período. ANÁLISE: quanto empresa LUCRA na atividade-fim antes estrutura. MARGEM BRUTA: (LB / RL) × 100. Setor: comércio ~30%, indústria ~40%, serviços ~60%. APÓS LB: deduzir DESPESAS OPERACIONAIS (vendas, administrativas, gerais) → Lucro Operacional. IMPORTANTE: CMV é CUSTO (ligado produção/aquisição), não despesa (estrutura). Empresas serviços: CPV (Custo Prestação Serviços) ou CSP. LB alto: boa precificação/compra; LB baixo: rever margens.', difficulty: 'easy', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'dre-demonstracao-resultado', question: 'EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) representa:', options: ['O lucro líquido após impostos', 'O resultado operacional antes de juros, impostos, depreciação e amortização', 'A receita bruta da empresa', 'O patrimônio líquido', 'Apenas receitas financeiras'], correctAnswer: 1, explanation: 'EBITDA (Lajida): lucro antes juros, impostos, depreciação e amortização. CÁLCULO: Lucro Líquido (+) IR/CSLL (+) Juros (+) Depreciação/Amortização. OU: Lucro Operacional (+) Depreciação/Amortização. INTERPRETAÇÃO: geração operacional de caixa (aproximado). Exclui: efeitos estrutura capital (juros), tributação, investimentos (depreciação). VANTAGENS: comparação empresas, setores, países. Mede eficiência operacional pura. LIMITAÇÕES: não considera capital giro, Capex. NÃO é fluxo caixa real. IMPORTANTE: métrica gerencial, não obrigatória em DRE publicada. Popular em valuation e análise.', difficulty: 'hard', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'dre-demonstracao-resultado', question: 'O Resultado Financeiro é composto por:', options: ['Apenas receitas financeiras', 'Receitas financeiras menos despesas financeiras', 'Lucro líquido menos despesas', 'CMV menos despesas operacionais', 'Vendas menos devoluções'], correctAnswer: 1, explanation: 'RESULTADO FINANCEIRO: Receitas Financeiras (-) Despesas Financeiras. RECEITAS: juros ativos (aplicações), descontos obtidos, variações cambiais ativas. DESPESAS: juros passivos (empréstimos), IOF, tarifas bancárias, descontos concedidos, variações cambiais passivas. APRESENTAÇÃO DRE: pode ser líquido ou separado (preferível). Vem APÓS Lucro Operacional. ANÁLISE: negativo indica alto endividamento; positivo indica boa gestão sobras caixa. IFRS: separa em "receitas/despesas financeiras". ATENÇÃO: desconto condicional (financeiro) ≠ desconto comercial (dedução receita). Empresas não financeiras: idealmente neutro/positivo pequeno.', difficulty: 'medium', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= LANÇAMENTOS CONTÁBEIS (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'lancamentos-contabeis', question: 'O lançamento contábil deve conter:', options: ['Apenas a data e o valor', 'Data, conta(s) debitada(s), conta(s) creditada(s), histórico e valor', 'Somente contas e valores', 'Apenas débito e crédito', 'Nome do contador'], correctAnswer: 1, explanation: 'ELEMENTOS ESSENCIAIS LANÇAMENTO (art. 1.183, CC): 1) DATA: quando ocorreu fato; 2) CONTAS: debitadas e creditadas; 3) HISTÓRICO: descrição fato; 4) VALOR: em moeda nacional. ESTRUTURA: LOCAL (Livro Diário). DATA. D - Conta debitada...valor. C - Conta creditada...valor. Histórico: descrição sucinta. FORMALIDADES: ordem cronológica, sem rasuras, em idioma/moeda nacional. TIPOS: 1ª fórmula (1D-1C), 2ª (1D-vários C), 3ª (vários D-1C), 4ª (vários D-vários C). IMPORTANTE: histórico deve ser claro, permitir entendimento. Documentação suporte: NF, recibo, contrato.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'lancamentos-contabeis', question: 'Uma empresa comprou mercadorias à vista por R$ 10.000. O lançamento correto é:', options: ['D - Caixa / C - Estoques', 'D - Estoques / C - Caixa', 'D - Fornecedores / C - Caixa', 'D - Despesas / C - Caixa', 'D - Caixa / C - Receitas'], correctAnswer: 1, explanation: 'COMPRA À VISTA: ENTRADA bem (Estoques) → DÉBITO Ativo. SAÍDA recurso (Caixa) → CRÉDITO Ativo. LANÇAMENTO: D - Estoques (Ativo)......10.000 | C - Caixa (Ativo)...........10.000 | Histórico: Aquisição mercadorias conf. NF xxx. LÓGICA: débito = onde entrou (Estoques); crédito = de onde saiu (Caixa). ATENÇÃO: compra NÃO é despesa (não vai DRE). Estoque é ATIVO (BP). Vira despesa (CMV) só quando VENDER. Partidas dobradas: débito = crédito. À prazo seria: D-Estoques C-Fornecedores.', difficulty: 'easy', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'lancamentos-contabeis', question: 'Pagamento de aluguel no valor de R$ 5.000. O lançamento é:', options: ['D - Caixa / C - Despesas de Aluguel', 'D - Despesas de Aluguel / C - Caixa', 'D - Imóveis / C - Caixa', 'D - Receitas / C - Caixa', 'D - Aluguel a Pagar / C - Despesas'], correctAnswer: 1, explanation: 'PAGAMENTO ALUGUEL (despesa incorrida): RECONHECE despesa → DÉBITO (aumenta despesa, natureza devedora). SAÍDA recurso → CRÉDITO Caixa (diminui ativo). LANÇAMENTO: D - Despesas Aluguel (Resultado).....5.000 | C - Caixa (Ativo)........................5.000 | Histórico: Pgto aluguel mês xx/xxxx. EFEITO: ↓ Resultado (despesa) e ↓ Caixa. REGIME: COMPETÊNCIA (reconhece no uso, não no pagamento). Se aluguel referente mês SEGUINTE → D-Despesas Antecipadas (Ativo), não Despesa. ATENÇÃO: despesa aluguel ≠ compra imóvel. Compra: D-Imóveis (Ativo Permanente).', difficulty: 'easy', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'lancamentos-contabeis', question: 'Empresa recebe R$ 8.000 de cliente referente a serviços que serão prestados no mês seguinte. O lançamento é:', options: ['D - Caixa / C - Receitas de Serviços', 'D - Caixa / C - Receitas Antecipadas (Passivo)', 'D - Clientes / C - Receitas', 'D - Caixa / C - Adiantamento de Clientes (Ativo)', 'D - Receitas / C - Caixa'], correctAnswer: 1, explanation: 'RECEBIMENTO ANTECIPADO: ENTRADA recurso → DÉBITO Caixa (aumenta ativo). OBRIGAÇÃO prestar serviço → CRÉDITO Passivo (Receita Antecipada/Adiantamento Clientes). LANÇAMENTO: D - Caixa.............................8.000 | C - Receitas Antecipadas (Passivo).8.000 | Histórico: Recebimento antecipado serviços. LÓGICA: NÃO é receita ainda (competência: só quando PRESTAR serviço). É OBRIGAÇÃO fazer (Passivo). QUANDO PRESTAR: D-Receitas Antecipadas | C-Receitas Serviços (aí reconhece receita). ATENÇÃO: Adiantamentos Clientes = Passivo (obrigação); Adiantamentos a Fornecedores = Ativo (direito).', difficulty: 'medium', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'lancamentos-contabeis', question: 'Uma empresa vende mercadorias por R$ 15.000 a prazo (custo R$ 9.000). Os lançamentos corretos são:', options: ['Apenas D - Clientes / C - Receitas', 'D - Clientes / C - Receitas (15.000) e D - CMV / C - Estoques (9.000)', 'D - Caixa / C - Receitas', 'Apenas D - CMV / C - Estoques', 'D - Receitas / C - Clientes'], correctAnswer: 1, explanation: 'VENDA A PRAZO: DOIS lançamentos (regime competência). 1) RECONHECER RECEITA: D - Clientes (Ativo)...........15.000 | C - Receitas Vendas (Resultado).15.000. 2) BAIXAR ESTOQUE (custo): D - CMV (Despesa/Resultado)...9.000 | C - Estoques (Ativo)...............9.000. EFEITO LÍQUIDO: ↑ Lucro R$ 6.000 (15k receita - 9k CMV). LÓGICA: confrontação (matching): receita e custo JUNTOS. ATENÇÃO: mesmo à prazo, reconhece receita (competência). Quando receber: D-Caixa C-Clientes (não afeta resultado novamente). CMV é DESPESA que vai DRE. Margem: (15-9)/15 = 40%.', difficulty: 'hard', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= DEPRECIAÇÃO (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'depreciacao', question: 'Depreciação é:', options: ['A valorização de um bem ao longo do tempo', 'O reconhecimento contábil da perda de valor de bens pelo uso, obsolescência ou tempo', 'A venda de bens do ativo imobilizado', 'O pagamento de dívidas', 'A distribuição de lucros'], correctAnswer: 1, explanation: 'DEPRECIAÇÃO: alocação sistemática do CUSTO de ativo TANGÍVEL ao longo VIDA ÚTIL. CAUSAS: 1) USO/desgaste físico; 2) OBSOLESCÊNCIA (tecnologia); 3) TEMPO/deterioração. LANÇAMENTO: D - Despesa Depreciação (Resultado) | C - Depreciação Acumulada (Retificadora Ativo). EFEITO: ↓ Resultado e ↓ Ativo (líquido). CONCEITO: rateio custo, NÃO desvalorização mercado. Despesa NÃO-CAIXA (não sai $). IMPORTANTE: terrenos NÃO depreciam. Ativos intangíveis → AMORTIZAÇÃO. Recursos naturais → EXAUSTÃO.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'depreciacao', question: 'Uma máquina foi adquirida por R$ 120.000, com vida útil de 10 anos e valor residual de R$ 20.000. A depreciação anual pelo método linear é:', options: ['R$ 12.000', 'R$ 10.000', 'R$ 8.000', 'R$ 6.000', 'R$ 15.000'], correctAnswer: 1, explanation: 'MÉTODO LINEAR (QUOTAS CONSTANTES): mais usado. FÓRMULA: Depreciação Anual = (Custo - Valor Residual) / Vida Útil. CÁLCULO: (120.000 - 20.000) / 10 = 100.000 / 10 = R$ 10.000/ano. TAXA: 100% / 10 anos = 10% a.a. VALOR RESIDUAL (sucata): valor esperado ao fim vida útil. BASE DEPRECIÁVEL: Custo - Residual = 100.000. LANÇAMENTO ANUAL: D-Desp. Depreciação...10.000 | C-Deprec. Acumulada...10.000. APÓS 10 ANOS: Custo 120k, Deprec.Acum. 100k → Valor Contábil = 20k (= residual). ATENÇÃO: VALOR CONTÁBIL = Custo - Depreciação Acumulada.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'depreciacao', question: 'Taxas anuais de depreciação segundo Receita Federal:', options: ['Veículos 20%, Máquinas 10%, Móveis 10%', 'Todas 10% ao ano', 'Veículos 10%, Edificações 4%, Computadores 20%', 'Apenas Edificações 2%', 'Máquinas 5%, Veículos 15%'], correctAnswer: 0, explanation: 'TAXAS FISCAIS (RIR/99 - simplificado): VEÍCULOS: 20% a.a. (5 anos). MÁQUINAS/EQUIPAMENTOS: 10% a.a. (10 anos). MÓVEIS/UTENSÍLIOS: 10% a.a. (10 anos). EDIFICAÇÕES: 4% a.a. (25 anos). COMPUTADORES/PERIFÉRICOS: 20% a.a. (5 anos). IMPORTANTE: taxas FISCAIS (IR). Contabilmente: empresa define vida útil ECONÔMICA (pode diferir). CPC 27: baseado vida útil estimada real, não tabelas. ACELERADA: turnos (coeficientes 1,0/1,5/2,0). Apenas benefício FISCAL, não contábil. ATENÇÃO: terrenos NÃO depreciam. Obras andamento: só deprecia quando concluída.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'depreciacao', question: 'Sobre a Depreciação Acumulada, é correto afirmar que:', options: ['É conta de despesa na DRE', 'É conta retificadora do Ativo, natureza credora', 'É conta do Passivo', 'Aumenta o valor contábil do bem', 'É distribuída aos sócios'], correctAnswer: 1, explanation: 'DEPRECIAÇÃO ACUMULADA: conta RETIFICADORA (redutora) do ATIVO IMOBILIZADO. NATUREZA: CREDORA (oposta ao grupo Ativo). APRESENTAÇÃO BP: (-) Depreciação Acumulada (subtrai do Imobilizado). SALDO: acumula ao longo dos anos (não zera). FUNÇÃO: mostrar quanto JÁ foi depreciado. VALOR CONTÁBIL: Custo Aquisição - Deprec. Acumulada. DIFERENÇA: Despesa Depreciação (anual, vai DRE) ≠ Deprec. Acumulada (acumulada, BP). LANÇAMENTO: C-Deprec.Acumulada (não sai caixa!). BAIXA BEM: zera junto com custo. IMPORTANTE: revela "idade contábil" do bem.', difficulty: 'medium', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'depreciacao', question: 'Uma empresa comprou um veículo por R$ 80.000 e vendeu após 2 anos por R$ 70.000. Depreciação acumulada: R$ 32.000 (20% a.a.). O resultado na venda foi:', options: ['Lucro de R$ 10.000', 'Prejuízo de R$ 10.000', 'Lucro de R$ 22.000', 'Prejuízo de R$ 22.000', 'Resultado zero'], correctAnswer: 2, explanation: 'VENDA ATIVO IMOBILIZADO: comparar PREÇO VENDA × VALOR CONTÁBIL. VALOR CONTÁBIL: Custo - Deprec.Acumulada = 80.000 - 32.000 = R$ 48.000. VENDA: R$ 70.000. RESULTADO: 70.000 - 48.000 = LUCRO R$ 22.000 (receita não-operacional). LANÇAMENTO: D-Caixa...................70.000 | D-Deprec.Acumulada....32.000 | C-Veículos................80.000 | C-Ganho Venda Ativo.....22.000. ATENÇÃO: NÃO comparar com custo original (80k)! Usar valor CONTÁBIL (48k). Ganho/Perda = Outras Receitas/Despesas (DRE). Se vendesse por 40k → Perda 8k.', difficulty: 'hard', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= REGIME DE COMPETÊNCIA E CAIXA (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'regime-competencia-caixa', question: 'O Regime de Competência estabelece que:', options: ['Receitas e despesas são reconhecidas no recebimento/pagamento', 'Receitas e despesas são reconhecidas no momento em que ocorrem os fatos geradores', 'Apenas receitas seguem regime de competência', 'Não há diferença com regime de caixa', 'Somente grandes empresas devem usar'], correctAnswer: 1, explanation: 'REGIME DE COMPETÊNCIA (accrual basis): receitas/despesas reconhecidas quando OCORRE FATO GERADOR, independente recebimento/pagamento. PRINCÍPIO CONTÁBIL: obrigatório (NBC TG). EXEMPLOS: 1) Venda à prazo → reconhece receita NA VENDA (não no recebimento); 2) Serviço consumido → reconhece despesa NA UTILIZAÇÃO (não no pagamento). CONFRONTAÇÃO: receitas × despesas relacionadas no MESMO período. DRE: sempre regime competência. DIFERENÇA CAIXA: não considera fatos sem movimentação financeira. IMPORTANTE: competência → resultado econômico real; caixa → fluxo financeiro.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'regime-competencia-caixa', question: 'Empresa presta serviço em dezembro/X1 (R$ 10.000) mas recebe em janeiro/X2. Pelo regime de competência, a receita é reconhecida:', options: ['Em janeiro/X2, quando recebe', 'Em dezembro/X1, quando presta o serviço', 'Metade em cada mês', 'Não reconhece receita', 'Apenas no balanço'], correctAnswer: 1, explanation: 'COMPETÊNCIA: receita reconhecida quando SERVIÇO É PRESTADO (dez/X1), independente recebimento. LANÇAMENTO DEZ/X1: D-Clientes (Ativo)........10.000 | C-Receitas Serviços.......10.000 | Histórico: Serviços prestados, receberemos jan/X2. RESULTADO: impacta DRE de X1 (ano prestação). JANEIRO/X2: quando receber: D-Caixa.........10.000 | C-Clientes......10.000 (não afeta resultado novamente!). REGIME CAIXA: reconheceria só em jan/X2. Por isso competência é OBRIGATÓRIO (retrata realidade econômica). Matching: receita do período = despesas do período.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'regime-competencia-caixa', question: 'Uma empresa pagou em janeiro/X1 o aluguel de fevereiro/X1. Pelo regime de competência, a despesa é reconhecida:', options: ['Em janeiro, quando paga', 'Em fevereiro, quando o imóvel é utilizado', 'Não reconhece despesa', 'Metade em cada mês', 'Apenas no balanço final'], correctAnswer: 1, explanation: 'COMPETÊNCIA: despesa reconhecida quando INCORRIDA (fev/X1), não quando PAGA. JANEIRO/X1 (pagamento antecipado): D-Despesas Antecipadas (Ativo).....valor | C-Caixa...............................valor. FEVEREIRO/X1 (reconhecimento despesa): D-Despesas Aluguel (Resultado).........valor | C-Despesas Antecipadas................valor. LÓGICA: jan = antecipação (ativo, direito usar); fev = consumo (despesa). DRE: despesa aparece em FEV (competência). REGIME CAIXA: reconheceria em jan. ATENÇÃO: pagamento ≠ reconhecimento despesa. Competência vincula ao USO/BENEFÍCIO.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'regime-competencia-caixa', question: 'Sobre regime de caixa, é correto afirmar que:', options: ['É obrigatório para contabilidade societária', 'Reconhece receitas/despesas nos recebimentos/pagamentos', 'É mais preciso que regime de competência', 'Não pode ser usado em nenhuma situação', 'É exigido pela Lei 6.404/76'], correctAnswer: 1, explanation: 'REGIME DE CAIXA (cash basis): receitas/despesas reconhecidas na MOVIMENTAÇÃO FINANCEIRA (recebimentos/pagamentos). USO: Fluxo de Caixa (DFC), controle gerencial, MEI/pequenos negócios (simplificado). NÃO PERMITIDO: DRE, Balanço (competência obrigatório - CPC 00, Lei 6.404). EXEMPLO: venda jan, recebe mar → caixa: receita em MAR; competência: receita em JAN. VANTAGENS CAIXA: simplicidade, mostra liquidez. DESVANTAGENS: não confronta receitas×despesas, distorce resultado. IMPORTANTE: IR pode aceitar caixa (lucro presumido), mas CONTABILIDADE deve ser competência.', difficulty: 'easy', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'regime-competencia-caixa', question: 'Ajuste de competência: empresa tem R$ 5.000 a receber de serviços prestados em dezembro, mas não registrou. O ajuste é:', options: ['Não fazer nada, aguardar recebimento', 'D - Caixa / C - Receitas', 'D - Clientes / C - Receitas de Serviços', 'D - Receitas / C - Clientes', 'D - Despesas / C - Receitas'], correctAnswer: 2, explanation: 'AJUSTE DE COMPETÊNCIA (accrual): reconhecer receitas/despesas INCORRIDAS mas NÃO REGISTRADAS. SITUAÇÃO: serviço prestado dez → DEVE reconhecer receita dez (competência), mesmo sem receber. LANÇAMENTO AJUSTE: D - Clientes a Receber (Ativo)......5.000 | C - Receitas de Serviços (Resultado).5.000 | Histórico: Ajuste competência - serviços dez/XX. EFEITO: ↑ Ativo (direito) e ↑ Receita (resultado). QUANDO RECEBER: D-Caixa C-Clientes. TIPOS AJUSTES: receitas a receber, despesas a pagar, antecipações. Essenciais ANTES fechar balanço. Sem ajuste → resultado errado.', difficulty: 'hard', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= PROVISÕES (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'provisoes', question: 'Provisão é:', options: ['Um pagamento realizado', 'Uma estimativa de obrigação presente cuja época ou valor são incertos', 'Uma conta do ativo', 'Um recebimento futuro', 'Uma distribuição de lucros'], correctAnswer: 1, explanation: 'PROVISÃO (CPC 25): PASSIVO de prazo/valor INCERTOS. REQUISITOS: 1) Obrigação PRESENTE (passado); 2) Provável SAÍDA recursos; 3) Estimativa CONFIÁVEL. EXEMPLOS: Provisão Férias, 13º, Garantias, Contingências (trabalhistas, fiscais). LANÇAMENTO: D-Despesa/Custo (Resultado) | C-Provisão (Passivo). DIFERENÇA: Provisão (obrigação) ≠ Reserva (PL, lucros retidos). APRESENTAÇÃO: Passivo Circulante ou Não Circulante (prazo). ATENÇÃO: NÃO confundir com "provisão matemática" (seguros) ou contas retificadoras (PECLD, Deprec.Acum - antes chamadas "provisões"). CPC: termo provisão APENAS para passivos incertos.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'provisoes', question: 'A Provisão para Férias deve ser constituída porque:', options: ['É obrigatória pela Receita Federal', 'Pelo regime de competência, deve-se reconhecer a despesa no período em que o empregado trabalha', 'Apenas empresas grandes devem fazer', 'Somente quando pagar as férias', 'Não é necessária'], correctAnswer: 1, explanation: 'PROVISÃO FÉRIAS: reconhece DESPESA no período que empregado TRABALHA (adquire direito), não quando TIRA FÉRIAS. COMPETÊNCIA: despesa (esforço empregado) × receita (produção período). CÁLCULO: (salário × 1/12 × meses) + 1/3 constitucional + encargos (INSS, FGTS). LANÇAMENTO MENSAL: D-Despesa Salários (Resultado)...valor | C-Provisão Férias (Passivo).......valor. PAGAMENTO FÉRIAS: D-Provisão Férias...valor | C-Caixa................valor. IMPORTANTE: cada mês trabalhado → 1/12 férias. Complemento: + 1/3. Não provisionar → despesa errada (concentrada quando pagar). Obrigatório contabilmente (CPC 33 - Benefícios Empregados).', difficulty: 'easy', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'provisoes', question: 'Uma empresa foi acionada judicialmente. Advogados estimam perda PROVÁVEL de R$ 50.000. A contabilização deve ser:', options: ['Não fazer nada, apenas divulgar em nota explicativa', 'Constituir provisão: D - Despesa / C - Provisão Contingências', 'Pagar imediatamente', 'Registrar como reserva', 'Apenas mencionar no relatório da administração'], correctAnswer: 1, explanation: 'CONTINGÊNCIAS (CPC 25): PROVÁVEL perda → PROVISIONAR (Passivo). POSSÍVEL perda → apenas DIVULGAR nota explicativa. REMOTA perda → não provisiona, nem divulga. LANÇAMENTO: D-Despesas Contingências (Resultado)....50.000 | C-Provisão Contingências (Passivo).......50.000. REAVALIAÇÃO: anualmente (atualizar estimativa). SE PERDER AÇÃO: D-Provisão Contingências | C-Caixa (usa provisão). SE GANHAR: D-Provisão Contingências | C-Receita (reversão). TIPOS: trabalhistas, fiscais, cíveis, ambientais. ATENÇÃO: GANHO CONTINGENTE (ativo contingente): só reconhece quando CERTEZA (prudência).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'provisoes', question: 'A Provisão para Garantias em uma indústria é constituída porque:', options: ['Lei obriga todas as empresas', 'Regime de competência: confrontar despesas com receitas do período', 'Apenas se cliente reclamar', 'Não é necessária', 'Somente exportadoras devem fazer'], correctAnswer: 1, explanation: 'PROVISÃO GARANTIAS: reconhece DESPESA estimada com reparos/substituições FUTURAS na VENDA (matching). COMPETÊNCIA: despesa garantia vincula receita venda MESMO período. CÁLCULO: % vendas baseado histórico (ex: 2% vendas). LANÇAMENTO VENDA: D-Despesa Garantia (ou CMV).......valor | C-Provisão Garantias (Passivo).......valor. USO GARANTIA: D-Provisão Garantias | C-Estoques/Caixa (peças/serviços). REVISÃO: ajustar estimativa conforme experiência. EXEMPLO: vende 1.000 produtos × R$ 500, histórico 2% defeito × custo reparo R$ 50 → Provisão = 1.000 × 2% × 50 = R$ 1.000. Não provisionar → despesa só quando cliente reclamar (errado, competência).', difficulty: 'hard', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'provisoes', question: 'A diferença entre Provisão e Passivo Contingente é:', options: ['Não há diferença', 'Provisão é reconhecida contabilmente; Passivo Contingente (perda possível) apenas divulgado', 'Passivo Contingente é mais importante', 'Provisão é opcional', 'Ambos não afetam demonstrações'], correctAnswer: 1, explanation: 'PROVISÃO vs PASSIVO CONTINGENTE (CPC 25): PROVISÃO: perda PROVÁVEL (>50%) → RECONHECE contabilmente (Passivo no BP, Despesa na DRE). PASSIVO CONTINGENTE: perda POSSÍVEL (10-50%) → apenas DIVULGA nota explicativa (não contabiliza). PERDA REMOTA (<10%): não provisiona, nem divulga. EXEMPLO: ação trabalhista: advogado diz provável perder R$ 100k → Provisão. Advogado diz possível → Passivo Contingente (nota). Diz remota → ignora. REVERSÃO: se situação muda, ajusta/reverte provisão ou reclassifica. IMPORTANTE: julgamento profissional na classificação (provável/possível). Auditoria revisa.', difficulty: 'medium', examBoard: 'CESGRANRIO', year: 2024 },

    // ============= ANÁLISE DE BALANÇOS (5) =============
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'analise-balancos', question: 'A Liquidez Corrente mede:', options: ['A rentabilidade da empresa', 'A capacidade de pagar dívidas de curto prazo', 'O endividamento total', 'A margem de lucro', 'O giro do ativo'], correctAnswer: 1, explanation: 'LIQUIDEZ CORRENTE (LC): capacidade pagar obrigações CURTO PRAZO. FÓRMULA: LC = Ativo Circulante / Passivo Circulante. INTERPRETAÇÃO: LC > 1: AC > PC (folga). LC = 1: AC = PC (justo). LC < 1: AC < PC (risco). EXEMPLO: AC = 500, PC = 250 → LC = 2,0 (cada R$ 1 dívida CP tem R$ 2 ativo CP). LIMITAÇÕES: não considera qualidade ativos (estoques obsoletos?), prazos. COMPLEMENTO: Liquidez Seca (exclui estoques), Liquidez Imediata (só disponível). SETOR: comércio ~1,5; indústria ~2,0. ATENÇÃO: LC alto demais → ineficiência ($ parado).', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'analise-balancos', question: 'O índice de Endividamento Geral é calculado por:', options: ['Passivo Circulante / Ativo Total', 'Passivo Total / Ativo Total', 'Patrimônio Líquido / Passivo Total', 'Ativo / Passivo', 'Receitas / Despesas'], correctAnswer: 1, explanation: 'ENDIVIDAMENTO GERAL: proporção RECURSOS TERCEIROS no financiamento ativos. FÓRMULA: EG = Passivo Total (Exigível) / Ativo Total. OU: (PC + PNC) / Ativo. INTERPRETAÇÃO: EG = 0,60 (60%) → 60% ativos financiados por dívidas, 40% capital próprio. QUANTO MAIOR: mais endividado, mais risco. BENCHMARK: industrial ~50%, comércio ~60%. COMPLEMENTOS: Composição Endividamento = PC/PE (dívidas CP/total). Endiv. PL = PE/PL (quanto dívida sobre capital próprio). ANÁLISE: endividamento moderado: alavancagem positiva. Excessivo: risco financeiro. BALANÇO: EG + (PL/Ativo) = 100%.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'analise-balancos', question: 'O Retorno sobre o Patrimônio Líquido (ROE) mede:', options: ['Lucro em relação às vendas', 'Rentabilidade do capital próprio investido pelos sócios', 'Capacidade de pagamento', 'Giro dos estoques', 'Liquidez imediata'], correctAnswer: 1, explanation: 'ROE (Return on Equity): rentabilidade CAPITAL PRÓPRIO. Quanto LUCRO gerado para cada R$ 1 investido pelos SÓCIOS. FÓRMULA: ROE = Lucro Líquido / Patrimônio Líquido Médio × 100. INTERPRETAÇÃO: ROE = 20% → cada R$ 100 PL gera R$ 20 lucro anual. COMPARAÇÃO: vs taxa livre risco (Selic), ROE competidores. ROE > custo capital → cria valor. DECOMPOSIÇÃO (DuPont): ROE = Margem Líquida × Giro Ativo × Alavancagem. EXEMPLO: LL=50, PL=250 → ROE=20%. IMPORTANTE: PL médio = (inicial+final)/2. S.A.: foco principal indicador (acionistas). Complemento: ROA (retorno ativo total).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'analise-balancos', question: 'A análise vertical do Balanço consiste em:', options: ['Comparar valores de um exercício com outro', 'Calcular o percentual de cada conta em relação ao total do grupo (Ativo Total = 100%)', 'Projetar valores futuros', 'Apenas somar os valores', 'Calcular médias'], correctAnswer: 1, explanation: 'ANÁLISE VERTICAL (AV): estrutura patrimonial. Cada item = % do TOTAL. BALANÇO: Ativo Total = 100%, cada conta = %. Passivo+PL = 100%, cada conta = %. DRE: Receita Líquida = 100%, demais itens = %. FÓRMULA: AV = (Valor Conta / Valor Base) × 100. EXEMPLO: Caixa=50, Ativo Total=500 → Caixa=10% do Ativo. INTERPRETAÇÃO: mostra RELEVÂNCIA itens. Compara estrutura empresas/períodos. VANTAGEM: elimina efeito tamanho (compara grandes/pequenas). vs ANÁLISE HORIZONTAL: evolução temporal (ano base=100). APLICAÇÃO: detecta concentrações, mudanças estrutura.', difficulty: 'easy', examBoard: 'ESAF', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-geral', topic: 'analise-balancos', question: 'O Giro do Ativo mede:', options: ['Quantas vezes o ativo "girou" em vendas no período', 'A liquidez da empresa', 'O endividamento', 'A margem de lucro', 'O prazo médio de recebimento'], correctAnswer: 0, explanation: 'GIRO DO ATIVO: eficiência uso ativos para GERAR VENDAS. FÓRMULA: Giro = Receita Líquida / Ativo Total Médio. INTERPRETAÇÃO: Giro=2,5 → cada R$ 1 ativo gerou R$ 2,50 vendas/ano. QUANTO MAIOR: melhor eficiência operacional. SETOR: comércio ~3x, indústria ~1x. ANÁLISE: Giro baixo → ativos ociosos, ineficiência. Alto → bem utilizado. RELACIONA: Rentabilidade = Margem × Giro. Empresa pode compensar baixa margem com alto giro (varejo) ou vice-versa. COMPOSIÇÃO: Giro Estoques, Giro Imobilizado (específicos). Ativo Médio = (inicial+final)/2.', difficulty: 'hard', examBoard: 'CESGRANRIO', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Contabilidade Geral questions...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Contabilidade Geral questions seeded successfully!');
}
