import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL ORÇAMENTO PÚBLICO QUESTIONS =============
export async function seedAllOrcamentoPublicoQuestions() {
  console.log('🚀 Starting to seed ALL Orçamento Público questions...');
  
  const allQuestions: Question[] = [
    // ============= PRINCÍPIOS ORÇAMENTÁRIOS (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'principios-orcamentarios', question: 'O Princípio Orçamentário da Unidade estabelece que:', options: ['Deve haver vários orçamentos para cada órgão', 'Deve existir apenas um orçamento para cada ente federativo', 'Cada Poder elabora seu orçamento separadamente', 'Não há necessidade de consolidação', 'Orçamento pode ser dividido por regiões'], correctAnswer: 1, explanation: 'PRINCÍPIO UNIDADE (Lei 4.320/64 art. 2º): orçamento deve ser ÚNICO para cada ente (União, Estado, Município). OBJETIVO: visão GLOBAL finanças, evitar duplicidades, facilitar controle. CONSOLIDAÇÃO: todos órgãos/entidades administração direta/indireta, fundos, fundações em ÚNICO DOCUMENTO (LOA). CF/88 art. 165 § 5º: LOA compreende orçamento fiscal, seguridade social, investimentos estatais (consolidados). vs MÚLTIPLOS orçamentos (passado): fragmentação, perda controle. IMPORTANTE: unidade FORMAL (documento único), não significa centralização execução. Cada órgão executa sua parte. Transparência, accountability, visão conjunta. Evita "orçamentos paralelos".', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'principios-orcamentarios', question: 'Segundo o Princípio da Universalidade:', options: ['Apenas receitas tributárias devem constar no orçamento', 'Todas as receitas e despesas devem estar previstas no orçamento', 'Somente despesas correntes são incluídas', 'Apenas transferências voluntárias constam', 'Receitas de capital não integram orçamento'], correctAnswer: 1, explanation: 'PRINCÍPIO UNIVERSALIDADE (Lei 4.320 art. 2º, 3º e 4º): TODAS receitas e TODAS despesas devem constar LOA. OBJETIVO: transparência TOTAL, controle COMPLETO, vedação "caixa dois". ABRANGÊNCIA: receitas correntes + capital; despesas correntes + capital; TODAS fontes (próprias, transferências, operações crédito, alienações). VALORES BRUTOS (não deduzidos). EXCEÇÃO APARENTE: operações intraorçamentárias (deduzir refinanciamento). VEDAÇÃO: receitas/despesas extraorçamentárias PERMANENTES (só transitórias - cauções, depósitos). CONSEQUÊNCIA: cidadão/Legislativo conhecem TOTAL movimentação recursos. Base: controle, fiscalização TCU/TCE. vs PARCIAL: risco ocultação gastos. IMPORTANTE: universalidade = CONTEÚDO completo. Unidade = FORMA (documento único). Complementares.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'principios-orcamentarios', question: 'O Princípio da Anualidade (ou Periodicidade) determina que:', options: ['Orçamento tem vigência indeterminada', 'Orçamento tem vigência de um exercício financeiro (ano civil)', 'Vigência de dois anos', 'Apenas seis meses', 'Vigência até aprovação do próximo'], correctAnswer: 1, explanation: 'PRINCÍPIO ANUALIDADE/PERIODICIDADE (CF art. 165 § 5º, Lei 4.320 art. 2º, 34): orçamento vigência EXERCÍCIO FINANCEIRO = ANO CIVIL (1º jan a 31 dez). OBJETIVO: controle periódico, autorização LEGISLATIVA anual, adaptação conjuntura. COINCIDÊNCIA: exercício financeiro = ano civil (Lei 4.320 art. 34). CONSEQUÊNCIA: após 31/12, créditos expiram (salvo plurianuais, créditos especiais/extraordinários reabertos - CF 167 § 2º). EXCEÇÕES CF: PPA (4 anos), créditos especiais/extraordinários (se autorizados últimos 4 meses, reabertos pelo saldo - art. 167 § 2º). RESTOS A PAGAR: despesas empenhadas não pagas (não desrespeitam anualidade - foram autorizadas no exercício). IMPORTANTE: anualidade ≠ rigidez total. Planejamento plurianual (PPA) convive. Autorização execução anual. Histórico: antes havia orçamentos bienais (abandonado - inflexível).', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'principios-orcamentarios', question: 'O Princípio da Exclusividade veda:', options: ['Incluir apenas matéria orçamentária na LOA', 'Incluir matéria estranha à previsão de receita e fixação de despesa (exceto autorizações créditos e operações de crédito)', 'Autorizar qualquer despesa', 'Incluir apenas receitas', 'Consolidar orçamentos'], correctAnswer: 1, explanation: 'PRINCÍPIO EXCLUSIVIDADE (CF art. 165 § 8º): LOA NÃO conterá dispositivo ESTRANHO a: previsão RECEITA, fixação DESPESA. EXCEÇÕES CF: autorização CRÉDITOS SUPLEMENTARES, autorização OPERAÇÕES CRÉDITO (inclusive ARO). OBJETIVO: evitar "CAUDAS/ORÇAMENTOS RABILONGOS": aproveitamento processo orçamentário para incluir matérias estranhas (mudança legislação, criação cargos, alteração estruturas). HISTÓRICO: comum pré-CF/88. Legislativo/Executivo incluíam assuntos diversos LOA (processo mais rápido, menos debate). VEDADO: criação tributos, aumento salários, mudança estrutura administrativa na LOA. PERMITIDO: autorizar Executivo suplementar até X% dotações, contratar empréstimos. PROTEÇÃO: processo legislativo orçamentário (foco técnico, análise financeira). IMPORTANTE: princípio democrático, transparência. Orçamento = peça TÉCNICA financeira.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'principios-orcamentarios', question: 'Sobre o Princípio da Não-Afetação (Não-Vinculação) de Receitas, é correto afirmar:', options: ['Todas as receitas podem ser vinculadas', 'É vedada vinculação de impostos a órgão, fundo ou despesa, ressalvadas exceções constitucionais', 'Taxas não podem ser vinculadas', 'Apenas receitas de capital podem ser vinculadas', 'Não há regra sobre vinculação'], correctAnswer: 1, explanation: 'PRINCÍPIO NÃO-AFETAÇÃO (CF art. 167-IV): VEDADA vinculação receita IMPOSTOS a órgão/fundo/despesa. OBJETIVO: FLEXIBILIDADE alocação recursos conforme prioridades. ABRANGÊNCIA: só IMPOSTOS (não taxas - naturalmente vinculadas; não contribuições - finalidade específica). EXCEÇÕES CONSTITUCIONAIS: 1) REPARTIÇÃO tributária (FPE 21,5%, FPM 23,5%, IPI-Exportação). 2) SAÚDE: 15% União, 12% Estados, 15% Municípios (mínimos). 3) EDUCAÇÃO: 18% União, 25% Estados/Municípios. 4) FUNDEB. 5) Administração tributária. 6) Garantias operações crédito (ARO, dívida externa). 7) Prestação garantias. FUNDAMENTO: evitar ENGESSAMENTO orçamento. Governante precisa liberdade alocar (prioridades ano, emergências). CONTROVÉRSIA: vinculações crescentes (EC sucessivas) reduziram flexibilidade. IMPORTANTE: exceções CONSTITUCIONAIS (só emenda constitucional cria). Lei ordinária NÃO pode vincular impostos (salvo exceções CF).', difficulty: 'hard', examBoard: 'FCC', year: 2023 },

    // ============= CICLO ORÇAMENTÁRIO (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ciclo-orcamentario', question: 'O Ciclo Orçamentário compreende:', options: ['Apenas a elaboração do orçamento', 'Elaboração, apreciação legislativa, execução e controle/avaliação', 'Somente a execução', 'Apenas controle', 'Não há ciclo definido'], correctAnswer: 1, explanation: 'CICLO ORÇAMENTÁRIO: processo contínuo, dinâmico, periódico. ETAPAS: 1) ELABORAÇÃO: Executivo prepara proposta LOA (STN/SOF coordena). Base: PPA, LDO, diagnóstico receitas, prioridades. Participação órgãos setoriais. Prazo envio Legislativo: 31 agosto (LDO art., CF 165 § 9º - lei complementar pendente, LDO define). 2) APRECIAÇÃO LEGISLATIVA: Legislativo (Congresso/Assembleia/Câmara) analisa, emenda, aprova. Comissão mista permanente (CMO - CN). Emendas limitadas (LDO define). Sanção Executivo. 3) EXECUÇÃO: ano seguinte (1º jan - 31 dez). Arrecadação receitas, realização despesas. Programação financeira, contingenciamento (LRF art. 9º). 4) CONTROLE/AVALIAÇÃO: interno (CGU - cada Poder) e EXTERNO (Legislativo + TC). Prestação contas. DURAÇÃO: aproximadamente 2 anos (elabora N-1, executa N, controla N+1). IMPORTANTE: ciclo CONTÍNUO (enquanto elabora N+1, executa N). Sobreposição.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ciclo-orcamentario', question: 'Na fase de elaboração do orçamento, compete ao Poder Executivo:', options: ['Aprovar o orçamento', 'Elaborar a proposta orçamentária e encaminhar ao Legislativo', 'Apenas executar', 'Julgar contas', 'Fiscalizar a execução'], correctAnswer: 1, explanation: 'ELABORAÇÃO ORÇAMENTO (CF art. 165, Lei 4.320 art. 22-28): COMPETÊNCIA: Poder EXECUTIVO (iniciativa PRIVATIVA). Presidente, Governador, Prefeito. PROCESSO: 1) ÓRGÃO CENTRAL: STN/SOF (União), Secretarias Fazenda/Planejamento (Estados/Municípios). 2) DIRETRIZES: baseado PPA (estratégico 4 anos), LDO (prioridades/metas ano), estimativa receitas. 3) COLETA: órgãos setoriais enviam propostas (necessidades, programas). 4) CONSOLIDAÇÃO: órgão central consolida, compatibiliza receitas×despesas. 5) REVISÃO: autoridades (ministros, secretários) negociam, ajustam. 6) MENSAGEM: Presidente/Governador/Prefeito envia PROJETO LEI ao Legislativo. PRAZO ENVIO: 31 agosto (União - LDO define; Estados/Municípios - Constituição Estadual/Lei Orgânica). PARTICIPAÇÃO: audiências públicas (LRF art. 48). IMPORTANTE: Executivo ELABORA (não aprova). Legislativo APROVA (pode emendar - limites LDO). Separação Poderes. Iniciativa orçamentária = Executivo (conhecimento máquina administrativa).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ciclo-orcamentario', question: 'Durante a apreciação legislativa, o Congresso Nacional:', options: ['Apenas referenda sem mudanças', 'Pode emendar o projeto de LOA, observadas limitações da LDO', 'Não pode fazer alterações', 'Apenas rejeita ou aprova totalmente', 'Elabora novo orçamento'], correctAnswer: 1, explanation: 'APRECIAÇÃO LEGISLATIVA (CF art. 166): Legislativo EXAMINA, EMENDA, VOTA projeto LOA. COMPETÊNCIA: Congresso Nacional (CN - União), Assembleias Legislativas, Câmaras Municipais. COMISSÃO MISTA (CN): CMO (Comissão Mista Orçamentos) - Deputados + Senadores. Relator. EMENDAS: parlamentares PODEM emendar, MAS limitações: a) Compatibilidade PPA/LDO. b) Indiquem RECURSOS (anulação despesas - exceto pessoal, serviço dívida, transferências constitucionais). c) Relacionadas: correção erros/omissões, dispositivos projeto. LDO define limites (emendas impositivas: individuais 1,2% RCL, bancada 1% RCL). VOTAÇÃO: Comissão mista, Plenário Congresso (sessão conjunta). REJEIÇÃO TOTAL: raridade (pode devolver Executivo). SANÇÃO: Presidente sanciona (promulga lei). NÃO há veto (entendimento). PRAZO: até encerramento sessão legislativa (22 dez - CN). IMPORTANTE: Legislativo NÃO elabora (só emenda). Executivo conhece máquina. Equilíbrio Poderes.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ciclo-orcamentario', question: 'A execução orçamentária é acompanhada por:', options: ['Apenas pelo Executivo', 'Sistemas de controle interno e externo simultaneamente', 'Somente Legislativo', 'Apenas Tribunais de Contas', 'Não há acompanhamento'], correctAnswer: 1, explanation: 'EXECUÇÃO E CONTROLE (CF art. 70-75, LRF): EXECUÇÃO: Poder Executivo/Legislativo/Judiciário (cada um executa seu orçamento). ACOMPANHAMENTO SIMULTÂNEO: 1) CONTROLE INTERNO: CADA Poder mantém sistema (CF 74). União: CGU (Executivo), cada Poder próprio. Finalidade: avaliar gestão, cumprimento metas, controles, apoiar controle externo. 2) CONTROLE EXTERNO: Legislativo + TC (CF 71). TC fiscaliza (inspeções, auditorias), aprecia contas Executivo, julga contas administradores, representações. Legislativo julga contas Chefe Executivo (parecer prévio TC). 3) CONTROLE SOCIAL: cidadãos, ONGs (Portal Transparência, audiências públicas LRF 48). SIMULTÂNEO: controles CONCOMITANTES execução (não só posterior). IMPORTANTE: controle INTERNO prepara/subsidia EXTERNO. Independentes mas complementares. Finalidades distintas: interno = apoio gestão, prevenção. Externo = accountability Legislativo/sociedade. Social = participação cidadã.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ciclo-orcamentario', question: 'O encerramento do exercício financeiro e a prestação de contas ocorrem em:', options: ['Qualquer data', '31 de dezembro (encerramento) e contas prestadas no exercício seguinte', 'Apenas após 5 anos', 'Não há data definida', 'Somente quando solicitado'], correctAnswer: 1, explanation: 'ENCERRAMENTO EXERCÍCIO (Lei 4.320 art. 34-36): EXERCÍCIO FINANCEIRO: coincide ano CIVIL (1º janeiro a 31 DEZEMBRO - art. 34). ENCERRAMENTO 31/12: apuração resultado orçamentário (receitas×despesas), financeiro (ingressos×dispêndios), patrimonial (VPA×VPD). Fechamento: contas, balanços (orçamentário, financeiro, patrimonial, DVP). RESTOS A PAGAR: inscrição despesas empenhadas não pagas (art. 36). PRESTAÇÃO CONTAS: Chefe Executivo (Presidente, Governador, Prefeito) presta contas ao Legislativo. PRAZO: 60 dias após abertura sessão legislativa (varia ente). TC: parecer prévio 60 dias recebimento (TCU). Legislativo julga. DOCUMENTOS: balanços, relatórios execução orçamentária, gestão fiscal, controle interno. IMPORTANTE: contas ANUAIS (anualidade). TC emite PARECER (Executivo), JULGA contas (administradores, ordenadores despesa). Prestação contas = accountability, transparência, controle social/institucional. Aprovação/rejeição contas consequências políticas/jurídicas.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ============= PPA - PLANO PLURIANUAL (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ppa-plano-plurianual', question: 'O Plano Plurianual (PPA) estabelece:', options: ['Apenas o orçamento anual', 'Diretrizes, objetivos e metas da administração pública para 4 anos, de forma regionalizada', 'Somente investimentos', 'Apenas despesas correntes', 'Vigência de 10 anos'], correctAnswer: 1, explanation: 'PPA - PLANO PLURIANUAL (CF art. 165-I, § 1º): instrumento PLANEJAMENTO estratégico médio prazo. CONTEÚDO: estabelece, forma REGIONALIZADA: 1) DIRETRIZES: orientações gerais políticas públicas. 2) OBJETIVOS: resultados almejados (qualitativos). 3) METAS: quantificação objetivos. Para DESPESAS CAPITAL, PROGRAMAS DURAÇÃO CONTINUADA (> 2 exercícios). VIGÊNCIA: 4 ANOS. Mandato: início 2º ano mandato (permite transição), termina 1º ano mandato seguinte (continuidade administrativa). Exemplo: PPA 2024-2027 (governo 2023-2026). REGIONALIZAÇÃO: atender desigualdades regionais (CF 165 § 1º). ESTRUTURA: programas (áreas atuação), ações (projetos, atividades, operações especiais). APROVAÇÃO: Lei (projeto Executivo 31 agosto 1º ano mandato). IMPORTANTE: PPA = ESTRATÉGICO (visão longo prazo). LDO = TÁTICO (prioridades ano). LOA = OPERACIONAL (execução ano). Hierarquia: LOA compatível LDO, LDO compatível PPA. Mudanças PPA: revisões (lei).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ppa-plano-plurianual', question: 'A vigência do PPA abrange:', options: ['Apenas o ano de sua aprovação', 'Do segundo ano do mandato do Chefe do Executivo até o primeiro ano do mandato seguinte', 'Todo o mandato do governante', 'Apenas dois anos', 'Não tem prazo definido'], correctAnswer: 1, explanation: 'VIGÊNCIA PPA (CF art. 165 § 9º - LC pendente, LDO define): PERÍODO: 4 anos. INÍCIO: 2º ano mandato Chefe Executivo. TÉRMINO: 1º ano mandato SEGUINTE. RACIONALIDADE: 1) TRANSIÇÃO: novo governante não inicia sem planejamento (tem PPA anterior 1 ano). 2) CONTINUIDADE: políticas públicas não interrompem mudança governo. 3) ELABORAÇÃO: eleito tem tempo elaborar novo PPA (1º ano). EXEMPLO UNIÃO: Presidente 2023-2026. PPA 2024-2027 (enviado 2023). Sucessor 2027-2030 executa PPA anterior em 2027, envia novo PPA 2028-2031. COMPATIBILIDADE: LOA cada ano COMPATÍVEL PPA vigente. Obras plurianuais (> 4 anos): podem constar PPAs sucessivos. ALTERAÇÃO: revisão anual (ajustes metas, inclusão/exclusão programas) via lei. IMPORTANTE: PPA instrumento PLANEJAMENTO. Não apenas peça formal. Deve orientar efetivamente ações governo. Metas devem ser realistas, mensuráveis. Avaliação anual cumprimento.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ppa-plano-plurianual', question: 'São elementos do PPA:', options: ['Apenas receitas', 'Programas, objetivos, metas, indicadores e ações', 'Somente despesas', 'Apenas investimentos', 'Não há estrutura definida'], correctAnswer: 1, explanation: 'ESTRUTURA PPA (Portaria MP 42/99 - referência, cada ente adapta): 1) PROGRAMAS: unidade maior. Articula ações (projetos/atividades) para enfrentar problema, atender demanda. Ex: "Saúde da Família". 2) OBJETIVOS: propósito programa (qualitativo). O que se busca. 3) METAS: QUANTIFICAÇÃO objetivos. Quanto se quer alcançar (físicas: nº escolas, km estradas). 4) INDICADORES: medição desempenho. Acompanhamento resultados (taxa mortalidade, índice educação). 5) AÇÕES: operacionalização programas. Tipos: a) PROJETO: obra/aquisição, tempo determinado (construir hospital). b) ATIVIDADE: contínua (manutenção UBS). c) OPERAÇÃO ESPECIAL: não gera produto (transferências, serviço dívida). 6) REGIONALIZAÇÃO: distribuição geográfica. PÚBLICO-ALVO: beneficiários. IMPORTANTE: PPA orientado RESULTADOS (não apenas insumos). Foco: impacto sociedade. Avaliação: indicadores (efetividade). Moderna gestão pública: planejamento estratégico, mensuração desempenho. Transparência: sociedade acompanha cumprimento promessas.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ppa-plano-plurianual', question: 'O prazo para envio do projeto de PPA ao Legislativo (União) é:', options: ['Até 15 de abril do primeiro ano do mandato', 'Até 31 de agosto do primeiro ano do mandato', 'Qualquer data', 'Após aprovação da LDO', 'Não há prazo legal'], correctAnswer: 1, explanation: 'PRAZOS PPA UNIÃO (CF art. 165 § 9º - LC pendente; ADCT art. 35 § 2º-I): ENVIO: até 31 AGOSTO 1º ano mandato (4 meses antes encerramento sessão legislativa). DEVOLUÇÃO: até ENCERRAMENTO SESSÃO LEGISLATIVA (22 dezembro). Congresso deve aprovar. ESTADOS/MUNICÍPIOS: Constituições Estaduais/Leis Orgânicas definem (geralmente similares). RACIONALIDADE PRAZO: governante eleito (jan), tem 8 meses elaborar PPA estratégico (diagnóstico, prioridades, consultas). Congresso: 4 meses analisar, emendar, aprovar. VIGÊNCIA: PPA aprovado fim ano 1 mandato, VIGORA a partir ano 2. CONSEQUÊNCIA ATRASO: se Legislativo não aprovar até 22/12 → sessões extraordinárias, prejuízo LDO ano seguinte (LDO compatível PPA). Histórico: atrasos causam tumulto orçamentário. IMPORTANTE: PPA BASE sistema orçamentário. Atraso compromete planejamento. Disciplina prazos essencial. Executivo deve cumprir (iniciativa). Legislativo deve apreciar tempestivamente (não pode simplesmente não votar - omissão).', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ppa-plano-plurianual', question: 'Nenhum investimento cuja execução ultrapasse um exercício financeiro poderá ser iniciado sem:', options: ['Aprovação do Legislativo a cada ano', 'Prévia inclusão no PPA ou sem lei que autorize a inclusão', 'Apenas decisão do Executivo', 'Não há restrições', 'Somente parecer do Tribunal de Contas'], correctAnswer: 1, explanation: 'INVESTIMENTOS PLURIANUAIS (CF art. 167-I): VEDAÇÃO: INICIAR investimento execução > 1 exercício SEM: prévia inclusão PPA OU lei autorize inclusão (sob pena crime responsabilidade - Lei 1.079/50). RACIONALIDADE: 1) PLANEJAMENTO: investimentos plurianuais (obras grandes) exigem planejamento médio prazo (PPA). 2) COMPROMETIMENTO: obra iniciada compromete recursos exercícios futuros (precisa terminar). 3) CONTROLE: evitar "obras inacabadas", início obras eleitoreiras sem sustentabilidade. INCLUSÃO PPA: constar PPA vigente (originalmente ou via revisão - lei específica). AUTORIZAÇÃO LEGISLATIVA: se não consta PPA, lei específica pode autorizar (excepcional). INVESTIMENTO: despesas capital geradoras acréscimo patrimonial (obras, equipamentos permanentes). vs DESPESAS CORRENTES continuadas (> 2 exercícios): exigência diferente (LRF art. 17 - impacto, compensação). IMPORTANTE: princípio LEGALIDADE, PLANEJAMENTO orçamentário. Evita aventuras fiscais. Obras devem ser planejadas, financiamento assegurado. Sanção: crime responsabilidade (impeachment), improbidade. Controle: TCU/TCE fiscalizam.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= LDO - LEI DE DIRETRIZES ORÇAMENTÁRIAS (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ldo-lei-diretrizes-orcamentarias', question: 'A LDO - Lei de Diretrizes Orçamentárias compreende:', options: ['Apenas fixação de despesas', 'Metas e prioridades, orientação para elaboração da LOA, alterações tributárias, política de pessoal', 'Somente investimentos', 'Apenas receitas', 'Não tem conteúdo definido'], correctAnswer: 1, explanation: 'LDO - LEI DIRETRIZES ORÇAMENTÁRIAS (CF art. 165-II): instrumento INTERMEDIÁRIO entre PPA (estratégico) e LOA (execução anual). VIGÊNCIA: 1 ano (anual). CONTEÚDO CONSTITUCIONAL (CF 165 § 2º): 1) METAS E PRIORIDADES: administração ano seguinte (obras, serviços). 2) ORIENTAÇÃO: elaboração LOA (estrutura, vedações). 3) ALTERAÇÕES: legislação tributária (se necessário). 4) POLÍTICA: aplicação agências financeiras oficiais fomento. LRF AMPLIOU (art. 4º): 5) ANEXO METAS FISCAIS: receitas, despesas, resultados (primário, nominal), montante dívida. 3 anos (anterior, corrente, 2 seguintes). 6) ANEXO RISCOS FISCAIS: passivos contingentes, eventos fiscais imprevistos. 7) Critérios LIMITAÇÃO EMPENHO (contingenciamento). 8) Normas CONTROLE CUSTOS, avaliação programas. 9) Condições TRANSFERÊNCIAS capital (convênios). IMPORTANTE: LDO = ELO PPA-LOA. Anual mas olha médio prazo (metas fiscais trienais). Essencial LRF (responsabilidade fiscal). Aprovada ANTES LOA (baliza elaboração).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ldo-lei-diretrizes-orcamentarias', question: 'O Anexo de Metas Fiscais da LDO deve conter:', options: ['Apenas despesas do exercício', 'Metas anuais de receitas, despesas, resultado primário e nominal, montante da dívida pública', 'Somente investimentos', 'Apenas resultado patrimonial', 'Não é obrigatório'], correctAnswer: 1, explanation: 'ANEXO METAS FISCAIS (LRF art. 4º § 1º): OBRIGATÓRIO LDO. Contém: 1) METAS ANUAIS: receitas, despesas, resultado PRIMÁRIO (receitas - despesas NÃO financeiras), resultado NOMINAL (inclui juros), montante DÍVIDA PÚBLICA. Para exercício + 2 seguintes. 2) AVALIAÇÃO: cumprimento metas ano ANTERIOR. Justificativas desvios. 3) EVOLUÇÃO: patrimônio líquido (3 exercícios anteriores). 4) ORIGEM/APLICAÇÃO: recursos obtidos alienação ativos. 5) AVALIAÇÃO: situação financeira/atuarial RPPS, FRGPS (regimes previdência). 6) ESTIMATIVA/COMPENSAÇÃO: renúncia receita. 7) MARGEM EXPANSÃO: despesas obrigatórias caráter continuado. OBJETIVO: TRANSPARÊNCIA fiscal, COMPROMISSO metas, PRESTAÇÃO CONTAS. Base: acompanhamento LRF (limites, resultado, endividamento). ANÁLISE: Legislativo avalia viabilidade, TCU/TCE acompanham. IMPORTANTE: metas PLURIANUAIS (não só ano). Visão trajetória fiscal. Permite avaliar sustentabilidade. Frustração meta → contingenciamento (LRF 9º).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ldo-lei-diretrizes-orcamentarias', question: 'O Anexo de Riscos Fiscais visa:', options: ['Apenas listar investimentos', 'Avaliar passivos contingentes e outros riscos capazes de afetar as contas públicas', 'Somente apresentar receitas', 'Não tem finalidade específica', 'Apenas riscos de mercado'], correctAnswer: 1, explanation: 'ANEXO RISCOS FISCAIS (LRF art. 4º § 3º): OBRIGATÓRIO LDO. Avalia RISCOS capazes afetar contas públicas, providências se materializarem. TIPOS RISCOS: 1) PASSIVOS CONTINGENTES: obrigações cuja existência/valor depende evento futuro incerto. Exemplos: demandas judiciais (processos Estado pode perder - precatórios futuros), garantias/avais concedidos (se devedor não pagar, Estado honra), PPPs (obrigações contratuais). 2) OUTROS RISCOS: a) Macroeconômicos: frustração receita (PIB menor, inflação diferente). b) Naturais: catástrofes (enchentes, secas). c) Setoriais: queda preço commodities (Estados/Municípios dependentes). CONTEÚDO: descrição riscos, quantificação (se possível), impacto fiscal potencial, medidas mitigação/resposta. OBJETIVO: TRANSPARÊNCIA, PRUDÊNCIA fiscal. Advertir sobre incertezas. RESERVA CONTINGÊNCIA: LOA pode incluir dotação (eventos imprevistos - compatível riscos fiscais). IMPORTANTE: gestão RISCOS (não só execução). Antecipar problemas. Exemplo: RS enchentes 2024 (risco materializado, impacto fiscal grande). Planejamento permite resposta adequada.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ldo-lei-diretrizes-orcamentarias', question: 'Os prazos da LDO (União) são:', options: ['Não há prazos definidos', 'Envio até 15 de abril, devolução até 17 de julho (encerramento primeiro período legislativo)', 'Envio em dezembro', 'Apenas após PPA', 'Qualquer data antes da LOA'], correctAnswer: 1, explanation: 'PRAZOS LDO UNIÃO (ADCT art. 35 § 2º-II): ENVIO: até 15 ABRIL (8 meses e meio antes encerramento exercício). DEVOLUÇÃO: até ENCERRAMENTO 1º PERÍODO LEGISLATIVO (17 JULHO). CN não entra recesso sem aprovar. VIGÊNCIA: ano SEGUINTE (LDO 2024 aprovada 2023, vigora 2024). SEQUÊNCIA: PPA → LDO → LOA. LDO aprovada ANTES elaboração LOA (orienta). ESTADOS/MUNICÍPIOS: CE/LO definem (similares proporcionalmente). RACIONALIDADE: LDO aprovada MEIO ANO antes LOA (Executivo tem base elaborar LOA). Congresso: 3 meses apreciar. CONSEQUÊNCIA NÃO APROVAÇÃO: CN NÃO ENTRA RECESSO julho sem aprovar LDO (ADCT). Pressão aprovar. Histórico: atrasos prejudicam LOA. IMPORTANTE: LDO mais "política" que técnica (prioridades = escolhas). Espaço maior disputa Legislativo. Emendas parlamentares disputam prioridades. Executivo negocia. Aprovação tempestiva essencial calendário orçamentário.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'ldo-lei-diretrizes-orcamentarias', question: 'A LDO estabelece critérios para limitação de empenho quando:', options: ['Sempre, independente de condições', 'Houver risco de não cumprimento das metas de resultado primário ou nominal', 'Apenas por decisão do Legislativo', 'Não há previsão de limitação', 'Somente em casos de calamidade'], correctAnswer: 1, explanation: 'LIMITAÇÃO EMPENHO - CONTINGENCIAMENTO (LRF art. 4º-I-b, art. 9º): LDO estabelece CRITÉRIOS/forma limitação (contingenciamento). QUANDO EXECUTAR (LRF 9º): se VERIFICADO, bimestre, REALIZAÇÃO RECEITA PODE NÃO comportar cumprimento METAS RESULTADO (primário/nominal - Anexo Metas Fiscais). MECÂNICA: 1) BIMESTRAL: comparar receita prevista × realizada (RREO). 2) PROJEÇÃO: se receita menor → risco não cumprir meta. 3) LIMITAÇÃO: Executivo/Legislativo/Judiciário (proporcionalmente) limitam empenho/movimentação financeira. Montante necessário ajustar. 4) EXCEÇÕES: não contingencia obrigatórias constitucionais/legais (pessoal, serviço dívida, precatórios, emendas impositivas - parcial). 5) REVERSÃO: se receita normalizar (30 dias), restabelece. CRITÉRIOS LDO: quais despesas contingenciar (geralmente discricionárias), forma calcular montante, prazos. OBJETIVO: GARANTIR cumprimento meta fiscal (LRF). Evitar déficit. IMPORTANTE: contingenciamento = ajuste fiscal DURANTE exercício (não ex-post). Gestão ativa. Frustra expectativas (obras, programas atrasam), mas mantém responsabilidade fiscal. Polêmico (conflito político × técnico).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= LOA - LEI ORÇAMENTÁRIA ANUAL (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'loa-lei-orcamentaria-anual', question: 'A LOA - Lei Orçamentária Anual compreende:', options: ['Apenas o orçamento fiscal', 'Orçamento fiscal, da seguridade social e de investimento das estatais', 'Somente despesas', 'Apenas investimentos', 'Não há divisão'], correctAnswer: 1, explanation: 'LOA - LEI ORÇAMENTÁRIA ANUAL (CF art. 165-III, § 5º): orçamento ANUAL (exercício financeiro). COMPOSIÇÃO (CF 165 § 5º): 1) ORÇAMENTO FISCAL: Poderes União, fundos, órgãos, entidades administração direta/indireta. RECEITAS: impostos, taxas, contribuições, outras. DESPESAS: custeio, investimentos (exceto estatais e seguridade). 2) ORÇAMENTO SEGURIDADE SOCIAL: órgãos/entidades a quem compete executar ações saúde, previdência, assistência. RECEITAS: contribuições sociais (empregador, trabalhador, receita/faturamento, importação, concursos prognósticos), outras. DESPESAS: benefícios previdenciários, saúde (SUS), assistência (BPC, Bolsa Família). 3) ORÇAMENTO INVESTIMENTO ESTATAIS: empresas controladas (> 50% capital votante). INVESTIMENTOS: obras, equipamentos. NÃO inclui custeio estatais (autossustentáveis). CONSOLIDAÇÃO: LOA = 3 orçamentos INTEGRADOS (compatibilizados). Demonstrativos consolidados + específicos. OBJETIVO: visão TOTAL finanças públicas. IMPORTANTE: seguridade = orçamento SEPARADO (financiamento próprio - contribuições), mas INTEGRADO LOA (não é peça autônoma).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'loa-lei-orcamentaria-anual', question: 'Os prazos da LOA (União) são:', options: ['Não há prazos legais', 'Envio até 31 de agosto, devolução até 22 de dezembro', 'Envio em janeiro', 'Após término do exercício', 'Qualquer data'], correctAnswer: 1, explanation: 'PRAZOS LOA UNIÃO (ADCT art. 35 § 2º-III): ENVIO: até 31 AGOSTO (4 meses antes encerramento exercício). DEVOLUÇÃO: até ENCERRAMENTO SESSÃO LEGISLATIVA (22 DEZEMBRO). CN não entra recesso natal sem aprovar. SANÇÃO: Presidente (não há veto - entendimento). VIGÊNCIA: exercício SEGUINTE (1º jan - 31 dez). ESTADOS/MUNICÍPIOS: CE/LO definem (proporcionais). RACIONALIDADE: LOA enviada fim agosto (Executivo teve base: PPA vigente, LDO aprovada julho). Congresso: 4 meses analisar (mais técnico que LDO, CMO trabalha). Aprovada dezembro, vigora janeiro. CONSEQUÊNCIA ATRASO: se não aprovada 31/12 → duodécimos (execução 1/12 orçamento anterior/mês - jurisprudência). Paralisia administrativa. Pressão aprovar. Histórico: raros atrasos (prejuízo governo/país). IMPORTANTE: prazo APERTADO (4 meses análise). CMO: trabalho intenso (centenas emendas, audiências, relatório). Pressão política (disputas alocação). Aprovação tempestiva = normalidade administrativa.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'loa-lei-orcamentaria-anual', question: 'A LOA conterá Reserva de Contingência destinada a:', options: ['Investimentos planejados', 'Atender passivos contingentes e outros riscos, eventos fiscais imprevistos', 'Apenas pagamento pessoal', 'Somente transferências', 'Não é permitida reserva'], correctAnswer: 1, explanation: 'RESERVA DE CONTINGÊNCIA (LRF art. 5º-III): dotação GLOBAL, NÃO específica a órgão/programa. FINALIDADE: atender PASSIVOS CONTINGENTES, outros RISCOS, eventos FISCAIS IMPREVISTOS. MONTANTE: LDO define (% RCL). Forma utilização. RELAÇÃO: Anexo RISCOS FISCAIS (LDO) → Reserva Contingência (LOA). Prudência. UTILIZAÇÃO: mediante CRÉDITOS ADICIONAIS (suplementares/especiais). Fonte: anulação reserva. EVENTOS: demandas judiciais materializadas (precatórios não previstos), calamidades (enchentes, secas), frustração receita além contingenciamento. NÃO pode: usar para despesas regulares, investimentos planejados. CONTROLE: TCU/TCE fiscalizam utilização (se compatível finalidade). DIFERENÇA: Reserva ≠ contingenciamento. Reserva = dotação prevista LOA, uso excepcional. Contingenciamento = bloqueio temporário dotações (ajuste receita). IMPORTANTE: instrumento RESPONSABILIDADE fiscal. Evita surpresas sem solução. "Colchão" eventos adversos. Boa prática gestão fiscal. Quanto maior risco fiscal (Anexo Riscos) → maior reserva prudente.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'loa-lei-orcamentaria-anual', question: 'É vedado consignar na LOA:', options: ['Investimentos prioritários', 'Crédito com finalidade imprecisa ou dotação ilimitada', 'Despesas de pessoal', 'Transferências constitucionais', 'Serviço da dívida'], correctAnswer: 1, explanation: 'VEDAÇÕES LOA (CF art. 167-VII, Lei 4.320 art. 5º, 7º): NÃO pode incluir: 1) CRÉDITO ILIMITADO (art. 167-VII): dotação sem limite valor. Contraria princípio ESPECIFICAÇÃO (quantificar). 2) FINALIDADE IMPRECISA (art. 5º Lei 4.320): dotação sem especificar finalidade. Genérica. Contraria princípio ESPECIFICAÇÃO/DISCRIMINAÇÃO. Exemplo vedado: "Despesas Diversas" sem detalhar. 3) "VERBAS SECRETAS": sem justificativa, controle. Exceção histórica: Inteligência (limitada, fiscalização CMO). OBJETIVO: TRANSPARÊNCIA, CONTROLE. Orçamento deve ser ESPECÍFICO (detalhar receitas/despesas - origem, categoria, programa). PRINCÍPIO ESPECIFICAÇÃO/DISCRIMINAÇÃO: receitas/despesas devem aparecer DISCRIMINADAS (evitar consolidações excessivas que escondam finalidade). CONSEQUÊNCIA: Legislativo/sociedade precisam entender ONDE vai cada real. Fiscalização efetiva. EXEMPLO ATUAL: dotações detalhadas por programa, ação, elemento despesa, fonte recursos. Grau detalhamento (Lei 4.320: elementos despesa). IMPORTANTE: transparência = democracia. Orçamento não pode ser "caixa preta". Vedação crédito ilimitado/impreciso = controle efetivo.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'loa-lei-orcamentaria-anual', question: 'A compatibilidade entre PPA, LDO e LOA significa que:', options: ['São documentos independentes', 'LOA deve estar em consonância com LDO, que deve estar compatível com PPA (hierarquia)', 'Apenas LOA é obrigatória', 'Não há relação entre eles', 'PPA substitui LOA'], correctAnswer: 1, explanation: 'COMPATIBILIDADE/HIERARQUIA (CF art. 165, 166 § 3º-I, 167-I): sistema orçamentário INTEGRADO. HIERARQUIA: 1) PPA (topo): estratégico 4 anos. Diretrizes, objetivos, metas. Base: tudo. 2) LDO (meio): tático anual. Prioridades dentre PPA, orientação LOA. COMPATÍVEL PPA. 3) LOA (base): operacional anual. Execução. COMPATÍVEL LDO (que é compatível PPA). CONSEQUÊNCIA: a) LDO NÃO pode contrariar PPA (prioridades devem ser programas/ações PPA). b) LOA NÃO pode contrariar LDO (deve seguir orientações, prioridades). c) LOA NÃO pode incluir investimento não previsto PPA (CF 167-I). EMENDAS: parlamentares a LOA devem compatibilidade PPA/LDO (CF 166 § 3º-I). CONTROLE: TCU/TCE verificam compatibilidade. Incompatibilidade = vício formal (pode gerar inconstitucionalidade). RACIONALIDADE: COERÊNCIA planejamento (médio prazo) × execução (anual). Evita "orçamentos autistas" (sem relação estratégia). IMPORTANTE: integração é PRINCÍPIO. Sistema orçamento = PROCESSO contínuo, hierarquizado. PPA pensa frente, LDO escolhe prioridades ano, LOA executa. Harmonia essencial efetividade políticas públicas.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= CRÉDITOS ADICIONAIS (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'creditos-adicionais', question: 'Créditos Adicionais são:', options: ['Apenas receitas extras', 'Autorizações de despesa não computadas ou insuficientemente dotadas na LOA', 'Somente dívidas', 'Apenas investimentos', 'Não existem'], correctAnswer: 1, explanation: 'CRÉDITOS ADICIONAIS (Lei 4.320 art. 40-46): autorizações DESPESA NÃO computadas OU insuficientemente dotadas LOA. NECESSIDADE: LOA aprovada ano anterior (agosto-dezembro N-1), executa ano seguinte (jan-dez N). Imprevistos, insuficiências, urgências. CLASSIFICAÇÃO: 1) SUPLEMENTARES (art. 41-I): reforçar dotação INSUFICIENTE. 2) ESPECIAIS (art. 41-II): despesas NÃO PREVISTAS orçamento. 3) EXTRAORDINÁRIOS (art. 41-III): despesas URGENTES/IMPREVISÍVEIS (guerra, comoção, calamidade). ABERTURA: Suplementares/Especiais = DECRETO (Executivo), baseado AUTORIZAÇÃO lei (LOA ou específica). Extraordinários = MEDIDA PROVISÓRIA (União - CF 167 § 3º) ou decreto (Estados/Municípios). VIGÊNCIA: Suplementares/Especiais: até fim exercício (podem ser reabertos RP se autorizados últimos 4 meses - CF 167 § 2º). Extraordinários: vinculados ao fato. IMPORTANTE: flexibilização orçamento (rígido insuficiente). Mas exige CONTROLE (limite suplementares LOA, fonte indicada, autorização legislativa especiais).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'creditos-adicionais', question: 'Os créditos suplementares destinam-se a:', options: ['Criar nova despesa não prevista', 'Reforçar dotação orçamentária insuficiente', 'Apenas situações de guerra', 'Somente calamidades', 'Não têm finalidade específica'], correctAnswer: 1, explanation: 'CRÉDITOS SUPLEMENTARES (Lei 4.320 art. 41-I, 42): FINALIDADE: REFORÇO dotação INSUFICIENTE. Dotação existe LOA, mas valor pequeno (execução superou, necessita mais). AUTORIZAÇÃO: LOA pode autorizar Executivo abrir suplementares até LIMITE (% despesa, ex: 20%). Acima limite: lei específica. ABERTURA: DECRETO Executivo (fundamentado autorização). FONTE (art. 43): OBRIGATÓRIA indicar recursos. Origens: I) Superávit financeiro exercício anterior (AF-PF). II) Excesso arrecadação (receita > prevista). III) Anulação total/parcial dotações. IV) Operações crédito (respeitada regra ouro - CF 167-III). V) Reserva contingência. PROCEDIMENTO: Executivo edita decreto, especifica dotação reforçada, origem recurso. CONTROLE: TCU/TCE verificam legalidade, existência fonte. IMPORTANTE: créditos + USADOS (reforço comum - previsão imperfeita). Autorização LOA agiliza (não precisa nova lei cada reforço). Limite LOA = controle Legislativo. Acima → precisa aprovar lei. Flexibilidade × controle. Boa prática: LOA autoriza 10-20% suplementação (evita engessamento sem perder controle).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'creditos-adicionais', question: 'Créditos especiais são abertos para:', options: ['Reforçar dotações insuficientes', 'Despesas para as quais não haja dotação orçamentária específica', 'Apenas situações de guerra', 'Somente pessoal', 'Não existem créditos especiais'], correctAnswer: 1, explanation: 'CRÉDITOS ESPECIAIS (Lei 4.320 art. 41-II, 42): FINALIDADE: despesas para as quais NÃO HÁ dotação orçamentária ESPECÍFICA. Despesa NOVA (não prevista LOA). AUTORIZAÇÃO: LEI ESPECÍFICA (não pode ser genérica LOA como suplementares). Legislativo aprova. ABERTURA: DECRETO Executivo (após lei autorizativa). FONTE: OBRIGATÓRIA (mesmas fontes suplementares - art. 43). VIGÊNCIA: até FIM EXERCÍCIO. Exceção: se autorizados últimos 4 meses exercício, podem reabrir pelo saldo exercício seguinte (CF 167 § 2º - reabertura decreto). EXEMPLOS: novo programa governo (não previsto LOA), despesa imprevista mas não urgente (obra adicional, novo convênio). vs SUPLEMENTAR: especial = despesa NOVA (cria dotação). Suplementar = reforça EXISTENTE. vs EXTRAORDINÁRIO: especial = não urgente/imprevisível (precisa lei). Extraordinário = urgente/imprevisível (MP). IMPORTANTE: exigência LEI = controle Legislativo reforçado. Despesa nova = decisão política (não só ajuste técnico). Processo legislativo completo. Menos ágil que suplementar, mais que lei ordinária despesa.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'creditos-adicionais', question: 'Créditos extraordinários são utilizados para:', options: ['Qualquer despesa não prevista', 'Despesas urgentes e imprevisíveis, como guerra, comoção interna ou calamidade pública', 'Apenas reforçar dotações', 'Somente investimentos', 'Despesas de pessoal'], correctAnswer: 1, explanation: 'CRÉDITOS EXTRAORDINÁRIOS (Lei 4.320 art. 41-III, 44; CF art. 167 § 3º): FINALIDADE: despesas URGENTES e IMPREVISÍVEIS. HIPÓTESES (art. 167 § 3º): GUERRA, COMOÇÃO INTERNA, CALAMIDADE PÚBLICA. ABERTURA: MEDIDA PROVISÓRIA (União - CF 167 § 3º). Estados/Municípios: decreto, submetendo Legislativo (CE/LO). TRAMITAÇÃO: urgência. FONTE: NÃO exige indicação (exceção art. 43 - urgência, imprevisibilidade). Pode gerar déficit. VIGÊNCIA: tempo necessário atender despesa (vinculado evento). Pode ultrapassar exercício (diferente outros). CONTROLE POSTERIOR: Legislativo aprecia (converte lei ou não). TC fiscaliza. EXEMPLOS: Covid-19 (calamidade pública - Dec. Leg. 6/2020), enchentes, guerras. POLÊMICA: uso indevido (despesas não urgentes/imprevisíveis). STF: controle restrito (conceito indeterminado, discricionariedade). IMPORTANTE: excepcionalíssimo. Emergências genuínas. Fonte não exigida = risco fiscal. Controle posterior essencial. Abuso = crime responsabilidade. Calamidade pública: reconhecida Legislativo (decreto legislativo).', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'creditos-adicionais', question: 'A indicação de fonte de recursos é obrigatória para:', options: ['Todos os créditos adicionais sem exceção', 'Créditos suplementares e especiais, mas dispensada para extraordinários', 'Apenas créditos suplementares', 'Apenas créditos especiais', 'Não é obrigatória para nenhum'], correctAnswer: 1, explanation: 'FONTE RECURSOS CRÉDITOS ADICIONAIS (Lei 4.320 art. 43): REGRA: OBRIGATÓRIA indicar recursos para abertura créditos suplementares/especiais. FONTES (art. 43-I a III): 1) Superávit financeiro: saldo positivo financeiro (ativo financeiro - passivo financeiro) exercício anterior. Apurado por fonte recursos (vinculações). 2) Excesso arrecadação: saldo positivo diferença receita realizada - prevista, considerado tendência exercício. 3) Anulação dotações: total/parcial. NÃO pode anular: pessoal/encargos, serviço dívida, transferências constitucionais/legais. Autorização legislativa (especiais) ou LOA (suplementares). 4) Operações crédito: empréstimos (observar regra ouro CF 167-III). 5) Reserva contingência: dotação global LOA. CRÉDITOS EXTRAORDINÁRIOS: DISPENSADA indicação (CF 167 § 3º). Urgência/imprevisibilidade. Podem gerar déficit. CONTROLE: TC verifica regularidade fontes (existência, disponibilidade, vinculação). IMPORTANTE: indicação fonte = responsabilidade fiscal. Vedado criar despesa sem receita (equilíbrio). Extraordinários: exceção justificada urgência. Abuso extraordinários (fonte) = irresponsabilidade fiscal.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= CLASSIFICAÇÃO ORÇAMENTÁRIA (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'classificacao-orcamentaria', question: 'A classificação institucional da despesa identifica:', options: ['Apenas funções de governo', 'O órgão e a unidade orçamentária responsável pela despesa', 'Somente categorias econômicas', 'Apenas programas', 'Não há classificação institucional'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO INSTITUCIONAL (Portaria SOF/STN): responde "QUEM" faz despesa. NÍVEIS: 1) ÓRGÃO ORÇAMENTÁRIO: maior nível agregação (Ministério, Secretaria Estado). Ex: 25000 - Ministério Economia. 2) UNIDADE ORÇAMENTÁRIA: menor nível (dentro órgão). Ex: 25101 - STN (dentro ME). ESTRUTURA: 5 dígitos (2 órgão + 3 unidade). OBJETIVO: identificar RESPONSÁVEL execução (accountability). INDEPENDE: função, programa, categoria econômica. EXEMPLO: 25101 - STN pode ter despesas função legislativa (transferências CN), administrativa (custeio próprio), investimentos. ORÇAMENTO FISCAL: cada Poder (Executivo, Legislativo, Judiciário, MP, Defensoria) desdobra órgãos/unidades. CONSOLIDAÇÃO: LOA consolida todos órgãos/unidades (visão total, mas permite desagregação por responsável). IMPORTANTE: classificação permite: controle por gestor, avaliação desempenho setorial, transparência (site: despesa por órgão). vs Programática (o quê), Funcional (área), Econômica (natureza).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'classificacao-orcamentaria', question: 'A classificação funcional responde:', options: ['Quem faz a despesa', 'Em que área de atuação governamental a despesa será realizada', 'Apenas natureza da despesa', 'Somente fonte de recursos', 'Não existe'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO FUNCIONAL (Portaria 42/99 atualizada): responde "EM QUE área governo atua". NÍVEIS: 1) FUNÇÃO: maior agregação ações governo por ÁREA. Ex: 10-Saúde, 12-Educação, 06-Segurança Pública, 04-Administração. Total: 28 funções. 2) SUBFUNÇÃO: partição função (detalhamento). Ex: função 12-Educação: subfunções 361-Ensino Fundamental, 362-Ensino Médio, 365-Educação Infantil. ESTRUTURA: XX.XXX (função.subfunção). TRANSVERSALIDADE: função típica órgão (Saúde-MS), mas outros podem atuar (Defesa hospitais militares = função saúde). Subfunção pode combinar funções diferentes. AGREGADOR: funções somam áreas independente quem executa (total gasto saúde = todos órgãos função saúde). FIXAS: Portaria 42/99 (União/Estados/Municípios - padronização, comparação). NÃO confundir: função administrativa (custeio órgão) × finalística (entrega serviço). IMPORTANTE: classificação permite: análise políticas públicas (quanto governo gasta educação, saúde), comparação temporal/entes, transparência. vs Institucional (quem), Programática (programa), Econômica (natureza).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'classificacao-orcamentaria', question: 'A classificação por natureza da despesa compreende:', options: ['Apenas órgãos', 'Categoria econômica, grupo de natureza, modalidade de aplicação, elemento de despesa', 'Somente funções', 'Apenas programas', 'Não existe'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO NATUREZA DESPESA (Portaria Interministerial 163/01 atualizada): responde "QUAL natureza" gasto. ESTRUTURA: C.G.MM.EE.DD (8 dígitos): 1) C - CATEGORIA ECONÔMICA (1 dígito): 3-Correntes, 4-Capital. 2) G - GRUPO NATUREZA (1): desdobra categoria. Correntes: 1-Pessoal, 2-Juros, 3-Outras. Capital: 4-Investimentos, 5-Inversões, 6-Amortização. 3) MM - MODALIDADE APLICAÇÃO (2): forma execução. 20-Transferências União, 30-Exec.Orçamentária Delegada, 40-Transf.Multigovernamental, 50-Transf.Inst.Privada, 90-Aplicações Diretas, 91-Apl.Dir.Dec.Oper.Entre Órgãos. 4) EE - ELEMENTO DESPESA (2): objeto gasto. Ex: 11-Vencimentos, 30-Material Consumo, 51-Obras, 92-Despesas Exercícios Anteriores. 5) DD - DESDOBRAMENTO (2): detalhamento (opcional ente). OBJETIVO: classificação ECONÔMICA (impacto contas nacionais), CONTROLE (vedações - Lei 4.320), TRANSPARÊNCIA. IMPORTANTE: natureza × função: natureza = como gasta (insumo). Função = onde atua (finalidade). Exemplo: 3.3.90.30 = Corrente, Outras, Aplicação Direta, Material Consumo.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'classificacao-orcamentaria', question: 'A classificação por fonte/destinação de recursos indica:', options: ['Apenas órgãos responsáveis', 'A origem e destinação (vinculação) dos recursos', 'Somente categorias econômicas', 'Apenas programas', 'Não existe'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO FONTE RECURSOS (Portaria STN): responde "DE ONDE vem" recursos, "PARA QUE vinculados". ESTRUTURA: geralmente 4 dígitos (varia ente). ELEMENTOS: 1) GRUPO: origem recursos (1-Recursos Próprios Não Vinculados, 2-Rec.Vinculados Impostos, 3-Rec.Vinculados Contribuições, etc). 2) ESPECIFICAÇÃO: detalhamento vinculação. Ex: 112-Educação, 150-Saúde, 169-Transferências SUS. IMPORTÂNCIA: 1) CONTROLE vinculações (CF 198/212 - saúde, educação). 2) Superávit financeiro POR FONTE (fonte vinculada só financia mesma vinculação). 3) Transparência aplicação recursos carimbados. EXEMPLO: 0150 - Recursos Saúde. Despesas só podem ser saúde. Superávit fonte 0150 → crédito adicional só saúde. CRÉDITOS ADICIONAIS: fonte recursos deve compatibilizar (anular dotação fonte X, abrir fonte X; superávit fonte Y, usar fonte Y). IMPORTANTE: Brasil forte vinculação receitas (exceções não-afetação). Gestão complexa (fragmentação fontes). Controle fonte essencial responsabilidade fiscal. STN padroniza fontes (comparabilidade). Alguns entes: + 100 fontes.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'classificacao-orcamentaria', question: 'A classificação programática identifica:', options: ['Apenas órgãos', 'Programas e ações governamentais', 'Somente categorias econômicas', 'Apenas funções', 'Não existe'], correctAnswer: 1, explanation: 'CLASSIFICAÇÃO PROGRAMÁTICA (Portaria 42/99, PPA): responde "O QUÊ" governo faz (entregas, realizações). NÍVEIS: 1) PROGRAMA: articula ações para enfrentar problema, atender demanda sociedade. Ex: Programa "Saúde da Família", "Bolsa Família". Objetivo, público-alvo, indicadores. 4 dígitos. 2) AÇÃO: operacionaliza programa. TIPOS: a) PROJETO: tempo limitado, gera produto (construir escola - 1234). b) ATIVIDADE: contínua, manutenção (atendimento UBS - 2000). c) OPERAÇÃO ESPECIAL: não gera produto (transferências, dívida - 0001 a 0999). 4 dígitos (letra inicial indica tipo: 1/3/5/7=projeto, 2/4/6/8=atividade, 0=op.especial). LOCALIZADOR: identifica beneficiário, local (0001=Nacional, UF, município). ESTRUTURA LOA: despesa classificada: órgão.unidade.função.subfunção.programa.ação.localizador. OBJETIVO: orçamento PROGRAMA (não só natureza despesa). Vincula recurso RESULTADO. PPA base. IMPORTANTE: evolução orçamento Brasil. Antes: incremental (base ano anterior). Hoje: baseado programas/resultados. Transparência: cidadão vê programas, não só rubricas. Avaliação desempenho. vs natureza: programática = finalidade. Natureza = insumo.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ============= EXECUÇÃO ORÇAMENTÁRIA (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'execucao-orcamentaria', question: 'A execução da receita orçamentária compreende os estágios:', options: ['Fixação, Empenho e Pagamento', 'Previsão, Lançamento, Arrecadação e Recolhimento', 'Apenas Arrecadação', 'Somente Previsão', 'Não há estágios'], correctAnswer: 1, explanation: 'ESTÁGIOS RECEITA ORÇAMENTÁRIA: 1) PREVISÃO: estimativa LOA (planejamento, não execução). Base: série histórica, projeções PIB/inflação, legislação. Responsável: RFB (tributos federais), Sec.Fazenda (Estados/Municípios). 2) LANÇAMENTO: procedimento IDENTIFICAR contribuinte, FATO GERADOR, CALCULAR montante, NOTIFICAR. Art. 142 CTN. Nem toda receita tem (ICMS não; IPTU sim). Tributos diretos, dívida ativa. 3) ARRECADAÇÃO: RECEBIMENTO recursos contribuinte a AGENTES ARRECADADORES (bancos, lotéricas). Momento: disponibilidade JURÍDICA (direito). Transferência posse dinheiro (contribuinte → agente). 4) RECOLHIMENTO: agente arrecadador TRANSFERE recursos CONTA ÚNICA Tesouro. Momento: disponibilidade FINANCEIRA (caixa Tesouro). Centralização recursos (princípio unidade caixa). RECONHECIMENTO CONTÁBIL: regime COMPETÊNCIA (quando direito nasce - pode ser lançamento ou fato gerador). IMPORTANTE: arrecadação × recolhimento: diferença temporal (banco recebe hoje, transfere Tesouro D+1). Unidade Caixa: centralizar controle, rendimentos.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'execucao-orcamentaria', question: 'A execução da despesa orçamentária compreende os estágios:', options: ['Previsão, Arrecadação e Recolhimento', 'Empenho, Liquidação e Pagamento', 'Apenas Empenho', 'Somente Pagamento', 'Não há estágios'], correctAnswer: 1, explanation: 'ESTÁGIOS DESPESA ORÇAMENTÁRIA (Lei 4.320 art. 58-70): 1) EMPENHO (art. 58-61): ATO autoridade competente que CRIA OBRIGAÇÃO pagamento, RESERVA dotação. Nota Empenho (NE). Tipos: ordinário (único), estimativo (estimado), global (parcelado). Primeiro estágio, ANTES despesa realizar. 2) LIQUIDAÇÃO (art. 63): VERIFICAÇÃO direito CREDOR mediante: títulos/documentos comprobatórios, exatidão material/formal (conferência entrega bem/serviço), importância pagar. Atesto. Reconhece despesa orçamentária EXECUTADA. 3) PAGAMENTO (art. 64-70): ENTREGA numerário credor, EXTINÇÃO obrigação. Ordem bancária. Ordem cronológica (art. 5º Lei 8.666 - fila credores). Conta Única. FIXAÇÃO: planejamento LOA (não execução). IMPORTANTE: sequência obrigatória. Exceção: suprimento fundos (adiantamento). Empenho: reserva crédito (compromisso). Liquidação: reconhece despesa (competência). Pagamento: regime caixa. Cada estágio: responsável, documentação, controles. Base: transparência, controle, responsabilização.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'execucao-orcamentaria', question: 'O empenho da despesa:', options: ['Só pode ocorrer após o pagamento', 'Cria obrigação de pagamento pendente e reserva dotação orçamentária', 'Não é obrigatório', 'Ocorre após liquidação', 'Não possui documento'], correctAnswer: 1, explanation: 'EMPENHO (Lei 4.320 art. 58-61): ATO emanado autoridade competente que CRIA OBRIGAÇÃO pagamento PENDENTE (condicionada liquidação) e RESERVA dotação. CARACTERÍSTICAS: 1) PRIMEIRO estágio (antes despesa). 2) VINCULA crédito (indisponibiliza para outro fim). 3) DOCUMENTO: Nota Empenho (NE). Conteúdo: nome credor, especificação, importância, dedução saldo dotação. 4) VALIDADE: até 31/12 (anual). Cancelamento ou Restos Pagar. TIPOS (art. 60): a) ORDINÁRIO: quantia CERTA, pagamento UMA VEZ. Ex: compra equipamento 50k. b) ESTIMATIVO: quantia ESTIMADA. Ex: água/luz (consumo variável). Reforço/anulação parcial conforme. c) GLOBAL: PARCELADO. Ex: aluguel 12x 10k (empenho global 120k, liquidação/pag mensal). VEDAÇÕES: empenhar sem saldo dotação, sem licitação/dispensa/inexigibilidade (quando exigível). IMPORTANTE: empenho NÃO é despesa orçamentária EXECUTADA (é compromisso). Execução = liquidação. Patrimonial: pode reconhecer antes (competência). Controle: sistema informatizado, SIAFI (União).', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'execucao-orcamentaria', question: 'Programação financeira (cronograma de desembolso) visa:', options: ['Aumentar despesas livremente', 'Assegurar recursos financeiros às unidades orçamentárias de acordo com a execução e metas fiscais', 'Apenas controlar receitas', 'Não tem finalidade', 'Somente pagar fornecedores'], correctAnswer: 1, explanation: 'PROGRAMAÇÃO FINANCEIRA (LRF art. 8º, Dec. 93.872/86): CRONOGRAMA desembolso mensal (fluxo caixa governo). OBJETIVO: compatibilizar EXECUÇÃO orçamentária × disponibilidade FINANCEIRA (caixa). Evitar déficit caixa, atrasos pagamentos. ELABORAÇÃO: até 30 DIAS após LOA (LRF 8º). Executivo (STN/SOF - União). Base: previsão receitas mês a mês, cronograma despesas, metas resultado (LRF). COTAS/REPASSES: libera recursos órgãos setoriais conforme programação. AJUSTES: bimestral (junto RREO). Receita menor → reduz cotas (contingenciamento). Normaliza → restabelece. CONTA ÚNICA: centraliza recursos (Tesouro), libera conforme programação. OBJETIVO LRF: compatibilizar receita REALIZADA (não prevista) × execução despesa. Garantir cumprimento METAS RESULTADO FISCAL. IMPORTANTE: antes: orçamento aprovado → gastar tudo (déficit caixa, atrasados). LRF: programação ativa, gestão caixa, ajustes. Ferramenta essencial responsabilidade fiscal. Evita restos pagar sem caixa, fornecedores esperando meses. Transparência: cronogramas públicos.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'execucao-orcamentaria', question: 'Se verificado que a realização de receita pode não comportar o cumprimento das metas de resultado (LRF art. 9º):', options: ['Nada precisa ser feito', 'Poderes deverão limitar empenho e movimentação financeira proporcionalmente', 'Apenas Executivo contingencia', 'Somente Legislativo toma medidas', 'Aumenta-se a dívida livremente'], correctAnswer: 1, explanation: 'CONTINGENCIAMENTO - LIMITAÇÃO EMPENHO (LRF art. 9º): se BIMESTRE verificar receita PODE NÃO comportar cumprimento METAS RESULTADO (primário/nominal - Anexo Metas Fiscais LDO), LIMITAÇÃO obrigatória. RESPONSÁVEIS: EXECUTIVO, LEGISLATIVO, JUDICIÁRIO, MP, Defensoria (CADA Poder limita seu orçamento). PROPORÇÃO: montante necessário compatibilizar EXECUÇÃO × META. LDO define CRITÉRIOS rateio (geralmente proporção dotações discricionárias cada Poder). EXCEÇÕES: NÃO limitam obrigações constitucionais/legais (pessoal, serviço dívida, transferências constitucionais, benefícios previdenciários). Emendas impositivas: limitação parcial (metade - EC 126/22). RESTABELECIMENTO: se receita NORMALIZAR (arrecadação melhora), 30 DIAS restabelecer dotações (art. 9º § 1º). TRANSPARÊNCIA: RREO (bimestral) demonstra receita prevista × realizada, necessidade limitação, montante limitado. OBJETIVO: GARANTIR meta fiscal aprovada LDO. Ajuste DURANTE exercício (não ex-post). IMPORTANTE: mecanismo central LRF. Impopular (corta investimentos, programas), mas responsabilidade fiscal. Alternativa: déficit, descontrole dívida. Exige disciplina política.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= CONTROLE E FISCALIZAÇÃO (5) =============
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'controle-e-fiscalizacao', question: 'O controle externo no Brasil é exercido por:', options: ['Apenas CGU', 'Poder Legislativo com auxílio dos Tribunais de Contas', 'Somente Executivo', 'Apenas Judiciário', 'Não há controle externo'], correctAnswer: 1, explanation: 'CONTROLE EXTERNO (CF art. 70-75): fiscalização contábil, financeira, orçamentária, operacional, patrimonial (legalidade, legitimidade, economicidade). TITULARIDADE: CONGRESSO NACIONAL (União), Assembleias Legislativas (Estados), Câmaras Municipais. AUXÍLIO: TRIBUNAIS DE CONTAS (TCU, TCE, TCM-SP/RJ). TC = órgão TÉCNICO auxiliar. COMPETÊNCIAS TC (CF 71): 1) APRECIAR contas Chefe Executivo (parecer prévio → Legislativo julga). 2) JULGAR contas administradores, ordenadores despesa. 3) APRECIAR legalidade atos admissão pessoal, aposentadorias, pensões. 4) FISCALIZAR aplicação recursos (auditorias, inspeções). 5) FISCALIZAR contas empresas estatais. 6) FISCALIZAR renúncia receitas. 7) APLICAR sanções (multa, inabilitação). 8) SUSTAR atos/contratos ilegais. 9) REPRESENTAR irregularidades (MP, Legislativo). NATUREZA: TC NÃO subordinado Legislativo (auxilia, independência técnica). DECISÕES: executórias (força título executivo). IMPORTANTE: modelo brasileiro híbrido (tribunal técnico + Legislativo político). vs Controle INTERNO: cada Poder (CGU - Executivo Federal). Complementares.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'controle-e-fiscalizacao', question: 'Cada Poder manterá sistema de controle interno com finalidades de:', options: ['Apenas contratar pessoal', 'Avaliar cumprimento de metas, comprovar legalidade, avaliar resultados, apoiar controle externo', 'Somente fazer auditorias externas', 'Apenas julgar contas', 'Não há obrigação'], correctAnswer: 1, explanation: 'CONTROLE INTERNO (CF art. 74): CADA Poder manterá sistema INTEGRADO. FINALIDADES: 1) AVALIAR cumprimento METAS PPA, execução programas governo, orçamentos. 2) COMPROVAR LEGALIDADE, avaliar resultados (eficácia, eficiência) gestão orçamentária/financeira/patrimonial, aplicação recursos. 3) EXERCER controle operações crédito, avais, garantias, direitos/haveres. 4) APOIAR controle EXTERNO (subsidiar TC/Legislativo). RESPONSÁVEIS: União: CGU (Executivo), cada Poder próprio sistema. Estados/Municípios: Controladorias, Secretarias Controle. ATUAÇÃO: auditorias internas, inspeções, acompanhamento execução, manifestações legalidade, certificados contas (chefes Executivo). OBRIGAÇÃO (CF 74 § 1º): responsáveis controle interno, CIÊNCIA irregularidade/ilegalidade, devem dar ciência TC, sob pena responsabilidade solidária. IMPORTANTE: controle interno PREVENTIVO/CONCOMITANTE (durante execução). Externo: posterior (embora também concomitante). Interno prepara contas, orienta gestores. Qualidade controle interno influencia confiança auditor externo (TC pode reduzir testes se CI efetivo).', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'controle-e-fiscalizacao', question: 'As contas do Presidente da República (União) são:', options: ['Julgadas pelo Congresso Nacional', 'Apreciadas pelo TCU (parecer prévio) e julgadas pelo Congresso Nacional', 'Apenas apreciadas, sem julgamento', 'Julgadas pelo TCU', 'Não prestam contas'], correctAnswer: 1, explanation: 'CONTAS CHEFE EXECUTIVO (CF art. 49-IX, 71-I): PRESTAÇÃO: anual (60 dias abertura sessão legislativa). TRAMITAÇÃO: 1) TCU: APRECIA, emite PARECER PRÉVIO (60 dias recebimento - CF 71-I). Opinião técnica: aprovação/rejeição (com ressalvas ou não). 2) CONGRESSO: JULGA contas (competência exclusiva - CF 49-IX). Decisão política. Pode divergir TCU (raro). Aprovação/rejeição. DOCUMENTOS: balanços União, relatórios execução orçamentária/programas, gestão fiscal, controle interno, outros. NATUREZA: contas GOVERNO (gerais, políticas públicas). Refletem gestão macroeconômica, cumprimento PPA/LDO/LOA. CONSEQUÊNCIA REJEIÇÃO: política (desgaste, impeachment possível), não automática inelegibilidade (precisa outros elementos). vs CONTAS GESTÃO: ordenadores despesa, administradores recursos → TCU JULGA (CF 71-II). Consequência: débito, multa, inabilitação. IMPORTANTE: separação contas governo (Presidente - CN julga) × gestão (administradores - TCU julga). Presidencialismo: Legislativo controla Executivo (checks and balances). Histórico: raras rejeições (maioria governo = maioria Congresso).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'controle-e-fiscalizacao', question: 'O Relatório Resumido de Execução Orçamentária (RREO) deve ser publicado:', options: ['Anualmente', 'Bimestralmente, até 30 dias após o encerramento do bimestre', 'Apenas no final do mandato', 'Não há obrigação', 'Apenas para União'], correctAnswer: 1, explanation: 'RREO - RELATÓRIO RESUMIDO EXECUÇÃO ORÇAMENTÁRIA (LRF art. 52-53): PERIODICIDADE: BIMESTRAL (jan-fev, mar-abr, mai-jun, jul-ago, set-out, nov-dez). PRAZO: até 30 DIAS após encerramento bimestre. RESPONSÁVEL: Executivo (todos entes). ABRANGÊNCIA: todos Poderes/órgãos (consolidado). CONTEÚDO: 1) Balanço orçamentário (receitas/despesas por categoria). 2) Demonstrativos execução: receitas, despesas, Restos Pagar. 3) Último bimestre: projeções cumprimento meta resultado (primário/nominal), receitas/despesas capital (regra ouro). ANEXOS: receita corrente líquida, receitas/despesas previdência, resultado primário/nominal, restos pagar, outros. PUBLICAÇÃO: até 30 dias, amplo acesso (internet - Portal Transparência). FISCALIZAÇÃO: TC, Legislativo, MP, cidadãos. OBJETIVO: acompanhamento execução orçamentária DURANTE exercício (não só fim ano). Base decisões (contingenciamento LRF 9º, análise desvios). vs RGF (quadrimestral): RREO = orçamentário. RGF = limites LRF (pessoal, dívida). IMPORTANTE: transparência LRF. Bimestral = atualização frequente. Permite intervenção tempestiva (frustra receita → contingenciar). Essencial controle social/institucional.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'orcamento-publico', topic: 'controle-e-fiscalizacao', question: 'O Relatório de Gestão Fiscal (RGF) deve ser publicado:', options: ['Anualmente', 'Quadrimestralmente (ou semestralmente para Municípios < 50 mil hab)', 'Mensalmente', 'Apenas no final do mandato', 'Não é obrigatório'], correctAnswer: 1, explanation: 'RGF - RELATÓRIO GESTÃO FISCAL (LRF art. 54-55): PERIODICIDADE: QUADRIMESTRAL (jan-abr, mai-ago, set-dez). Municípios < 50 mil hab: SEMESTRAL (opção). PRAZO: até 30 DIAS após período. RESPONSÁVEL: CADA Poder/órgão (Executivo, Legislativo, Judiciário, MP, Defensoria) emite PRÓPRIO RGF. CONTEÚDO: 1) DESPESA PESSOAL: valor executado, % sobre RCL, comparativo LIMITES (totais, por Poder - LRF 19-20). 2) DÍVIDA CONSOLIDADA: saldo, variação período, comparativo limite (Resolução Senado 40/01). 3) CONCESSÃO GARANTIAS: valores concedidos, limite (LRF 40). 4) OPERAÇÕES CRÉDITO: contratações, saldos, limites (regra ouro, ARO). ASSINATURA: chefe Poder, responsáveis controle interno, contabilidade, outros. PUBLICAÇÃO: amplo acesso público (internet). FISCALIZAÇÃO: TC, Legislativo, MP. OBJETIVO: demonstrar cumprimento LIMITES LRF (pessoal, dívida, garantias). Transparência, accountability. SANÇÕES descumprimento: multa (Lei 10.028/00), inelegibilidade (LC 64/90), vedações LRF (aumento pessoal, operações crédito). IMPORTANTE: vs RREO: RGF = limites/gestão fiscal. RREO = execução orçamentária. Complementares. Publicação essencial LRF.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Orçamento Público questions...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Orçamento Público questions seeded successfully!');
}
