import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL CONTABILIDADE PÚBLICA QUESTIONS =============
export async function seedAllContabilidadePublicaQuestions() {
  console.log('🚀 Starting to seed ALL Contabilidade Pública questions...');
  
  const allQuestions: Question[] = [
    // ============= PRINCÍPIOS DA CONTABILIDADE PÚBLICA (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'principios-contabilidade-publica', question: 'Segundo o MCASP (Manual de Contabilidade Aplicada ao Setor Público), são princípios orçamentários:', options: ['Unidade, Universalidade e Anualidade', 'Apenas Legalidade e Publicidade', 'Somente Economicidade', 'Exclusivamente Moralidade', 'Apenas Eficiência'], correctAnswer: 0, explanation: 'PRINCÍPIOS ORÇAMENTÁRIOS (Constituição + Lei 4.320/64): 1) UNIDADE: orçamento único (consolidado). 2) UNIVERSALIDADE: todas receitas/despesas no orçamento. 3) ANUALIDADE (periodicidade): vigência 1 ano. 4) EXCLUSIVIDADE: só matéria orçamentária. 5) PUBLICIDADE: transparência. 6) EQUILÍBRIO: receitas = despesas. 7) LEGALIDADE: aprovação legislativa. 8) ESPECIFICAÇÃO (discriminação): detalhar receitas/despesas. 9) NÃO-AFETAÇÃO: receitas não vinculadas (exceto CF). MCASP: NBC TSP + IPSAS. Base: regime competência patrimonial. IMPORTANTE: distinguir princípios orçamentários × contábeis × administrativos.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'principios-contabilidade-publica', question: 'O regime contábil adotado pela Contabilidade Pública, conforme MCASP, é:', options: ['Regime de Caixa para receitas e despesas', 'Regime de Competência Patrimonial (integral)', 'Regime Misto: Caixa (receitas) e Competência (despesas)', 'Regime de Caixa apenas', 'Não há regime definido'], correctAnswer: 1, explanation: 'REGIME CONTÁBIL PÚBLICO (MCASP 9ª ed.): COMPETÊNCIA PATRIMONIAL (integral): receitas E despesas reconhecidas no fato gerador. MUDANÇA: antes era MISTO (caixa receitas, competência despesas - Lei 4.320/64 art. 35). CONVERGÊNCIA IPSAS: NBC TSP adota competência PLENA. ORÇAMENTÁRIO: ainda regime misto (arrecadação/empenho). PATRIMONIAL: competência. EXEMPLO: serviço prestado dez → receita dez (competência), mesmo arrecade jan. IMPORTANTE: distinguir REGIME ORÇAMENTÁRIO (misto) × CONTÁBIL (competência). DCASP (Demonstrações): competência. RREO/RGF: orçamentário.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'principios-contabilidade-publica', question: 'O Princípio Orçamentário da Exclusividade estabelece que:', options: ['Orçamento deve conter apenas matéria orçamentária, vedando "caudas orçamentárias"', 'Todas as receitas devem estar no orçamento', 'Vigência de um ano', 'Orçamento deve ser único', 'Deve haver publicidade'], correctAnswer: 0, explanation: 'EXCLUSIVIDADE (CF art. 165 § 8º): Lei Orçamentária NÃO conterá dispositivo estranho a: previsão receita, fixação despesa. EXCEÇÕES: autorização créditos suplementares, operações de crédito (ARO). OBJETIVO: evitar "CAUDAS/RABILONGOS ORÇAMENTÁRIOS" (matérias estranhas aproveitando processo). EXEMPLO VEDADO: mudança legislação tributária, criação cargos na LOA. PERMITIDO: autorizar suplementação até %, contratar operações crédito. HISTÓRICO: antes era comum incluir assuntos diversos. PÓS-CF88: proibido. IMPORTANTE: proteção processo legislativo orçamentário, foco técnico.', difficulty: 'medium', examBoard: 'FGV', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'principios-contabilidade-publica', question: 'Sobre o Princípio da Não-Afetação (ou Não-Vinculação) de Receitas, é INCORRETO afirmar:', options: ['Veda vinculação de impostos a órgão, fundo ou despesa', 'Não há exceções constitucionais', 'Permite repartição tributária (FPE, FPM)', 'Exceção: saúde, educação, FUNDEB', 'Exceção: garantia operações de crédito'], correctAnswer: 1, explanation: 'NÃO-AFETAÇÃO (CF art. 167-IV): regra: vedada vinculação IMPOSTOS a órgão/fundo/despesa. OBJETIVO: flexibilidade alocação recursos. EXCEÇÕES CF: 1) Repartição tributária (FPE, FPM, Estados). 2) Saúde (15% mínimo). 3) Educação (18%/25% mínimo). 4) FUNDEB. 5) Administração tributária. 6) Garantia/contragarantia União, dívida externa. 7) Prestação garantias operações crédito ARO. IMPORTANTE: só IMPOSTOS (não taxas, contribuições). INCORRETA: alternativa B (HÁ exceções). Princípio visa evitar engessamento orçamentário. TAXAS: naturalmente vinculadas (contraprestação).', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'principios-contabilidade-publica', question: 'O Princípio da Universalidade determina que:', options: ['Apenas receitas correntes integrem o orçamento', 'Todas as receitas e despesas devem constar no orçamento', 'Somente despesas de capital sejam incluídas', 'Orçamento vigore por dois anos', 'Apenas receitas tributárias constem'], correctAnswer: 1, explanation: 'UNIVERSALIDADE (Lei 4.320 art. 2º): LOA conterá TODAS receitas e TODAS despesas. OBJETIVO: visão completa finanças públicas, controle total. ALCANCE: receitas correntes + capital; despesas correntes + capital; operações especiais. INCLUI: convênios, transferências, vinculadas. BRUTO: valores brutos (não líquidos). PROIBIDO: receitas/despesas "extra-orçamento". TRANSPARÊNCIA: sociedade conhece total movimentação. vs UNIDADE: orçamento único (forma). UNIVERSALIDADE: conteúdo completo. EXCEÇÃO APARENTE: fundos (consolidados). IMPORTANTE: base controle, fiscalização TCU/TCE, transparência fiscal.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ============= RECEITA PÚBLICA (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'receita-publica', question: 'Quanto à categoria econômica, as receitas públicas classificam-se em:', options: ['Correntes e de Capital', 'Ordinárias e Extraordinárias', 'Tributárias e Não-Tributárias', 'Apenas Correntes', 'Próprias e Transferidas'], correctAnswer: 0, explanation: 'CATEGORIA ECONÔMICA (Lei 4.320 art. 11): 1) RECEITAS CORRENTES: não alteram patrimônio líquido duradouramente. Subfontes: tributária, contribuições, patrimonial, agropecuária, industrial, serviços, transferências correntes, outras. 2) RECEITAS DE CAPITAL: alteram patrimônio líquido (reduzem ativo/aumentam passivo). Subfontes: operações crédito, alienação bens, amortização empréstimos, transferências capital, outras. CLASSIFICAÇÃO: 1.x.x.x (corrente), 2.x.x.x (capital). IMPORTANTE: receita corrente → despesa corrente (custeio). Capital → investimentos. EXCEÇÃO: superávit financeiro (capital, mas não ingresso novo).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'receita-publica', question: 'Os estágios da Receita Pública, segundo a Lei 4.320/64, são:', options: ['Fixação, Empenho e Pagamento', 'Previsão, Lançamento, Arrecadação e Recolhimento', 'Apenas Arrecadação', 'Liquidação e Pagamento', 'Somente Previsão'], correctAnswer: 1, explanation: 'ESTÁGIOS RECEITA PÚBLICA: 1) PREVISÃO: estimativa LOA (não é estágio realização, é planejamento). 2) LANÇAMENTO: identificação devedor, valor, vencimento (tributos diretos, dívida ativa). NEM TODA receita tem (ex: ICMS). 3) ARRECADAÇÃO: contribuinte paga agente arrecadador (banco). 4) RECOLHIMENTO: agente transfere para conta única Tesouro. MOMENTO INGRESSO: arrecadação (disponibilidade jurídica). CONTÁBIL: reconhecimento pode ser antes (VPD - competência). DESPESA: fixação, empenho, liquidação, pagamento. ATENÇÃO: PREVISÃO não é obrigatória ocorrer (estimativa); demais são execução.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'receita-publica', question: 'São receitas de capital:', options: ['Receitas Tributárias e de Contribuições', 'Operações de Crédito, Alienação de Bens e Amortização de Empréstimos', 'Receita Patrimonial e de Serviços', 'Apenas Transferências Correntes', 'Somente Receita Agropecuária'], correctAnswer: 1, explanation: 'RECEITAS DE CAPITAL (código 2.x.x.x): 1) OPERAÇÕES DE CRÉDITO: empréstimos, financiamentos (aumenta passivo). 2) ALIENAÇÃO DE BENS: venda imóveis, móveis (reduz ativo permanente). 3) AMORTIZAÇÃO EMPRÉSTIMOS: recebimento principal emprestado (reduz ativo). 4) TRANSFERÊNCIAS DE CAPITAL: convênios investimentos, auxílios. 5) OUTRAS: integralização capital, doações, etc. CARACTERÍSTICA: modificam patrimônio líquido (não sustentáveis). vs CORRENTES: operação contínua, sustentável. APLICAÇÃO: receitas capital → despesas capital (regra ouro CF 167-III). EXCEÇÃO: ARO. IMPORTANTE: superávit financeiro (capital) = saldo exercício anterior.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'receita-publica', question: 'A Dívida Ativa consiste em:', options: ['Créditos da Fazenda Pública vencidos e não pagos', 'Apenas dívidas previdenciárias', 'Somente multas de trânsito', 'Empréstimos contratados pelo ente', 'Receitas correntes em geral'], correctAnswer: 0, explanation: 'DÍVIDA ATIVA (Lei 4.320 art. 39): créditos FAZENDA PÚBLICA, VENCIDOS e NÃO PAGOS. INSCRIÇÃO: ato controle, liquida certeza crédito, permite cobrança executiva. TIPOS: 1) TRIBUTÁRIA: impostos, taxas, contribuições, multas tributárias. 2) NÃO-TRIBUTÁRIA: aluguéis, foros, indenizações, multas não-tributárias. NATUREZA RECEITA: receita corrente (origem tributária/não-trib). CONTABILIZAÇÃO INSCRIÇÃO: D-Ativo (Dívida Ativa) | C-Receita (variação patrimonial aumentativa). AJUSTE: Provisão Perdas (redutora). COBRANÇA: judicial (execução fiscal) ou administrativa. CDA: Certidão Dívida Ativa (título executivo). PRESCRIÇÃO: 5 anos (regra geral).', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'receita-publica', question: 'A regra de ouro, prevista no art. 167, III da Constituição Federal, estabelece que:', options: ['Receitas correntes devem superar despesas correntes', 'É vedado realizar operações de crédito que excedam despesas de capital', 'Todas as receitas devem ser aplicadas em investimentos', 'Operações de crédito são proibidas', 'Não há limite para endividamento'], correctAnswer: 1, explanation: 'REGRA DE OURO (CF art. 167-III): vedado operações crédito > despesas capital. FÓRMULA: Operações Crédito ≤ Despesas Capital. EXCEÇÃO: autorizadas por maioria absoluta Legislativo (créditos suplementares/especiais). OBJETIVO: evitar ENDIVIDAMENTO para CUSTEIO. Dívida só para INVESTIMENTO (geração ativo/benefício futuro). OPERAÇÕES CRÉDITO: empréstimos, financiamentos (não ARO). DESPESAS CAPITAL: investimentos, inversões, amortização dívida. EXEMPLO VEDADO: emprestar para pagar salários. PERMITIDO: emprestar para construir escola. ARO: exceção (até limite). IMPORTANTE: proteção gerações futuras, sustentabilidade fiscal.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= DESPESA PÚBLICA (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'despesa-publica', question: 'Os estágios da Despesa Pública são:', options: ['Previsão, Arrecadação e Recolhimento', 'Fixação, Empenho, Liquidação e Pagamento', 'Apenas Empenho e Pagamento', 'Somente Liquidação', 'Lançamento e Arrecadação'], correctAnswer: 1, explanation: 'ESTÁGIOS DESPESA PÚBLICA (Lei 4.320): 1) FIXAÇÃO: dotação orçamentária LOA (planejamento, não execução). 2) EMPENHO: reserva dotação, cria obrigação (art. 58). Tipos: ordinário, estimativo, global. 3) LIQUIDAÇÃO: verificação direito credor, documento comprobatório (art. 63). 4) PAGAMENTO: entrega recursos ao credor, extinção obrigação (art. 64). Ordem cronológica (art. 5º Lei 8.666). IMPORTANTE: EMPENHO não é despesa contábil (compromisso). LIQUIDAÇÃO: reconhecimento despesa (competência). PAGAMENTO: regime caixa. SEQUÊNCIA obrigatória. EXCEÇÃO: suprimento fundos. Restos a Pagar: empenhado não pago.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'despesa-publica', question: 'Quanto à categoria econômica, as despesas classificam-se em:', options: ['Correntes e de Capital', 'Obrigatórias e Discricionárias', 'Fixas e Variáveis', 'Apenas Correntes', 'Primárias e Financeiras'], correctAnswer: 0, explanation: 'CATEGORIA ECONÔMICA DESPESA (Lei 4.320 art. 12): 1) DESPESAS CORRENTES (3.x): não geram acréscimo patrimônio. Grupos: pessoal, juros, outras correntes. Subgrupos: transferências. 2) DESPESAS DE CAPITAL (4.x): acrescem patrimônio. Grupos: investimentos, inversões financeiras, amortização dívida. CLASSIFICAÇÃO: 3.x.x.x (corrente), 4.x.x.x (capital). CORRENTES: manutenção, funcionamento, custeio. CAPITAL: expansão, melhorias, equipamentos. IMPORTANTE: Investimentos (obras, equipamentos novos). Inversões (aquisição bens usados, imóveis, participações). VINCULAÇÃO: receita corrente → despesa corrente (regra). Capital → capital (regra ouro).', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'despesa-publica', question: 'O empenho da despesa:', options: ['É o pagamento ao fornecedor', 'É o ato que cria obrigação de pagamento e reserva dotação orçamentária', 'Ocorre após o pagamento', 'Não possui documento', 'É opcional'], correctAnswer: 1, explanation: 'EMPENHO (Lei 4.320 art. 58-60): ato autoridade que CRIA OBRIGAÇÃO pagamento e RESERVA DOTAÇÃO. DOCUMENTO: Nota Empenho (NE). MOMENTO: ANTES despesa realizada (exceção: pequenas despesas). EFEITO: vincula crédito, impede uso outro fim. TIPOS: 1) ORDINÁRIO: valor determinado, pagamento único. 2) ESTIMATIVO: valor estimado (água, luz). 3) GLOBAL: parcelado (aluguéis). IMPORTANTE: empenho NÃO é despesa orçamentária executada (é reserva). Despesa ORÇAMENTÁRIA: quando liquida. PATRIMONIAL: pode ser antes (competência). VEDADO: empenho sem crédito/saldo ou sem licitação/contrato. Validade: até 31/12 (anulação ou RP).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'despesa-publica', question: 'A liquidação da despesa consiste em:', options: ['Reservar a dotação orçamentária', 'Verificar o direito adquirido pelo credor através de documentos comprobatórios', 'Efetuar o pagamento', 'Anular o empenho', 'Prever a despesa'], correctAnswer: 1, explanation: 'LIQUIDAÇÃO (Lei 4.320 art. 63): verificação DIREITO ADQUIRIDO CREDOR baseado: 1) Títulos/documentos comprobatórios entrega bem/serviço. 2) Exatidão material/formal (conferência). 3) Importância a pagar. OBJETIVO: atestar que obrigação foi cumprida. DOCUMENTOS: NF, contrato, termo recebimento, medição. MOMENTO: após fornecimento, antes pagamento. EFEITO: reconhece despesa ORÇAMENTÁRIA (executada). CONTÁBIL: regime competência (VPD). RESPONSÁVEL: servidor designado. IMPORTANTE: liquidação atesta origem/objeto gasto. Indispensável pagamento. Se irregular → responsabilização. Base: três elementos (entrega, exatidão, valor). Lei 8.666: atesto.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'despesa-publica', question: 'São despesas de capital:', options: ['Pessoal e Encargos Sociais', 'Investimentos, Inversões Financeiras e Amortização da Dívida', 'Juros e Encargos da Dívida', 'Apenas Outras Despesas Correntes', 'Somente Material de Consumo'], correctAnswer: 1, explanation: 'DESPESAS DE CAPITAL (categoria 4): alteram patrimônio permanente. GRUPOS: 1) INVESTIMENTOS (4.4): planejamento/execução obras, aquisição instalações/equipamentos/material PERMANENTE, softwares. 2) INVERSÕES FINANCEIRAS (4.5): aquisição imóveis/bens capital JÁ USO, participações acionárias, concessão empréstimos. 3) AMORTIZAÇÃO DÍVIDA (4.6): pagamento PRINCIPAL dívidas (não juros). vs CORRENTES: pessoal, juros (encargos), custeio. IMPORTANTE: Investimento → BEM NOVO produção. Inversão → bem usado, ações, empréstimos. Amortização → reduz passivo. CLASSIFICAÇÃO facilita controle aplicação recursos. Receita capital deve financiar (regra ouro).', difficulty: 'easy', examBoard: 'FCC', year: 2024 },

    // ============= LEI DE RESPONSABILIDADE FISCAL (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'lei-responsabilidade-fiscal', question: 'A Lei de Responsabilidade Fiscal (LRF) estabelece limites para despesa com pessoal. Para a União, o limite é:', options: ['50% da Receita Corrente Líquida', '60% da Receita Corrente Líquida', '40% da Receita Corrente Líquida', '70% da Receita Corrente Líquida', 'Não há limite'], correctAnswer: 0, explanation: 'LIMITES DESPESA PESSOAL (LRF art. 19-20): UNIÃO: 50% RCL. ESTADOS: 60% RCL. MUNICÍPIOS: 60% RCL. REPARTIÇÃO UNIÃO: Legislativo (2,5%+TCU), Judiciário (6%), MP (0,6%), Executivo (40,9%). ESTADOS: Leg.(3%), Jud.(6%), MP(2%), Exec.(49%). MUNICÍPIOS: Leg.(6% <300k hab; 8% >300k), Exec.(54%/51%). VERIFICAÇÃO: cada QUADRIMESTRE. LIMITES: total e por Poder. PRUDENCIAL: 95% limite (art. 22). ALERTA: 90% (art. 59). SANÇÕES: ultrapassar → vedações (aumento, reajuste, horas-extras, criação cargos). RECONDUÇÃO: 2 quadrimestres (1/3 cada). IMPORTANTE: TCU julga contas, mas não compõe Judiciário (vinculado Legislativo).', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'lei-responsabilidade-fiscal', question: 'A Receita Corrente Líquida (RCL) é calculada por:', options: ['Soma das receitas correntes', 'Receitas correntes deduzidas transferências constitucionais, contribuições e outras deduções legais', 'Apenas receitas tributárias', 'Receitas totais menos despesas', 'Somente receitas de capital'], correctAnswer: 1, explanation: 'RECEITA CORRENTE LÍQUIDA (LRF art. 2º-IV): somatório receitas correntes (-) DEDUÇÕES: UNIÃO: transf. constitucionais (FPE, FPM, IPI-Exp), contrib. sociais, CIDE-combustíveis. ESTADOS: transf. constitucionais (municípios - 25% ICMS/IPVA), FUNDEF/FUNDEB. MUNICÍPIOS: transf. constitucionais, FUNDEF/FUNDEB. PERÍODO: 12 meses (mês referência + 11 anteriores). ATUALIZAÇÃO: inflação (se necessário). FINALIDADE: base cálculo limites LRF (pessoal, dívida, ARO). IMPORTANTE: RCL ≠ receita total (exclui capital). É receita disponível/líquida. Fundamental todos cálculos LRF. Apurada mensalmente.', difficulty: 'hard', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'lei-responsabilidade-fiscal', question: 'Segundo a LRF, são vedadas nos últimos dois quadrimestres do mandato:', options: ['Todas as despesas de capital', 'Apenas despesas com pessoal', 'Operações de crédito por antecipação de receita (ARO) e despesas que não possam ser pagas no exercício', 'Somente contratação de pessoal', 'Não há vedações'], correctAnswer: 2, explanation: 'VEDAÇÕES FINAL MANDATO (LRF art. 38-42): ÚLTIMOS 2 QUADRIMESTRES (maio-dez, ano eleitoral): 1) CONTRAIR OBRIGAÇÃO DESPESA não paga no exercício (ou RP suficiência caixa - art. 42). 2) ÚLTIMOS 8 MESES: ARO (Antecipação Receita Orçamentária - art. 38). OBJETIVO: evitar deixar "esqueletos" sucessor, restos a pagar sem caixa. PERMITIDO: despesas correntes normais (se disponibilidade). CONTROLE: TCE fiscaliza. SANÇÃO: crime responsabilidade fiscal, inelegibilidade, multa. IMPORTANTE: RP processados permitidos (liquidados). Não processados: só se caixa. Planejamento essencial.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'lei-responsabilidade-fiscal', question: 'O Relatório de Gestão Fiscal (RGF) deve ser publicado:', options: ['Anualmente', 'Mensalmente', 'Quadrimestralmente (ou semestralmente para Municípios < 50 mil hab)', 'Apenas no final do mandato', 'Não é obrigatório'], correctAnswer: 2, explanation: 'RELATÓRIO GESTÃO FISCAL (LRF art. 54-55): PERIODICIDADE: QUADRIMESTRAL (jan-abr, mai-ago, set-dez). EXCEÇÃO: Municípios < 50 mil hab → SEMESTRAL. PRAZO: até 30 dias após período. CONTEÚDO: 1) Despesa pessoal (comparativo limites). 2) Dívida consolidada. 3) Operações crédito, ARO. 4) Garantias. 5) Restos pagar. RESPONSÁVEL: Executivo, Legislativo, Judiciário, MP, Defensoria (cada Poder/órgão). ASSINATURA: chefe Poder + contabilidade + controle interno. PUBLICAÇÃO: amplo acesso (internet). IMPORTANTE: vs RREO (bimestral, orçamentário). RGF: quadrimestral, limites LRF. Essencial transparência.', difficulty: 'easy', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'lei-responsabilidade-fiscal', question: 'A criação ou expansão de despesa continuada (com duração > 2 exercícios) requer:', options: ['Apenas autorização do chefe do Executivo', 'Estimativa impacto e declaração de adequação orçamentária', 'Não há exigências', 'Somente aprovação legislativa', 'Apenas parecer do Tribunal de Contas'], correctAnswer: 1, explanation: 'DESPESA OBRIGATÓRIA CONTINUADA (LRF art. 17): despesa corrente DERIVADA lei/ato administrativo, DURAÇÃO > 2 exercícios. REQUISITOS CRIAÇÃO/EXPANSÃO: 1) ESTIMATIVA IMPACTO ORÇAMENTÁRIO-FINANCEIRO no exercício + 2 seguintes. 2) DECLARAÇÃO origem recursos (adequação orçamentária). 3) COMPENSAÇÃO: aumento permanente receita OU redução permanente outra despesa. EXEMPLOS: criação cargos, reajuste servidores, benefícios previdenciários. NÃO ALCANÇA: despesas capital, variáveis. OBJETIVO: sustentabilidade fiscal, evitar comprometimento futuro sem fonte. RESPONSABILIDADE: ordenador despesa. SANÇÃO: invalidade ato (não gera efeito).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= BALANÇO ORÇAMENTÁRIO (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-orcamentario', question: 'O Balanço Orçamentário demonstra:', options: ['A situação patrimonial da entidade', 'As receitas previstas e executadas, despesas fixadas e executadas, comparando orçamento com execução', 'Apenas as receitas arrecadadas', 'Somente as despesas pagas', 'O fluxo de caixa'], correctAnswer: 1, explanation: 'BALANÇO ORÇAMENTÁRIO (Lei 4.320 art. 102, MCASP): demonstra execução ORÇAMENTÁRIA. ESTRUTURA: RECEITAS: Prevista × Executada (arrecadada). Diferença: excesso/insuficiência arrecadação. DESPESAS: Fixada (dotação) × Executada (empenhada/liquidada). Economia/excesso execução. RESULTADO: Superávit/Déficit Orçamentário. COLUNAS MCASP: previsão atualizada, realizada, saldo (a realizar/economia). REFINANCIAMENTO: deduzir operações crédito/amortização (intra-orçamentárias). OBJETIVO: accountability, verificar cumprimento orçamento. vs BP: situação patrimonial. BO: execução orçamentária. IMPORTANTE: regime CAIXA receitas (arrecadação), COMPETÊNCIA despesas (empenho MCASP, liquidação Lei 4.320).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-orcamentario', question: 'O Resultado Orçamentário (Superávit ou Déficit) é apurado por:', options: ['Receitas Correntes - Despesas Correntes', 'Receitas Executadas (arrecadadas) - Despesas Executadas (empenhadas)', 'Ativo - Passivo', 'Apenas Receitas Tributárias - Despesas Pessoal', 'Não há resultado orçamentário'], correctAnswer: 1, explanation: 'RESULTADO ORÇAMENTÁRIO: Receitas REALIZADAS (-) Despesas EXECUTADAS. SUPERÁVIT: Receitas > Despesas (sobra orçamento). DÉFICIT: Despesas > Receitas (falta recursos). ZERO: equilíbrio. OBSERVAÇÃO MCASP: deduzir refinanciamento (op.crédito/amortização - são intra-orçamentárias). RESULTADO PRIMÁRIO: exclui juros/amortização (mede esforço fiscal). DIFERENTE: Resultado Patrimonial (VPA - VPD, regime competência integral). Resultado Financeiro (ingressos - dispêndios). IMPORTANTE: déficit NÃO significa má gestão se planejado (investimentos). Déficit crônico: insustentável. Análise conjunta outras demonstrações.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-orcamentario', question: 'A diferença entre receita prevista e arrecadada, quando negativa, indica:', options: ['Excesso de arrecadação', 'Insuficiência de arrecadação (frustração receita)', 'Economia orçamentária', 'Superávit orçamentário', 'Déficit financeiro'], correctAnswer: 1, explanation: 'ANÁLISE EXECUÇÃO RECEITA: ARRECADADA > PREVISTA: EXCESSO ARRECADAÇÃO (positivo). Permite suplementação (créditos adicionais). ARRECADADA < PREVISTA: INSUFICIÊNCIA/FRUSTRAÇÃO receita (negativo). Problema: necessidade contingenciamento despesas (LRF art. 9º). CAUSAS FRUSTRAÇÃO: erro previsão, crise econômica, inadimplência. CONSEQUÊNCIA: limitação empenho/movimentação financeira (para cumprir meta resultado). IMPORTANTE: previsão deve ser TÉCNICA (série histórica, cenário). Otimista: risco frustração. Pessimista: subestima capacidade. Bimestral: comparar previsão × realização (RREO).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-orcamentario', question: 'Economia orçamentária ocorre quando:', options: ['Receita arrecadada > prevista', 'Despesa executada < dotação (fixada)', 'Despesa executada > dotação', 'Receita arrecadada < prevista', 'Não há diferença'], correctAnswer: 1, explanation: 'ECONOMIA ORÇAMENTÁRIA: dotação (fixada) > despesa EXECUTADA. SOBRA crédito orçamentário. CAUSAS: 1) Eficiência: menor custo. 2) Licitação favorável. 3) Não execução programas. 4) Contingenciamento LRF. ANÁLISE: economia por eficiência: positivo. Por NÃO execução: pode ser negativo (metas não cumpridas). REMANEJAMENTO: se créditos não utilizados → podem anular/suplementar (limitações legais). vs EXCESSO EXECUÇÃO: despesa > dotação (VEDADO sem crédito adicional). IMPORTANTE: economia reflete planejamento × execução. Ideal: execução próxima 100% (eficiência sem desperdício). Muito alta: subdimensionamento orçamento.', difficulty: 'easy', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-orcamentario', question: 'Sobre créditos adicionais, é correto afirmar:', options: ['Créditos Suplementares destinam-se a despesas não previstas', 'Créditos Especiais atendem despesas urgentes e imprevistas', 'Créditos Extraordinários são para despesas previstas insuficientes', 'Créditos Suplementares reforçam dotação insuficiente; Especiais: despesas não previstas; Extraordinários: urgentes/imprevisíveis', 'Não existem créditos adicionais'], correctAnswer: 3, explanation: 'CRÉDITOS ADICIONAIS (Lei 4.320 art. 40-46): 1) SUPLEMENTARES: reforço dotação INSUFICIENTE. Autorização LOA, abertura decreto. Fonte: anulação, excesso arrecadação, superávit. 2) ESPECIAIS: despesas NÃO PREVISTAS orçamento. Autorização lei específica, vigência limitada. 3) EXTRAORDINÁRIOS: despesas URGENTES/IMPREVISÍVEIS (guerra, calamidade). Abertura Medida Provisória (União) ou decreto (Estados/Mun.). Independe fontes compensatórias. VIGÊNCIA: suplementares/especiais: até fim exercício (prorrogável RP). Extraordinários: exercício. IMPORTANTE: suplementar: reforça existente. Especial/Extraordinário: cria nova dotação. Diferença: previsibilidade/urgência.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= BALANÇO FINANCEIRO (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-financeiro', question: 'O Balanço Financeiro evidencia:', options: ['A execução orçamentária', 'Os ingressos e dispêndios financeiros (receitas e despesas orçamentárias + extra-orçamentárias)', 'Apenas a situação patrimonial', 'Somente receitas orçamentárias', 'O resultado patrimonial'], correctAnswer: 1, explanation: 'BALANÇO FINANCEIRO (Lei 4.320 art. 103, MCASP): movimentação FINANCEIRA (caixa). ESTRUTURA: INGRESSOS (receitas): Orçamentárias (correntes, capital). Extra-orçamentárias (restos pagar, cauções, consignações). DISPÊNDIOS (despesas): Orçamentárias (correntes, capital). Extra-orçamentárias (pagamento RP, devolução cauções). SALDOS: inicial (caixa + bancos início) e final exercício. RESULTADO: Saldo Atual Financeiro. OBJETIVO: controle CAIXA, verificar entradas×saídas. vs BO: orçamentário (previsto×executado). BF: financeiro (regime caixa total). IMPORTANTE: extra-orçamentárias: não integram orçamento mas movimentam caixa (transitórias). Consignações, cauções, RP.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-financeiro', question: 'São ingressos extra-orçamentários:', options: ['Receitas tributárias e de contribuições', 'Restos a Pagar, Cauções, Consignações, Depósitos de Terceiros', 'Apenas operações de crédito', 'Somente despesas de capital', 'Não existem ingressos extra-orçamentários'], correctAnswer: 1, explanation: 'INGRESSOS EXTRA-ORÇAMENTÁRIOS: valores NÃO PREVISTOS orçamento, TRANSITÓRIOS (devem devolver). EXEMPLOS: 1) RESTOS A PAGAR: inscrição (dívida exercício anterior, pagar agora). 2) CAUÇÕES: garantias contratos, depósitos licitação. 3) CONSIGNAÇÕES: IRRF, INSS descontados (repassar). 4) DEPÓSITOS TERCEIROS: judiciais, fianças. 5) SERVIÇO DÍVIDA A PAGAR (SDR). CARACTERÍSTICA: PASSIVO FINANCEIRO (obrigação). NÃO são receita pública (não pertencem ente). vs ORÇAMENTÁRIAS: integram orçamento, definitivas. CONTÁBIL: aumenta caixa (débito) e passivo financeiro (crédito). DEVOLUÇÃO: dispêndio extra-orçamentário. IMPORTANTE: controle rigoroso, são recursos terceiros.', difficulty: 'hard', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-financeiro', question: 'O saldo final do Balanço Financeiro representa:', options: ['O resultado orçamentário', 'O disponível (caixa e bancos) ao final do exercício', 'O patrimônio líquido', 'Apenas dívidas', 'O superávit patrimonial'], correctAnswer: 1, explanation: 'SALDO BALANÇO FINANCEIRO: DISPONÍVEL final exercício. FÓRMULA: Saldo Inicial + Ingressos - Dispêndios = Saldo Final. COMPOSIÇÃO: Caixa, Bancos conta movimento, Aplicações Financeiras resgate imediato. CONCILIAÇÃO: deve bater com ATIVO FINANCEIRO (Balanço Patrimonial). vs RESULTADO FINANCEIRO: Ingressos - Dispêndios (pode ≠ variação saldo se inicial ≠ 0). IMPORTÂNCIA: mostra liquidez imediata, capacidade pagamento. ANÁLISE: saldo alto: folga financeira ou ineficiência aplicação. Baixo: risco insuficiência caixa. CONFRONTO: Saldo Financeiro × Restos a Pagar (Passivo Financeiro) = Superávit/Déficit Financeiro. ESSENCIAL: programação financeira, fluxo caixa.', difficulty: 'easy', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-financeiro', question: 'A diferença entre o Balanço Financeiro e o Balanço Orçamentário é que:', options: ['Não há diferença', 'BF evidencia movimentação financeira (caixa) incluindo extra-orçamentárias; BO mostra execução orçamentária (previsto × realizado)', 'BO inclui extra-orçamentárias', 'BF não considera receitas', 'BF é apenas patrimonial'], correctAnswer: 1, explanation: 'BF × BO: BALANÇO FINANCEIRO: movimentação CAIXA (regime caixa). Inclui orçamentárias + EXTRA-ORÇAMENTÁRIAS. Saldos inicial/final. Foco: fluxo financeiro. BALANÇO ORÇAMENTÁRIO: execução ORÇAMENTO. Previsão × Realização. Apenas ORÇAMENTÁRIAS. Resultado orçamentário. Foco: compliance orçamento. EXEMPLO: inscrição RP 1.000: BF: +1.000 ingresso extra (aumenta caixa? NÃO, é obrigação). BO: não aparece (é de exercício anterior). RELACIONAMENTO: ambos complementares. BF: liquidez. BO: autorização×execução. IMPORTANTE: análise conjunta essencial. BO: legalidade. BF: capacidade pagamento.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-financeiro', question: 'Receitas extra-orçamentárias são:', options: ['Receitas previstas no orçamento', 'Ingressos financeiros temporários que não integram o orçamento (cauções, consignações)', 'Apenas receitas tributárias', 'Despesas pagas', 'Não existem'], correctAnswer: 1, explanation: 'RECEITAS EXTRA-ORÇAMENTÁRIAS (nomenclatura antiga, hoje INGRESSOS extra): valores ENTRAM caixa mas NÃO integram ORÇAMENTO. TEMPORÁRIOS: devem ser DEVOLVIDOS. EXEMPLOS: cauções licitação, consignações INSS/IR, depósitos judiciais, restos a pagar (inscrição). NATUREZA: PASSIVO FINANCEIRO (dívida flutuante). NÃO confundir: receita pública (definitiva, orçamento, receita ente). CONTABILIZAÇÃO: D-Bancos (Ativo Financeiro) | C-Cauções Recebidas (Passivo Financeiro). DEVOLUÇÃO: D-Cauções | C-Bancos (dispêndio extra). EVIDENCIAÇÃO: Balanço Financeiro. IMPORTANTE: controle rígido, prestação contas. Erro: usar como receita própria (desvio).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },

    // ============= BALANÇO PATRIMONIAL PÚBLICO (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-patrimonial-publico', question: 'O Balanço Patrimonial do setor público evidencia:', options: ['Apenas receitas e despesas', 'Ativo, Passivo e Patrimônio Líquido, segregados em financeiro e permanente', 'Somente o orçamento', 'Apenas o fluxo de caixa', 'Não existe BP público'], correctAnswer: 1, explanation: 'BALANÇO PATRIMONIAL PÚBLICO (MCASP): situação PATRIMONIAL. ESTRUTURA: ATIVO: Circulante, Não Circulante. Segregação: Financeiro (disponível, realizável exercício) × Permanente (demais). PASSIVO: Circulante, Não Circulante. Segregação: Financeiro (exigível exercício) × Permanente (demais). PATRIMÔNIO LÍQUIDO: Capital, Reservas, Resultados Acumulados. EQUAÇÃO: A = P + PL. ATIVO/PASSIVO FINANCEIRO: conceito Lei 4.320 (disponível/exigível financeiro). COMPENSADO: atos potenciais (extinto MCASP, agora controles). IMPORTANTE: convergência IPSAS, regime competência. Ativo: ordem LIQUIDEZ. Passivo: ordem EXIGIBILIDADE.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-patrimonial-publico', question: 'Ativo Financeiro compreende:', options: ['Apenas imóveis', 'Créditos e valores realizáveis independentemente de autorização orçamentária (disponível, realizável)', 'Somente estoques', 'Apenas investimentos permanentes', 'Não existe ativo financeiro'], correctAnswer: 1, explanation: 'ATIVO FINANCEIRO (Lei 4.320 art. 105 § 1º): créditos/valores cuja MOBILIZAÇÃO/ALIENAÇÃO independem AUTORIZAÇÃO ORÇAMENTÁRIA. EXEMPLOS: 1) DISPONÍVEL: caixa, bancos. 2) CRÉDITOS: realizáveis exercício (tributos a receber CP, dívida ativa CP). 3) INVESTIMENTOS TEMPORÁRIOS: resgate imediato. vs ATIVO PERMANENTE: dependem autorização (imobilizado, realizável LP). FINALIDADE: confronto PASSIVO FINANCEIRO (exigível exercício) → SUPERÁVIT/DÉFICIT FINANCEIRO. FÓRMULA: AF - PF = SF ou DF. SF: recursos disponíveis > obrigações. DF: insuficiência. IMPORTANTE: SF pode abrir créditos adicionais (fonte). DF: vedado. Lei 4.320: conceito tradicional. MCASP: mantém segregação informativa.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-patrimonial-publico', question: 'Passivo Financeiro abrange:', options: ['Apenas fornecedores de longo prazo', 'Compromissos exigíveis independentemente de autorização orçamentária (restos a pagar, serviço dívida)', 'Somente patrimônio líquido', 'Apenas receitas antecipadas', 'Não existe passivo financeiro'], correctAnswer: 1, explanation: 'PASSIVO FINANCEIRO (Lei 4.320 art. 105 § 2º): compromissos PAGAMENTO independem AUTORIZAÇÃO ORÇAMENTÁRIA. EXEMPLOS: 1) RESTOS A PAGAR: processados e não-processados. 2) SERVIÇO DÍVIDA A PAGAR: parcelas vencidas/vincendas exercício. 3) DEPÓSITOS/CAUÇÕES: obrigações devolver. 4) CONSIGNAÇÕES: retenções a recolher. vs PASSIVO PERMANENTE: exigível LP, depende autorização futura. DESTINAÇÃO: CONFRONTO Ativo Financeiro → Resultado Financeiro (superávit/déficit). IMPORTÂNCIA: mostra compromissos IMEDIATOS. Alto PF sem AF: risco insolvência. CONTROLE: programação financeira essencial. INSCRIÇÃO RP: aumenta PF (e AF se tiver saldo caixa, senão déficit).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-patrimonial-publico', question: 'O superávit financeiro é apurado por:', options: ['Receitas - Despesas Orçamentárias', 'Ativo Financeiro - Passivo Financeiro', 'Ativo Total - Passivo Total', 'Apenas receitas correntes', 'Patrimônio Líquido positivo'], correctAnswer: 1, explanation: 'SUPERÁVIT FINANCEIRO: Ativo Financeiro (-) Passivo Financeiro > 0. INTERPRETAÇÃO: recursos disponíveis EXCEDEM compromissos financeiros. CÁLCULO: (Disponível + Realizável Financeiro) - (RP + SDR + Depósitos). UTILIZAÇÃO: FONTE créditos adicionais (suplementar, especial). EXIGÊNCIA: específico por FONTE recursos (vinculações). DÉFICIT FINANCEIRO: AF < PF. Insuficiência recursos. VEDADO: fonte créditos. IMPORTÂNCIA: equilíbrio financeiro, não confundir: Superávit ORÇAMENTÁRIO (receita > despesa orçamento). FINANCEIRO: disponível × exigível. PATRIMONIAL: PL > 0. ANÁLISE: SF alto: folga abrir créditos. DF: contingenciar.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'balanco-patrimonial-publico', question: 'Sobre o Patrimônio Líquido no setor público, é correto afirmar:', options: ['É sempre positivo', 'Pode ser negativo (Passivo a Descoberto)', 'Não existe no setor público', 'É igual ao superávit financeiro', 'Apenas compreende capital social'], correctAnswer: 1, explanation: 'PATRIMÔNIO LÍQUIDO PÚBLICO: resultado EQUAÇÃO PATRIMONIAL: PL = Ativo - Passivo. COMPOSIÇÃO: 1) PATRIMÔNIO SOCIAL/CAPITAL SOCIAL (inicial). 2) RESERVAS. 3) RESULTADOS ACUMULADOS: superávits/déficits patrimoniais acumulados. PODE SER NEGATIVO: Passivo a Descoberto (passivo > ativo). Raro, mas possível (entes insolventes). FORMAÇÃO: resultado patrimonial cada exercício (VPA - VPD) → acumula PL. DIFERENTE: setor privado (capital subscrito). Público: não há acionistas/sócios. PL representa RIQUEZA LÍQUIDA ente. vs Superávit Financeiro: conceitos distintos (SF = AF-PF, PL = A-P). IMPORTANTE: boa gestão → PL crescente. Negativo → patrimônio comprometido.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ============= DÍVIDA ATIVA (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'divida-ativa', question: 'A Dívida Ativa é constituída por:', options: ['Empréstimos tomados pelo ente', 'Créditos da Fazenda Pública, tributários ou não, vencidos e não pagos', 'Apenas impostos correntes', 'Somente multas de trânsito', 'Não existe dívida ativa'], correctAnswer: 1, explanation: 'DÍVIDA ATIVA (Lei 4.320 art. 39, CTN art. 201): CRÉDITOS FAZENDA PÚBLICA, VENCIDOS, NÃO PAGOS. CLASSIFICAÇÃO: 1) TRIBUTÁRIA: impostos, taxas, contribuições, multas tributárias. Prescrição: 5 anos (CTN). 2) NÃO-TRIBUTÁRIA: aluguéis, foros, laudêmios, indenizações, multas administrativas. Prescrição: variável (civil). INSCRIÇÃO: ato formal, apura líquido/certo crédito. Requisitos: certeza, liquidez. Termo inscrição: controle. CDA: Certidão Dívida Ativa (título executivo extrajudicial). COBRANÇA: administrativa (notificação) ou judicial (execução fiscal - Lei 6.830/80). IMPORTANTE: após inscrição → ativo realizável. Atualização: juros, multa, correção.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'divida-ativa', question: 'A contabilização da inscrição em Dívida Ativa é:', options: ['Não contabiliza', 'Débito: Dívida Ativa (Ativo) / Crédito: Variação Patrimonial Aumentativa (Receita)', 'Débito: Despesa / Crédito: Caixa', 'Apenas nota de rodapé', 'Débito: Passivo / Crédito: Receita'], correctAnswer: 1, explanation: 'CONTABILIZAÇÃO INSCRIÇÃO DÍVIDA ATIVA: LANÇAMENTO: D - Dívida Ativa Tributária/Não-Trib. (Ativo) | C - Variação Patrimonial Aumentativa - VPA (Receita sob enfoque patrimonial). EFEITO: aumenta Ativo e reconhece RECEITA patrimonial (regime competência). OBSERVAÇÃO: se crédito JÁ reconhecido (tributos lançados), faz: D-Dív.Ativa | C-Crédito a Receber (reclassificação, sem nova receita). AJUSTE: Provisão Perdas Dívida Ativa (PPDA - retificadora, estimar incobráveis). D-VPD | C-PPDA. RECEBIMENTO: D-Caixa | C-Dív.Ativa. BAIXA: prescrição/anistia: D-VPD (ou Provisão) | C-Dív.Ativa. IMPORTANTE: inscrição aumenta ativo MAS prevê perdas (prudência).', difficulty: 'hard', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'divida-ativa', question: 'A Certidão de Dívida Ativa (CDA) é:', options: ['Um comprovante de pagamento', 'Título executivo extrajudicial que permite execução fiscal sem processo de conhecimento', 'Uma nota fiscal', 'Apenas informativo', 'Não tem valor jurídico'], correctAnswer: 1, explanation: 'CDA - CERTIDÃO DÍVIDA ATIVA (Lei 6.830/80 art. 2º-3º): documento TÍTULO EXECUTIVO EXTRAJUDICIAL. PERMITE: EXECUÇÃO FISCAL direta, SEM processo conhecimento. REQUISITOS VALIDADE (art. 2º § 5º): nome devedor/corresponsáveis, CPF/CNPJ, endereço, valor originário, multa, juros, correção, fundamentação legal, origem crédito, data inscrição, nº processo. EFEITOS: inversão ônus prova (presunção legitimidade), possibilita penhora, leilão. DISCUSSÃO: via Embargos Execução (15 dias). NULIDADE: falta requisitos essenciais. IMPORTANTE: poder coercitivo Estado, facilita recuperação créditos. Inscrição regular essencial. Contestação: demonstrar pagamento, prescrição, erro cálculo.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'divida-ativa', question: 'O prazo de prescrição da Dívida Ativa Tributária é:', options: ['10 anos', '3 anos', '5 anos, contados da constituição definitiva do crédito', '2 anos', 'Não prescreve'], correctAnswer: 2, explanation: 'PRESCRIÇÃO DÍVIDA ATIVA TRIBUTÁRIA (CTN art. 174): PRAZO: 5 ANOS. INÍCIO: constituição definitiva crédito (lançamento não contestado ou decisão final administrativa). INTERRUPÇÃO (art. 174 parágrafo único): despacho juiz execução, protesto judicial, qualquer ato inequívoco reconhecimento dívida. SUSPENSÃO: moratória, depósito, reclamações/recursos, parcelamento. EFEITO PRESCRIÇÃO: EXTINGUE crédito tributário (CTN 156-V). BAIXA: cancelamento dívida ativa. vs NÃO-TRIBUTÁRIA: prazos variáveis (Código Civil - geralmente 5 ou 10 anos dependendo natureza). IMPORTANTE: controle rigoroso prazos, atos interruptivos (notificação, protesto). Prescrição intercorrente (durante execução): possível se inércia Fazenda.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'divida-ativa', question: 'A Provisão para Perdas com Dívida Ativa (PPDA) tem por objetivo:', options: ['Aumentar a receita', 'Estimar valores incobráveis, reduzindo o ativo ao valor realizável', 'Pagar a dívida', 'Cancelar todos os créditos', 'Não existe essa provisão'], correctAnswer: 1, explanation: 'PPDA - PROVISÃO PERDAS DÍVIDA ATIVA: OBJETIVO: ajustar Dívida Ativa ao VALOR REALIZÁVEL (provável recebimento). PRUDÊNCIA: reconhecer potencial NÃO recebimento. CÁLCULO: baseado experiência, histórico recuperação, idade crédito, análise risco. MÉTODOS: percentual sobre saldo (ex: 30% > 5 anos), análise individual. CONTABILIZAÇÃO: D-VPD (Variação Patrimonial Diminutiva) | C-PPDA (retificadora Ativo). APRESENTAÇÃO BP: Dívida Ativa (bruto) (-) PPDA = Dívida Ativa Líquida. AJUSTE: anual (revisar estimativa). BAIXA: quando prescrever/cancelar: D-PPDA | C-Dívida Ativa. IMPORTANTE: não confundir: provisão ≠ cancelamento. É estimativa contábil. Melhora qualidade informação (ativo real).', difficulty: 'medium', examBoard: 'FCC', year: 2024 },

    // ============= RESTOS A PAGAR (5) =============
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'restos-a-pagar', question: 'Restos a Pagar são:', options: ['Receitas não arrecadadas', 'Despesas empenhadas mas não pagas até 31/12', 'Apenas despesas de pessoal', 'Receitas de exercícios futuros', 'Não existem'], correctAnswer: 1, explanation: 'RESTOS A PAGAR (Lei 4.320 art. 36): despesas EMPENHADAS mas NÃO PAGAS até 31/DEZEMBRO. INSCRIÇÃO: 31/12, transfere compromisso exercício seguinte. CLASSIFICAÇÃO: 1) PROCESSADOS: LIQUIDADAS (direito credor atestado, serviço/bem entregue). Obrigação líquida. 2) NÃO-PROCESSADOS: apenas empenhadas, NÃO liquidadas (incerto se obrigação cumprida). PAGAMENTO: exercício seguinte, independe inclusão orçamento. VALIDADE: Lei 4.320: não especifica. Prática: RP processados: até pagar. Não-processados: até validade empenho ou cancelamento. IMPORTANTE: RP é DÍVIDA FLUTUANTE (passivo financeiro). Excesso RP: má gestão. LRF art. 42: restrições final mandato.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'restos-a-pagar', question: 'A diferença entre Restos a Pagar Processados e Não-Processados é:', options: ['Não há diferença', 'Processados foram liquidados (serviço/bem entregue); Não-Processados apenas empenhados', 'Processados são de pessoal', 'Não-processados foram pagos', 'Processados não têm valor'], correctAnswer: 1, explanation: 'RP PROCESSADOS vs NÃO-PROCESSADOS: PROCESSADOS: despesa EMPENHADA + LIQUIDADA. Requisitos: serviço prestado/bem entregue, documentação completa, direito credor verificado. OBRIGAÇÃO LÍQUIDA/CERTA. Prioridade pagamento. CONTÁBIL: despesa executada. NÃO-PROCESSADOS: apenas EMPENHADA, NÃO liquidada. Incerteza cumprimento (pode cancelar se não entregar). RISCO maior. LRF art. 42: exige DISPONIBILIDADE CAIXA inscrever (último ano mandato). EXEMPLO: RP Processado: obra concluída, medição aceita, NF recebida, não pagou. RP Não-Proc.: obra contratada, não concluída, empenho global. IMPORTANTE: processados: obrigação reconhecida. Não-proc.: condicional.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'restos-a-pagar', question: 'A inscrição de Restos a Pagar no último ano de mandato, segundo a LRF, exige:', options: ['Não há exigências', 'Disponibilidade de caixa para pagamento', 'Apenas autorização do Legislativo', 'Somente parecer do Tribunal de Contas', 'É proibida qualquer inscrição'], correctAnswer: 1, explanation: 'LRF ART. 42 (RESTOS A PAGAR FINAL MANDATO): ÚLTIMOS 2 QUADRIMESTRES: vedado contrair obrigação DESPESA que NÃO POSSA SER PAGA no exercício OU que tenha parcelas a pagar no seguinte SEM SUFICIÊNCIA CAIXA. INSCRIÇÃO RP: permitida SE: DISPONIBILIDADE FINANCEIRA que atenda compromisso. CÁLCULO: Disponibilidade Caixa (líquida vinculações) ≥ RP a inscrever. RP PROCESSADOS: maior tranquilidade (obrigação líquida). NÃO-PROCESSADOS: requer cuidado. OBJETIVO: evitar "herança maldita", deixar contas em dia. SANÇÃO: crime responsabilidade (Lei 10.028/2000), inelegibilidade. CONTROLE: TCE fiscaliza. IMPORTANTE: planejamento essencial último semestre. Contingenciamento preventivo.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'restos-a-pagar', question: 'O cancelamento de Restos a Pagar gera:', options: ['Despesa orçamentária', 'Receita orçamentária (superveniência)', 'Não gera efeito contábil', 'Apenas nota explicativa', 'Aumento do passivo'], correctAnswer: 1, explanation: 'CANCELAMENTO RESTOS A PAGAR: anulação compromisso (prescrição, não entrega bem/serviço, decisão administrativa). EFEITO ORÇAMENTÁRIO: RECEITA ORÇAMENTÁRIA (categoria própria: "Outras Receitas Correntes - Receita Dívida Ativa" ou específica RP cancelados). NATUREZA: superveniência (receita extraordinária, ganho cancelamento obrigação). CONTÁBIL: D-RP (Passivo Financeiro) | C-VPA (Variação Patrimonial Aumentativa). ATENÇÃO: se serviço/bem FOI entregue → NÃO pode cancelar (obrigação existe). Cancelar indevido: dano erário. REINSCRIÇÃO: se motivo cancelamento cessar, pode reinscrever (análise caso). IMPORTANTE: controle, evitar cancelamentos irregulares. Superveniência ≠ receita derivada.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    
    { area: 'fiscal', subject: 'contabilidade-publica', topic: 'restos-a-pagar', question: 'Sobre a contabilização do pagamento de Restos a Pagar, é correto afirmar:', options: ['É despesa orçamentária do exercício do pagamento', 'É despesa extra-orçamentária (já foi despesa orçamentária no empenho)', 'Não afeta o orçamento', 'É receita', 'Apenas registra em nota'], correctAnswer: 1, explanation: 'PAGAMENTO RESTOS A PAGAR: NATUREZA: DESPESA EXTRA-ORÇAMENTÁRIA. MOTIVO: despesa JÁ foi ORÇAMENTÁRIA no exercício do EMPENHO (princípio competência orçamentária). Evitar duplicidade. CONTABILIZAÇÃO: D-Restos a Pagar (Passivo Financeiro) | C-Bancos (Ativo Financeiro). EFEITO: reduz passivo e caixa, NÃO afeta orçamento corrente. BALANÇO ORÇAMENTÁRIO: não aparece (extra-orçamentário). BALANÇO FINANCEIRO: dispêndio extra-orçamentário. IMPORTANTE: inscrição RP (31/12): D-RP C-Caixa? NÃO! Inscrição: D-RP C-Despesa Exercício Anterior (ajuste, se regime caixa). MCASP: já reconheceu despesa no empenho/liquidação. Pagamento RP: apenas financeiro. Diferente: nova despesa (empenho ano corrente).', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Contabilidade Pública questions...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Contabilidade Pública questions seeded successfully!');
}
