import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL ECONOMIA QUESTIONS IN ONE SEED =============
export async function seedAllEconomiaQuestions() {
  console.log('🚀 Starting to seed ALL Economia questions...');
  
  // Todas as 45 questões juntas para importação em batch
  const allQuestions: Question[] = [
    // MICROECONOMIA (5)
    { area: 'fiscal', subject: 'economia', topic: 'microeconomia', question: 'A Lei da Demanda estabelece que, mantidas as demais condições constantes (ceteris paribus), quando o preço de um bem aumenta, a quantidade demandada desse bem:', options: ['Aumenta, pois os consumidores têm maior poder de compra', 'Diminui, devido ao efeito substituição e ao efeito renda', 'Permanece constante, independentemente do preço', 'Aumenta proporcionalmente ao aumento do preço', 'Não sofre alteração, pois a demanda é perfeitamente inelástica'], correctAnswer: 1, explanation: 'Lei da Demanda: relação INVERSA entre preço e quantidade demandada. Quando preço ↑, quantidade demandada ↓. FUNDAMENTOS: 1) EFEITO SUBSTITUIÇÃO: bem fica relativamente mais caro, consumidor substitui por alternativas; 2) EFEITO RENDA: preço maior reduz poder de compra real. EXCEÇÕES (bens de Giffen): extremamente raros. CURVA DE DEMANDA: inclinação negativa. Importante para análise de elasticidade-preço.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'microeconomia', question: 'Em relação à elasticidade-preço da demanda, é CORRETO afirmar que:', options: ['Bens essenciais tendem a ter demanda elástica (|E| > 1)', 'Quando a demanda é inelástica, aumento de preço reduz a receita total', 'Bens de luxo geralmente apresentam demanda mais elástica que bens necessários', 'A elasticidade mede apenas a sensibilidade da oferta em relação ao preço', 'Demanda perfeitamente inelástica significa que o consumidor não compra o produto'], correctAnswer: 2, explanation: 'ELASTICIDADE-PREÇO DA DEMANDA (EPD) = % variação Qtd / % variação Preço. CLASSIFICAÇÃO: |E| > 1: elástica (sensível); |E| < 1: inelástica (pouco sensível); |E| = 1: unitária. BENS DE LUXO: alta elasticidade (podem ser adiados, têm substitutos). BENS ESSENCIAIS: baixa elasticidade (necessários, poucos substitutos). RECEITA TOTAL: se demanda inelástica, ↑ preço → ↑ receita. FATORES: disponibilidade de substitutos, essencialidade, proporção da renda, tempo.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'microeconomia', question: 'No modelo de concorrência perfeita, as empresas maximizam lucro quando:', options: ['Receita marginal é igual ao custo médio', 'Receita marginal é igual ao custo marginal', 'Custo total é minimizado', 'Preço é igual ao custo fixo médio', 'Receita total é máxima, independentemente dos custos'], correctAnswer: 1, explanation: 'MAXIMIZAÇÃO DE LUCRO: RMg = CMg (Receita Marginal = Custo Marginal). LÓGICA: produzir unidade adicional aumenta lucro se RMg > CMg; reduz lucro se RMg < CMg; maximiza quando RMg = CMg. CONCORRÊNCIA PERFEITA: empresa é price-taker (aceita preço de mercado), então RMg = P (preço). CONDIÇÃO: P = CMg. CURTO PRAZO: pode ter lucro, prejuízo ou lucro zero. LONGO PRAZO: lucro econômico zero (P = CMg = CMe mínimo).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'microeconomia', question: 'Uma empresa monopolista, ao contrário de uma empresa em concorrência perfeita:', options: ['Não possui poder de mercado para definir preços', 'Opera onde preço é igual ao custo marginal', 'Enfrenta uma curva de demanda perfeitamente elástica', 'Define preço acima do custo marginal, gerando peso morto', 'Maximiza lucro produzindo onde receita média é máxima'], correctAnswer: 3, explanation: 'MONOPÓLIO: único vendedor, poder de mercado, define preço. CARACTERÍSTICAS: 1) Curva de demanda DECRESCENTE (não é price-taker); 2) RMg < P (receita marginal menor que preço); 3) Maximiza lucro: RMg = CMg, mas cobra P > CMg. INEFICIÊNCIA: gera PESO MORTO (deadweight loss) - perda de bem-estar social. BARREIRAS À ENTRADA: legais, tecnológicas, controle de recursos. REGULAÇÃO: necessária para proteger consumidores (preço-teto, antitruste).', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'microeconomia', question: 'Sobre externalidades, é CORRETO afirmar que:', options: ['Externalidades positivas sempre beneficiam apenas quem as produz', 'Externalidades negativas ocorrem quando benefícios sociais superam custos privados', 'Uma fábrica poluidora gera externalidade negativa, pois custo social excede custo privado', 'Externalidades são sempre internalizadas pelo mercado sem necessidade de intervenção', 'O Teorema de Coase afirma que externalidades jamais podem ser resolvidas por negociação'], correctAnswer: 2, explanation: 'EXTERNALIDADES: efeitos (custos/benefícios) sobre terceiros não envolvidos na transação. TIPOS: 1) NEGATIVAS: poluição, barulho (custo social > custo privado); 2) POSITIVAS: educação, vacina (benefício social > benefício privado). FALHA DE MERCADO: mercado não internaliza externalidades, levando a alocação ineficiente. SOLUÇÕES: impostos pigouvianos (negativas), subsídios (positivas), regulação, direitos de propriedade. TEOREMA DE COASE: se direitos bem definidos e custos transação baixos, partes negociam solução eficiente.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    
    // MACROECONOMIA (5)
    { area: 'fiscal', subject: 'economia', topic: 'macroeconomia', question: 'O Produto Interno Bruto (PIB) pode ser calculado por três óticas. Pela ótica da despesa, o PIB é igual a:', options: ['Soma dos valores adicionados em cada etapa da produção', 'Consumo + Investimento + Gastos do Governo + (Exportações - Importações)', 'Soma de todos os salários, lucros, juros e aluguéis', 'Valor total da produção bruta menos os impostos indiretos', 'Apenas a soma do consumo das famílias e dos investimentos privados'], correctAnswer: 1, explanation: 'PIB PELA ÓTICA DA DESPESA: PIB = C + I + G + (X - M). COMPONENTES: C = Consumo das famílias; I = Investimento (FBCF + variação estoques); G = Gastos do governo; X = Exportações; M = Importações; (X-M) = saldo da balança comercial. OUTRAS ÓTICAS: 1) PRODUÇÃO/OFERTA: soma valores adicionados; 2) RENDA: salários + lucros + juros + aluguéis. IDENTIDADE: as três óticas geram MESMO valor. PIB NOMINAL vs REAL: real ajustado pela inflação.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'macroeconomia', question: 'Sobre a Curva de Phillips, é CORRETO afirmar que:', options: ['Representa trade-off entre inflação e desemprego no curto prazo', 'Demonstra relação positiva entre inflação e desemprego', 'É vertical no curto prazo e inclinada no longo prazo', 'Foi confirmada empiricamente em todos os períodos históricos', 'Afirma que inflação zero sempre leva ao pleno emprego'], correctAnswer: 0, explanation: 'CURVA DE PHILLIPS: relação INVERSA entre inflação e desemprego. CURTO PRAZO: inclinada negativamente - ↓ desemprego → ↑ inflação (trade-off). Política expansionista reduz desemprego mas aumenta inflação. LONGO PRAZO: VERTICAL no nível natural de desemprego (NAIRU). Expectativas racionais: agentes antecipam inflação, anulando efeito sobre desemprego. ESTAGFLAÇÃO (anos 70): quebrou relação original, levando à versão com expectativas. POLÍTICA: não há trade-off permanente.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'macroeconomia', question: 'No modelo IS-LM, uma política fiscal expansionista (aumento dos gastos do governo) provoca:', options: ['Deslocamento da IS para a direita, aumentando renda e taxa de juros', 'Deslocamento da LM para a direita, reduzindo taxa de juros', 'Deslocamento da IS para a esquerda, reduzindo renda e juros', 'Não afeta o equilíbrio, pois política fiscal não influencia o modelo', 'Deslocamento da LM para a esquerda, aumentando apenas a renda'], correctAnswer: 0, explanation: 'MODELO IS-LM: equilíbrio conjunto mercados BENS (IS) e MOEDA (LM). CURVA IS: equilíbrio mercado bens (renda × juros). Inclinação negativa: ↑ juros → ↓ investimento → ↓ renda. CURVA LM: equilíbrio mercado monetário. Inclinação positiva: ↑ renda → ↑ demanda moeda → ↑ juros. POLÍTICA FISCAL EXPANSIONISTA: ↑ G → IS desloca DIREITA → ↑ Y (renda) e ↑ r (juros). EFEITO CROWDING-OUT: ↑ juros reduz investimento privado parcialmente. EFICÁCIA: maior quando LM mais horizontal.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'macroeconomia', question: 'O multiplicador keynesiano indica que:', options: ['Um aumento nos gastos autônomos gera aumento mais que proporcional na renda de equilíbrio', 'A propensão marginal a consumir não afeta o valor do multiplicador', 'Quanto maior a propensão marginal a poupar, maior o multiplicador', 'Em economia fechada, multiplicador é sempre igual a 1', 'Impostos progressivos aumentam o valor do multiplicador'], correctAnswer: 0, explanation: 'MULTIPLICADOR KEYNESIANO: k = 1 / (1 - c), onde c = propensão marginal a consumir. LÓGICA: ↑ gastos → ↑ renda → ↑ consumo → ↑ renda (efeito em cadeia). EXEMPLO: se c = 0,8, k = 5. ↑ G em 100 → ↑ Y em 500. FATORES QUE REDUZEM k: 1) ↑ propensão a poupar; 2) impostos sobre renda; 3) importações (vazamentos). ECONOMIA ABERTA: k = 1 / (1 - c + m), onde m = propensão a importar. CRÍTICA: pressupõe recursos ociosos.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'macroeconomia', question: 'Sobre o ciclo econômico, é CORRETO afirmar que:', options: ['As fases são: expansão, pico, recessão (contração) e vale', 'Recessão técnica ocorre após seis trimestres consecutivos de crescimento negativo', 'Depressão é sinônimo de recessão, sem diferença conceitual', 'Ciclos econômicos foram eliminados após adoção de políticas anticíclicas', 'A fase de expansão sempre tem duração idêntica à fase de contração'], correctAnswer: 0, explanation: 'CICLO ECONÔMICO: flutuações periódicas da atividade econômica. FASES: 1) EXPANSÃO: ↑ PIB, emprego, renda; 2) PICO: máximo da atividade; 3) RECESSÃO/CONTRAÇÃO: ↓ PIB (2 trimestres consecutivos = recessão técnica); 4) VALE: mínimo da atividade. DEPRESSÃO: recessão severa e prolongada (ex: 1929). INDICADORES: PIB, emprego, produção industrial, vendas. CAUSAS: choques oferta/demanda, política monetária, expectativas. POLÍTICAS ANTICÍCLICAS: fiscais e monetárias para suavizar flutuações.', difficulty: 'easy', examBoard: 'FCC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} questions for import...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('✅ Part 1/5 imported! Continuing...');
  
  // Continuar com as questões restantes...
  const moreQuestions: Question[] = [
    // POLÍTICA FISCAL E MONETÁRIA (5)
    { area: 'fiscal', subject: 'economia', topic: 'politica-fiscal-e-monetaria', question: 'A política fiscal expansionista caracteriza-se por:', options: ['Aumento de impostos e redução de gastos públicos', 'Redução de impostos e/ou aumento de gastos públicos', 'Aumento da taxa básica de juros (Selic)', 'Redução da oferta monetária para controlar inflação', 'Venda de títulos públicos pelo Banco Central'], correctAnswer: 1, explanation: 'POLÍTICA FISCAL: uso de GASTOS PÚBLICOS e TRIBUTOS para influenciar economia. EXPANSIONISTA: estimular economia → ↑ G (gastos) e/ou ↓ T (impostos) → ↑ demanda agregada → ↑ PIB, emprego. CONTRACIONISTA: conter inflação → ↓ G e/ou ↑ T → ↓ demanda. INSTRUMENTOS: 1) Gastos: investimentos, custeio, transferências; 2) Receitas: impostos, contribuições. MULTIPLICADOR FISCAL: efeito amplificado na renda. SUSTENTABILIDADE: atenção para dívida pública.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'politica-fiscal-e-monetaria', question: 'Quando o Banco Central eleva a taxa Selic (Sistema Especial de Liquidação e Custódia), espera-se que, ceteris paribus:', options: ['O consumo e o investimento aumentem devido ao maior retorno das aplicações', 'A inflação aumente, pois juros mais altos elevam custos de produção', 'O crédito fique mais caro, reduzindo consumo e investimento', 'A taxa de câmbio se desvalorize, tornando importações mais baratas', 'Não haja impacto sobre a economia real, apenas sobre o mercado financeiro'], correctAnswer: 2, explanation: 'POLÍTICA MONETÁRIA: Banco Central usa taxa de juros (SELIC) e oferta monetária para controlar inflação e estabilizar economia. ↑ SELIC (contracionista): 1) Crédito mais caro → ↓ consumo e investimento; 2) ↑ retorno aplicações → ↓ consumo presente; 3) ↓ inflação; 4) Valoriza câmbio (atrai capital externo). MECANISMOS DE TRANSMISSÃO: juros, crédito, câmbio, preços ativos, expectativas. OPERAÇÕES DE MERCADO ABERTO: compra/venda títulos. META INFLAÇÃO: COPOM define Selic.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'politica-fiscal-e-monetaria', question: 'O regime de metas de inflação adotado pelo Brasil caracteriza-se por:', options: ['Banco Central tem total liberdade para definir meta de inflação anualmente', 'Conselho Monetário Nacional (CMN) define meta, Banco Central usa política monetária para alcançá-la', 'Meta é secreta para não influenciar expectativas dos agentes econômicos', 'Utiliza exclusivamente controle de preços administrativos', 'Política fiscal é o principal instrumento, não a política monetária'], correctAnswer: 1, explanation: 'REGIME DE METAS DE INFLAÇÃO (1999): ESTRUTURA: 1) CMN define META (centro) e BANDA (tolerância); 2) COPOM (Banco Central) ajusta SELIC para atingir meta; 3) TRANSPARÊNCIA: decisões públicas, atas divulgadas. VANTAGENS: ancora expectativas, credibilidade, accountability. ÍNDICE: IPCA (IBGE). SE NÃO ATINGIR META: presidente BC escreve carta aberta explicando. TRADE-OFF: controle inflação vs crescimento econômico. INSTRUMENTOS: taxa juros, compulsório, redesconto.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'politica-fiscal-e-monetaria', question: 'Sobre a dívida pública, é CORRETO afirmar que:', options: ['Dívida bruta inclui ativos do governo, enquanto dívida líquida não', 'Dívida líquida desconta as reservas internacionais e créditos do setor público', 'Superávit primário significa que receitas totais superam despesas totais', 'Juros nominais não afetam a evolução da dívida pública', 'Relação Dívida/PIB é irrelevante para análise de sustentabilidade fiscal'], correctAnswer: 1, explanation: 'DÍVIDA PÚBLICA: DLSP (Dívida Líquida Setor Público) = dívida bruta - ativos (reservas, créditos). SUSTENTABILIDADE: relação Dívida/PIB deve ser estável. RESULTADO PRIMÁRIO: receitas - despesas (SEM juros). SUPERÁVIT PRIMÁRIO: economiza para pagar juros. RESULTADO NOMINAL: inclui juros. FATORES: déficit primário, juros reais, crescimento PIB, câmbio (dívida externa). RISCO FISCAL: alta dívida/PIB eleva juros (risco default). LRF: limite despesas, metas fiscais.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'politica-fiscal-e-monetaria', question: 'O depósito compulsório dos bancos comerciais no Banco Central é um instrumento de política monetária que:', options: ['Não afeta a capacidade de criação de moeda pelos bancos', 'Quando elevado, reduz a capacidade dos bancos de emprestar e criar moeda', 'É utilizado exclusivamente para garantir depósitos em caso de falência bancária', 'Tem efeito apenas sobre bancos públicos, não privados', 'Aumenta automaticamente quando há redução da taxa Selic'], correctAnswer: 1, explanation: 'DEPÓSITO COMPULSÓRIO (recolhimento compulsório): % depósitos que bancos devem manter no BC. FUNÇÃO: controlar oferta monetária e MULTIPLICADOR BANCÁRIO. ↑ COMPULSÓRIO: ↓ capacidade emprestar → ↓ criação moeda → política CONTRACIONISTA (↓ inflação). MULTIPLICADOR = 1/compulsório. Ex: compulsório 20% → multiplicador 5. VANTAGENS: efeito imediato, preciso. DESVANTAGENS: custos para bancos. OUTRAS FUNÇÕES: prudencial (segurança sistema), liquidez.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    // INFLAÇÃO (5)
    { area: 'fiscal', subject: 'economia', topic: 'inflacao', question: 'A inflação de demanda ocorre quando:', options: ['Custos de produção aumentam, elevando preços dos produtos finais', 'Demanda agregada supera a capacidade produtiva da economia', 'Governo imprime moeda sem lastro, causando hiperinflação', 'Há monopólios que controlam preços artificialmente', 'Ocorrem choques de oferta, como aumento do preço do petróleo'], correctAnswer: 1, explanation: 'TIPOS DE INFLAÇÃO: 1) DEMANDA: excesso demanda sobre oferta → preços sobem. Causas: ↑ gastos governo, ↑ crédito, ↑ exportações. Economia aquecida, pleno emprego. 2) CUSTOS: ↑ custos produção (salários, matérias-primas) → ↑ preços. 3) INERCIAL: expectativas inflacionárias → indexação → perpetua inflação. 4) ESTRUTURAL: gargalos setoriais. CONTROLE: demanda → política monetária contracionista; custos → políticas estruturais.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'inflacao', question: 'Os principais índices de inflação no Brasil são:', options: ['IPCA (consumidor), IGPM (mercado), INPC (famílias baixa renda) e IPA (atacado)', 'Apenas IPCA, pois é o único oficial reconhecido', 'IPCA, Selic e Taxa de Câmbio', 'IGP-DI, TJLP e CDI', 'IPC-Fipe, que é usado exclusivamente para metas de inflação'], correctAnswer: 0, explanation: 'ÍNDICES DE INFLAÇÃO BRASIL: 1) IPCA (IBGE): oficial, meta inflação, famílias 1-40 SM. 2) INPC (IBGE): famílias 1-5 SM. 3) IGP-M (FGV): IPA (60%) + IPC (30%) + INCC (10%), usado contratos. 4) IPA: atacado. 5) INCC: construção civil. 6) IPC-FIPE: São Paulo. IMPORTÂNCIA: correção salários, contratos, títulos públicos. IPCA: meta BC. DIFERENÇAS: cestas consumo, regiões, períodos coleta.', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'inflacao', question: 'Sobre a relação entre inflação e taxa de juros, é CORRETO afirmar que:', options: ['Taxa de juros real = taxa nominal - inflação esperada', 'Taxa de juros real = taxa nominal + inflação esperada', 'Inflação não afeta o poder de compra de aplicações financeiras', 'Taxa de juros nominal sempre é menor que a taxa real', 'Efeito Fisher não se aplica à economia brasileira'], correctAnswer: 0, explanation: 'EQUAÇÃO DE FISHER: taxa real ≈ taxa nominal - inflação. TAXA NOMINAL: observada no mercado (ex: 10% a.a.). TAXA REAL: desconta inflação, mede ganho efetivo de poder de compra. EXEMPLO: nominal 10%, inflação 4% → real ≈ 6%. IMPORTÂNCIA: 1) Investimentos: avaliar retorno real; 2) Financiamentos: custo real da dívida; 3) Política monetária: BC considera taxa real. EXPECTATIVAS: ex-ante (esperada) vs ex-post (realizada).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'inflacao', question: 'As expectativas de inflação são importantes porque:', options: ['Não influenciam o comportamento dos agentes econômicos', 'Afetam decisões de consumo, investimento e podem tornar-se autorrealizáveis', 'São irrelevantes para o Banco Central na definição da taxa Selic', 'Sempre coincidem exatamente com a inflação efetiva', 'Apenas consumidores formam expectativas, empresas não'], correctAnswer: 1, explanation: 'EXPECTATIVAS DE INFLAÇÃO: IMPORTÂNCIA: 1) DECISÕES: consumo (antecipar compras), poupança, investimento, reajuste preços/salários. 2) PROFECIA AUTORREALIZÁVEL: se todos esperam inflação alta → reajustam preços → inflação realmente sobe. 3) INÉRCIA INFLACIONÁRIA: expectativas perpetuam inflação (indexação). BC MONITORA: pesquisa Focus (mercado), ajusta Selic para ancorar expectativas. CREDIBILIDADE: BC confiável → expectativas convergem para meta. QUEBRA INÉRCIA: planos de estabilização.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'inflacao', question: 'A estagflação, fenômeno econômico observado na década de 1970, caracteriza-se por:', options: ['Alto crescimento econômico com baixa inflação', 'Estagnação econômica (baixo crescimento) combinada com inflação elevada', 'Deflação persistente em período de recessão', 'Crescimento econômico com pleno emprego', 'Inflação zero e desemprego crescente'], correctAnswer: 1, explanation: 'ESTAGFLAÇÃO: estagnação + inflação. RARO: normalmente inflação alta vem com economia aquecida. DÉCADA 70: choques petróleo (1973, 1979) → ↑ custos → inflação de custos + ↓ produção. DILEMA: política anti-inflação (↑ juros) agrava estagnação; política expansionista agrava inflação. QUEBROU: Curva Phillips tradicional. TEORIA: expectativas racionais, choques oferta. SOLUÇÃO: políticas estruturais (oferta) + controle demanda.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
  ];

  for (const q of moreQuestions) {
    await saveQuestion(q);
  }
  
  console.log('✅ Part 2/5 imported! Continuing...');
  
  // Continua com PIB, Comércio, Câmbio, Trabalho e Desenvolvimento...
  const finalQuestions: Question[] = [
    // PIB E CRESCIMENTO (5)
    { area: 'fiscal', subject: 'economia', topic: 'pib-e-crescimento-economico', question: 'A diferença entre PIB (Produto Interno Bruto) e PNB (Produto Nacional Bruto) está em que:', options: ['PIB mede produção dentro do país, PNB mede produção de nacionais (dentro e fora)', 'PIB inclui apenas bens finais, PNB inclui bens intermediários', 'PIB é nominal, PNB é sempre real', 'Não há diferença, são sinônimos', 'PIB mede fluxo, PNB mede estoque'], correctAnswer: 0, explanation: 'PIB vs PNB: PIB = produção DENTRO território nacional (brasileiros + estrangeiros). PNB = produção de NACIONAIS (no Brasil + exterior). RLEE (Renda Líquida Enviada ao Exterior): PNB = PIB - RLEE. Se RLEE > 0: mais remessas que recebimentos → PNB < PIB. RNB (Renda Nacional Bruta) = PNB. PIB: critério territorial. PNB: critério nacionalidade. BRASIL: PIB > PNB (empresas estrangeiras remessam lucros).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'pib-e-crescimento-economico', question: 'O PIB per capita é calculado dividindo-se o PIB total pela:', options: ['População economicamente ativa', 'População ocupada', 'População total do país', 'População urbana', 'Força de trabalho'], correctAnswer: 2, explanation: 'PIB PER CAPITA = PIB / População Total. SIGNIFICADO: renda média por habitante, proxy de padrão de vida. LIMITAÇÕES: 1) não considera DISTRIBUIÇÃO renda (desigualdade); 2) não mede bem-estar (saúde, educação); 3) ignora economia informal. ÍNDICES ALTERNATIVOS: IDH (saúde, educação, renda), Índice de Gini (desigualdade), felicidade. COMPARAÇÕES: PPP (Paridade Poder de Compra) ajusta diferenças custo vida entre países.', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'pib-e-crescimento-economico', question: 'Segundo a teoria do crescimento de Solow, no longo prazo:', options: ['Crescimento econômico depende exclusivamente de acumulação de capital', 'Crescimento sustentado advém apenas do progresso tecnológico', 'População não afeta o crescimento per capita', 'Poupança determina o nível de renda de longo prazo', 'Não há estado estacionário, crescimento é perpétuo'], correctAnswer: 1, explanation: 'MODELO DE SOLOW: CURTO PRAZO: ↑ poupança/investimento → ↑ capital → ↑ PIB. LONGO PRAZO: ESTADO ESTACIONÁRIO - retornos decrescentes do capital → crescimento per capita ZERO sem progresso tecnológico. CRESCIMENTO SUSTENTADO: apenas via PROGRESSO TECNOLÓGICO (A na função produção). CONVERGÊNCIA: países pobres crescem mais rápido (catching-up). FATORES: 1) capital físico; 2) capital humano; 3) tecnologia (TFP). CRÍTICA: tecnologia exógena (nova teoria: endógena).', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'pib-e-crescimento-economico', question: 'O deflator do PIB difere do IPCA porque:', options: ['Deflator mede preços de todos os bens produzidos, IPCA mede apenas consumo das famílias', 'Deflator é calculado pelo IBGE, IPCA pelo Banco Central', 'Não há diferença, ambos medem inflação da mesma forma', 'Deflator mede apenas bens importados, IPCA apenas nacionais', 'IPCA é usado para ajustar PIB nominal, deflator não'], correctAnswer: 0, explanation: 'DEFLATOR DO PIB vs IPCA: DEFLATOR: preços de TODOS bens/serviços produzidos internamente (C + I + G + X - M). Cesta variável (reflete mudanças produção). IPCA: preços CONSUMO FAMÍLIAS (cesta fixa). DIFERENÇAS: 1) abrangência; 2) ponderação; 3) bens importados (IPCA inclui, deflator não). DEFLATOR: PIB real = PIB nominal / Deflator. USO: ajustar séries históricas PIB.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'pib-e-crescimento-economico', question: 'A produtividade total dos fatores (PTF) representa:', options: ['Apenas a quantidade de trabalho e capital utilizados na produção', 'A eficiência com que trabalho e capital são combinados, refletindo tecnologia e organização', 'O salário médio dos trabalhadores', 'A taxa de investimento em máquinas e equipamentos', 'Exclusivamente o nível educacional da força de trabalho'], correctAnswer: 1, explanation: 'PRODUTIVIDADE TOTAL FATORES (PTF): parte crescimento NÃO explicada por ↑ trabalho ou capital. MEDE: eficiência, tecnologia, inovação, organização, instituições. FUNÇÃO PRODUÇÃO: Y = A × f(K, L), onde A = PTF. CRESCIMENTO: decomposição - parte vem de K e L (acumulação), parte de A (eficiência). ↑ PTF: educação, P&D, infraestrutura, instituições. RESIDUAL DE SOLOW: PTF como "resíduo" após descontar K e L.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    // COMÉRCIO INTERNACIONAL (5)
    { area: 'fiscal', subject: 'economia', topic: 'comercio-internacional', question: 'Segundo a teoria das vantagens comparativas de David Ricardo, o comércio entre países é benéfico quando:', options: ['Um país é mais eficiente na produção de todos os bens', 'Países especializam-se na produção do bem em que têm menor custo de oportunidade', 'Apenas países com vantagem absoluta devem comercializar', 'Não há diferenças de produtividade entre países', 'Países produzem exatamente os mesmos bens'], correctAnswer: 1, explanation: 'VANTAGENS COMPARATIVAS (Ricardo): país deve especializar-se no bem com MENOR CUSTO DE OPORTUNIDADE (não absoluto). MESMO que um país seja menos eficiente em tudo, ainda há ganhos de comércio. EXEMPLO: Portugal e Inglaterra (vinho e tecido). LÓGICA: focar no que faz relativamente melhor → comércio → ambos ganham. DIFERENTE de VANTAGEM ABSOLUTA (Smith): ser mais eficiente. IMPLICAÇÃO: livre comércio benéfico para todos.', difficulty: 'medium', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'comercio-internacional', question: 'A balança comercial de um país é:', options: ['A diferença entre exportações e importações de bens', 'A soma de todas as transações financeiras internacionais', 'Apenas o valor das exportações', 'A diferença entre investimentos diretos e de portfolio', 'O saldo das remessas de lucros e dividendos'], correctAnswer: 0, explanation: 'BALANÇA COMERCIAL: exportações - importações de BENS. SUPERÁVIT: X > M (exporta mais). DÉFICIT: M > X (importa mais). BALANÇA DE SERVIÇOS: viagens, transportes, royalties, etc. BALANÇA DE TRANSAÇÕES CORRENTES: comercial + serviços + rendas primárias + transferências. BALANÇO DE PAGAMENTOS: transações correntes + conta capital + conta financeira. EQUILÍBRIO: BP sempre fecha (contabilmente).', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'comercio-internacional', question: 'Sobre barreiras ao comércio internacional, é CORRETO afirmar que:', options: ['Tarifas de importação beneficiam sempre os consumidores', 'Quotas de importação limitam quantidade, não afetam preços', 'Barreiras não-tarifárias incluem normas técnicas, sanitárias e burocráticas', 'Subsídios à exportação não distorcem o comércio internacional', 'OMC (Organização Mundial do Comércio) proíbe todas as formas de proteção'], correctAnswer: 2, explanation: 'BARREIRAS COMERCIAIS: TARIFÁRIAS: impostos importação (↑ preço importado, protege produção nacional, ↓ consumo). QUOTAS: limites quantitativos. SUBSÍDIOS: ajuda produtores nacionais (exportação ou substituição importação). NÃO-TARIFÁRIAS: normas técnicas, sanitárias, fitossanitárias, burocracia (crescente importância). EFEITOS: proteção indústria nacional, custo para consumidores, ineficiência. OMC: rodadas negociação, solução controvérsias, busca livre comércio (com exceções).', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'comercio-internacional', question: 'A apreciação da moeda nacional (valorização do real) tende a:', options: ['Estimular as exportações e desestimular as importações', 'Tornar exportações mais caras e importações mais baratas', 'Não afetar o comércio exterior', 'Beneficiar apenas o setor agrícola', 'Reduzir o déficit comercial em todos os casos'], correctAnswer: 1, explanation: 'APRECIAÇÃO CAMBIAL (valorização real): ↑ valor moeda nacional. EFEITOS: 1) EXPORTAÇÕES: produtos nacionais ficam MAIS CAROS em moeda estrangeira → ↓ competitividade → ↓ X. 2) IMPORTAÇÕES: produtos estrangeiros ficam MAIS BARATOS em moeda nacional → ↑ M. 3) SALDO COMERCIAL: tende a piorar (↓ X e ↑ M). DEPRECIAÇÃO: efeito oposto. CURVA J: curto prazo pode piorar antes de melhorar. TURISMO: real forte favorece viagens ao exterior.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'comercio-internacional', question: 'O Mercosul (Mercado Comum do Sul) é classificado como:', options: ['Zona de livre comércio (sem tarifas entre membros)', 'União aduaneira (livre comércio + tarifa externa comum)', 'Mercado comum (livre circulação bens, serviços, capital e pessoas)', 'União econômica e monetária (moeda única)', 'Área de preferência tarifária (redução parcial tarifas)'], correctAnswer: 1, explanation: 'INTEGRAÇÃO ECONÔMICA (níveis): 1) ÁREA PREFERÊNCIA: redução tarifas; 2) ZONA LIVRE COMÉRCIO: elimina tarifas entre membros (ex: Nafta); 3) UNIÃO ADUANEIRA: livre comércio + TEC (Tarifa Externa Comum) - MERCOSUL; 4) MERCADO COMUM: + livre circulação fatores (UE objetivo); 5) UNIÃO ECONÔMICA: + políticas comuns; 6) UNIÃO MONETÁRIA: moeda única (Zona Euro). MERCOSUL: Brasil, Argentina, Uruguai, Paraguai. TEC: proteção conjunta.', difficulty: 'hard', examBoard: 'FCC', year: 2024 },
    
    // TAXA DE CÂMBIO (5)
    { area: 'fiscal', subject: 'economia', topic: 'taxa-de-cambio', question: 'No regime de câmbio flutuante, a taxa de câmbio é determinada por:', options: ['Decreto governamental fixando o valor diário', 'Banco Central que estabelece preços de compra e venda', 'Oferta e demanda de moeda estrangeira no mercado', 'Acordo internacional entre bancos centrais', 'Paridade com o ouro (padrão-ouro)'], correctAnswer: 2, explanation: 'REGIMES CAMBIAIS: 1) FIXO: BC fixa taxa, intervém sempre (compra/vende reservas). Risco: crise cambial se insustentável. 2) FLUTUANTE (BRASIL): mercado determina (oferta × demanda). BC pode intervir ocasionalmente (flutuação suja). 3) BANDAS: flutua dentro de limites. CÂMBIO FLUTUANTE: ↑ demanda dólar → ↑ cotação (depreciação real). VANTAGENS: absorve choques, autonomia monetária. DESVANTAGENS: volatilidade.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'taxa-de-cambio', question: 'Quando dizemos que o dólar passou de R$ 5,00 para R$ 5,50, isso significa que houve:', options: ['Apreciação do real', 'Depreciação do real (ou apreciação do dólar)', 'Nenhuma alteração no poder de compra', 'Valorização da balança comercial', 'Redução das reservas internacionais'], correctAnswer: 1, explanation: 'COTAÇÃO NO BRASIL (incerto): R$/US$ (quanto reais por dólar). ↑ cotação (ex: 5,00 → 5,50): DEPRECIAÇÃO do real (real vale menos, precisa mais reais para comprar 1 dólar) = APRECIAÇÃO do dólar. ↓ cotação: APRECIAÇÃO do real = DEPRECIAÇÃO do dólar. ATENÇÃO: pode confundir! EFEITOS DEPRECIAÇÃO REAL: ↑ competitividade exportações, ↑ inflação (importados), ↑ custo dívida externa em reais.', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'taxa-de-cambio', question: 'A paridade do poder de compra (PPP - Purchasing Power Parity) sugere que, no longo prazo:', options: ['Taxa de câmbio se ajusta para igualar preços de bens idênticos em diferentes países', 'Taxa de câmbio é sempre fixa, independente de inflação', 'Não há relação entre câmbio e níveis de preços', 'Países com inflação mais alta terão moeda valorizada', 'Comércio internacional não afeta taxa de câmbio'], correctAnswer: 0, explanation: 'PARIDADE PODER DE COMPRA (PPP): LONGO PRAZO, câmbio se ajusta para que MESMO bem custe IGUAL em diferentes países (convertido pela taxa). LÓGICA: se não, haveria arbitragem (comprar onde é barato, vender onde é caro). VERSÃO RELATIVA: país com ↑ inflação → moeda DEPRECIA proporcionalmente. LIMITAÇÕES: 1) bens não comercializáveis (haircut); 2) custos transporte/tarifas; 3) curto prazo não vale. ÍNDICE BIG MAC: teste informal PPP.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'taxa-de-cambio', question: 'O carry trade consiste em:', options: ['Exportar commodities aproveitando câmbio favorável', 'Tomar empréstimo em moeda com juros baixos e aplicar em moeda com juros altos', 'Comprar dólares e guardar embaixo do colchão', 'Investir apenas em títulos públicos nacionais', 'Operação proibida pelo Banco Central'], correctAnswer: 1, explanation: 'CARRY TRADE: operação especulativa. ESTRATÉGIA: 1) EMPRESTAR em país juros BAIXOS (ex: Japão, EUA); 2) APLICAR em país juros ALTOS (ex: Brasil). GANHO: diferencial juros (quando expectativa câmbio estável). RISCO: depreciação moeda destino pode anular ganho. EFEITOS: 1) entrada capital → aprecia moeda; 2) volatilidade (fuga rápida em crise); 3) BC monitora. BRASIL: historicamente atraiu carry trade (juros altos).', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'taxa-de-cambio', question: 'As reservas internacionais de um país são importantes porque:', options: ['Servem apenas para pagar dívida externa', 'Proporcionam segurança contra crises cambiais e garantem liquidez internacional', 'Não têm utilidade prática para a economia', 'São usadas exclusivamente para fins militares', 'Reduzem automaticamente a inflação doméstica'], correctAnswer: 1, explanation: 'RESERVAS INTERNACIONAIS: ativos externos líquidos (moedas fortes, ouro, DES). FUNÇÕES: 1) LIQUIDEZ: pagar importações em crise; 2) INTERVENÇÃO: BC pode intervir no câmbio; 3) CONFIANÇA: reduz risco país, atrai investimento; 4) COLCHÃO: proteção contra ataques especulativos. CUSTO: oportunidade (rendem pouco). NÍVEL ÓTIMO: debate (regras: 3 meses importações, % PIB). BRASIL: ~US$ 350 bi (2024). COMPOSIÇÃO: dólares, euros, ouro.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    // MERCADO DE TRABALHO (5)
    { area: 'fiscal', subject: 'economia', topic: 'mercado-de-trabalho', question: 'A População Economicamente Ativa (PEA) é composta por:', options: ['Apenas pessoas empregadas', 'Pessoas ocupadas e desocupadas (desempregadas) em idade de trabalhar', 'Toda a população do país', 'Apenas trabalhadores formais', 'Somente desempregados'], correctAnswer: 1, explanation: 'CONCEITOS (IBGE/PNAD): POPULAÇÃO TOTAL → em idade trabalhar (14+ anos) → PEA + PEI. PEA (força trabalho): OCUPADOS + DESOCUPADOS (procuram emprego). PEI (Não Economicamente Ativa): estudantes, aposentados, do lar (não procuram). TAXA DESEMPREGO = desocupados / PEA. TAXA PARTICIPAÇÃO = PEA / população idade trabalhar. DESEMPREGO OCULTO: desalentados (pararam de procurar).', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'mercado-de-trabalho', question: 'O desemprego friccional é caracterizado por:', options: ['Resultar de recessões econômicas e queda de demanda', 'Ser temporário, ocorrendo durante transição entre empregos', 'Decorrer de mudanças estruturais na economia (automação)', 'Representar desemprego de longo prazo e difícil reinserção', 'Não existir em economias desenvolvidas'], correctAnswer: 1, explanation: 'TIPOS DESEMPREGO: 1) FRICCIONAL: temporário, busca/transição empregos. Normal, saudável. Tempo para matching. 2) ESTRUTURAL: mudanças estrutura econômica (tecnologia, globalização). Habilidades desatualizadas. Longo prazo. 3) CÍCLICO/CONJUNTURAL: recessões, ↓ demanda agregada. Sensível a política macroeconômica. 4) SAZONAL: variações sazonais (agricultura, turismo). NAIRU: taxa natural (friccional + estrutural). POLÍTICAS: friccional → ↑ informação; estrutural → requalificação; cíclico → política expansionista.', difficulty: 'medium', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'mercado-de-trabalho', question: 'O salário mínimo, quando fixado acima do salário de equilíbrio de mercado, tende a:', options: ['Não afetar o mercado de trabalho', 'Aumentar emprego, pois trabalhadores ganham mais', 'Criar desemprego involuntário, pois oferta de trabalho excede demanda', 'Reduzir automaticamente a inflação', 'Beneficiar apenas trabalhadores qualificados'], correctAnswer: 2, explanation: 'SALÁRIO MÍNIMO: piso legal. EFEITOS SE ACIMA EQUILÍBRIO: ↑ oferta trabalho (mais querem trabalhar por salário maior), ↓ demanda (empresas contratam menos). RESULTADO: DESEMPREGO (oferta > demanda). DEBATE: 1) CONTRA: causa desemprego, afeta jovens/não qualificados; 2) A FAVOR: reduz pobreza, ↑ consumo, monopsônio (poder empregadores). EVIDÊNCIA: depende magnitude, elasticidades, enforcement. BRASIL: impacta setor formal, informais não afetados diretamente.', difficulty: 'medium', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'mercado-de-trabalho', question: 'A Lei de Okun estabelece uma relação entre:', options: ['Inflação e desemprego (Curva de Phillips)', 'Crescimento do PIB e variação da taxa de desemprego', 'Salários e produtividade', 'Oferta e demanda de moeda', 'Exportações e importações'], correctAnswer: 1, explanation: 'LEI DE OKUN: relação EMPÍRICA entre crescimento PIB e desemprego. REGRA: crescimento PIB ACIMA potencial → ↓ desemprego; ABAIXO potencial → ↑ desemprego. COEFICIENTE: varia por país (Brasil ~2-3%). Exemplo: PIB cresce 1% acima potencial → desemprego cai ~0,5 p.p. LÓGICA: ↑ produção → ↑ contratações. LIMITAÇÕES: relação instável, depende estrutura mercado trabalho. POLÍTICA: para reduzir desemprego, necessário crescimento robusto.', difficulty: 'hard', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'mercado-de-trabalho', question: 'Sobre a informalidade no mercado de trabalho brasileiro, é CORRETO afirmar que:', options: ['Trabalhadores informais têm todos os direitos trabalhistas garantidos', 'Informalidade não tem impacto sobre arrecadação tributária e previdenciária', 'Trabalhadores informais não contribuem para Previdência e não têm proteção CLT', 'Informalidade é inexistente no Brasil atualmente', 'Apenas trabalhadores rurais podem ser informais'], correctAnswer: 2, explanation: 'INFORMALIDADE BRASIL: trabalho SEM carteira assinada ou conta própria sem CNPJ. CARACTERÍSTICAS: 1) SEM direitos CLT (férias, 13º, FGTS); 2) NÃO contribuem INSS (sem aposentadoria); 3) menor renda média. CAUSAS: alto custo formalização, burocracia, tributação, baixa fiscalização. CONSEQUÊNCIAS: 1) ↓ arrecadação; 2) ↓ proteção social; 3) ↓ produtividade. TAXA: ~40% ocupados (2024). POLÍTICAS: simplificação (MEI), redução custos, fiscalização.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
    
    // DESENVOLVIMENTO ECONÔMICO (5)
    { area: 'fiscal', subject: 'economia', topic: 'desenvolvimento-economico', question: 'O Índice de Desenvolvimento Humano (IDH) mede o desenvolvimento considerando:', options: ['Apenas renda per capita', 'Apenas expectativa de vida', 'Renda, educação (escolaridade) e saúde (longevidade)', 'Exclusivamente indicadores ambientais', 'Apenas taxa de alfabetização'], correctAnswer: 2, explanation: 'IDH (PNUD/ONU): índice composto (0 a 1). DIMENSÕES: 1) LONGEVIDADE: expectativa de vida ao nascer; 2) EDUCAÇÃO: anos médios estudo + anos esperados; 3) RENDA: RNB per capita PPP. CÁLCULO: média geométrica das 3 dimensões. CLASSIFICAÇÃO: muito alto (>0,800), alto, médio, baixo. BRASIL: ~0,760 (alto). VANTAGENS: holístico, além do PIB. LIMITAÇÕES: não capta desigualdade, liberdades, meio ambiente. IDH Ajustado: considera desigualdade.', difficulty: 'easy', examBoard: 'CESPE', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'desenvolvimento-economico', question: 'A diferença entre crescimento e desenvolvimento econômico está em que:', options: ['Crescimento mede apenas ↑ PIB; desenvolvimento inclui melhorias qualitativas (educação, saúde, distribuição)', 'São sinônimos, não há diferença', 'Crescimento é de longo prazo, desenvolvimento de curto prazo', 'Desenvolvimento mede apenas PIB nominal', 'Crescimento considera apenas setor agrícola'], correctAnswer: 0, explanation: 'CRESCIMENTO vs DESENVOLVIMENTO: CRESCIMENTO: ↑ quantitativo PIB, renda. Necessário mas insuficiente. DESENVOLVIMENTO: mudanças qualitativas e estruturais - ↑ bem-estar, educação, saúde, igualdade, liberdades. POSSÍVEL: crescimento sem desenvolvimento (concentração renda, poluição). OBJETIVO: desenvolvimento sustentável e inclusivo. INDICADORES: IDH, Gini, pobreza, mortalidade infantil. ESTRATÉGIAS: investimento capital humano, infraestrutura, instituições, inovação.', difficulty: 'easy', examBoard: 'FCC', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'desenvolvimento-economico', question: 'A "maldição dos recursos naturais" sugere que:', options: ['Países ricos em recursos naturais sempre se desenvolvem mais rapidamente', 'Abundância de recursos pode levar a menor diversificação, corrupção e fraco desenvolvimento institucional', 'Recursos naturais não têm nenhum impacto sobre o desenvolvimento', 'Apenas países sem recursos naturais se desenvolvem', 'Minérios sempre garantem desenvolvimento sustentável'], correctAnswer: 1, explanation: 'MALDIÇÃO RECURSOS (resource curse / paradoxo abundância): países ricos recursos naturais (petróleo, minérios) frequentemente têm MENOR crescimento/desenvolvimento. CAUSAS: 1) DOENÇA HOLANDESA: valoriza câmbio → prejudica indústria; 2) baixa diversificação econômica; 3) rent-seeking, corrupção; 4) instituições fracas; 5) volatilidade preços commodities; 6) conflitos. EXEMPLOS: Venezuela, Nigéria. CONTRA-EXEMPLOS: Noruega, Botswana (boa governança). SOLUÇÃO: diversificação, transparência, fundos soberanos, instituições fortes.', difficulty: 'hard', examBoard: 'FGV', year: 2024 },
    { area: 'fiscal', subject: 'economia', topic: 'desenvolvimento-economico', question: 'O Índice de Gini mede:', options: ['Crescimento econômico de um país', 'Desigualdade na distribuição de renda', 'Inflação acumulada', 'Taxa de desemprego', 'Balança comercial'], correctAnswer: 1, explanation: 'ÍNDICE DE GINI: mede DESIGUALDADE distribuição renda (ou riqueza). ESCALA: 0 (perfeita igualdade, todos ganham igual) a 1 (máxima desigualdade, uma pessoa tem tudo). CURVA DE LORENZ: gráfico % população × % renda acumulada. Gini = área entre curva e linha igualdade. BRASIL: ~0,52 (alto, melhorou de ~0,60 anos 90). COMPARAÇÃO: Escandinávia ~0,25, África do Sul ~0,63. POLÍTICAS: transferências (Bolsa Família), tributação progressiva, educação.', difficulty: 'medium', examBoard: 'CESPE', year: 2023 },
    { area: 'fiscal', subject: 'economia', topic: 'desenvolvimento-economico', question: 'Os Objetivos de Desenvolvimento Sustentável (ODS) da ONU incluem metas relacionadas a:', options: ['Apenas crescimento econômico', 'Exclusivamente preservação ambiental', 'Dimensões econômica, social e ambiental (erradicação pobreza, educação, clima, etc.)', 'Somente questões militares', 'Apenas países desenvolvidos'], correctAnswer: 2, explanation: 'ODS (AGENDA 2030 - ONU): 17 objetivos integrados. EXEMPLOS: 1-Erradicação pobreza; 2-Fome zero; 3-Saúde; 4-Educação; 5-Igualdade gênero; 8-Trabalho decente e crescimento; 10-Redução desigualdades; 13-Ação clima; 16-Paz, justiça, instituições. TRIPÉ: econômico, social, AMBIENTAL (sustentabilidade). UNIVERSAL: todos países (não só pobres). 169 METAS específicas. MONITORAMENTO: indicadores. IMPORTÂNCIA: articulação desenvolvimento com sustentabilidade.', difficulty: 'medium', examBoard: 'FCC', year: 2024 },
  ];

  for (const q of finalQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Economia questions seeded successfully!');
}
