import { projectId, publicAnonKey } from '../utils/supabase/info';

const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-50734795`;

interface Question {
  area: string;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  examBoard: string;
  year: number;
}

async function saveQuestion(question: Question) {
  try {
    const formattedQuestion = {
      area: question.area,
      subject: question.subject,
      topic: question.topic,
      enunciado: question.question,
      alternativas: {
        A: question.options[0],
        B: question.options[1],
        C: question.options[2],
        D: question.options[3],
        E: question.options[4],
      },
      gabarito: ['A', 'B', 'C', 'D', 'E'][question.correctAnswer],
      explicacao: question.explanation,
      banca: question.examBoard,
      ano: question.year,
      cargo: question.difficulty,
    };

    const response = await fetch(`${API_BASE}/questions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${publicAnonKey}`,
      },
      body: JSON.stringify(formattedQuestion),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response:', errorText);
      throw new Error(`Failed to save question: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving question:', error);
    throw error;
  }
}

// ============= ALL AUDITORIA QUESTIONS =============
export async function seedAllAuditoriaQuestions() {
  console.log('🚀 Starting to seed ALL Auditoria questions...');
  
  const allQuestions: Question[] = [
    // ============= CONCEITOS E OBJETIVOS DA AUDITORIA (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'conceitos-e-objetivos-auditoria', question: 'O objetivo da auditoria das demonstrações contábeis é:', options: ['Detectar todas as fraudes existentes', 'Expressar opinião sobre se as demonstrações estão apresentadas adequadamente, em conformidade com estrutura de relatório financeiro aplicável', 'Garantir que não há erros nas demonstrações', 'Certificar a lucratividade da empresa', 'Aprovar as demonstrações contábeis'], correctAnswer: 1, explanation: 'OBJETIVO AUDITORIA (NBC TA 200): aumentar grau de CONFIANÇA nas demonstrações contábeis por usuários. AUDITOR expressa OPINIÃO sobre se demonstrações apresentadas ADEQUADAMENTE, em TODOS aspectos relevantes, conforme ESTRUTURA RELATÓRIO FINANCEIRO aplicável (BR-GAAP, IFRS). NÃO É OBJETIVO: garantir ausência total erros/fraudes (segurança RAZOÁVEL, não absoluta). Detectar fraude: responsabilidade ADMINISTRAÇÃO (controles internos). Auditor: avaliar riscos, aplicar procedimentos. IMPORTANTE: opinião sobre ADEQUAÇÃO apresentação, não aprovação/certificação qualidade gestão. Limitação inerente: amostragem, julgamento.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'conceitos-e-objetivos-auditoria', question: 'Segurança razoável em auditoria significa:', options: ['Certeza absoluta de que não há distorções', 'Alto nível de segurança, mas não absoluto, devido a limitações inerentes', 'Garantia de 100% de detecção de fraudes', 'Apenas verificação superficial', 'Ausência de procedimentos de auditoria'], correctAnswer: 1, explanation: 'SEGURANÇA RAZOÁVEL (NBC TA 200): ALTO nível segurança, mas NÃO ABSOLUTO. LIMITAÇÕES INERENTES: 1) AMOSTRAGEM: não examina 100% transações. 2) JULGAMENTO: estimativas contábeis envolvem subjetividade. 3) CONTROLES INTERNOS: conluio pode contornar. 4) EVIDÊNCIAS: persuasivas, não conclusivas. 5) FRAUDE: ocultação sofisticada dificulta detecção. RESULTADO: risco detecção inevitável (risco auditoria). NÃO significa: trabalho malfeito ou insuficiente. É reconhecimento limitações práticas/custos. MITIGAÇÃO: ceticismo profissional, procedimentos apropriados, supervisão. IMPORTANTE: usuários devem entender não há garantia absoluta. Responsabilidade compartilhada (administração/auditoria).', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'conceitos-e-objetivos-auditoria', question: 'Sobre a responsabilidade do auditor, é correto afirmar:', options: ['O auditor é responsável pela elaboração das demonstrações contábeis', 'A responsabilidade pelas demonstrações é da administração; o auditor é responsável por sua opinião', 'O auditor garante a continuidade operacional da entidade', 'O auditor decide a distribuição de dividendos', 'A detecção de fraude é responsabilidade exclusiva do auditor'], correctAnswer: 1, explanation: 'RESPONSABILIDADES (NBC TA 200/240): ADMINISTRAÇÃO: 1) ELABORAR demonstrações conforme estrutura aplicável. 2) CONTROLES INTERNOS adequados. 3) PREVENIR/DETECTAR fraudes/erros. 4) FORNECER informações/acesso auditor. AUDITOR: 1) PLANEJAR/EXECUTAR trabalho obter segurança razoável. 2) EXPRESSAR OPINIÃO fundamentada. 3) CETICISMO PROFISSIONAL. 4) Avaliar RISCOS distorção relevante (fraude/erro). 5) COMUNICAR deficiências controle. IMPORTANTE: responsabilidades NÃO SE CONFUNDEM. Auditor não substitui administração. Fraude: responsabilidade primária administração (prevenir). Auditor: identificar riscos, procedimentos resposta. Continuidade: administração avalia; auditor opina sobre avaliação. Dividendos: decisão acionistas/administração.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'conceitos-e-objetivos-auditoria', question: 'Ceticismo profissional significa:', options: ['Desconfiança permanente da administração', 'Postura que inclui estar alerta a evidências contraditórias e questionar evidências de auditoria', 'Acreditar em tudo que a administração informa', 'Apenas duvidar de tudo', 'Não fazer perguntas à administração'], correctAnswer: 1, explanation: 'CETICISMO PROFISSIONAL (NBC TA 200): postura que inclui MENTE QUESTIONADORA e AVALIAÇÃO CRÍTICA evidências auditoria. CARACTERÍSTICAS: 1) ALERTA: condições que indiquem distorção (erro/fraude). 2) QUESTIONAMENTO: evidências contraditórias, confiabilidade respostas/documentos. 3) NÃO PRESUMIR: nem desonestidade, nem honestidade inquestionável. 4) INDEPENDÊNCIA MENTAL: julgamento próprio, não influenciado. APLICAÇÃO: durante TODO trabalho (planejamento, execução, conclusão). Especialmente: transações incomuns, estimativas, relacionadas partes, julgamentos administração. NÃO É: suspeita permanente/desconfiança. É equilíbrio profissional. ESSENCIAL: detectar fraudes sofisticadas, avaliar adequadamente riscos. Diferencia auditoria de mera conferência.', difficulty: 'easy', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'conceitos-e-objetivos-auditoria', question: 'Risco de auditoria é composto por:', options: ['Apenas risco de detecção', 'Risco de distorção relevante (inerente e controle) e risco de detecção', 'Somente risco inerente', 'Apenas risco de controle', 'Risco de mercado e risco operacional'], correctAnswer: 1, explanation: 'RISCO DE AUDITORIA (NBC TA 200): possibilidade auditor expressar OPINIÃO INADEQUADA quando demonstrações DISTORCIDAS relevantemente. COMPONENTES: 1) RISCO DISTORÇÃO RELEVANTE (RDR): a) Risco INERENTE (RI): suscetibilidade distorção, ausência controles. Natureza negócio, complexidade transações, estimativas. b) Risco CONTROLE (RC): controles não previnam/detectem distorção. Efetividade controles internos. 2) RISCO DETECÇÃO (RD): procedimentos auditor não detectem distorção existente. Natureza/época/extensão procedimentos. RELAÇÃO INVERSA: ↑RDR → ↓RD aceito (mais procedimentos). ↓RDR → ↑RD aceito (menos procedimentos). FÓRMULA: RA = RDR × RD. OBJETIVO: reduzir RA a nível aceitavelmente baixo. IMPORTANTE: RI e RC são da ENTIDADE; RD é do AUDITOR (controlável).', difficulty: 'hard', examBoard: 'CFC', year: 2024 },

    // ============= AUDITORIA INTERNA (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-interna', question: 'A Auditoria Interna se caracteriza por:', options: ['Ser executada por profissional independente e externo', 'Ser executada por empregados da própria entidade para avaliar controles, processos e governança', 'Emitir parecer para o mercado', 'Ser obrigatória para todas as empresas', 'Apenas verificar cumprimento de normas externas'], correctAnswer: 1, explanation: 'AUDITORIA INTERNA (NBC TI 01 - revogada, atual: boas práticas): atividade INDEPENDÊNCIA dentro organização, executada por EMPREGADOS. OBJETIVOS: 1) AVALIAR eficácia CONTROLES INTERNOS. 2) VERIFICAR cumprimento políticas/procedimentos. 3) EXAMINAR informações financeiras/operacionais. 4) REVISAR operações/programas. 5) ASSESSORAR administração. CARACTERÍSTICAS: subordinação ALTA ADMINISTRAÇÃO (independência funcional). Acesso irrestrito. Recomendações melhoria. vs AUDITORIA EXTERNA: interna = empregado, melhoria processos, relatório interno. Externa = independente, opinião demonstrações, relatório público. IMPORTANTE: não substitui externa. Complementares. Interna: apoio gestão, prevenção, consultoria. Externa: asseguração mercado.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-interna', question: 'São objetivos da Auditoria Interna:', options: ['Apenas emitir parecer para investidores', 'Avaliar a eficácia dos controles internos, identificar riscos e propor melhorias nos processos', 'Somente auditar demonstrações financeiras', 'Executar a contabilidade da empresa', 'Apenas fiscalizar empregados'], correctAnswer: 1, explanation: 'OBJETIVOS AUDITORIA INTERNA: 1) AVALIAR EFICÁCIA: controles internos, gestão riscos, governança corporativa. 2) IDENTIFICAR RISCOS: operacionais, conformidade, financeiros, fraude. 3) VERIFICAR CONFORMIDADE: leis, regulamentos, políticas internas. 4) EXAMINAR INFORMAÇÕES: confiabilidade, tempestividade dados. 5) AVALIAR OPERAÇÕES: eficiência, eficácia, economicidade. 6) RECOMENDAR MELHORIAS: processos, controles, sistemas. 7) INVESTIGAR: irregularidades, fraudes quando solicitado. ABORDAGEM: baseada RISCOS (prioriza áreas maior risco). PLANO ANUAL: aprovado alta administração/comitê auditoria. RESULTADO: relatórios gerenciais, matriz riscos, planos ação. IMPORTANTE: adiciona VALOR organização. Papel consultivo + asseguração. Suporte gestão estratégica.', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-interna', question: 'A independência do auditor interno é garantida por:', options: ['Sua subordinação ao contador', 'Subordinação à alta administração e reporte ao comitê de auditoria ou conselho', 'Não ter independência por ser empregado', 'Subordinação ao gerente operacional', 'Não é necessária independência'], correctAnswer: 1, explanation: 'INDEPENDÊNCIA AUDITOR INTERNO: ESTRUTURAL: 1) SUBORDINAÇÃO: Alta Administração (CEO), idealmente Comitê Auditoria/Conselho Administração. NÃO subordinado a: gerentes operacionais, áreas auditadas. 2) REPORTE: funcional ao Comitê (independência), administrativo ao CEO (recursos). FUNCIONAL: 1) OBJETIVIDADE: imparcialidade, sem conflitos interesse. 2) LIVRE ACESSO: documentos, áreas, pessoas. 3) RECURSOS ADEQUADOS: equipe, orçamento, tecnologia. LIMITAÇÕES: vínculo empregatício limita independência vs auditor externo. MITIGAÇÕES: estatuto auditoria interna (aprovado Conselho), rotação auditores internos áreas, vedação auditoria trabalho próprio. IMPORTANTE: independência = credibilidade. Boa prática: auditoria interna reportar Comitê Auditoria (órgão independente administração).', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-interna', question: 'O relacionamento entre auditoria interna e externa deve ser:', options: ['De completa independência sem interação', 'De coordenação e cooperação para evitar duplicidade de esforços', 'Auditoria interna subordina-se à externa', 'Ambas fazem exatamente o mesmo trabalho', 'Não deve haver comunicação'], correctAnswer: 1, explanation: 'RELACIONAMENTO INTERNA × EXTERNA (NBC TA 610): COORDENAÇÃO/COOPERAÇÃO: evitar duplicidade, otimizar recursos, complementariedade. AUDITOR EXTERNO pode: 1) UTILIZAR trabalho auditoria interna (se competente/objetiva). 2) SOLICITAR assistência específica. 3) COMPARTILHAR achados relevantes. BENEFÍCIOS COORDENAÇÃO: 1) Eficiência: auditor externo confia trabalhos internos (reduz testes). 2) Conhecimento: interna conhece profundamente organização. 3) Cobertura: áreas operacionais (interna) + financeiras (externa). LIMITES: auditor EXTERNO mantém responsabilidade EXCLUSIVA por opinião. Não pode delegar totalmente. Deve AVALIAR: competência, objetividade interna. IMPORTANTE: trabalhos COMPLEMENTARES, não substitutos. Interna: processos/controles. Externa: demonstrações financeiras. Comunicação estruturada, respeito independências.', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-interna', question: 'São ferramentas da Auditoria Interna:', options: ['Apenas fluxogramas', 'Matriz de riscos, fluxogramas, questionários de controle interno, testes substantivos e de controles', 'Somente entrevistas', 'Apenas análise de balanços', 'Não utiliza ferramentas específicas'], correctAnswer: 1, explanation: 'FERRAMENTAS AUDITORIA INTERNA: 1) MATRIZ RISCOS: identificação, avaliação, priorização riscos. 2) FLUXOGRAMAS: mapeamento processos, identificação controles/gaps. 3) QUESTIONÁRIOS: avaliação controles internos (COSO). 4) TESTES: a) Controles: efetividade operacional. b) Substantivos: exatidão valores. 5) AMOSTRAGEM: estatística/não estatística. 6) ANÁLISE DADOS: mineração dados, análise 100% população. 7) BENCHMARKING: comparação melhores práticas. 8) ENTREVISTAS: levantamento informações, confirmações. 9) INSPEÇÃO: física ativos, documentos. 10) OBSERVAÇÃO: execução processos. SOFTWARE: ACL, IDEA, Tableau (análise dados). IMPORTANTE: abordagem baseada RISCOS. Ferramentas variam conforme objetivo trabalho. Tecnologia cada vez mais presente (auditoria contínua, big data).', difficulty: 'medium', examBoard: 'CFC', year: 2024 },

    // ============= AUDITORIA EXTERNA/INDEPENDENTE (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-externa-independente', question: 'A independência do auditor externo é essencial porque:', options: ['Permite que ele trabalhe mais rápido', 'Garante credibilidade da opinião para usuários das demonstrações', 'Reduz o custo da auditoria', 'Elimina a necessidade de procedimentos', 'Facilita o relacionamento com a administração'], correctAnswer: 1, explanation: 'INDEPENDÊNCIA AUDITOR EXTERNO (NBC PA 290, CFC): pilar CREDIBILIDADE opinião. USUÁRIOS confiam demonstrações auditadas porque auditor é INDEPENDENTE (sem conflito interesse, imparcialidade). DIMENSÕES: 1) INDEPENDÊNCIA APARÊNCIA: percepção terceiros razoáveis/informados. 2) INDEPENDÊNCIA MENTE: estado mental (objetividade, integridade, ceticismo). AMEAÇAS: autorrevisão, interesse próprio, advocacia, familiaridade, intimidação. SALVAGUARDAS: rodízio sócios, revisão qualidade, comitê auditoria, vedações (serviços não-auditoria, relacionamentos). CONSEQUÊNCIAS PERDA: opinião sem valor, responsabilidade civil/criminal, perda registro CVM/CFC. IMPORTANTE: independência ≠ neutralidade completa (tem cliente/honorários), mas INTERESSE PÚBLICO prevalece. Regulação rigorosa (SOX, CVM 308).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-externa-independente', question: 'Segundo normas CVM e CFC, são vedadas ao auditor independente:', options: ['Apenas serviços de consultoria tributária', 'Prestar serviços de escrituração contábil e manter vínculo empregatício com auditado', 'Somente ter participação acionária', 'Apenas auditar empresas do mesmo setor', 'Não há vedações específicas'], correctAnswer: 1, explanation: 'VEDAÇÕES AUDITOR INDEPENDENTE (CVM Instrução 308, NBC PA 290): SITUAÇÕES INCOMPATÍVEIS: 1) ESCRITURAÇÃO CONTÁBIL: preparar demonstrações que auditará (autorrevisão). 2) VÍNCULO EMPREGATÍCIO: auditor/equipe com auditado/coligadas. 3) PARTICIPAÇÃO FINANCEIRA: ações, quotas auditado (interesse próprio). 4) RELACIONAMENTO PESSOAL: cônjuge/parentes administração/controle. 5) HONORÁRIOS CONTINGENTES: baseados resultado auditoria. 6) SERVIÇOS PROIBIDOS: avaliação ativos para demonstrações, auditoria interna (operacional), advocacia, recrutamento executivos. ROTATIVIDADE: sócio 5 anos (firma 10 anos S.A. grande porte - Brasil suspendeu). OBJETIVO: eliminar ameaças independência. PUNIÇÃO: perda registro, multas, responsabilização. IMPORTANTE: lista não exaustiva. Princípio: evitar autorrevisão, interesse próprio, advocacia.', difficulty: 'hard', examBoard: 'CVM', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-externa-independente', question: 'O rodízio de auditores visa:', options: ['Reduzir custos de auditoria', 'Preservar independência, evitando familiaridade excessiva entre auditor e auditado', 'Aumentar honorários', 'Dificultar o trabalho de auditoria', 'Apenas cumprir formalidade'], correctAnswer: 1, explanation: 'RODÍZIO AUDITORES (CVM 308 - revogada CVM 765, mas princípio mantido): OBJETIVO: preservar INDEPENDÊNCIA evitando FAMILIARIDADE excessiva. Longo relacionamento → risco: complacência, confiança cega, perda ceticismo. TIPOS: 1) RODÍZIO FIRMA: auditoria externa troca firma (CVM: exigido, depois dispensado para firmas Big Four com revisão externa qualidade). 2) RODÍZIO SÓCIO: sócio-chave troca a cada 5 anos (CFC mantém). PRÓS: nova visão crítica, independência reforçada. CONTRAS: perda conhecimento negócio, custo transição, período aprendizado. SOLUÇÃO INTERMEDIÁRIA: rodízio sócio (mantém firma conhecedora, troca responsável). INTERNACIONAL: SOX (EUA): rodízio sócio 5 anos. União Europeia: firma 10 anos (extensível 20 com rotação). IMPORTANTE: equilíbrio independência × conhecimento negócio.', difficulty: 'medium', examBoard: 'CVM', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-externa-independente', question: 'Sobre os honorários de auditoria, é incorreto afirmar:', options: ['Devem ser justos e adequados ao trabalho', 'Podem ser contingentes ao resultado da auditoria para incentivar qualidade', 'Não podem criar dependência financeira excessiva', 'Devem ser aprovados pelo comitê de auditoria', 'Honorários muito baixos podem comprometer qualidade'], correctAnswer: 1, explanation: 'HONORÁRIOS AUDITORIA (NBC PA 290): PRINCÍPIOS: 1) JUSTOS/RAZOÁVEIS: refletir complexidade, risco, horas, qualificação. 2) NÃO CONTINGENTES: VEDADO basear em resultado auditoria (tipo opinião, achados). Cria interesse próprio. 3) NÃO DEPENDÊNCIA: receita de um cliente não deve ser excessiva (>15% faturamento firma/sócio - risco). 4) TRANSPARÊNCIA: divulgação honorários (S.A. abertas). APROVAÇÃO: Comitê Auditoria/Conselho (governança). INCORRETO B: honorários contingentes PROIBIDOS. Compromete independência (interesse resultado favorável). RISCOS: honorários muito BAIXOS: compromete qualidade (lowballing). Muito ALTOS de não-auditoria: dependência. IMPORTANTE: CVM exige divulgação: honorários auditoria vs não-auditoria (avaliar independência). Regulador fiscaliza adequação.', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-externa-independente', question: 'O período de vedação (cooling-off period) estabelece que:', options: ['Auditor pode imediatamente trabalhar no auditado após deixar firma', 'Há período mínimo entre deixar firma de auditoria e assumir posição-chave no auditado', 'Não há restrições para mudança de emprego', 'Aplica-se apenas a sócios minoritários', 'Vale somente para empresas pequenas'], correctAnswer: 1, explanation: 'COOLING-OFF PERIOD (NBC PA 290, CVM): VEDAÇÃO TEMPORÁRIA sócio/gerente firma auditoria assumir POSIÇÃO-CHAVE auditado. PERÍODO: mínimo 12 MESES (pode variar regulação). POSIÇÕES-CHAVE: CEO, CFO, diretor financeiro, controller, cargo supervisão contabilidade/auditoria. RACIONAL: evita: 1) AUTORREVISÃO: auditor revisar trabalho próprio. 2) INFLUÊNCIA INDEVIDA: relacionamento prévio compromete independência sucessor. 3) FAMILIARIDADE: manutenção vínculos pessoais. ABRANGÊNCIA: sócios responsáveis, gerentes seniores equipe. VERIFICAÇÃO: anual, declarações independência. SANÇÃO: perda independência firma, CVM pode questionar auditorias anteriores. IMPORTANTE: "porta-giratória" controlada. Protege mercado. Alguns defendem período mais longo (24 meses). Aplicável S.A. abertas, entes regulados.', difficulty: 'hard', examBoard: 'CVM', year: 2024 },

    // ============= AUDITORIA GOVERNAMENTAL (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-governamental', question: 'A Auditoria Governamental realizada pelos Tribunais de Contas tem por objetivo:', options: ['Apenas verificar a contabilidade', 'Fiscalizar a aplicação de recursos públicos quanto à legalidade, legitimidade, economicidade', 'Somente auditar balanços', 'Aprovar orçamentos', 'Executar políticas públicas'], correctAnswer: 1, explanation: 'AUDITORIA GOVERNAMENTAL (CF art. 70-71, NAT - Normas Auditoria TC): TRIBUNAIS DE CONTAS fiscalizam aplicação RECURSOS PÚBLICOS. DIMENSÕES: 1) LEGALIDADE: conformidade leis, regulamentos, contratos. 2) LEGITIMIDADE: adequação finalidade pública, interesse coletivo. 3) ECONOMICIDADE: minimização custos, otimização recursos. 4) EFICIÊNCIA: relação produtos/insumos (produtividade). 5) EFICÁCIA: alcance metas/objetivos. 6) EFETIVIDADE: impactos/transformações sociedade. TIPOS AUDITORIA TC: operacional (desempenho), conformidade (legalidade), financeira (demonstrações), integrada. NÃO COMPETE: aprovar orçamento (Legislativo), executar políticas (Executivo). IMPORTANTE: controle EXTERNO (independente). Julga contas, multa, determina ressarcimento. Auditoria + julgamento (quase-judicial).', difficulty: 'easy', examBoard: 'TCU', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-governamental', question: 'São tipos de auditoria governamental:', options: ['Apenas auditoria financeira', 'Auditoria de conformidade, operacional, financeira e de obras', 'Somente auditoria de folha de pagamento', 'Apenas análise de contratos', 'Não há tipos específicos'], correctAnswer: 1, explanation: 'TIPOS AUDITORIA GOVERNAMENTAL (NAT, TCU): 1) CONFORMIDADE (legalidade): verifica cumprimento normas, leis, contratos. Exemplo: licitações, convênios. 2) OPERACIONAL (desempenho): avalia eficiência, eficácia, economicidade programas/ações. Exemplo: política saúde, educação. 3) FINANCEIRA (contábil): opinião demonstrações contábeis entes. Similares auditoria externa. 4) OBRAS: acompanhamento físico-financeiro, medições, sobrepreço, superfaturamento. 5) ESPECIAL: investigação denúncias, irregularidades graves. 6) INTEGRADA: combina tipos (conformidade + operacional). ABRANGÊNCIA: todos Poderes, entes (União, Estados, Municípios), empresas estatais, convênios. CGU: auditoria interna Executivo Federal. TC: externa. IMPORTANTE: auditoria operacional = foco RESULTADOS (impacto), não só legalidade. Tendência: auditoria baseada riscos, ênfase efetividade políticas.', difficulty: 'medium', examBoard: 'TCU', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-governamental', question: 'O controle externo no Brasil é exercido:', options: ['Pelo Poder Executivo exclusivamente', 'Pelo Poder Legislativo com auxílio dos Tribunais de Contas', 'Apenas pela CGU', 'Somente pelo Ministério Público', 'Não há controle externo'], correctAnswer: 1, explanation: 'CONTROLE EXTERNO (CF art. 70-75): TITULARIDADE: Congresso Nacional (Federal), Assembleias (Estados), Câmaras (Municípios). AUXÍLIO: Tribunais de Contas (TCU, TCE, TCM). TC: órgão TÉCNICO, auxilia Legislativo. COMPETÊNCIAS TC (CF 71): 1) Apreciar contas (Executivo). 2) Julgar contas (administradores). 3) Apreciar legalidade atos. 4) Fiscalizar aplicação recursos. 5) Fiscalizar contas nacionais empresas. 6) Fiscalizar renúncia receitas. 7) Aplicar sanções. 8) Representar irregularidades. vs CONTROLE INTERNO: cada Poder (CGU no Executivo Federal). IMPORTANTE: TC não subordinado Legislativo (auxilia, independência técnica). Decisões TC: coercitivas (executórias). MP: fiscal da lei (acompanha, não julga contas). Modelo brasileiro: híbrido (tribunal técnico + controle político Legislativo).', difficulty: 'medium', examBoard: 'TCU', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-governamental', question: 'A CGU (Controladoria-Geral da União) atua como:', options: ['Controle externo da União', 'Órgão central de controle interno do Poder Executivo Federal', 'Tribunal de Contas da União', 'Apenas combate à corrupção', 'Substituto do TCU'], correctAnswer: 1, explanation: 'CGU - CONTROLADORIA-GERAL DA UNIÃO: órgão CONTROLE INTERNO Poder EXECUTIVO FEDERAL. FUNÇÕES (Lei 10.683/03, Decreto 11.529/23): 1) AUDITORIA INTERNA: governamental, avaliar gestão programas. 2) CORREIÇÃO: apurar responsabilidade servidores federais. 3) OUVIDORIA: canal cidadão, transparência. 4) PREVENÇÃO CORRUPÇÃO: integridade, compliance, educação. COMPETÊNCIAS: auditorias programas governo, avaliação gestão, tomadas contas, recomendações, instauração TCE/PAD. CERTIFICADO AUDITORIA: emite certificado contas anuais (Presidente, ministros), encaminha TCU. vs TCU: CGU = controle INTERNO (auxilia gestor). TCU = EXTERNO (fiscaliza todos Poderes). IMPORTANTE: CGU fortalecida pós-CF88, combate corrupção, transparência. Relatórios públicos. Cooperação TCU, MPF. Ministério (status alta hierarquia).', difficulty: 'hard', examBoard: 'CGU', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'auditoria-governamental', question: 'As Normas de Auditoria do Tribunal de Contas (NAT) estabelecem:', options: ['Apenas procedimentos contábeis', 'Princípios, conceitos e diretrizes para auditorias governamentais no âmbito dos TCs', 'Somente regras para licitações', 'Apenas estrutura de relatórios', 'Não há normas específicas'], correctAnswer: 1, explanation: 'NAT - NORMAS AUDITORIA TRIBUNAL DE CONTAS (Portaria-TCU 168/2011): OBJETIVO: padronizar, profissionalizar auditorias governamentais TCs brasileiros. INSPIRAÇÃO: ISSAI (International Standards Supreme Audit Institutions - INTOSAI). ESTRUTURA: 1) PRINCÍPIOS FUNDAMENTAIS: independência, competência, ceticismo, julgamento profissional. 2) NORMAS GERAIS: planejamento, supervisão, materialidade, risco, evidência, documentação. 3) NORMAS CAMPO: execução, testes, amostragem. 4) NORMAS RELATÓRIO: comunicação, estrutura, conteúdo. TIPOS AUDITORIA ABORDADOS: financeira, conformidade, operacional. CARACTERÍSTICAS: foco setor público (legalidade + desempenho), accountability, tempestividade. APLICAÇÃO: TCU federal, TCEs/TCMs orientação. IMPORTANTE: convergência internacional (INTOSAI), profissionalização controle externo, credibilidade. Revisão periódica. Base técnica auditorias governamentais.', difficulty: 'hard', examBoard: 'TCU', year: 2024 },

    // ============= NORMAS DE AUDITORIA (NBC TA) (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'normas-de-auditoria-nbc-ta', question: 'As NBC TA (Normas Brasileiras de Contabilidade - Técnicas de Auditoria) são:', options: ['Opcionais para auditores', 'Obrigatórias para auditores independentes de demonstrações contábeis', 'Apenas recomendações', 'Somente para auditoria interna', 'Não são regulamentadas'], correctAnswer: 1, explanation: 'NBC TA - NORMAS BRASILEIRAS CONTABILIDADE TÉCNICAS AUDITORIA: emitidas CFC (Conselho Federal Contabilidade), OBRIGATÓRIAS auditores independentes. OBJETIVO: estabelecer PADRÕES qualidade, UNIFORMIZAR procedimentos, garantir CREDIBILIDADE auditorias. BASE: convergência ISA (International Standards Auditing - IFAC). ABRANGÊNCIA: planejamento, execução, relatório, controle qualidade, ética. ESTRUTURA NBC TA: NBC TA 200: objetivos gerais. NBC TA 300-450: avaliação risco, resposta. NBC TA 500-580: evidência auditoria. NBC TA 600-720: áreas especializadas, relatórios. PA (prática auditoria): específicas. FISCALIZAÇÃO: CFC, CVM (S.A. abertas), Bacen (instituições financeiras). SANÇÃO descumprimento: perda registro, multas, responsabilização. IMPORTANTE: NBC TA ≠ lei (norma profissional técnica), mas descumprir = imperícia. Atualização constante (revisões CFC).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'normas-de-auditoria-nbc-ta', question: 'A NBC TA 500 trata de:', options: ['Planejamento da auditoria', 'Evidência de auditoria - obtenção de evidência apropriada e suficiente', 'Relatório do auditor', 'Apenas fraudes', 'Controle de qualidade'], correctAnswer: 1, explanation: 'NBC TA 500 - EVIDÊNCIA AUDITORIA: define procedimentos obter evidência APROPRIADA e SUFICIENTE fundamentar opinião. CARACTERÍSTICAS EVIDÊNCIA: 1) APROPRIADA: QUALIDADE (relevância, confiabilidade). Depende: fonte (externa > interna), natureza (original > cópia), controles entidade. 2) SUFICIENTE: QUANTIDADE. Depende: risco distorção, qualidade evidência. Relação: ↓qualidade → ↑quantidade necessária. PROCEDIMENTOS OBTENÇÃO (NBC TA 500): inspeção, observação, confirmação externa, recálculo, reexecução, procedimentos analíticos, indagação. FONTES: registros contábeis (básica) + informações corroborativas (essencial). JULGAMENTO: auditor avalia suficiência/apropriação. IMPORTANTE: quantidade NÃO compensa baixa qualidade. Evidência = base opinião. Persuasiva, não conclusiva. Relação custo-benefício (não examina 100%).', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'normas-de-auditoria-nbc-ta', question: 'A materialidade em auditoria (NBC TA 320) refere-se a:', options: ['Apenas valores muito altos', 'Magnitude de distorções que, individual ou agregadamente, influenciariam decisões usuários', 'Somente fraudes', 'Não tem importância', 'Apenas erros intencionais'], correctAnswer: 1, explanation: 'MATERIALIDADE (NBC TA 320): magnitude DISTORÇÕES (omissões/incorreções) que, INDIVIDUAL ou AGREGADAS, influenciariam DECISÕES ECONÔMICAS usuários (tomadas com base demonstrações). DETERMINAÇÃO: 1) MATERIALIDADE DEMONSTRAÇÕES: nível planejamento geral. Base: referencial (lucro, receita, ativo) × percentual (5% lucro, 1% receita, 0,5-1% ativo). 2) MATERIALIDADE EXECUÇÃO: MENOR, margem segurança, reduz risco distorções não-detectadas agregadas excederem materialidade geral. 3) LIMIAR TRIVIALIDADE: valores claramente irrelevantes (não acumula). APLICAÇÃO: planejamento (natureza/extensão procedimentos), avaliação distorções identificadas, conclusão. JULGAMENTO PROFISSIONAL: não há regra fixa. REVISÃO: se mudança circunstâncias (conhecimento negócio). IMPORTANTE: materialidade ≠ valor absoluto. RELATIVO usuários. Quantitativa + QUALITATIVA (fraude, relacionadas partes, covenant).', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'normas-de-auditoria-nbc-ta', question: 'A comunicação de deficiências de controle interno deve:', options: ['Ser omitida para não constranger a administração', 'Ser comunicada tempestivamente aos responsáveis pela governança e administração (NBC TA 265)', 'Apenas mencionar no relatório público', 'Não é obrigação do auditor', 'Somente se houver fraude'], correctAnswer: 1, explanation: 'COMUNICAÇÃO DEFICIÊNCIAS CONTROLE INTERNO (NBC TA 265): auditor DEVE comunicar TEMPESTIVAMENTE deficiências SIGNIFICATIVAS identificadas. CLASSIFICAÇÃO: 1) DEFICIÊNCIA: controle inexistente/ineficaz. 2) DEFICIÊNCIA SIGNIFICATIVA: atenção governança. Pode resultar distorção relevante. Gravidade suficiente merecer atenção. COMUNICAÇÃO: POR ESCRITO aos responsáveis GOVERNANÇA (Conselho, Comitê Auditoria). Também administração (corrigir). CONTEÚDO: descrição deficiências, explicação potenciais efeitos, recomendações (se aplicável). PRAZO: TEMPESTIVO (permite ação corretiva). Deficiência significativa: antes emissão relatório. IMPORTANTE: comunicação NÃO substitui relatório auditoria (assuntos distintos). NÃO é opinião sobre controles (não é objetivo auditoria). Limitação: amostragem (pode haver deficiências não identificadas). Obrigação PROFISSIONAL, adiciona valor. Melhora governança.', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'normas-de-auditoria-nbc-ta', question: 'O relatório de auditoria, segundo NBC TA 700, deve conter:', options: ['Apenas a opinião do auditor', 'Título, destinatário, base para opinião, opinião, responsabilidades, assinatura, data', 'Somente recomendações', 'Apenas ressalvas', 'Não há estrutura definida'], correctAnswer: 1, explanation: 'RELATÓRIO AUDITORIA (NBC TA 700/701): ELEMENTOS OBRIGATÓRIOS: 1) TÍTULO: "Relatório Auditor Independente". 2) DESTINATÁRIO: acionistas, cotistas, conselho. 3) OPINIÃO: parágrafo inicial, destaque. Sobre demonstrações identificadas. 4) BASE OPINIÃO: NBC TAs, independência, evidência suficiente/apropriada. 5) RESPONSABILIDADES: a) Administração: elaboração, controles. b) Auditor: obter segurança razoável, expressar opinião. 6) PRINCIPAIS ASSUNTOS AUDITORIA (PAA - NBC TA 701): S.A. abertas, listadas. Assuntos mais significativos. 7) OUTRAS INFORMAÇÕES: responsabilidade auditor sobre relatório administração (NBC TA 720). 8) ASSINATURA: auditor responsável (nome, CPF, nº registro CFC). 9) DATA: conclusão procedimentos. 10) ENDEREÇO: auditor. IMPORTANTE: padronização facilita leitura. Opinião em destaque. Linguagem clara. Modelo evoluiu (antes: parágrafo padrão; hoje: mais informativo, PAA).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },

    // ============= PROCEDIMENTOS DE AUDITORIA (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'procedimentos-de-auditoria', question: 'São procedimentos de auditoria:', options: ['Apenas entrevistas com administração', 'Inspeção, observação, confirmação externa, recálculo, reexecução, procedimentos analíticos, indagação', 'Somente leitura de relatórios', 'Apenas análise de balanços', 'Não há procedimentos definidos'], correctAnswer: 1, explanation: 'PROCEDIMENTOS AUDITORIA (NBC TA 500): técnicas obter EVIDÊNCIA. TIPOS: 1) INSPEÇÃO: exame registros, documentos (NF, contratos), ativos tangíveis (estoque físico). 2) OBSERVAÇÃO: acompanhar processo/procedimento (contagem estoque, controles). 3) CONFIRMAÇÃO EXTERNA: circularização (bancos, clientes, advogados). Resposta direta auditor. 4) RECÁLCULO: verificar exatidão aritmética (conferir somas, depreciação). 5) REEXECUÇÃO: executar independentemente procedimento/controle (refazer conciliação bancária). 6) PROCEDIMENTOS ANALÍTICOS: avaliação informações via análise relações (índices, tendências, comparações). 7) INDAGAÇÃO: buscar informações pessoas conhecedoras (dentro/fora entidade). COMBINAÇÃO: procedimentos combinados (evidência mais robusta). SELEÇÃO: baseada RISCO, materialidade, natureza item. IMPORTANTE: indagação ISOLADA insuficiente. Confirmação externa: evidência mais confiável. Procedimentos analíticos: planejamento + revisão final.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'procedimentos-de-auditoria', question: 'A confirmação externa (circularização) é mais apropriada para:', options: ['Verificar políticas contábeis', 'Confirmar saldos bancários, contas a receber, passivos', 'Apenas avaliar controles internos', 'Somente testar estoques', 'Não tem aplicação prática'], correctAnswer: 1, explanation: 'CONFIRMAÇÃO EXTERNA/CIRCULARIZAÇÃO (NBC TA 505): obter evidência DIRETAMENTE terceiro (resposta enviada AUDITOR, não entidade). APLICAÇÕES: 1) BANCOS: saldos contas, empréstimos, garantias prestadas. 2) CONTAS RECEBER: clientes confirmam dívidas (saldo positivo). 3) CONTAS PAGAR: fornecedores confirmam saldos (menos comum, risco subavaliação passivo). 4) ADVOGADOS: contingências, processos judiciais. 5) ESTOQUES terceiros: armazéns gerais, consignação. 6) INVESTIMENTOS: custodiantes. TIPOS: POSITIVA: solicita confirmação saldo específico (resposta sempre). NEGATIVA: responder só se discordar (menos confiável). BRANCO: pede informar saldo (mais confiável, evita sugestão). VANTAGENS: evidência externa (mais confiável), independente entidade. LIMITAÇÕES: não-resposta, pode haver conluio. IMPORTANTE: confirmação NÃO substitui outros procedimentos (complementa). Essencial áreas risco fraude.', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'procedimentos-de-auditoria', question: 'Procedimentos analíticos consistem em:', options: ['Apenas calcular índices financeiros', 'Avaliação de informações por meio de estudo de relações plausíveis entre dados financeiros e não-financeiros', 'Somente entrevistas', 'Apenas inspeção de documentos', 'Não são considerados procedimentos'], correctAnswer: 1, explanation: 'PROCEDIMENTOS ANALÍTICOS (NBC TA 520): avaliação informações via análise RELAÇÕES PLAUSÍVEIS entre dados FINANCEIROS e NÃO-FINANCEIROS. TIPOS: 1) COMPARAÇÕES: valores correntes × anteriores, orçado, setor, expectativa auditor. 2) ANÁLISE TENDÊNCIAS: evolução temporal (vendas, margens). 3) ÍNDICES/QUOCIENTES: liquidez, rentabilidade, endividamento. 4) MODELOS: regressão, correlação. FINALIDADES: a) PLANEJAMENTO: entender negócio, identificar riscos (obrigatório - NBC TA 315). b) EVIDÊNCIA SUBSTANTIVA: testar razoabilidade saldos. c) REVISÃO FINAL: avaliar consistência geral (obrigatório - NBC TA 520). EXPECTATIVA: auditor desenvolve expectativa valor esperado, compara real, investiga DIFERENÇAS SIGNIFICATIVAS. VANTAGENS: eficiente (grandes volumes), identifica incomum. LIMITAÇÕES: evidência indireta (não substitui testes detalhes áreas risco). IMPORTANTE: mais eficaz quando controles efetivos, dados confiáveis, relações estáveis/previsíveis.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'procedimentos-de-auditoria', question: 'A amostragem em auditoria (NBC TA 530) permite:', options: ['Evitar qualquer trabalho de auditoria', 'Aplicar procedimentos a menos de 100% dos itens para obter evidência sobre toda a população', 'Apenas selecionar itens de maior valor', 'Garantir ausência total de erros', 'Substituir o julgamento profissional'], correctAnswer: 1, explanation: 'AMOSTRAGEM AUDITORIA (NBC TA 530): aplicar procedimentos < 100% população para obter/avaliar evidência sobre TODA população. OBJETIVO: conclusão sobre população inteira. TIPOS: 1) ESTATÍSTICA: seleção aleatória, probabilidade conhecida, permite quantificar risco/projetar resultados. Exemplos: aleatória simples, sistemática, estratificada. 2) NÃO-ESTATÍSTICA: julgamento auditor. Estratégias: valor, julgamento, bloco. RISCO AMOSTRAGEM: amostra não representativa, conclusão diferente se examinasse 100%. TAMANHO AMOSTRA: função: materialidade, risco aceitável, erro tolerável, desvio esperado. Quanto MENOR risco aceitável/erro tolerável → MAIOR amostra. PROJEÇÃO ERROS: encontrados amostra → projetar população. AVALIAÇÃO: se erros projetados + não-amostragem > materialidade → mais procedimentos. IMPORTANTE: amostragem ≠ aleatório total. Planejada. 100% se população pequena/risco alto. Julgamento sempre necessário (interpretar resultados).', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'procedimentos-de-auditoria', question: 'Testes de controles visam:', options: ['Detectar todos os erros nas demonstrações', 'Avaliar a efetividade operacional dos controles internos', 'Apenas entrevistar a administração', 'Substituir testes substantivos', 'Não são necessários'], correctAnswer: 1, explanation: 'TESTES CONTROLES (NBC TA 330): avaliar EFETIVIDADE OPERACIONAL controles internos. QUANDO: auditor pretende CONFIAR em controles (reduzir testes substantivos). OBJETIVO: verificar se controle: 1) OPEROU efetivamente (foi executado). 2) Com que FREQUÊNCIA (consistência). 3) Por QUEM (pessoa autorizada). 4) Como (manualmente/automatizado). EXEMPLOS: reexecução conciliação bancária, inspeção aprovações, observação segregação funções, verificar logs sistema (controles TI). NATUREZA: inspeção documentos evidência (assinaturas), indagação + observação, reexecução. ÉPOCA: momento apropriado (normalmente período auditado). EXTENSÃO: maior frequência controle/mais auditor confia → maior amostra. RESULTADO: se controles EFETIVOS → reduz natureza/época/extensão testes substantivos. Se INEFETIVOS → apenas substantivos. IMPORTANTE: testes controles ≠ testes substantivos. Controles: como funciona controle. Substantivos: distorções saldos. Complementares. Pode fazer SÓ substantivos (não confiar controles).', difficulty: 'medium', examBoard: 'CFC', year: 2024 },

    // ============= PAPÉIS DE TRABALHO (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'papeis-de-trabalho', question: 'Papéis de trabalho são:', options: ['Apenas rascunhos sem importância', 'Documentação dos procedimentos aplicados, evidências obtidas e conclusões alcançadas', 'Somente cópias de documentos da entidade', 'Apenas para arquivo interno', 'Não são obrigatórios'], correctAnswer: 1, explanation: 'PAPÉIS DE TRABALHO (NBC TA 230 - Documentação Auditoria): REGISTRO procedimentos executados, evidências OBTIDAS, conclusões ALCANÇADAS. FINALIDADES: 1) EVIDENCIAR fundamentação opinião. 2) COMPROVAR trabalho executado conforme NBC TAs. 3) AUXILIAR planejamento/execução. 4) SUPERVISÃO/REVISÃO trabalho. 5) RESPONSABILIZAÇÃO (defesa auditor). 6) REVISÃO QUALIDADE (pares, CVM, CFC). 7) INSPEÇÕES REGULATÓRIAS. CONTEÚDO: natureza/época/extensão procedimentos, resultados, assuntos significativos, conclusões, quem executou/revisou. FORMA: eletrônica/papel. Padronizada (facilitação). CUSTÓDIA: auditor, propriedade auditor (confidencialidade). RETENÇÃO: mínimo 5 anos fim trabalho (NBC TA 230; Lei: 10-20 anos dependendo natureza). IMPORTANTE: "se não está documentado, não foi feito". Essencial defesa judicial/regulatória. Deve permitir auditor experiente SEM envolvimento prévio entender trabalho.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'papeis-de-trabalho', question: 'Os papéis de trabalho devem:', options: ['Ser acessíveis ao auditado a qualquer momento', 'Ser suficientes para permitir que auditor experiente, sem prévio envolvimento, entenda trabalho executado', 'Apenas conter opiniões pessoais', 'Ser destruídos imediatamente após auditoria', 'Não precisam ter organização'], correctAnswer: 1, explanation: 'CARACTERÍSTICAS PAPÉIS TRABALHO (NBC TA 230): 1) CLAREZA: linguagem objetiva, conclusões evidentes. 2) SUFICIÊNCIA: detalhamento permite auditor experiente SEM ENVOLVIMENTO PRÉVIO entender: natureza/época/extensão procedimentos, resultados, evidências, conclusões, assuntos significativos + julgamentos. 3) ORGANIZAÇÃO: indexação, referenciação cruzada, arquivos corrente/permanente. 4) TEMPESTIVIDADE: preparação durante trabalho (não retrospectivamente). 5) REVISÃO: evidenciar revisão (rubricas, datas). PADRONIZAÇÃO: modelos/checklists (eficiência, consistência). Softwares auditoria. ACESSO: CONFIDENCIAL. Não entregues auditado (pode solicitar cópias documentos próprios). Acesso restrito: equipe, revisores, sucessores (circunstâncias específicas), reguladores, autoridades judiciais. ALTERAÇÃO: após data relatório: só circunstâncias específicas, documentar. IMPORTANTE: objetividade. Evitar opinião pessoal sem fundamentação. Fatos, evidências, conclusões suportadas.', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'papeis-de-trabalho', question: 'São exemplos de papéis de trabalho:', options: ['Apenas o relatório de auditoria', 'Programas de auditoria, análises, memorandos, cartas de confirmação, representações formais, listas de verificação', 'Somente contratos da entidade', 'Apenas demonstrações contábeis', 'Não existem exemplos específicos'], correctAnswer: 1, explanation: 'TIPOS PAPÉIS TRABALHO: 1) PROGRAMAS AUDITORIA: procedimentos planejados, executados (checklist). 2) ANÁLISES: movimentação contas (reconciliações, composições saldos). 3) MEMORANDOS: entendimento negócio, controles, avaliação riscos, discussões. 4) CONFIRMAÇÕES: circularizações (bancos, clientes, advogados). 5) REPRESENTAÇÕES FORMAIS: carta administração (NBC TA 580). 6) LISTAS VERIFICAÇÃO: compliance NBC TAs, revisão. 7) MINUTAS RELATÓRIO. 8) EXTRATOS/CÓPIAS: documentos entidade (contratos, atas, NF). 9) TESTES: substantivos (amostras, cálculos) e controles. 10) SÍNTESES: lead schedules, sumários. ARQUIVO CORRENTE: trabalho exercício específico. PERMANENTE: informações contínuas (estatuto, contratos longo prazo, organograma). REFERENCIAÇÃO: índices (A-ativo, B-passivo, C-receita, D-despesa). Tiques (procedimentos executados). IMPORTANTE: cópias documentos SÓ não são suficientes (falta conclusão auditor). Deve evidenciar TRABALHO executado.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'papeis-de-trabalho', question: 'O prazo de guarda dos papéis de trabalho é:', options: ['Não há prazo definido', 'Mínimo 5 anos (NBC TA 230), podendo ser maior conforme regulação específica', 'Apenas 1 ano', 'Até emissão do relatório', 'Podem ser destruídos imediatamente'], correctAnswer: 1, explanation: 'PRAZO GUARDA PAPÉIS TRABALHO: NBC TA 230: mínimo 5 ANOS data RELATÓRIO AUDITOR. Lei 10.406/02 (CC): prescrição ações: 10 anos (regra geral). CVM Instrução 308 (revogada 765): papéis auditoria S.A. abertas: arquivados. Prática: 10-20 anos (proteção legal). FORMA: eletrônica/física. Backup. Segurança (confidencialidade). ALTERAÇÃO: VEDADA após montagem arquivo final (60 dias emissão relatório). Exceções: adicionar documentação (novo fato), administrativo (organização). DEVE documentar razão/quando. ACESSO POSTERIOR: reguladores (CVM, CFC, Bacen), sucessor (NBC TA 510), judicial (requisição). IMPORTANTE: retenção LONGA necessária: ações responsabilidade civil (10 anos), discussões tributárias/judiciais. Descarte: procedimentos garantem confidencialidade (destruição segura). Sistemas eletrônicos facilitam (custo armazenamento ↓).', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'papeis-de-trabalho', question: 'A revisão dos papéis de trabalho visa:', options: ['Apenas corrigir erros de digitação', 'Assegurar que trabalho foi executado conforme planejado, evidências são suficientes e conclusões são apropriadas', 'Somente reorganizar arquivos', 'Não é necessária', 'Apenas para cumprir formalidade'], correctAnswer: 1, explanation: 'REVISÃO PAPÉIS TRABALHO (NBC TA 220 - Controle Qualidade): NÍVEIS: 1) SÓCIO RESPONSÁVEL: revisão geral, assuntos significativos, julgamentos críticos, consultas, conclusões, relatório. 2) GERENTE/SUPERVISOR: revisão detalhada trabalho equipe, procedimentos adequados, documentação suficiente, conclusões. 3) SÊNIOR: revisão trabalho assistentes. 4) REVISOR QUALIDADE (EQCR): S.A. listadas, alto risco. Independente, antes emissão relatório. OBJETIVOS: 1) CONFORMIDADE: trabalho conforme NBC TAs, planejamento. 2) SUFICIÊNCIA: evidências apropriadassuficientes. 3) CONSISTÊNCIA: conclusões fundamentadas, relatório alinhado achados. 4) RESOLUÇÃO: assuntos significativos resolvidos, consultados. 5) SUPERVISÃO: orientação, treinamento equipe. DOCUMENTAÇÃO: evidenciar revisão (rubrica, data, comentários). QUANDO: durante trabalho (não só final). IMPORTANTE: revisão HIERÁRQUICA. Trabalho júnior → sênior → gerente → sócio (+ EQCR se aplicável). Essencial controle qualidade. Reduz risco auditor.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },

    // ============= RELATÓRIO DE AUDITORIA (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'relatorio-de-auditoria', question: 'Os tipos de opinião do auditor independente são:', options: ['Apenas opinião com ressalva', 'Não modificada (limpa), com ressalva, adversa e abstenção de opinião', 'Somente opinião adversa', 'Apenas abstenção', 'Não há tipos definidos'], correctAnswer: 1, explanation: 'TIPOS OPINIÃO (NBC TA 705): 1) NÃO MODIFICADA (LIMPA/SEM RESSALVA): demonstrações apresentadas ADEQUADAMENTE, em TODOS aspectos RELEVANTES, conforme estrutura. 2) MODIFICADA: a) RESSALVA: distorção relevante (não generalizada) OU limitação alcance (não generalizada). "Exceto por/Exceto quanto". Demonstrações adequadas, EXCETO efeitos assunto ressalvado. b) ADVERSA: distorções RELEVANTES e GENERALIZADAS. Demonstrações NÃO apresentadas adequadamente. "Opinião adversa". c) ABSTENÇÃO: limitação alcance RELEVANTE e GENERALIZADA. Impossível obter evidência suficiente. "Não expressamos opinião". SEM OPINIÃO. GENERALIZADA: não confinado a elementos específicos, OU confinado mas representa/poderia substancial das demonstrações, OU obscurece (impossível avaliar). IMPORTANTE: auditor busca NÃO MODIFICADA. Modificadas: situações adversas. Administração deve corrigir. Mercado reage negativamente ressalvas/adversas. Abstenção: raridade (normalmente auditor renuncia).', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'relatorio-de-auditoria', question: 'Uma opinião com ressalva é emitida quando:', options: ['Não há problemas nas demonstrações', 'Há distorção relevante mas não generalizada, ou limitação de alcance não generalizada', 'As demonstrações estão totalmente incorretas', 'O auditor não conseguiu obter nenhuma evidência', 'Apenas por formalidade'], correctAnswer: 1, explanation: 'OPINIÃO COM RESSALVA (NBC TA 705): emitida quando: 1) DISTORÇÃO RELEVANTE (erro/desacordo): efeito relevante MAS NÃO GENERALIZADO. Exemplo: provisão inadequada, ativo superavaliado. 2) LIMITAÇÃO ALCANCE: impossível obter evidência suficiente, efeito relevante MAS NÃO GENERALIZADO. Exemplo: não observou inventário (impossibilidade), entidade não forneceu confirmações. REDAÇÃO: parágrafo "Base Ressalva" (descreve assunto). Parágrafo "Opinião Ressalva": "Em nossa opinião, EXCETO pelos efeitos do assunto descrito... demonstrações apresentam adequadamente...". EFEITO: demonstrações adequadas EXCETO quanto a aspecto específico (quantificável). vs ADVERSA: ressalva = problema localizado. Adversa = generalizado, demonstrações como todo não adequadas. vs ABSTENÇÃO: ressalva = evidência suficiente restante demonstrações. Abstenção = impossível opinar. IMPORTANTE: auditor QUANTIFICA efeito (se praticável). Administração deve ajustar. Ressalva última opção (negocia correção).', difficulty: 'medium', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'relatorio-de-auditoria', question: 'Opinião adversa é apropriada quando:', options: ['Há pequenos erros sem importância', 'Distorções são relevantes e generalizadas, demonstrações não estão apresentadas adequadamente', 'Apenas há limitação de alcance', 'O auditor discorda de políticas contábeis da administração', 'Nunca é apropriada'], correctAnswer: 1, explanation: 'OPINIÃO ADVERSA (NBC TA 705): DISTORÇÕES relevantes E GENERALIZADAS. Demonstrações NÃO ADEQUADAS. QUANDO: 1) Erros/desacordos RELEVANTES múltiplos elementos (generalizado). 2) Distorção isolada MUITO relevante (representa substancial demonstrações). 3) Inadequação prática contábil fundamental (ex: não consolidar controladas, não reconhecer receitas). REDAÇÃO: "Base Opinião Adversa" (descreve distorções, quantifica se praticável). "Opinião Adversa": "Em nossa opinião, devido relevância assuntos descritos... demonstrações NÃO apresentam adequadamente...". GRAVIDADE: pior opinião (exceto abstenção = sem opinião). CONSEQUÊNCIAS: perda confiança mercado, covenant quebrado, questionamento investidores, possível destituição auditor (se administração discorda). DIFERENÇA vs RESSALVA: adversa = problema generalizado, contaminando demonstrações. Ressalva = localizado. IMPORTANTE: raridade (administração normalmente ajusta antes). Obrigação profissional auditor.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'relatorio-de-auditoria', question: 'Abstenção de opinião ocorre quando:', options: ['Há distorções nas demonstrações', 'Há limitação de alcance relevante e generalizada, impossibilitando expressar opinião', 'As demonstrações estão corretas', 'Apenas por prazo curto de auditoria', 'Não há evidências mas auditor opina mesmo assim'], correctAnswer: 1, explanation: 'ABSTENÇÃO OPINIÃO (NBC TA 705): LIMITAÇÃO ALCANCE relevante E GENERALIZADA. IMPOSSÍVEL obter evidência SUFICIENTE/APROPRIADA. NÃO expressa opinião. QUANDO: 1) Entidade IMPEDE acesso (registros, pessoas, confirmações). 2) Contratação TARDIA (impossível procedimentos essenciais - ex: inventário inicial). 3) Registros INADEQUADOS (contabilidade caótica). 4) INCERTEZA extrema (generalizada, múltiplos elementos). REDAÇÃO: "Base Abstenção" (descreve limitação). "Abstenção Opinião": "Não obtivemos evidência suficiente... NÃO expressamos opinião sobre demonstrações...". RESPONSABILIDADES: declara auditor responsável por obter segurança razoável, MAS não conseguiu. vs RESSALVA: abstenção = impossível opinar (muito extenso). Ressalva = opina exceto sobre algo específico. CONSEQUÊNCIA: tão grave quanto adversa. Mercado desconfia. RENÚNCIA: se limitação imposta administração (não acidental), auditor deve avaliar RENUNCIAR trabalho. IMPORTANTE: abstenção NÃO protege auditor se negligente.', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'relatorio-de-auditoria', question: 'Principais Assuntos de Auditoria (PAA) - NBC TA 701:', options: ['São obrigatórios para todas as empresas', 'São assuntos mais significativos, obrigatórios para S.A. listadas, reportados em seção específica do relatório', 'Apenas substituem a opinião', 'Não têm regulação', 'São opcionais sempre'], correctAnswer: 1, explanation: 'PAA - PRINCIPAIS ASSUNTOS AUDITORIA (NBC TA 701): assuntos que, no julgamento profissional auditor, foram MAIS SIGNIFICATIVOS auditoria demonstrações período corrente. OBRIGATORIEDADE: S.A. LISTADAS (capital aberto, bolsa). OPCIONAL: outras (recomendado). SELEÇÃO: entre assuntos comunicados governança, considerar: áreas maior risco distorção relevante/riscos significativos, julgamentos significativos auditor (estimativas, áreas subjetividade), efeito eventos/transações significativos. EXEMPLOS: reconhecimento receita (complexo), impairment ativos, contingências, combinação negócios, áreas julgamento. COMUNICAÇÃO RELATÓRIO: SEÇÃO específica "Principais Assuntos Auditoria", APÓS opinião. Para cada: descrição, por que considerado significativo, como auditoria abordou. NÃO substitui: opinião modificada, ênfase, outros assuntos. OBJETIVO: TRANSPARÊNCIA, valor informacional relatório. IMPORTANTE: PAA NÃO opinião separada. Contextualiza trabalho auditor. Usuários entendem áreas foco/complexidade.', difficulty: 'hard', examBoard: 'CFC', year: 2024 },

    // ============= CONTROLE INTERNO (5) =============
    { area: 'fiscal', subject: 'auditoria', topic: 'controle-interno', question: 'Controles internos são de responsabilidade:', options: ['Exclusiva do auditor externo', 'Da administração da entidade', 'Apenas da auditoria interna', 'Somente do conselho fiscal', 'Não há responsável definido'], correctAnswer: 1, explanation: 'CONTROLE INTERNO (NBC TA 315): responsabilidade ADMINISTRAÇÃO. CONCEITO COSO: processo conduzido conselho/administração/colaboradores, destinado fornecer segurança RAZOÁVEL quanto: eficácia/eficiência operações, confiabilidade informações, conformidade leis/regulamentos. COMPONENTES (COSO 2013): 1) AMBIENTE CONTROLE: cultura ética, integridade, estrutura governança. 2) AVALIAÇÃO RISCOS: identificação/análise riscos objetivos. 3) ATIVIDADES CONTROLE: políticas/procedimentos (aprovações, segregação funções, conciliações, controles TI). 4) INFORMAÇÃO/COMUNICAÇÃO: sistemas informação, comunicação interna/externa. 5) MONITORAMENTO: avaliações contínuas/pontuais efetividade. AUDITOR: entende controles RELEVANTES auditoria, AVALIA design/implementação, TESTA efetividade operacional (se confiar), COMUNICA deficiências. NÃO elabora/implementa. IMPORTANTE: bons controles PREVINEM/DETECTAM erros/fraudes. Base demonstrações confiáveis.', difficulty: 'easy', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'controle-interno', question: 'São componentes do controle interno segundo COSO:', options: ['Apenas atividades de controle', 'Ambiente de controle, avaliação de riscos, atividades de controle, informação e comunicação, monitoramento', 'Somente monitoramento', 'Apenas comunicação', 'Não há componentes definidos'], correctAnswer: 1, explanation: 'COSO - COMMITTEE SPONSORING ORGANIZATIONS TREADWAY COMMISSION: modelo referência controle interno. COMPONENTES (COSO 2013): 1) AMBIENTE CONTROLE: fundação demais componentes. Tom topo (tone at top), integridade, valores éticos, filosofia administração, estrutura organizacional, competência pessoas. 2) AVALIAÇÃO RISCOS: identificar, analisar riscos impedirem objetivos. Interno/externo. Fraude incluído. 3) ATIVIDADES CONTROLE: políticas/procedimentos asseguram diretrizes administração executadas. Tipos: preventivos/detectivos, manuais/automatizados. Exemplos: aprovações, autorizações, verificações, conciliações, análise desempenho, segregação funções, segurança física, controles TI. 4) INFORMAÇÃO/COMUNICAÇÃO: capturar, processar, comunicar informações tempestivas. Sistemas informação, comunicação interna (políticas) e externa (clientes, fornecedores, reguladores). 5) MONITORAMENTO: avaliar qualidade desempenho controles. Avaliações contínuas (supervisão), pontuais (auditoria interna), corrigir deficiências. IMPORTANTE: inter-relacionados, integrados processos. Entidade adapta seu porte/complexidade.', difficulty: 'medium', examBoard: 'COSO', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'controle-interno', question: 'Segregação de funções é um controle que visa:', options: ['Aumentar a burocracia', 'Impedir que uma única pessoa controle todas as fases de uma transação (reduz risco fraude/erro)', 'Apenas dividir tarefas', 'Complicar processos', 'Não tem objetivo específico'], correctAnswer: 1, explanation: 'SEGREGAÇÃO FUNÇÕES: princípio controle interno. NENHUMA pessoa deve controlar TODAS fases transação. FASES: 1) AUTORIZAÇÃO: aprovar transação. 2) EXECUÇÃO: realizar operação. 3) REGISTRO: contabilizar. 4) CUSTÓDIA: guarda ativo. OBJETIVO: reduzir risco FRAUDE (conluio necessário, mais difícil) e ERRO (revisão independente). EXEMPLOS: quem autoriza compra ≠ quem recebe mercadoria ≠ quem paga ≠ quem contabiliza. Quem custodia caixa ≠ quem registra movimento. Quem emite cheque ≠ quem assina. LIMITAÇÕES: empresas PEQUENAS (poucos funcionários, difícil segregar). Mitigação: controles compensatórios (supervisão próxima proprietário, conciliações). CONLUIO: duas+ pessoas combinam burlar controle. Segregação dificulta mas não elimina. IMPORTANTE: controle PREVENTIVO (evita ocorrência). Base auditoria (se segregação inadequada → risco controle alto → mais testes substantivos). Essencial prevenção fraudes.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'controle-interno', question: 'Limitações inerentes aos controles internos incluem:', options: ['Controles são perfeitos e eliminam todos os riscos', 'Possibilidade de conluio, burla pela administração, erro humano, custo-benefício', 'Controles não têm limitações', 'Apenas falhas tecnológicas', 'Somente questões de custo'], correctAnswer: 1, explanation: 'LIMITAÇÕES INERENTES CONTROLE INTERNO (NBC TA 315): controles fornecem segurança RAZOÁVEL, NÃO ABSOLUTA. LIMITAÇÕES: 1) JULGAMENTO HUMANO: decisões podem ser falhas (erro, má interpretação). 2) FALHAS EXECUÇÃO: erro humano, distração, fadiga. 3) CONLUIO: duas+ pessoas combinam fraudar (contornam segregação). 4) BURLA ADMINISTRAÇÃO (management override): administração ignora controles (autoridade, pressão). 5) CUSTO-BENEFÍCIO: controle não pode custar mais que benefício. Alguns riscos aceitos (controlar tudo = inviável). 6) MUDANÇAS: controles podem tornar-se inadequados (mudança condições, novos riscos). CONSEQUÊNCIAS AUDITORIA: auditor NÃO pode confiar cegamente controles. Ceticismo profissional. Testes controles + substantivos. Especial atenção áreas julgamento, relacionadas partes, estimativas (risco burla administração). IMPORTANTE: boa governança MITIGA (não elimina). Comitê auditoria independente, canal denúncias, cultura ética. Administração íntegra = controles efetivos.', difficulty: 'hard', examBoard: 'CFC', year: 2023 },
    
    { area: 'fiscal', subject: 'auditoria', topic: 'controle-interno', question: 'O auditor deve comunicar deficiências significativas de controle interno:', options: ['Apenas verbalmente', 'Por escrito aos responsáveis pela governança e administração (NBC TA 265)', 'Não precisa comunicar', 'Somente no relatório público', 'Apenas se houver fraude comprovada'], correctAnswer: 1, explanation: 'COMUNICAÇÃO DEFICIÊNCIAS (NBC TA 265): auditor OBRIGAÇÃO comunicar TEMPESTIVAMENTE, POR ESCRITO, deficiências SIGNIFICATIVAS controles internos. DEFICIÊNCIA SIGNIFICATIVA: importância suficiente merecer atenção GOVERNANÇA. Gravidade depende: magnitude potencial distorção, probabilidade ocorrer, natureza/sensibilidade contas envolvidas. DESTINATÁRIOS: 1) GOVERNANÇA (Conselho, Comitê Auditoria): deficiências significativas. 2) ADMINISTRAÇÃO: deficiências (significativas + outras relevantes). CONTEÚDO COMUNICAÇÃO: descrição deficiências, explicação potenciais efeitos, contexto suficiente entender, recomendações (se apropriado). PRAZO: TEMPESTIVO (permite ação corretiva), de preferência ANTES emissão relatório. REPETIÇÃO: se não corrigidas, comunicar novamente exercício seguinte. IMPORTANTE: comunicação ADICIONA VALOR (consultoria). NÃO substitui relatório auditoria (assuntos distintos). Limitação: amostragem (pode haver deficiências não identificadas). Responsabilidade profissional, ética.', difficulty: 'medium', examBoard: 'CFC', year: 2024 },
  ];

  console.log(`📦 Prepared ${allQuestions.length} Auditoria questions...`);
  
  for (const q of allQuestions) {
    await saveQuestion(q);
  }
  
  console.log('🎉 ALL 45 Auditoria questions seeded successfully!');
}
